import type { VideoContent } from "./types";

export const podcastluiz_gustavo_S2_ep02: VideoContent = {
  slug: "podcast-luiz-gustavo-s2-ep02",
  youtubeId: "rG0BJ1O3SwI",
  title: "BestBarbers Podcast com Luiz Gustavo — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 2 da Temporada 2 do BestBarbers Podcast com Luiz Gustavo. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "luiz gustavo",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2023-02-06",
  duration: "1:05:45",
  category: "Podcast",
  tags: ["podcast", "temporada 2", "entrevista", "gestão", "barbeiro"],

  transcript: `[Música] senhoras e senhores sejam bem-vindos a mais um best barbras podcast é sempre uma honra ter você nos acompanhando para quem ainda não conhece eu sou André um dos fundadores aqui do best barbras eu estou recebendo essa presença ilustre Luizão esse Astro aí do mundo da barbearia Muito obrigado irmão por ter aceitado nosso convite bom sem mais delongas se apresenta pessoal conta um pouquinho Quem que é o Luiz Gustavo e como se se envolveu nesse mundo da barbearia elas não obrigado pelo convite tamo junto demais quero agradecer você eu peço pelo convite agora não me conhece gente meu nome é Luiz Gustavo eu sou barbeiro há 10 anos sou barbeiro sou educador eu sou proprietário de uma barbearia André o basicamente o meu envolvimento com a barbearia ele veio bem cedo né ali primeiramente como um cliente né primeiro cortando o meu cabelo e a partir daí cara eu comecei a cortar meu cabelo perto de casa assim e tal a gente né quer dar uma mais vai dar mais vaidoso assim quer ficar um pouquinho melhor E aí um amigo meu foi cortar o cabelo no lugar e depois indicou esse lugar para gente

e esse lugar era com Elias cara antes da barbearia seu Elias chamava Torres Cabeleireiros ele cortava lá com Elias e com Edmar né que é o Torres que eu acredito que muita gente aqui também conheça E aí esse foi meu primeiro envolvimento foi a primeira vez que eu tive com alguém ali assim realmente que eu vi um salão uma barbearia Um negócio diferente a gente fez uma amizade ali até legal e tal e aí o Elias uma época ele precisou de um assistente para trabalhar lá e aí ele fez um convite para mim ou para um irmão né ali tal que ele tava precisando de gente eu fui trabalhar nessa época trabalhei lá durante oito meses ali com eles depois desse convite ali de barbearia e ele me botou essa pilha ele falou cara faz um curso de barbeiro bicho é começa ali faz uma coisa que vai ser legal para você você vai conseguir você vai se dar bem nessa parada e eu não acho que eu esperava muito não é quantos anos tinha 14 anos de idade nessa época eu entrei lá com 14 anos aí quando eu saí eu já tinha 15

né eu já tinha feito 15 anos eu saí fiz meu curso foi trabalhar no centro da cidade aqui em Belo Horizonte que é daqui de BH ou da região aqui sábado do salões que tem lá no centro que a gente fica lá na porta essa área cara a gente fica lá chamando a galera é você não fica dentro da barbearia esperando como que as pessoas entrem ficava na porta gritando a galera né então passava todo mundo assim falou irmão cortar o cabelo aí parceiro velho chega aí vamos cortar o cabelo então entrou lotado entro lotado cara então assim você não esperava né o Market é o melhor marca que tem né você fica na porta e chamando as pessoas ali você aprende a vender de verdade né aí gente cara cara e assim foi lá com o que eu aprendi aumentar ticketing médio lá foi onde eu aprendi a chamar mais cliente a vender mais serviços a gente não vendia produto lá por exemplo não tinha gel pomada esse negócio lá não tinha mas como saísse era muito barato né o corte era r 10 e ainda aí a gente dividia ainda né com o

dono então era 50% dele 50% nossa estava com r 5 então assim Tinha que trabalhar muito para gerar uma grana lumina e vendendo o volume e os outros serviços que cobravam mais que a gente conseguia ganhar uma comissão melhor era na Química porque a gente comprava o produto e aí acho que dava 70% se eu não me engano então eu precisava gerar muito aquilo então era relaxamento e selagem não sei o quê tinta preta para tudo que é lado colorido atrás descolorido Nossa cara fazia de tudo bicho porque a gente precisava Abrir oferecer isso então cara Pô queria fazer uma escova beleza só que tem que fazer o pezinho fala ah não dá para fazer falar não dá cara é a gente é complicado ali e vendia um serviço e vendia outro passar duas horas quando a gente na cadeira final r 50 que deu tudo ali sabe dono metade pra você pode dividir É isso aí e aí eu fiquei lá durante um ano e quando tava quase completando ano que eu tava lá eu eu recebi um SMS cara SMS e nem tinha WhatsApp ainda recebi um sms do Elias falando trocar uma

ideia com você eu posso ligar aí e tal me apresentou o projeto da barbearia seu Elias tal me falou eu falei olha tô com um projeto novo de uma barbearia eu vou abrir e tal e eu queria que você fosse trabalhar comigo né com isso era a primeira loja que ele abri ainda foi na primeira loja que foi abrir e aí a gente foi participar do projeto inteiro cara a primeira barbearia seu Elias que foi ter lembro quando eu cheguei lá na loja tinha quatro paredes cimento em volta é e falei cara vai ser aqui vai ficar muito bonito o projeto e esse tá a gente ia para lá limpar a obra porque no outro dia ia ter alarmar alguma coisa assim várias vezes cara antes de começar a primeira barbearia a gente saiu de lá 1:30 2 horas da manhã porque tava limpando tava fazendo alguma coisa que era necessário lá no outro dia da obra galera cuidar então assim eu sempre participei do negócio a fundo né o grosso mesmo é que a primeira pedra ali da construção você tava lá né E aí nessa época a gente precisava fazer também divulgação já

tinha uns panfletos eu saía pelo bairro panfletava o bairro inteiro num bairro Ouro Preto na Pampulha né que Belo Horizonte entregava lá ficava parado no semáforos entregava para galera sair entregando em caixa de correio e tal isso antes da barbearia brinca cara é lembro tava perto se eu não menina na Copa das Confederações né que rola um ano rolou um ano antes e entregando bastante coisa ali então foi um tempo legal ali de ter passado tá cara isso foi construindo sua carreira ali né dentro da barbearia seu Elias dentro do grupo Sueli assim eu imagino que a dúvida de muito barbeiros né Deve ser Como é trabalhar com o seu Elias bicho ao mesmo tempo que é muito muito bom é muito legal porque é um desenvolvimento muito grande né um trabalho que você cresce muito rápido cresce muito bem um acompanhamento muito honroso é que eu tive na minha vida né muita gente quer ser acompanhada por alguma pessoa assim eu entendo muita gente quer crescer mas falta oportunidade porém não é para todo mundo não é para todo mundo porque não tô falando que não é todo mundo que é capaz o que

não pode trabalhar lá dentro Mas não é para todo mundo que vai dar o mesmo crescimento senão a gente teria várias pessoas com os mesmos resultados inteiro e cara é dolorido bicho é não é facinho não ao longo de todo esse tempo que eu passei lá dentro de estudos de investimento de grana de trabalhar para caramba de me dedicar para barbearia a média né Normal normal de fazer você aí na sua casa vai para o seu trabalho Acabou o trabalho você vai sei lá Vai para academia vai jogar uma bola vai descansar eu sempre fiz mais Eu Sempre busquei mais então ter um cara como eles do meu lado foi fundamental né quando você quiser crescer cara ele é uma pessoa que vai te estender a mão vai te ajudar é eu devo muito da minha vida profissional Elias é a visibilidade ao trabalho que eu tenho hoje as coisas com que eu tenho hoje logicamente que tem muito trabalho tem muito estudo tem muita dedicação mas a devo isso muito também ao Elias cara ele nessa época ele me chamou cara para trabalhar Acho que assim eu não tinha nem certeza se eu queria

mesmo ser barbeiro ou não é o Elias acreditou em mim como profissional antes de eu acreditar entendeu achar que dava certo sabe então isso foi assim foi Fundamental e como você falou é uma importância né você ter alguém ali para se espelhar alguém como se aumentou né E você teve também um privilégio é e é o que você falou né também ajudar quem quer ser ajudado é não adianta ele estender a mão também para quem não quer ser ajudado porque a pessoa não vai sair do lugar nenhum né pode ser a melhor pessoa do mundo orar e caráter mas aí a pessoa também tem que fazer a sua parte não havia de uma dupla ele tem é uma coisa que tá aqui cara para quem Para você que é dono aí do seu negócio para você que é dono da sua barbearia seja da sua empresa não adianta cara você querer o tempo inteiro se dedicar ajudar uma pessoa que não quer crescer a primeira coisa que a gente precisa entender para alguém que você deseja ajudar até onde essa pessoa quer ir porque às vezes você quer levar ela para um caminho que ela

não tá afim de ir irmão para se você fizer isso isso aqui você vai crescer para caramba Seu nome vai ficar maior você vai ralar mais você vai e na cabeça dele tá assim quem disse que eu quero ralar mais é indisca eu quero mais dinheiro eu tô feliz do jeito que eu tô se eu continuar com a vida do jeito que eu tô aqui para mim já tá legal então primeiro ponto para a gente entender cara né e o líder precisa entender isso muito bem é onde o meu liderado que aí o papel do líder é isso é te desenvolver para onde você quer ir não para onde eu quero te levar é eu te ajudo no caminho que você quer e assim a gente quer aproveitar a cara com isso né até aprender isso porque você quer ajudar e fala assim poxa essa pessoa tem potencial essa pessoa ela consegue muito mais longe tem que tá criando expectativa irmão o cara nem que é ele tá de boa ali sabe e cara você falou de alguns pontos Chaves aí né que é liderança e pessoas é ao longo do tempo se tornou um

dos maiores líderes ali dentro também aumente no sentido de liderar pessoas liderar ao grupo implementar cultura é que você acha que é o maior desafio na hora de você montar uma equipe Quais você acha que são as peças chaves para você fazer uma boa contratação conseguir montar uma boa equipe cara é um negócio que para mim dentro da barbearia ainda é subestimado que é cultura a cultura ela tá em tudo em absolutamente tudo dentro da barbearia da forma como se corta o cabelo da forma como se atende o cliente do comportamento dos profissionais lá dentro da forma com que o convívio das pessoas lá dentro da forma com que você sei lá os acabamentos os atendimentos a limpeza tudo isso faz parte da cultura faz parte da sua empresa e esse é o ponto mais difícil porque ensinar técnica sei lá se você resolver cortar cabelo amanhã eu te garanto que daqui a pouco você tá aprendendo Você tá bem Você vai conseguir fazer né mas cultura cara é você conseguir moldar as pessoas de forma com que elas acreditem que aquilo seja verdade porque que se a cultura não faz parte de você a

ponto de que as pessoas acreditam que aquilo seja verdade elas vão fazer enquanto você tá perto assim que você virar as costas eles vão fazer do jeito que ele acha mais fácil ele acha que é mais viável ou aquela famosa tipo assim pô não tem necessidade de fazer desse jeito aqui tem outras formas de fazerem também mas quando Isso faz parte da cultura quando Isso faz parte de verdade das pessoas ali que elas já entenderam real sentido de fazer da forma com que a cultura da barbearia pede você pode ficar fora cara E aí quando ele sair daí ele vai para outro lugar ele vai trabalhar em outro lugar ele vai abrir a barbearia dele ele vai carregar um pouco da sua cultura também porque a forma como que ele aprendeu a fazer taca então a forma de se fazer né para quem não sabe para quem não entende muito bem ainda talvez a cultura é são as crenças os valores a forma com que você faz seu trabalho ali dentro e tudo isso é fundamental para trazer a sua identidade a sua características né todas essas características que você tem como empresa como barbearia

que se apresenta para o seu cliente está ligado lá na sua cultura aí acho que o Elias é um cara que consegue fazer isso muito bem é em movimentar as pessoas e moverem elas é Crendo sempre em algo sempre mantendo ali os princípios da barbearia desde que vocês começaram é eu vejo isso muito presente nele e acho que é o maior desafio e tem nas empresas hoje em geral né você conseguir é inspirar as outras pessoas a realmente acreditarem no potencial que elas têm no melhor que elas podem fazer né e eu acho que esse como você falou é uma coisa muito subestimada Na barbearia que eu vejo porque o pessoal às vezes pensa assim tô cortando muito bem já fidelizei muito cliente né vou abrir minha barbearia é e acha que é só lotar a agenda e fazer uma boa gestão ali mas não tem essa visão de que precisa engajar os colaboradores né Que precisa dar o exemplo acima de tudo também né Eu acho que isso é fundamental se você quer que alguém Creia e te siga em algo que você tem que dar o exemplo daquilo mostrar na prática o porquê

daquilo né para fazer acreditar então eu acho que isso é um dos principais desafios que tem hoje é do grupo seu Elias como que foi isso para você a experiência lá dentro né Eu acredito que devem você deve ter passado por muitos processos ali tanto de contratação como gestão de pessoas e você tem algum episódio marcante de você falar cara ali eu tentei de tudo mas como eu falei no às vezes não era uma pessoa que queria ser ajudado uma pessoa que não queria evoluir eu tenho para contar a gente Ah já sei sim cara com certeza tem assim é o que eu falei tem muita gente que para você passar por um processo de completa mudança você tem que estar desligado do que que você do que a gente pode chamar aqui de antigo né eu posso estar afim de desligar o que que é o Luiz antigo para aprender uma coisa nova e tem gente que não tá afim mano tá tudo certo gente não tem problema talvez você vai contratar uma pessoa um colaborador alguém que vai estar com você aí e não quer se desfazer das antigas Manias não tem problema

isso acontecer você só não vai trabalhar comigo você não encaixa nesse lugar é tá tudo certo eu fiz um último curso agora de liderança cara em que um dos professores foi o Bernardinho que era esse treinador de da seleção de vôlei né E aí ele falava que teve um dos cortes em que ele fez os jogadores assim para seleção e tal em que o cara culturalmente não se encaixava na cultura de time de que o time era campeão de que a equipe era campeã e o cara era um pouco mais individualista e ele cortou o cara mesmo sendo o melhor jogador do mundo na posição na época cortou o melhor jogador do mundo na posição na época por conta disso mas porque cara você é excelente é muito bom no que você faz só que dentro do que eu quero não se encaixa então muito obrigado É pô mas o que eu escuto muito e geralmente é isso que acontece é o que o mas esse cara dá muito resultado Esse cara é meu primeiro lugar de faturamento o que que eu faço com ele ele vai me falar é você pô e que é

mais importante para você Depende do que você quer né quer ganhar mais importante para você resultado manter a sua cultura a sua equipe daquele jeito porque rapidamente se você não fizer uma mudança nisso você começa a perder os outros que estão lá para a galera vai ver que não faz sentido ou é melhor fazer o quê trabalhar muito rápido sei lá e atender mal a galera porque eu tô precisando ganhar dinheiro ou eu preciso atender devagar um pouquinho mais com mais Capricho ali e tal para expressar mais atenção serviço melhor e tal saca Então depende de cada pessoa depende do que que você quer para cada negócio aquele negócio que vai trabalhar por velocidade tem negócio que vai trabalhar por experiência vai ter negócios diferentes opções diferentes é as pessoas que estão com você elas têm que encaixar na cultura que você espera Independente se for mais rápido se for mais devagar se for com mais experiência com problema mais barato cobra mais caro todo mundo só precisa estar alinhado ali cara eu acho que uma das dificuldades muito grande né que os barbeiros tem uns longas de barbearias principalmente é na hora da contratação

você entender que essa pessoa realmente compactua com os mesmos valores que você Então porque às vezes na entrevista a pessoa se mostra uma coisa mas na realidade Quando você vai ver é outra E aí gera uma série de frustrações e tudo mais Então qual que é a dica que você daria para o pessoal que tá precisando contratar alguém tá precisando adquirindo novos membros aí para sua equipe cara é sempre muito desafiador por conta disso né a gente às vezes acha que é uma coisa e a pessoa chega por outra primeira coisa cara eu eu sempre costumo fazer um filtro através de indicação porém eu consigo fazer esse filtro através de indicação porque eu recebo um volume enorme de pessoas querendo trabalhar comigo Graças a Deus eu quero agradecer você seja já me chamou você quer trabalhar comigo Fico muito honrado por isso mas não cabe todo mundo né cara ainda não dá para colocar todo mundo é a primeira coisa o primeiro filtro que eu faço é um filtro de indicação eu pego indicação e alguém que já tá lá dentro do grupo que já trabalha tem algum amigo porque eu acho que fica mais

fácil fica mais próximo da gente conhecer segunda coisa cara na hora da entrevista na hora da contratação vejo muitas vezes as pessoas perguntando sobre técnicas sobre outra coisa e falta perguntar sobre a pessoa né Eu entendo sim que nós precisamos da diversidade da diferença ali de pessoas pensando diferente no mesmo local porém a cultura ela já precisa estar mais próxima se eu tenho uma cultura então de uma pessoa que é completamente diferente para trazer para cá vai ser difícil Ah eu vou levar mais tempo não é que não pode você vai ter que ter mais paciência mais energia sacou eu sei que eu gastei energia demais de muita gente para me informar eu comecei a cortar cabelo com 15 anos então assim era moleque para caramba e assim mas o que eu vejo que às vezes falta essa conversa de entender um pouco da vida pessoal entendeu um pouco dos planos entendeu um pouco dos desejos de entender do pouco o André o que que você quer fazer da sua vida cara legal por que que você quer vir para cá e você pensou que era bom para você vir para cá porque Indique quais

são os seus pontos fortes que que você acha que são seus pontos fracos é seu sei lá se eu ligar pro seu chefe antigo chefe o que que ele vai me passar de referência de você indiquei por exemplo vou pegar seus pontos fortes aí a pessoa pode mentir pode é uma parada muito legal aí na para usar na hora da contratação que é o seguinte a gente chama de metodologia Star o Star é uma abreviação uma sigla de situação tarefa ação e resultado então quando o cara fala uma coisa é por exemplo eu sou muito paciente aí você aplica o estar em cima dali Então beleza qual situação em que ocorreu que você foi paciente e tarefa que você precisou executar qual ação que você tomou em cima disso e qual o resultado que você trouxe para barbearia para empresa por exemplo ou sei lá uma criança tava chorando desesperada gritando demais e a mãe e o pai segurando ali tá e eu não fiquei nervoso mano tive a calma falei legal a situação era essa Qual a tarefa Qual que você executou ele vai falar da tarefa Qual ação que você morreu e qual

foi o resultado disso o resultado pode ter sido que o pai e a mãe ficaram satisfeitos pela paciência do profissional do barbeiro e tal então isso pega cara porque o cara ele pode mentir na hora mas mentir com mais quatro perguntas ele tem que ser muito profissional irmão quanto mais a mentira vai crescendo mais dificuldade o cara vai tendo ali gaguejar E aí entrega é cara eu acho que você entendeu o ser humano né já é difícil por si só e Principalmente nesse momento eles são desses edifícios que ser tomadas Mas já deu aí duas dicas super valiosas né Eu acredito que muita gente não conhecia esse método por exemplo muita gente é não fazia esse tipo de pergunta realmente só estava preocupada ali em cortar o que se vê se o cara é se ele faz um feed legal se ele tem uma técnica realmente avançada né ah não ele que se encaixa aqui nos padrões de barbearia mas vai muito além disso né e cara é Além disso ser abrir uma barbearia agora um novo franqueado do seu Elias Como tem sido essa experiência de gestão da barbearia você já viveu um pouco

de tudo né Eu acho que você já passou por quase todos os ciclos aí de barbearia e agora essa nova fase de um proprietário e ainda gestor para o seguinte eu eu sou muito grato a Deus cara pela história que eu vivi dentro da barbearia sabe beija minha entrada na barbearia como assistente eu agendava os horários lá no Torres Cabeleireiros não tinha sistema cara era uma prancheta com uma régua e um lápis ou uma caneta que a gente anotava no quadradinho lá sabe feito no Excel mesmo uma planilha e os horários eram marcados de 15 em 15 minutos Eram quatro clientes por hora basicamente era muita gente cara eram três telefones lembro Vesper era o Vesper era um telefonezinho lá então três telefones cara eram dois celulares e era telefone o dia inteiro cara porque pensa então quatro no sábado de manhã de 8 a meio-dia tem dia 16 clientes era 15:15 não lavava não tinha degradê tipo assim o cara que passava a máquina não do lado ele era usado para caramba tá ligado não tinha feito não tinha esse negócio o lavatório que tinha lá era só para Química entendeu vamos horários eram

tipo 8:15 8:30 8:45 9 horas e assim por sequência e às vezes e as pessoas sem marcar horário também então tinha que enrolar desenrolar tudo lá eu fui Cuidar dessa parte de cuidar da limpeza de cuidados agendamentos Então fui entender um salão masculino como que funcionava quando eu comecei a cortar cabelo eu aprendi outras coisas então eu fui como eu disse aqui por exemplo antes lá no centro foi aprender a vender mais serviços aumentar um ticketing médio ia segurar mais um cliente ali então isso também foi legal lá para ele ficar esperto velho lá eu aprendi você tem desenrolar dia né exatamente Quando eu fui para o seu Elias eu voltei para ser assistente e eu precisei aprender um novo tipo uma nova coisa então Pô fui entendendo que opa não existe só a forma simples de fazer ela do centro Existe uma forma diferente também que pode ser proposta demorei aprender isso demorei aprender isso cara quando começou a ser o Elias e não entrava cliente eu ficava assim comigo pensando eu falei cara porque com Elias não me deixa lá na rua chamar os outros velho eu queria ficar lá na Sueli como

eu ficava no centro lá na rua foi ali deixa eu ficar lá na porta chamando vocês assim velho você tá doido mano não tem nada a ver isso aqui velho não é nosso perfil feliz mas os cara não entra deixa eu gritar hahaha ai bicho cabeça né velho estava acostumado né novo então fui passando essa fase depois eu comecei a liderar a equipe a minha primeira experiência de liderança foi uma frustração Total tinha 18 anos de idade totalmente imaturo me faltou acompanhamento me faltou treinamento me faltou é Maturidade me falta um monte de coisa cara foi dizer assim de tudo não foi uma experiência legal Provavelmente o Fogo Prova de Fogo Total foi complicado e um momento em que a barbearia estava crescendo eu não culpo ninguém é que a barbearia estava crescendo mas Vivi esse momento de liderança troquei de loja por várias vezes então tive oportunidade de trabalhar em quatro das quatro lojas da seu Elias e tem hoje eu trabalhei nas quatro eu entender culturas diferentes mesmo dentro da mesma cidade cara é muito diferente de comportamento né regiões regiões de poder aquisitivo e tal então tudo isso cara foi me construindo

foi me formando para ser o profissional que eu sou hoje E aí eu tive também uma coisa que aí eu posso falar que eu acredito que foi um acerto meu mesmo de ter a paciência de esperar o momento certo e muita gente enfiar nos pés pelas mãos para sair e Pô cara se tivesse esperado um pouquinho mais se tivesse informado um pouquinho mais estaria muito melhor hoje precisava aprender uns outros algumas outras coisas sabe uma coisa que o Elias fala cara e que eu sempre tive isso comigo lá dentro da seu Elias não era qualquer um o liderava equipe eu tinha uma agenda lotada eu tava começando a dar aula por que que eu sairia para rua para ser mais uma barbearia eu não queria sair mais um eu queria sair para fazer bem cara para trabalhar bem para ter sucesso para ter resultado e o resultado disso hoje é que graças a Deus a minha barbearia Ela completa ela completou nesse mês agora três meses cara e já anda tudo sozinho eu não preciso estar lá para abrir eu não preciso estar lá para fechar eu já tive por duas oportunidades passar cinco dias

viajando para fazer curso para dar aula ou para fazer aula e tá tudo funcionando cara tá tudo rodando e assim isso no terceiro mês nós completamos no segundo mês já estava assim taca eles às vezes eu vejo o dom de barbearia que tá lá seis anos sete anos 10 anos e se ele sair de lá não funciona nada a férias não consegue parar a família e quer vender aquilo ali mano ele quer ir embora Achei um cliente Cara eu já cheguei nessa fase ele chega cliente chegava O cliente tava na recepção fala tô marcado com o Luiz eu nossa mano eu não acredito velho pelo amor de Deus esse carro podia ir embora aí eu viajando assim podia faltar velho não tô afim só descansar cansaço irmão não era porque eu não gostava do cara é porque eu tava cansado velho exausto não queria mais trabalhar não tava aguentando mais aquilo né então tive a paciência para esperar isso sabe então eu fui crescendo por parte eu acredito que a gente tem que tocar um projeto bem de cada vez você não vai conseguir fazer 10 coisas muito bem de cada vez a não ser

que você tenha uma equipe gigantesca como eu tô começando eu precisava fazer bem um ponto eu queria dar mais aulas até que chegou num ponto cara em que eu tava com barbear a cara vai perder online em todos os báter o business o like seu start E aí tem toda uma demanda do meu Instagram do meu perfil que eu preciso gerar um conteúdo tem os meus cursos que eu viajo tem a barbearia seu Elias eu liderava que pensava em projetos novos e cara comecei a ficar maluco fazendo tudo isso assim praticamente sozinho aí tem a Larissa que a minha que faz hoje a minha assessoria para os cursos que responde aquilo ali eu falei cara preciso de equipe Agora eu preciso de gente então chegou o momento de abrir a barbearia isso coincidiu com o momento da barbearia começar a franquear E aí quando eu já tinha passado por esse processo falei acho que agora o time agora o momento e eu já tava me preparando já tava me preparando financeiramente para uma alguma coisa assim não tanto quanto eu achei no tanto quanto eu achei que seria mais foi e tem sido muito bem

cara graças a Deus hoje eu tenho provado a gente precisou fazer algumas mudanças lá de equipe por algumas coisas né dois profissionais que eram de outras cidades se tiveram que voltar pra cidade deles e aí a gente precisa contratar e cara já tá indo bem já tá funcionando é constantemente né um treinamento as coisas acontecendo mas graças a Deus com três meses a barbearia assim já é uma vitória maravilhosa pro pessoal aí onde que a sua barbearia Pô minha barbearia aqui no aqui em Belo Horizonte no bairro Buritis a gente tá ali que bairro que a região ali sei lá centro sul não mas enfim faço ideia do que que ali mas estamos Ali no bairro Buritis é hoje nos bairros mais populosos aqui de BH né Foi por isso que eu quis ir para lá e é a região também que eu tinha mais cliente cadastrados né o cliente que eu tinha a região que eu tinha mais clientes em que eu atendia eu falei cara e me cabe ali Acho que vou estar bem indo para lá também então tá lá no Buritis em BH quem quiser conhecer estamos na Rua Rubens Campori

Ribeiro número 707 Vai ser um prazer receber você lá não deixem de ir lá e cara você falou aí de alguns pontos também muito importantes né na sua construção aí como um todo de virar se tornar esse Líder né Mais um ponto principal eu acho que é o treinamento né pessoal esquece né acho que só de dar o treinamento uma vez já tá suficiente se esquece ali de Treinamento tem que ser constante né que o Óbvio tem que ser dito que tem que ser reforçado E você também falou da sua experiência né que você começou a ter um volume muito grande de aulas da serenidades como é que foi esse também essa inserção no mundo da Educação né Eu acredito que você não tinha nem ideia do que quero dar aula para alguém né e dá aula também é super difícil né Então como é que fez para você cara eu sempre fui muito desinibido assim eu sempre não tá aberto eu não tinha vergonha para isso não quem me chamasse ali para fazer qualquer coisa eu ia eu sempre fui muito zoeira assim muito extrovertido e tal mas para dar aula cara Jamais pensei

isso tanto quando eu recebi o convite eu fui com o Elias mano ó aqui me chamaram que que você acha velho sei lá velho eu acho que dá para você ir acho que tá legal Vai lá faz isso pega algumas dicas com ele foi lá e a primeira aula cara foi para um almoço que inclusive é muito legal você trazer aqui pra entrevistar foi pra Fran Dias primeiro você vai ter que assistir lá oh Meu Primeiro Curso foi para a Fran mano você acredita Você acredita demais chamou e tal ele deu um curso prático Na barbearia na antiga barbearia né não é não é a barbearia que tem hoje na antiga ainda é um curso para ela lá pra ela e para mais para mais uma barbeira para Aline e foi ele que eu dei processo nessa caminhada a partida ali foram surgindo alguns convites e tal mas ainda assim não foi aquele negócio que fomentou mesmo acredito que essa chama porque eu queria eu queria muita coisa ainda dentro da barbearia cara que eu ainda não tinha alcançado eu acredito que isso tem mexido comigo mesmo vamos dizer que de três ou quatro anos

para cá E aí sim que eu fui realmente dedicar mesmo enfiar a cara mesmo três anos para cá Com certeza enfiar a cara falou cara agora eu quero crescer nisso aqui e no meio da pandemia quando parou eu vi que muita gente tava quieto eu tava parada e eu comecei cara a estudar igual um maluco eu não tô brincando gente no meio da pandemia eu cheguei a passar 10 12 horas com computador ligado bicho assistindo curso online fazendo anotação acabei com dois caderninhos de anotação no meio da pandemia Dani assistindo Live e muita gente liberou curso gratuito né hoje de criatividade curso de Inteligência Emocional curso de não sei o quê um monte de coisa e eu passava o dia todo cara na frente do computador eu esqueci de comer velho Eu Perdi 8 kg em casa nesse período cara você acredita Velho 8 kg em casa porque eu acordava pegar uma xícara de café e botava do meu lado descia para almoçar depois eu só descia tipo 11:30 meia noite do quarto de novo para comer antes de dormir porque eu já tava tipo treme fraco estudando para caramba e eu lembro que eu

comentei com com o Danilo uma vez com Danilo Moretti a gente tava conversando Falou mano a gente faz as coisas não tá dando resultado porque se tentar tudo fechado eu falei mano agora a gente tá naquele momento sabe na corrida lá nas olimpíadas aquele 100 metros rasos em que tem dois apitos antes em que os corredores ele se preparam e cara a gente tá preparado a gente tá se preparando quando eu tô vendo tem muita gente em pé e nem se preparou ainda ele vai querer tentar sair Nesse estilo Tá se preparando já alonguei eu já tô na posição na hora que der eu tiro irmão na hora que soltar eu vou voar eu vou voar ele estava postando muito nisso e graças a Deus foi o que ocorreu em 2021 em 2022 foi um dos meus maiores anos confusos eu rodei assim Brasil inteiro amor hoje aqui no final de dezembro tem data agora só para o final de Fevereiro do ano que vem Caramba então são três meses aí de datas consecutivas aí fechadas e assim tem sido cada vez melhor cara e muita gente não entende né às vezes de ansiedade às

vezes por não saber por falta de conhecimento né como é importante você se preparar né como é importante você estar sempre busca de conhecimento Porque o mercado tá aí vai ter muita gente também correndo atrás e hoje principalmente como você falou né na época da pandemia foi o bom ali também do marketing digital da divulgação digital e Como foi o processo para você para inserir nesse mundo acho que muitos barbeiros ainda é não viraram essa chave né do quão importante do quão pode fazer o seu serviço escalar através do digital Então qual a dica que você dá para esse pessoal cara eu comecei a prestar mais atenção no digital no Instagram se foi quando a gente estava no meio da pandemia mesmo eu falei cara vou estudar Isso aqui eu fiz acho que com 50 60 mil seguidores velho em um ano totalmente orgânico na unha sabe de Direct todo dia respondendo geral e dedicava tempo e criava pose mas uma média de 10 a 12 posts no feed por semana era mais de um dia pô todos os dias tinha alguma coisa só que pensa irmão tava fechada a barbearia Como que eu ia

criar conteúdo se eu não cortava cabelo como é que faz isso a matéria prima tava suspensado e ali pô eu comecei a criar uns negócios comecei a pegar vídeo da internet comecei a pegar vídeo que não era sobre barbearia para falar de propaganda de tal e o conteúdo que eram compartilhar visse e tal e cara isso Começou dar um bom absurdo no Instagram logicamente ele entregava mais era melhor ainda trabalhar e no meio da pandemia tinha muita gente online provavelmente eu fizesse os meses trabalhos hoje não dariam tanto resultado mas no meio da pandemia a galera estava com o celular na mão era um momento de você atingir né a gente cara precisa pegar Style Tem gente com celular na mão tem um assunto quente tem um assunto do momento você precisa explorar isso velho é preciso explorar isso né esse ano bem que perigosamente assim mas eu resolvi me posicionar por exemplo politicamente na época da eleição né para presidência E aí cara eu eu fiz um vídeo que eu sabia que muita gente ia gostar e muita gente ia dar porrada para caramba e eu tomei e tomei pancada para caramba bem polêmica

Porque a partir da hora que você vai falar e você tá Você tá sujeito a isso né então já sabia já estava previsto mas cara o negócio tá uma proporção que eu não pensava eu gosto de tomar uma proporção de quando eu imaginava assim ficou muito maior do que eu pensava ficou muito maior do que eu achava ela fala assim Ah cara como não tem cabelo ali não vai deve chegar sei lá poucos mil views e foi passando 30 50 60 120 130 depois que passou que eu vi assim tava dando briga já a galera tava brigando não era eu eu galera nos comentários tava brigando com outro falei não mano eu vou arquivar isso aqui porque vai vai dar ruim mesmo essa semana porque a galera começou a tomar time assim mas é isso cara pegar o assunto do momento é pegar uma parada assim vamos barbeiro que não se atentou nisso ainda cara ele vai ficar para trás são várias oportunidades né quer queira ou não além do todo seu esforço do ao longo desse tempo né Você soube aproveitar muito menos oportunidades que teve né seja no marketing digital Aproveitou muito bem

esse time aí cara Quais são as dificuldades que você tem visto agora como empreendedor também antes já era né na área dos cursos e tudo mais mas agora mais ainda né E principalmente gerindo muitas coisas ao mesmo tempo é qual que é a dica para conseguir gerir equilibrar tudo isso e fora a vida pessoal a vida amorosa como é que fica tudo isso aí ao mesmo tempo cara tem um negócio que é fundamental eu vejo que tem muita gente que tem medo de fazer é confiar nas pessoas precisa eu falar para você cara até hoje eu não paguei um boleto da barbearia eu tenho uma pessoa que é uma gerente da barbearia ela é minha cunhada Ela é irmã da minha esposa uma pessoa que eu chamei uma pessoa que eu confio e até hoje no meu celular eu tenho aqui o aplicativo do banco da conta da barbearia eu não consigo fazer um pix daqui porque o token tá cadastrado do celular dela então tudo quem vai fazer cara é ela eu acompanho tudo acompanho todos os números eu vejo as planilhas eu vejo o fechamento de mesa eu busco tudo lá no sistema

tudo bonitinho eu vou acompanhando tudo só que Essas funções operacionais não é para você que é dono cara eu ouvi uma coisa um cara uma vez cara que para mim assim sabe aquele estouro assim na cabeça falei meu Deus cara é isso aqui quando você quer o profissional você é o cara com a agenda mais feia você é o cara que mais trabalha você tá cobrando mais caro do que os outros você tá ganhando grana com aquilo ali você deixa de fazer aquilo para fazer um trabalho de recepção das pagando o salário de recepcionista quando você deixa de fazer o seu trabalho para fazer um trabalho lá de comprar coisa não sei onde você tá fazendo um trabalho de alguém que pode cuidar do estoque outra coisa que o pessoal não entende é o seu valor ora né se tem que colocar justamente essa conta para fazer esse trabalho seu aí então enquanto eu tenho algumas pessoas para fazer isso a minha hora custa mais para outras coisas velho então se eu posso ter alguém para cuidar desses números só que tem gente que fala assim não vai mexendo meu dinheiro de jeito nenhum eu

sei quando tem aqui você sabe irmão ou se tiver faltar 10 centavos a mais Ali você vai conversar tem gente ruim no mundo tem cara mas vamos com calma que não é todo mundo que te inveja assim também não o alecrim dourado é calma cara é um charme pessoas de confiança quando eu chamei a minha cunhada para trabalhar comigo aqui é plena convicção de que ela não tava pronta avisava entender a cultura da barbearia ela precisava aprender sobre barbearia ela precisava aprender sobre um monte de coisa ela é mais nova ela precisava amadurecer com uma série de coisas mas ela tem se mostrado muito competente ela tem feito um trabalho muito legal né tem que começar a levar elas para os cursos agora para para quando o Michael quando Elias ou Michael falam lá sobre gestão leve ela para fazer o Barber de Business ela teve lá no no grip também para entender mais essa visão e essa parada dentro da barbearia e mexer com esse negócio na cabeça Trazer isso então primeiro ponto em que eu penso assim cara você precisa ter confiança na sua equipe eu subi lá um cara também de líder

técnico que é o Régis eu falei com ele falei cara você precisa dar mais agora mais treinamentos para os meninos ele Tecnicamente ele muito bem ele já dá aula também né ele fez dois cursos comigo fez o barbear a carne então ele é um cara que já manda muito bem eu falei cara agora se você precisa treinar essa equipe se for velho tô achando que fazer tal coisa cara o que que você pensa acho que assim assado legal concordo com você eu confie nisso pode ir lá vamos desenvolver isso na equipe junto então assim Precisa de ter confiança nas pessoas sabe eu tenho duas Chaves lá da barbearia eu dou uma na mão de um e um na mão do outro falou tá hora precisa estar aberto tá tudo certo para você você consegue chegar Esse horário tá tudo certinho então beleza e vai embora irmão descansa confia nas pessoas se algum dia acontecer um problema vai ser um imprevisto né confia em alguém cara confia nas pessoas e as pessoas elas precisam e é legal tem certeza que você ou você que tá me ouvindo agora quando alguém que sei lá tá num carro

acima de você deposita confiança em você cara a gente se sente bem a gente se sente útil a gente se sente participante de um negócio de um processo de um meio né e isso é fundamental a maior dificuldade esse processo eu acredito que eu tenho vivido tem se cuidar de tudo cara vamos conseguir tomar conta de tudo porque ainda assim no início ainda assim conseguindo delegar muita coisa ainda são muitas funções ainda são muitas coisas eu ainda tô no operacional ainda tendo muita gente ainda trabalha com muita coisa Eu não posto tanto que eu queria no meu Instagram eu não tomo tanto de conta da rede social quanto eu queria que gostaria de ter mais tempo para isso mas eu entendo que também isso é um é um processo né à medida com que eu tô no momento de de pagar os investimentos ali ainda né as coisas as contas à medida que essas coisas forem acontecendo eu já sei qual que é o caminho então o negócio é me preparar a maior dificuldade com isso cara é a gestão de tempo né quando o trabalho tá muito bem o curso tá muito bem se

alinhou tudo com a sua rede social você vai escutar na sua família pô mas você sumiu você não vem mais aqui em casa não sei o quê vai fazer você casou e eu nem fui na sua casa depois se você tem tempo demais com a família e você tá aproveitando e você volta para cá assim feliz você chega em casa e vê aquela pilha de trabalho acumulada Então cara vai sempre faltar um pouquinho não tem jeito eu costumo falar uma coisa que é o seguinte cara se você quer crescer né na profissão se você quer crescer dentro da barbearia você quer sair do lugar que você está hoje para ir para um lugar maior esse crescimento ele é desequilibrado eu não conheço ninguém que cresceu bem um equilíbrio de vida que que eu tô querendo falar com equilíbrio de vida eu vou dormir 8 horas de sono eu vou ter 8 horas de lazer e não tem cara tem várias pessoas que são super felizes assim não tem problema nenhum mas não saiu daqui do Ponto X para o ponto Y aqui muito grande o ser humano ele é movido pela necessidade é só quando

a gente tá ali no aperto na pressão que a gente realmente as histórias aí dos barbeiros Os Profissionais referentes que a gente tem de quem cresceu para caramba Elias o Rafa o Danilo o Marconi cara os cara trabalha para [&nbsp;__&nbsp;] bicho trabalha 10 12 horas por dia sai de lá vai para casa e vai estudar esse curso e tal não sei o que aí vão jogar bola Ô velho posso não tô pensando na minha carreira aqui daqui a pouco o velho vamos pra tal lugar não posso não meu dia tá aplicado dentro da barbearia tô sem grana pô mas você tá trabalhando Você só trabalha tem que viver calma pô trabalha esse tanto mas não tá aproveitando seu dinheiro cara falou que vocês um negócio se você ver várias centenas de pessoas andando para um lado e se você tiver indo para esse mesmo lado cuidado cuidado que você tá andando no meio da média e se você quer fugir disso aí você não pode estar nesse meio com certeza e fazendo tudo isso né de como você tem construído a sua vida e sua carreira né Eu acho que é muito importante centrado muito

bem definido muito bem claro aonde você quer chegar é ter as suas diretrizes seus propósitos porque vai acontecer um mar de coisas no meio do caminho que você não tá prevendo vai acontecer muita coisa que vai te chatear que vai te frustrar né e muita gente inclusive existe né porque acha que vai ter um sucesso rápido né que vai ser tudo do dia pra noite ah vou construir uma barbearia aqui vai bombar e tudo mais aí na realidade não é assim começa a dar problema o cara já fica doido aí os problemas já vão para casa então que que você recomenda o pessoal principalmente tentar pensando em abrir um negócio que pensa em iniciar essa jornada o que que é o conselho para eles conseguirem vencer tudo sem ao longo do caminho bom primeira coisa cara é Eu acredito muito em Deus eu sou cristão então primeira coisa que eu fiz na hora de decidir abrir a minha barbearia eu saber se eu estava de acordo com e Deus queria para mim orei muito é Em oração eu fiz pedido até entender que era um sim quando eu entendi que era um sim eu falei

Pronto agora é meia hora agora é meu momento agora eu vou arregaçar nesse negócio aqui vou para cima segunda coisa é quem tá com você precisa comprar seu sonho Antes de eu me casar um ano antes ali mais de um ano antes talvez de eu abrir a Barbie Há dois anos antes de eu abrir a barbearia quando eu fiquei noivo a minha esposa hoje ela já sabia e Eu montaria uma barbearia antes tem um apartamento antes de fazer uma viagem muito cara antes de ir para algum lugar de ter algum carro melhor então eu lembro que você questionado isso cara lá na casa dela né A minha sogra falou assim Ah mas e apartamentos vão morar vocês querem comprar Eles vão alugar eu falei não vou morar de aluguel porque eu vou montar uma barbearia sabe você pensa em fazer filipinhos dois anos antes já tava na cabeça já sabia né Para onde estava indo então quem tá com você e eu fui vender esse sonho para ela falei cara e ela mas tipo meio desconfiada né vai não vai como é que vai ser isso os dois pés atrás e nós vamos morar aonde

é dentro da barbearia né vai ter aquela desconfiança até mostrar falei Calma Vamos investir aqui primeiro você vai dar um retorno atrás a gente tá num momento de vida ali e tal enfim primeiro ponto eu entrego para Deus e se for de Deus amém segundo ponto o seu cônjuge que o seu parceiro quem tá com você se você for solteiro não né mas quem é casado a pessoa que tá você cara precisa comprar seu sonho porque senão na primeira oportunidade que der alguma coisinha de errado Na barbearia tá assim viu eu falei falei que não era para fazer aí começa as brigas você já tá pilhado que deu errado você vai responder com educado né Já tá se vai ficar maluco não precisa desse apoio tem dia que eu desanimo indica que ela tá meio desanimada Então vai ser um ele ajudando o outro terceiro ponto se prepara mentalmente cara fica esperto mentalmente porque tem gente acha que vai entrando e com a expectativa sempre aqui em cima é lógico que a sua felicidade sua alegria ela vai ser aqui em cima mas não vai dar o tempo inteiro só alegria a gente já teve

o dia lá na barbearia cara na segunda-feira que entrou uma pessoa e a vontade de chorar aqui primeiro mês cara assim a primeira semana a gente bombou bombou todos os dias da semana eu falei nossa a gente manter isso aqui até o final do ano eu tô três Nossa eles vão falar para mim que eu ia pagar a loja com dois anos eu vou pagar com 6 meses eu tô tô rico e cara na semana seguinte passou uma pessoa lá cara isso é normal porque ninguém conhecia cara tá uma barbearia nova no bairro novo ah é uma marca sim mas tipo assim na mesma semana no fim de semana nós atendemos sei lá 52 pessoas no sábado mas no dia na segunda-feira lá em específico tinha passado uma pessoa e isso mexeu comigo até que eu ia embora para casa eu falei espera aí cara eu tô fazendo uma análise macro eu tô pegando um dia individual me esperando por causa disso não se prepara mentalmente antes para saber que você vai ter Dias bons ou ter dias mais ou menos e Vai ter dias ruins é natural se prepara o seu trabalho é o

que diminuir o dias ruins trabalhar em cima dos dias mais ou menos para que todos eles sejam bons Então você vai ter mais resultado Então se preparar mentalmente para isso também é fundamental e acredito que quarto ponto cara tem que ter dedicação demais mano pode trabalhar não precisa de vontade aí tem hora que você não sabe e esses são esses momentos cara que eu acredito que sai o melhor de nós nesse momento que tipo assim eu cheguei em momento eu falar assim Eu sempre tive muito projeto eu sempre fui muito bom em pensar em projetos eu sempre fui péssima tirar isso do papel eu planejo guarda a ideia planeje planeja planejado da ideia E aí cara pensando chegou em momentos de eu falar assim ou paga essa conta aqui ou sei lá vão cortar vai atrasar vou com o cheque especial Então eu tinha que fazer o projeto ou eu faço para eu ganhar um dinheiro e pagar isso ou eu vou vai dar ruim então assim isso te obriga a fazer mais sabe se te coloca numa posição de fazer mais é esse instinto de sobrevivência né Vamos chamar assim eles colocam mais para

frente e quando tá na zona do conforto tá tudo ótimo tá tudo lindo né exatamente mas eu acredito sempre que a gente pode muito mais é tem pessoas que vão querer ali como você falou manter na média aí pô tá tudo certo pessoal que não quer não quer a vida tá aí pra tudo pra todos os gostos podem ver do jeito que quiserem Mas eu acredito muito e é por isso que a gente sempre tem até mais né a gente traz esse tipo de conteúdo a gente faz nosso projeto a gente corre atrás e principalmente sempre Tentando Manter o time é acho que isso é fundamental para qualquer sucesso cara e dentro da sua carreira é o principalmente com acredito que uma das maiores referência você vai ter vai ser o Elias ou de quem que você achar também pode ser uma referência qual que foi o maior ensinamento que essas pessoas conseguiram trazer para sua vida cara então eu tive algumas pessoas que me que me Trouxeram muita inspiração assim vou falar de três Aqui foram de três assim que principalmente no meu começo assim quem mais me impulsionou primeiro Elias para dedicação porque

eu vi que era possível cara Eu ainda acredito fielmente de quem mudou a visão do que que é ser um barbeiro no Brasil foi o Elias é ele mostrou que é capaz dá para crescer dá para ganhar grana dá para viver bem dá para andar de carro bom e eu olhei essa frase pra gente em 2013 eu quero crescer a barbearia porque eu quero que Barbeiro de carro bom vai em restaurante mais caro da cidade anda de roupa de marca vai nos melhores lugares porque a gente tem que se respeitado cara pela profissão que a gente faz em 2013 cara olha isso todo movimento né Exatamente olha o que que o negócio virou e continua com a mesma coisa ele continua falando espanhol galera velho Pega com a gente cara tá conversando foi mal Ô ilusão vou te passar o contato da minha gerente lá pega um cartão Black para você pega não sei o quê ele quer te fazer crescer cara veio pra frente ou eles me mostrou que era possível uma coisa que eu não achava eu vim de uma família muito simples eu nunca tive é antes de trabalhar com Elias eu

nunca tive essa vontade aguçada de mudar de vida de querer ganhar grana de você e quando eu vi que era possível viu Elias fazendo me colocar nessa pilha eu falei mano pô ele tá aqui do meu lado ele tá fazendo eu também consigo ele tá me incentivando a fazer cara então dá para fazer eles me aguçou isso então essa mudança que eu tenho de vida ela primeiro foi aguçada lá atrás mas para essa mudança cara demora e para qualquer coisa que você for fazer durante bastante tempo você precisa de disciplina um dos caras mais disciplinados cara ele não é o cara mais talentoso para tudo que você for ver mas uns caras mais disciplinados que eu vi até hoje é o Rafa o Rafa é fenomenal quando ele se propõe a fazer uma parada cara ele vai cumprir aquilo ali ele vai fazendo e pronto ele trabalho não tô afim de fazer ele vai fazer ele vai cumprir o cara consistência cara com que é feito vou te dar uma ideia um exemplo por exemplo de produção de conteúdo no Instagram a consistência com que o Rafa produz cara é diariamente né todos os dias

sem conteúdo tem aquela ali e tal é isso aqui tem que ser feito beleza é muito bem feito muito bem produz e cara mas eu te dei manda muito tempo esse demanda muita energia e vai todo mundo falando né ou lesão está cansado vai descansar até você nem tá mas as pessoas te falam tanto você acredita que você tá cansado eu olho pra minha cara fala caramba mas logo hoje é olheira e tal Hoje que eu dormi bem cara você tá na pilha você quer fazer mais coisas você consegue fazer mais você sabe que você consegue produzir mais e eu fui cair nessa pilha uma época tô cansado preciso sair dali preciso descansar depois do trabalho eu vou dormir depois do trabalho não sei o quê E aí cara a minha terceira inspiração Foi a terceira inspiração maior assim quer dizer que mandar um beijo para ela beijo amor a minha esposa cara como e quando não quero fazer falsa modesta aqui para vocês eu ficar fazendo média não mas é porque a [&nbsp;__&nbsp;] é irritada velho eu lembro que ela trabalhava também no lugar trabalhava durante o dia e ela saía de lá e

ia para faculdade à noite uma fase Odontologia ela conseguiu 40% de bolsa lá porque senão não era impossível fazer não dava para a gente fazer elas dedicou estudou fez a prova lá e a gente conseguiu o negócio e aí como era muita matéria era muita coisa ela precisava aproveitar não podia você não pode pegar uma uma matéria de dependência alguma coisa que você perde isso né então ela no outro dia acordava mais cedo acordava 4:30 5 horas da manhã estudava até às sete cara orar que tinha para sair de casa para trabalhar trabalhava o dia todo saía de lá ia para faculdade saia da faculdade 10:40 no outro dia levantava 5:30 6:00 de novo Dormi umas três horas por noite né cara e nesse ritmo bicho trabalhando estudando e tal não sei o quê e aí fim de semana eu vou não tô cansada né não tem os projetos na igreja ela cantava na igreja liderava um negócio aqui ajudava em casa a fazer as coisas aí eu falei meu Deus cara e eu vendo tudo isso eu falei irmão eu faço muito pouco cara tô cansada nada tô cansado do quê velho eu tenho

que ter vergonha na minha cara então assistir ela cara tem muita gente me fala isso velho você não dorme você não cara foi porque eu vi que era possível mas para que eu visse que era possível precisei isso com ela então Primeira coisa eu enxerguei que era possível vendo Elias fazer ele me colocou essa visão eu me tornei mais disciplinado vendo alguém disciplinado que foi o Rafa vivendo ele se propô a fazer as coisas e terceiro com gás com essa energia que eu tenho conseguindo assistir a minha esposa fazer de perto cara na época a gente namorava ainda então quando eu conseguir ver isso eu consegui enxergar esse casal essas três vantagens as três pessoas ao meu redor assim São pessoas que me influenciaram demais assim sabe vocês estão quanto tempo juntos a gente tá junto às 7 anos agora completa no final do ano Caramba então muito tempo aí também então ela te pegou lá no comecinho a gente começou que eu tinha 19 anos ela tinha 18 é a gente tá não tem bico forte né cara como é importante né você ter esse tipo de pessoa do seu lado né pessoas que

querem o seu crescimento que querem ver você avançar e que te fazem expandir o seu Horizonte né Eu acredito que se você também ficar andando só com pessoa ali que te joga para baixo ou que se quer só ficar na média e você quer ser Acima da Média você não vai a lugar nenhum né o famoso ditado a guerra anda com águia é então você quer alcançar voos mais longos você tem que realmente almejar e correr atrás e principalmente se espelhar naqueles que contribuem né cara não tem jeito com quem que você anda vai influenciar é tem um cara que fala isso né me fala com quem que você anda falando você vai estar daqui 3 anos irmão isso é loucura velho ao longo do tempo eu fui quase que vamos falar trocando mas eu fui deixando de andar deixando de estar mais presente com algumas pessoas os caras só queria saber a mesma coisa o que eu tinha pensamentos diferentes entenda uma coisa cara O problema não é de quem que é alguma coisa diferente o problema é seu de estar com quem tá vivendo essa vida porque cara vai ter gente que quer

viver com festa com balada com isso é da vida e o cara tá na vida dele o negócio é você escolher se você quer isso ou não não é que você não possa ter amizade com alguém que pensa diferente de você pode sim mas talvez não seja a pessoa que você vai mais ouvir que você vai pedir conselho que você vai contar seus sonhos que você vai contar seus planos que você vai estudar junto você vai trocar uma ideia ao invés disso Cara eu preferia ficar sozinho eu não sou um cara de diversos amigos eu tenho pouquíssimos amigos sabe eu tenho poucos amigos próximos a mim eu tenho menos gente ainda que eu me abro que eu converso que eu conto os planos Mas essas pessoas cara são pessoas que eu tenho confiança que eu sei que estão olhando para a mesma coisa tão milhando tão estudando tão crescendo estão investindo sabe então isso te aproxima e vai te colocando cada vez mais aí pô tô lendo uma parada aqui eu lembrei de você Eu tô lendo um negócio que eu te mando aí eu tô fazendo eu mando para alguém junto também então entendo

que esse Network vamos chamar assim entre mesmo entre os amigos são pessoas que vão se colocando para frente é todo mundo crescendo velho eu não quero crescer sozinho quero crescer com todo mundo junto cara o cara que minha família esteja comigo quero os meus amigos estejam comigo se eles não quiserem tá tudo certo continuar aí crescendo os meus momentos de Lázaro eu vou estar lá mas no meu momento de trabalho cara momento de investimento eu preciso estar separado e hoje é a coisa mais valiosa que a gente tem é o tempo é como você bem citou aí e muita gente não entende que cada relacionamento né é uma dedicação que você tá dando ali tanto de energia Quanto tempo né E se você se dedica as pessoas erradas você vai perder tempo na sua vida vai estar perdendo alcançar os seus sonhos para ter o seu sucesso e muita gente perde tempo justamente nessa né perde o time às vezes de uma oportunidade justamente porque não está no lugar certo ou com as pessoas certas né e a importância do Network né como você vem investir nisso hoje como você é ver o Network hoje

Principalmente nesse ramo da barbearia é o que tem feito uma diferença brutal na vida dos barbeiros E como que tem sido para você também isso cara seguinte a gente precisa de pessoas também né tanto para desconectar com alguém com indicações ou parcerias E aí eu fui entender que no meu Network eu precisava crescer para a área dos cursos por exemplo ali que eu virei algumas Chaves ali para mim para entender que o Network ia me facilitar e me fazer crescer em relação aos trabalhos aos cursos que eu dava né que eu queria dar na verdade que eu queria crescer mais E aí eu fui conhecendo pessoas os produtores ou gente que tá lá em tal estado com barbeiros me aproximar da Galera então por exemplo sempre que eu estive em algum lugar sempre fiz questão de vamos dizer que o contratante ele é o meu cliente ela tá me contratando o que que ele vai achar de mim depois ele vai me dar um feedback ele vai me dar um retorno ou alguém quando for me contratar pode pegar uma indicação com ele depois né então estar conhecido nesse mérito Mas eu precisava também estar

conhecido no meio de quem os conhecia né então o que que eu entendi e aí foi uma oportunidade legal que funcionou muito bem para para mim nesse caso o Moisés que é o cara que faz que é o produtor do Elias né que vem discursos inclusive ele também na primeira temporada ele recebe muito contato muita gente para produzir evento para muita coisa né E aí o Moisés ele ele a esposa dele saiu lá do bar dele Ela trabalha lá durante um tempo eles tiveram e tal e aí eu tava precisando de alguém para cuidar da minha parte de agenda tá essas coisas para fazer essa parte comercial e aí eu falei cara aí ele ofereceu Foi caro Você acha que a Larissa vai bem para fazer isso aqui eu falei top demais tão legal ela faz o meu e do Danilo eu falei mano que massa vamos lá vamos junto e eu pensei comigo falei mano isso é legal porque se chega muita coisa no Moisés eu já tô no meio dele aqui isso já tô próximos Tá massa mas não só ali cara eu precisei aumentar esse networking ali comigo como na minha rede

social se eu não conseguir estar em muito lugar o tempo inteiro por exemplo Dentro de Belo Horizonte mas é legal mas eu queria ir para fora eu queria ir para outros lugares Não precisei começar a interagir com mais pessoas para poder começar a interagir com o Barbeiro de fora com pessoas de fora com gente lá da região por exemplo eu quero ir lá para lá para o Rio de Janeiro por exemplo Pô vou interagir com a galera de lá vou trocar uma ideia com a galera de lá porque daqui a pouco tem um contratante perguntando tipo falando sobre aquilo falei eu tenho o Luiz aqui que é legal então não só para isso para cursos mais no meio da barbearia para entender do meio da barbearia eu sempre fui de muito de trocar ideia de fazer amizade e tal e aí cara trocando a ideia fazer uma amizade foi muito ó o negócio eu tô com um problema lá no meu aplicativo aí como que vocês fazem isso aqui meio que despretensiosamente mas é usando velho é uma ajuda um para o outro né Tipo se eu vejo que você tá numa caminhada de crescimento

da sua empresa e eu também tô a gente já se aproximou mais cara então já fica mais fácil né então assim andar no meio de pessoas que que também estão fazendo mesmo trabalho tão relevantes talvez diferentes em coisas diferentes é fundamental para que esse é tipo o que acontece e muita gente quer crescer mas não quer justamente ter o esforço de correr atrás desse crescimento né não quer justamente chamar uma pessoa ali de uma outra região conversar falar mas eu não conheço Tanta gente assim ah mas eu não conheço ninguém lá do Rio de São Paulo é mas tá dependendo só de você né Eu acho que não todo né tudo depende só de você né porque você pode ter as melhores oportunidades do mundo outras pessoas ao seu lado mas se você não correr atrás isso não vai valer de nada né e eu vejo que você correu muito atrás alcançou muita coisa alcançou muitos projetos Mas que que você espera para o futuro o que que o Luiz Gustavo Quais são os planos aí para frente cara vou abrir isso para vocês aqui mas eu nunca nem trouxe isso cara nunca contei isso

para ninguém vou contar isso aqui a primeira vez cara espero empreender muito sabe eu espero não parar na primeira franquia não parar na primeira loja quero fazer mais barbearias eu quero ter mais coisas bem focado assim não tem gente que fala de propósito né e eu sempre falei assim ah mano propósito é que depois que tem dinheiro no bolso né porque é muito mais fácil falar para os outros ter propósito não corre atrás de dinheiro o bolso com seu próprio quando você tem dinheiro é fácil falar isso né É E aí assim depois de entender isso cara de entender alguns pontos entendeu algumas coisas não necessariamente era só isso né Não era só por causa do dinheiro mas olhando hoje eu comecei a entender que eu quero ter eu enxerguei uma missão um propósito vamos dizer assim de realmente levar uma parte de gestão de pessoas de liderança para dentro das barbearias eu quero poder ajudar eu quero poder evoluir esse processo de profissionalização das barbearias eu vou focar muito nisso a minha carreira daqui para frente né em Expandir os negócios em fazer com que Empreendimentos sejam cada vez maiores e em segundo lugar

implementar isso projetos de contratação de treinamento de motivação de engajamento Da galera né projetos como por exemplo eu fui um dos idealizadores A Primeira ideia ali que eu levei lá do Punho de Ferro né que a gente tem lá na barbearia Suel Elias para quem não conhece é um esquema de premiação que a gente tem lá de gameficação dos colaboradores que tá dando resultado para caramba um mega evento último né cara tá sendo evento foram três até agora se eu não me engano três ou quatro a gente não foram três né E já tá dando muito resultado e não só pelo engajamento da Galera os números subiram números estão melhores né A galera tá mais feliz a galera tá mais para cima a galera participa mais na empresa e os números são melhores Então você quer ser nada melhor que esse então testando isso cara eu fui entender que eu falei cara dá para fazer muito mais e quando eu vejo algumas barbearias parado com muita coisa falei não vou implantar isso aqui O Elias foi o responsável pelo crescimento das barbearias ela pulverização das barbearias no Brasil agora o cara são um dos responsáveis

pelo crescimento profissional dentro das barbearias agora as barbearias já abriram agora vamos profissionalizar esse negócio crescer mais crescer com qualidade exatamente não são todas logicamente tem barbearias aí magníficas com processos maravilhosos aí de treinamento de tudo mas para Muita gente Ainda não tem e assim eu tenho isso comigo de desenvolver isso ao longo do tempo agora né vou pautar bem a minha carreira nisso e dispandir cara de crescer quero empreender quero crescer quero ganhar dinheiro se vocês estão me vendo aqui agora gente eu não tô rico mas eu pretendo ficar é um objetivo de vida se você achar que ah para mim não tá não precisa Ah quer viver bem com conforto não rico mesmo sabe rico quero eu quero isso exatamente assim ah quero ficar confortável não é Hitler quero ganhar dinheiro cara eu vim na realidade muito simples e eu quero mudar isso eu quero poder mudar para minha família mudar para minha esposa poder mudar lá para a igreja que Eu congrego as pessoas que eu ajudo né para as pessoas em que estão próximas a mim poder ajudar a gente cara eu quase não fui barbeiro porque a gente não tinha

dinheiro para comprar material Pensa a minha mãe e meu pai parcelaram no cartão de crédito lá eu quero ajudar a gente quero ter projeto assim sabe poder financiar material poder dar material para as pessoas poder ajudar com o curso poder ter algum lugar que ajuda pessoas assim sabe eu sei que pô eu lá atrás não pensaria que eu poderia chegar aqui hoje alguém estendeu a mão e me ajudou eu quero poder estender a mão para ajudar mais gente também só que pra isso E para isso de recursos exatamente então assim eu pretendo bastante isso cara crescer bastante crescer ajudar mais gente e fazer Impacto assim realmente barulhento no mercado da barbearia cara e para quem ficar achando aí a Luisa soberba quer ficar rico e não sei o quê mas todos vem aí quer comprar um propósito né não é simplesmente pelo dinheiro né o dinheiro ele quer queira ou não é uma ferramenta que facilita muito as coisas né E principalmente você ajudar os outros né você consegue criar muito mais oportunidades quantas pessoas não querem uma oportunidade né não estão doidas para se esforçar dar o máximo de cima mas infelizmente a oportunidade

não chega até elas então que bom cara que bom que você quer fazer isso por pessoas mas pessoas como você né Assim como Elias né entendeu a mão aí pô você virou um fenômeno que possa gerar muitos frutos tudo isso daí também cara eu tenho só agradecer né por esse momento para esse papo de qualidade Espero que possa alcançar muitas pessoas Espero que possa ajudar muitas pessoas o seu sucesso já é mais que realidade Mas eu acredito que você chega muito longe ainda Pô ainda tá novo né cara cheio de energia aí para gastar mas para a gente fechar Qual que você acha que é então o seu propósito de vida Ixi mano aí pega pesado eu acredito que hoje o propósito que eu tenho é muito pautado sobre impactar positivamente a vida de alguém transformar em alguma coisa que talvez essa pessoa achava que não poderia ser assim como foi comigo e é o que eu tento fazer com os meus colaboradores com os meus amigos com as pessoas que estão lá na minha célula por exemplo lá na minha igreja mostrar que dá para fazer alguma coisa maior alguma coisa melhor e eu

só faço isso porque constantemente eu enxergo que dá para eu ser mais do que eu sou hoje e dá para eu crescer que dá para eu evoluir Então quem tá do meu lado tô sempre puxando para frente não é fácil trabalhar comigo eu cobro muito eu tô sempre muito exigente mas é um exigente no sentido de que eu olho e fala cara André você consegue sim mas cara e se você não consegue cara mas eu quero ser isso mas eu não tenho medo de fazer isso vamos aprender junto eu aprendo te ensino a gente ler junto a gente faz um curso Vamos fazer vamos juntos assim sabe eu acredito que hoje o meu maior propósito cara é desenvolver pessoas é fazer essa parte de liderança mesmo guiar eu entendo que o líder alguém que desenvolve que treina pessoas sabe todo o restante disso vem como consequência eu como educador quando eu vejo que um aluno meu ele cresceu na profissão Nossa cara não tem problema na cidade maior na minha vida real isso é legal para caramba sabe ver que eu pude meu propósito maior Talvez seja esse né impactar positivamente a vida de cada

um talvez que um dia com aprendizado que você teve alguma coisa que você lembrou e falou assim pô cara com o Luiz me ajudou com isso aqui para mim vai me dar uma satisfação maravilhosa que não tem dinheiro no mundo que pague isso sabe show demais com certeza a minha vida você já impactou com esse papo aqui super esclarecedor super agregou pra nossa vida né Principalmente aí Espero que agregue a vida dos barbeiros principalmente na Gestão na cultura super dicas aí para você para ter um sucesso na sua profissão também e nós estamos aí também para te ajudar na sua carreira para aliviar aí uma série de coisas que você não precisa gastar energia o best Barbie mas é o melhor sistema de agendamento em gestão para barbearias a gente pode também vai te ajudar a ter sucesso em tudo isso irmão mais uma vez obrigado Foi show demais espero que a gente consiga juntos impactar através desse Episódio muitas pessoas aí para cumprir seu propósito de vida meu irmão estamos juntos Muitíssimo obrigado pelo convite são você a galera equipe toda aí do best Barbie que plantificou também querem receber Muito obrigado para você

que assistiu Muito obrigado se você nos acompanhou até aqui fica honrado de coração obrigado por todo carinho admiração que eu recebo de todos os lados eu sou muito grato a Deus por isso e a cada um de vocês também tá muito sucesso para todo mundo fiquem com Deus Valeu demais para fechar para fechar depois que que é isso velho para que que é isso nosso Episódio Com certeza aqui pera aí agora sim o que que é isso mano Tô com moral aqui velho cara não mexe babes a gente também não pensa só em ser um sistema de agendamento né um sistema de gestão aí para ajudar o pessoal mas a gente pensa justamente também em tornar as pessoas aí melhores alcançar aí ó os melhores versões de cada um abraço tem camisa se liga é tem Caraca velho tem tudo aqui galera obrigado demais viu galera pelo presente pelo convite pela lembranças são sensacionais Obrigado irmão Eu que agradeço [Música]`,

  summary:
    "Episódio 2 da Temporada 2 do BestBarbers Podcast. Luiz Gustavo compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
