import type { VideoContent } from "./types";

export const podcastalvaro_daniel_S2_ep06: VideoContent = {
  slug: "podcast-alvaro-daniel-s2-ep06",
  youtubeId: "_WcoqfMyDjM",
  title: "BestBarbers Podcast com Alvaro Daniel — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 6 da Temporada 2 do BestBarbers Podcast com Alvaro Daniel. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "alvaro daniel",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2023-03-06",
  duration: "1:09:09",
  category: "Podcast",
  tags: ["podcast", "temporada 2", "entrevista", "gestão", "barbeiro"],

  transcript: `[Música] prazer ter você nos acompanhando para quem ainda não me conhece eu sou André um dos donos aqui do best barbras e hoje tem a honra de receber essa fera aqui astro da barbearia esse cara falando bem Aqui quem dera meu querido Álvaro Daniel para quem ainda não segue ele no instagram@alvaro_debar o barbear e o nosso @bertbarros.ep Então siga a gente antes de mais nada cara sem mais delongas vou pedir para você se apresentar para galera contar um pouquinho aí como é que foi a sua trajetória Por que que você decidiu ser barbeiro Quais são as dificuldades que você enfrentou até chegar onde você tá hoje Daniel meu Instagram então sou um cara curto e grosso né caminhada dentro da barbearia né nunca foi fácil eu com meus 24 anos de idade eu tinha trabalhado como sommelier é vendido então eu tinha um amigo que trabalhava com barbearia sempre cortava o meu cabelo e tal e um dia ficava cara você trabalha muito bem você fala um serviço muito legal Dá até vontade de aprender você não faz um curso barbeiro Ah cara não tem nada a ver comigo não gosto de carro e tal

não tenta pesquisar tenta correr atrás né para você ver se realmente é isso mesmo então cheguei nessa época eu tinha saído desse sommelier tava com uma graninha e falei com meu pai Pai preciso de um fazer um curso de barbeiro e tal tem essa grana para investir mas vai faltar e tal ele não eu te ajudo né Passa meu cartão meu filho eu quero que você vire um profissional de exemplo e tal e matutando essa ideia aí cheguei no meus amigos Cara eu tô querendo fazer um curso de barbearia os cara você é doido barbearia Vai fazer uns mecânicas né Depois de um homem não é cabeleireiro né tem essa briga de cabeleireiro e barbeiro com os cabeleireiro e tal cara é o que eu quero eu desejo né e eu quero buscar isso os caras me zuou demais baixei nada a cabeça levantei bola para frente e fui né na época ela tinha um Itec que é o Instituto técnico cabeleireiro aqui na Rua da Bahia e tal fui lá Paguei minha inscrição lá fiz grandes amigos lá dentro a maioria os meus amigos fizeram vieram Cabeleireiros né femininos Hoje os caras são estouradíssima

em Belo Horizonte e tal e referência e comecei dois meses fazendo curso de barbeiro né lá dentro sair meu primeiro Salão que Mila dentro do mercado central cara eu fui ser barbeiro dentro do mercado central da Galera falava comigo assim ô velho é o corte que ganhou abacaxi tem esse essa piadinha aí cara a gente não dá para caixa a gente corta cabelo então eu acabei meu curso na sexta no sábado o cara falou assim você pode vir que amanhã cortar cabelo e cara mas eu nunca trabalhei e tal não você já teve uma experiência aí já a compra com aprendizado aí no curso pode vir aí eu cheguei no sábado cara não tinha nem secador nesse dia eu cortei 17 cabelos eu não sabia nem que eu tava fazendo né que a gente a gente no curso a gente tem umas etapas né ó separa o cabelo aqui você começa com lá O Cagão velho já começa a K2 aqui em cima e a um ser só paga o pezinho aí e marca a barba do cara e corta em cima e libera Que A Gente Tá agarrada a filha grande e eu tava

sentado na minha cadeira eu sentando no bambu cara cortei 17 cabeças né mas foi um grande aprendizado na minha vida fiquei lá 9 meses até que um cara passou um dia lá me olhou ficou me olhando ficou me olhando falei cara me conhece e tal ficou me olhando não cara Fiquei vendo você trabalhar aí e tem interesse de chamar você para você trabalhar no meu salão ela não Padre Eustáquio tá um Chanel ele é mesmo cara é quero que você faz um teste lá porque eu perdi um grande barbeiro lá que tava lá cinco anos saiu para beber barbearia dele eu gostaria de estar dando essa oportunidade para você lá fazer um teste e tal Olha lá vou vamos lá né aí cheguei lá o poste era um poste maior Era quatro Cabeleireiros femininos era mais quatro barbeiros era sete manicures é tinha sala de estética ela mais ou menos uns 25 profissionais Nossa prova de fogo né para quem trabalhava no mercado central com quatro cadeiras aumentou aí fui comecei esse cara me ensinou tudo a minha base de química minha base de fazer Química de progressiva todos os procedimentos assim né para cabelo

masculino foi ele Edilson que chama o cara que eu guardo muito do coração e se eu comecei a ganhar grana e tal e fazer aqueles aquela época Os meninos gostaram de casa escovar o cabelo ficava o cabelo arrepiadinha assim aqueles moicano fiquei fera naquilo e passava aquelas pomadas nervosas aquele topete aqueles cabelos bem arrepiados e eu falei ó tô bem pra caramba né Estou bem para caramba e um amigo meu né que trabalhava com um salão feminino Trabalhou muito tempo sério Faria uns grandes salões dentro da BH ou alvo tem um cara velho que tem uma barbear montou uma barbearia legal lá no bairro Ouro Preto segue a escada né Facebook nem Instagram ainda segue esse cara esse aqui ó eu li os cara legal mas tipo assim sabe nem quem que era porque a gente salão de baile a gente fica muito loucamente pequena né Fechado só naquele espaço né aí Eu segui cara ele não o cara montou num conceito de barbearia legal e tal tem muita ideia não mas eu fui ficando meio limitado dentro onde eu trabalhava Eu já queria crescer eu queria já aí a barbearia estava começando a crescer

né dentro de BH e eu queria despontar aí eu falei cara eu vou vou mandar mensagem para feliz outros bem trabalha aqui no salão Chanel e ele conhecia porque o primeiro Salão que ele trabalhou junto com o irmão dele foi no Padre Eustáquio e esse Chanel era da região ele conhecia cara é tão montei aqui e tal mas o time tá completo e tal mas tem seu telefone aqui esquenta a cabeça não né porque a gente mandava eu postar muito foto de Costa no Facebook e tal ele começou a seguir lá no Facebook e tal aí um dia ele me chamou o cara a gente tá fazendo um teste a gente vai abrir a barbearia maior Você tem interesse de fazer um teste com a gente aqui falei claro tenho certeza então é Me manda as fotos aí pelo e-mail eu não te é cara eu não tinha e-mail aí eu falei nossa como é que eu vou fazer aí tinha uma amiga minha e Taiara gente boa demais eu gosto muito de você viu tô sumido você ela cria um e-mail para você tem como Uai você trabalha no Chanel Seu nome é Álvaro

seu filho ideal vim faz ao vivo Chanel ué isso até hoje cara falei uai vou fazer então eu fiz um e-mail Chanel né bonitinho tal mandei as fotos aí teve dinheiro a gente faz o teste eu marquei com um cara velho um dia antes cara você vai né modelo Não foge não ou precisa é uma coisa né muito sério Beleza tamo junto cara beleza o cara era cliente meu já seis anos lá não vão beleza vamos vamos chegou o cara não podia não entendeu nenhum telefone cara não atendeu o telefone eu fiquei desesperado que era meu teste e o Elias olhando para mim e falei assim nossa ele é o seguinte os caras tinham chegado com os modelos eu não tinha chegado meu modelo ainda nossa o único que não falei nossa aí tinha um amigo meu que estava indo para um rolé Diegão tamo junto hoje você é careca mas quando você tinha cabelo você não deu moral para [&nbsp;__&nbsp;] me salvou os cara tava indo para um rolé tava ele Fabiano Maurinho estava dirigindo uma feirinha do Mineirinho vem vira esse carro aqui eu preciso cortar seu cabelo Cara eu tenho um teste

e tal aí os cara foi me deu moral passou lá deixou ele lá aí ele tinha um cabelinho cortei o cabelo Relaxei na época tinha relaxamento né e relaxar o cabelo dele ele fez um arrepiadinho então bacana e tal a gente entra em contato com você beleza aí sumiu uma semana velho o cara não falou nada comigo eu era eu sou um cara muito ansioso trabalho isso né Graças a Deus hoje estou bem menos mas eu ficava assim será que eu mando mensagem fiz alguma coisa de errado você não gostou e tal aí ele mandou mensagem para mim cara tem como você vir aqui hoje à noite para a gente conversar falei tem aí eu fui lá e conversei com ele troca uma ideia e tal e nada de falar me contratar eu falei não e tal você trabalha aonde você mora aonde Ah trabalha no Chanel moro no Itapuã e minha vida toda do lado da Pampulha e tal aí você trabalhou não já trabalhei em salão e vai fazendo aquele sério questionamento comigo beleza era um cara nessa época Como assim ele é um cara religioso Mas é porque ele era um cara

muito mais entendeu assim não que ele deixou de ser mas ele ele ficava assim pô eu acho até legal você precisa você precisa ter uma invocação assim né buscar mais Deus sempre pregava para gente né mostrando os bons caminhos não é porque o cara é não o cara é cristão está pegando meu pé não ele sempre dava bons conselhos uma fala que ele tem que ele fala até hoje contrato você pelo caráter não pelo que você é profissional meu professor pode ser muito bom mas pode ser mau caráter e isso que ele falou comigo então você que eu vou te ensinar né você não é um bom profissional eu achava que eu era top você não é um bom profissional você vai aprender você é lapidado né mas eu quero ser o caráter né Eu quero que isso possa acreditei em você aqui você tá mostrando a pessoa que você é realmente tal e eu quero te dar esse voto de confiança eu quero estar mais perto de você e tal lá então beleza então mas é como é que vai ser não já tá contratada estou contratado Nossa do cara que isso e ele

tinha feito acho que só era um 50 caras tinham cortado o cabelo lá 50 testes isso para quantas vagas uma era para duas vagas duas vagas duas vagas aí nesse nessa época passou eu e passou o Elon que trabalha comigo até hoje eu não cara se eu achava que eu era bom era 20 vezes pior o elão tava tinha acabado de fazer um curso tava né Começando na área da barbearia e tal e aí então praticamente seis anos de profissão você foi para o Elias em terceiro lugar que você trabalho isso é lugar aí Eles contratou a gente e cara O Elias é um cara muito perfeccionista né Lógico que é o dele que tá na reta né cara tá com dois meninos novato esse cara tava já no áudio bombando e tal mídia televisão o cara tinha que mesmo que voltar a gente na na coleira mesmo Pô velho vocês podem ser mole e tal então no começo cara fiquei muito assim puxa véio Elias vai me esganar porque eu faço cada coisa aqui cara ele Nossa não é assim não me chamava lá para a gente começar e tal me dava ideia no

outro dia fazer errado e tal e eu demorei a entender isso né que isso era importante para a marca dele né eu não sabia a grandeza que ela já estava e fui acostumando aos poucos Falei pô o lugar que eu tô trabalhando a gente foi Pioneiro dentro da barbearia a primeira a gente foi Pioneiro muita gente hoje que tem né vários profissionais hoje todo mundo dando curso e tal mas não tinha isso né antes beleza não tinha nada de barbearia não né mudou o planeta Então fui né e tal e lá íamos jogadores né de futebol um jogadores sempre atendia porque só ele que atende os jogadores no começo mas alguns o Rafael o Luiz também já atenderam alguns mas era muito poucos sempre procuravam mais o Elias aí eles vão daqui a pouco Caiu um jogador no seu colo aí tal Fica tranquilo e tal aí o primeiro jogador que eu atendi foi o Alessandro velho jogava no América lembra um branquinho jogou no Atlético depois Primeiro o cara que eu aprendi o cara sentou na minha cadeira você vai entender o Alessandra Pô olha só é hoje é hoje e tal cortei o

cabelo dele tal não ficou top menino aí é bom e tal Eu falei não fechou aí passou um tempo ele vai atender Paulo César Célio César beijo para você gente boa demais uma pessoa do bem sabe um cara de família um cara aqui dentro do futebol para mim é um psicólogo né ele dentro do Atlético ele foi um cara que ajudou vários jogadores a desenvolver essa essa mente né dentro do futebol que não é não é fácil né cara essa convivência é demais então ele ele sempre ajudava os caras que invadir esse um beijo para vocês tínhamos de coração entendi ele cortei o cabelo dele eu fui pegando confiança aí cara deslanchei isso mais ou menos quando você cortou o primeiro jogador tinha uns 8 7 8 meses de Elias [Música] nem um ano ainda né aí foi pegando Elias começou a viajar muito e tal né então a padronização hoje né o estilo a gente tem que seguir é muito importante porque o jogador vem né a pessoa e de uma pessoa de rede social mas sou bem conhecida vem a gente tem uma certa assim nossa tá vendo essa pessoa como é que

eu vou fazer então a gente essa padronização que a gente tem na equipe é para a gente não ter esse tremor cara fica tranquilo isso fica tranquilo você a gente Segue o mesmo padrão né a gente tenta buscar o melhor então não esquenta a cabeça não vai dar certo então os jogadores vinham né um espaço lá dentro da Toca da Raposa onde eu comecei aí muito mais ia muito Atlético também Aí fui pegando amizade com jogadores Então hoje eu converso com gidão aqui com Dedé com o Edilson os cara me liga como é que você tá ouvindo como é que você tá o Wallace do vôlei o Willian do vôlei cara o William William foi lá na barbearia quando ele tinha sido uma semana campeão olímpico aqui aí eu trouxe um negócio para você tirar foto tirou a medalha do bolsa velho coloquei a medalha e tal sentir o peso do Ouro mas tipo assim velho é coisas que vão marcar na minha vida né para você conseguir entrar ali mas que que você acha que foram os pontos extremamente importantes para você conseguir chegar esse patamar para o Elias ter essa confiança em você

de te indicar a cortar o cabelo de um jogador cara é ouvir né eu o cara que eu não gostava de ouvir eu sempre não que ele falava uma coisa comigo eu já vinha com desculpa não mas né isso então eu comecei a ouvir mais né eu comecei a ser mais um cara mais observador né menos invasivo né que essa essa galera eu sou que é mais celebridade ela era é uma pessoa mais reservada galera não quer abrir a vida então você vai perguntando toda hora você vai querer não ser invasivo as pessoas automaticamente já cortam e isso né para entrar então como vocês são um cara mais tranquilo o jogador converso 1% de futebol não conversa de futebol Então dentro de cada Esporte dentro de cada segmento que a pessoa tem eu saio fora porque às vezes o cara vive isso o cara trabalha com isso então acho que vai ficar perguntando né da vida do cara ou aquilo lá tá acontecendo no Cruzeiro que tá acontecendo lá no Sada Cruzeiro que tá acontecendo dentro do Minas ah você entendeu então isso é uma coisa muito invasiva eles não queres discute sobre isso vocês

querem buscar outras áreas conhecer mais você né Você tem um papo legal um papo envolvente porque isso que atrai né as pessoas isso então comecei a escutar mais comecei a aprender isso comecei a melhorar a postura né o tratamento cara o tratamento hoje em dia é essencial hoje você não precisa ser o melhor barbeiro não precisa você pode cortar um cabelo bem né fazer uma barba boa fazer um procedimento químico legal mas a sua pessoa a sua essência né a sua postura e isso aí Conquista mais qualquer outra coisa então hoje eu tenho muitos amigos dentro da barbearia né tanto essas pessoas do meio de futebol e outros meses e São pessoas que que convivem comigo passa o fim de semanas com ele vou no churrasco ou Carlos Carlos do Galo beijo para você viu é meu parceirão tamo junto atacante tá morando lá na Arábia Saudita então o cara que eu vou lá na casa deles come churrasco e essa a mãe conhecer a esposa conheço filho ele quando ele foi casar eu que levei na igreja é Que honra o cara entrou dentro do meu Punto 1.6 batendo batendo biela e fomos até

não vai vender ele ficar lá então são coisas assim confiança Então hoje no patamar que eu tô né graças a Deus foi ouvindo né tendo sabedoria tendo discernimento das coisas sabendo o meu lugar também porque isso também conta muito Às vezes as pessoas ganham o status e atropela né já não sou o cara que quer o Sena entendeu eu nem muitas pessoas falam ah você tem Instagram tem meu nome e tal mas eu não sou um cara de gabar que eu já entendi tal pessoa que eu já fui o melhor faturamento que eu fui campeão do Punho de fé esse negócio que eu uso uma capa diferente das outras tem pessoas que perguntam na barbear e pô porque a sua capa é diferente ah é porque eu tenho uma premiação de 3 em 3 meses e tal aí você vai falar isso a pessoa te Abra a oportunidade isso Eu não chego e olha que você vê aqui ó sou top ó sentado com [&nbsp;__&nbsp;] não sou assim sou um cara muito humilde nessa questão sabe então isso te faz alcançar lugares mais altos né cara comunicativo você se comunica bem demais né mas sempre

foi assim porque eu vejo que é uma dificuldade muito latente que os barbeiros tem né ah eu não consigo gerar essa conexão com meu cliente né eu tenho vergonha não sei sobre o que falar sempre foi assim para você ou você tem que vencer isso também não graças a Deus sempre foi assim desde sempre desde criança então eu sou um cara muito observado eu buscava sentar numa roda de amigos e prestar atenção em todo mundo que a galera tá falando então olhava e tal o papo de um papo de ouro papo de outro e tum e entrava não mas você falou isso mas observei que ele falou isso também então você tá indo Contra isso então não é certo então eu sempre fui tentando ajudar os caras de alguma forma sabe nem sabia cara que aconteceu uma vez eu tava vendo 9 MG e tava até aquela amostra de profissões cara eu tava lá sentado fui lanchar e nisso Na época eu fui panfletar lá dentro um curso de informática para ganhar uma grana tinha 15 anos de idade aí sentou o uma menina que era aluna que ela fazia na parte da comunicação lá

dentro um professor e uns tipos de reitor não lembro cara e eles começaram a conversar junto comigo e eu com vergonha velho que eu tava ali só entregando panfleto não tô fazendo a base da informática aqui tô começando a aprender e aquilo foi desenbolando ó que legal você é novo desse jeito fazer isso e tal é mas é tipo assim vergonha mas é conseguir sair né para não ficar não só tô panfletando aqui tô indo embora então envolvendo o papo dele foi e tal trocando ideia até hoje né lembrasse Nossa lembra que fazia informática na verdade eu só tava panfletando mas essa parte da comunicação Graças a Deus eu sempre tive sempre boto os meninos dentro da barbearia para frente que às vezes o cliente senta na cadeira os cara não sabe que o cara trabalha até hoje entendeu não sabe o que o cara fácil o cara tem filho não sendo invasivo mas trocou na ideia normal E aí beleza querido como é que foi seu dia hoje tá vindo do trabalho não tal tal o cara vai abrindo para você se ele é abertura ele vai não com certeza naturalmente levando ali e

isso com certeza então às vezes os caras não atende aí eu atendo o cliente né que era dele pô mas ele faz isso é caro fazer mas você tinha que procurar mas como é que o cara tá saber mais do cara né sendo invasivo Mas isso é bom porque esse cara sentar lá um ano na sua cadeira e você não sabe o que o cara mexe de onde o cara vem se o cara mora aqui na região se o cara gosta de comer um chocolate tem cliente meu que manda mensagem só ouvi me indica um lugar bom para comer uma massa aí velho tô aqui não sei onde que eu vou entendeu eu gosto eu sou um cara eu gosto demais velho de comer comigo mesmo então ou tem esse lugar aqui vai lá né Vai te garantir uma longevidade aí na relação com o cliente e isso tem cliente que eu pode vir aqui dormir no meu hotel aqui você não vai pagar nada tem cliente tem um caso aqui na Barra da Tijuca pode passar o final de semana com essa família que eu vou te cobrar nada então tipo assim são são

agrados e não precisa nem forçar o cara te oferece né porque ele sabe a pessoa ele sabe o envolvimento que tem com você Ele sabe até onde você vai eles ele você respeita o espaço dele e respeita esse espaço né que às vezes você faz muito cliente né faz muito amigo né Tem cara que são invasivos e tal mas um certo limite e o cara não ultrapassa isso te respeita mas dentro dessa conexão cara é muito bom eu gosto muito de ouvir as pessoas eu gosto muito de tentar ajudar Às vezes o cara tá com problema no guarda-roupa lá da casa dele cara pô tem esse marceneiro aqui velho gente boa amigo meu fala que é o Alvin e tal então isso aí cara é muito satisfatório né entendi o cara o cara tem que sentir feliz confortável né dentro da sua barbearia tem que ser algo prazeroso ele não pode ir lá só falar Ah vou lá só cortar o cabelo é não pode ser assim o cara tem que falar pô vou lá trocar uma ideia com alguém ou então quantos clientes toma um café comigo aqui velho chegou velho não acredito cara

entendeu isso é muito legal e isso ao longo desses 10 anos dentro do seu Elias que me faz ficar enraizado né amo essa marca amo tá compartilhando meu dia com meus amigos eu fico lá 12 13 horas lá dentro né mas fica em casa né mas que em casa né fica em casa 9:00 9:30 da noite beijo minha esposa vou dormir 8:00 da manhã Tô em pé de novo para ir trabalhar então o clima é muito bom não tem briga sabe briguinha Ai fiquei Fulano lá é chato Ah não sei o que não tem esse negócio de inveja sabe a galera é bem unida né tem as atrizes que são boas né Eu sou um cara que tipo assim eles chamam muito minha atenção Você zoa demais tem cara que não gosta né mas fala eu gosto também mas tem cara que não gosta velho então toma cuidado e tal então assim às vezes essas brincadeiras para mim é leva outras pessoas são pesadas né e eu venho trabalhando isso cada dia mais relação com certeza aí eu venho trabalhando isso mais por a gente ter uma liberdade grande por eu ser um cara que

eu tô muito tempo dentro da celíase Então ela fala assim não cara aqui é um jeito assim e tal na sessência assim ela vai acostumar a gente não gosta e tal e eu respeito né mas eu não vejo Com certeza mas eu não deixo brincar e faça uma brincadeira mais saidiza aí ó já tenho três super conselhos aí ó seria um bons ouvintes sejam observadores e façam boas conexões façam Network isso mesmo a chave de sucesso do garoto com certeza mas me conta mais aí da barbearia seu Elias né Você acabou de ser campeão Geral do Punho de Ferro né explica pro pessoal rapidinho o que que é o Punho de Ferro e que que você precisou fazer para chegar até lá cara o Punho de Ferro foi criado né tem pouco tempo foi tem um ano ele é para premiar os barbeiros então é um evento trimestral que acontece de todas as barbearias e ele você tem cinco categorias que a categoria faturamento a categoria fidelização A categoria venda de produtos a categoria divulgação e a categoria de uma outra categoria que eu esqueci mas vou lembrar aqui são cinco categorias Então você tem

que ser bem sim e dentro dessas cinco não adianta você ser bom só no faturamento assim você não é bom nas vendas não adianta você ser bom na divulgação a outra categoria fidelização Lembrei no dia de ser bom na fidelização e ser bom no faturamento Então você tem que fazer uma boa pontuação dentro da cinco né para ver você fica em primeiro lugar no faturamento mas ficou em segundo lugar na fidelização então isso conta porque às vezes que o cara que ganhou da outra barbearia fidelização ele ficou em segundo lugar no faturamento então tem essa média então é muito concorrido né são praticamente 50 barbeiros que disputam e eu sempre fui mais light nisso assim na competição é Porque para mim é normal primeiro quero ganhar dinheiro então precisa atender muito falar Será que eu quero ganhar muito dinheiro eu atendo muito que eu preciso ganhar dinheiro né e eu preciso encher minha agenda eu preciso disso barbearia ele depende disso né e é uma lógica que todo barbeiro tem que botar na cabeça você é barbeiro tem barbeiro que é qualidade de vida ah eu quero trabalhar só três dias essa semana e sexta

e sábado para o meio-dia segunda eu folgo não é barbeiro Você trabalha com comissionamento você precisa de trabalhar né é corte para lá dinheiro para cá isso trabalho por posição então sempre fiz isso a divulgação Normal graças a Deus eu tenho uma facilidade nos Stories e dar bom dia de postar uma foto com um cliente acho que não é importante é mulher na rede social eu falei com a galera que tem gente que tem dificuldade né ah eu não consigo ouvir e tal cara grava um vídeo ele primeiro de 10 segundos ver a ficou legal vou tacar no Store não vai direto nos Stories né que você já fica já inibido Nossa se eu clicar aqui já vai lançar não grava o primeiro sozinho e tal você ver Depois você posta aí você vai criando né esse vinho com o Instagram o hábito isso já sempre foi normal a fidelização tem cliente lá a barbearia que começou a cortar cabelo com 8 anos de idade hoje já tá dirigindo tem 18 caramba caduzão tamo junto sem meu parceiro tem 18 anos de idade eu tô falando até de namorada com ele já pô você vem

aqui com oito anos de idade né sua mãe deixar você na esquina aqui atravessar a rua para cortar o cabelo e tal Hoje você dirigindo cara então assim uma coisa muito legal venda de produtos Todo mundo precisa de algum produto ou produto para barba ou produto do cabelo shampoo é balm cara todo mundo precisa né você não pode ser um cara cansativo né que você não levou você tem que levar esse mês né a gente entende a realidade do cliente né a gente tem que saber pô é o corte de cabelo o cara fez uma barba o cara seu cliente o cara vem aqui de duas em duas semanas Então não é porque o cara tá aqui de duas semanas você tem que levar produto de duas semanas né você tem que abrir o leque pô tem um shampoo o condicionador acabou né você não pode ficar focado só no produto que o cara fica até chato pô os cara vai me oferecer a pomada lá de novo até pensando entendeu então você tem que saber conversar com um cara oferecer né os tipos de produtos envolver né e eu sempre sou um cara assim

eu falo com meus problemas cara você tem que saber usar seu produto porque às vezes o cara compra uma pomada aí o cara fala Ah vou usar só pra sair é isso Acabou só venda porque o cara falou assim velho eu vou comprar uma pomada semana que vem a minha acabou falei é a mesa acabou velho tem oito meses que eu tô com ela você me arrebenta oito milhões Porque eu só uso ela só para sair no tubetes Não cara não mas eu não sei secar não vou te ensinar ó como essa escovinha aqui legal para você secar o cabelo modelar aí o cara comprou a escova e o cara começou a usar o produto direitinho esse daí o cara passar né então isso isso faz que o que você tem a venda mais rápido né E graças a Deus eu consegui despontar nisso também a outra categoria que a deixa comigo que ela deixa comigo serviço que é de encaixe talvez o cara coloca cabelo uma hora cara uma hora para você cortar um cabelo tem seis pessoas na fila aqui esperando cara tô precisando de fazer um encaixe e tal então isso o

cara consegue reduzir o tempo dele encaixar mais pessoas hoje meu corte de cabelo de meia meia hora era de 40 e 40 minutos então como eu reduzir ele para 30 eu ganhei mais ou menos aí duas horas na agenda então se botar duas horas na agendas é quatro cortes de cabelo a mais cara entendeu então tem um horário de almoço ali que às vezes você tem uma hora de almoço você consegue fazer ela em meia para você encaixar um cliente e tal tem que saber ganhar de todo plataforma eu penso assim você tem você almoçou tá de boa tá tô chegou um cara que a cliente do cara velho não perde nada o cara tem uns minutos na vida mas cada vez que prefere ficar com certeza cada vez prefere ficar lá jogando vídeo game porque atender o cara botar um dinheiro no bolso né Então graças a Deus eu consegui destacar nisso também e dentro dessa série fatores eu consegui fazer uma boa pontuação e ser campeão aí eu ganhei sapato a gente tem uma parceria Savassi ganhei uma viagem eu escolhi né eu vou para Balneário Camboriú Ganhei uma máquina da UOL de

acabamento Ganhei ganhei uma caixa de kit da Babu não tinha mais de 22 produtos lá então você bota em média aí um produtor é r 60 nada nada ali seis vezes dois 12 1.200 fonte de produto cara é muita coisa é muita coisa né ganhei quatro voltas para o baby beef vocês não gosta de comer né E foi isso então experimentação tanto de coisa que eu ganhei né nesse voto que eu ganhei de quatro quatro eu levei meus amigos da barbearia os cara é [&nbsp;__&nbsp;] você não pagam um churrasco que não sei o que você tá bom então esses três volts que eu vou dividir nós seis aqui beleza ó os cara pô aí sim aí tem esse cara que foi lá no BBB e falar comer pagou r 30 e achou ruim ainda não leva vocês mais não viu camada de folgado então eu fiquei muito feliz que eu sou um cara competitivo mas eu sou um cara competir saudável eu não fico mal sabe tipo nossa porque cara ganhou gol já que ganhou de novo o cara teve um uma regularidade o cara foi persistente tá legal a gente troca ideia e tal

então sempre a gente está no páreo ele ele um já ganhou também então é uma competição Sadia e para os barbeiros que estão entrando é muito importante isso né a galera precisa parar de olhar só para o corte de cabelo Na barbearia o leque é muito grande então você precisa fidelizar você precisa divulgar sua empresa né você precisa vender mais produtos você precisa fidelizar Com certeza que às vezes a pessoa fica assim ah vou lá vou fazer meus 10 corte de cabelo e vai embora entendeu então você precisa diversificar cara você precisa abrir mais a sua mente em questão você não pode ficar só preso aquele cliente está marcado com você você fazer seu atendimento e correr lá para dentro da Copa e ficar sentado esperando o próximo né você tem que movimentar a sua rede social você tem que movimentar a barba porque a barbearia precisa disso a barbearia não pode só ficar dependendo Ah eu faço meus Stories e pronto eles precisam de você tem lá dentro tem outro oito profissionais lá dentro então os outros profissionais lá ajudando também na divulgação atirando dúvidas dos clientes às vezes o cliente Pô queria fazer

uma selagem mas como é que essa selagem Às vezes o cara no Instagram dele o cara entra lá para ver não tem nada falando né especificando então eu sempre faço esse passo a passo de selagem de finalização de pomada Às vezes o cara 30 segundos ali o cara para olha seca assim olha ele passa a pomada no cabelo assim ah é assim gera muito valor o cliente ele te segue já já quebra essa essa dúvida dele então é muito importante isso eu eu podia estar lá assim cara não não preciso Já tem uns 15 aqui eu não preciso ganhar mais dinheiro não para quê ficar aí para a rede social Todo mundo me conhece dentro da barbearia Zezão ganhei premiações de faturamento antes do plano de Ferro eu já ganhei três vezes né de faturamento geral vocês verem também que não é uma coisa da hora para outra viu gente com certeza foi teve escalas né a gente tem que ter escala na nossa vida a gente tem que se preparar para isso às vezes a competição é você não pode ter ganância pode ter ambição né totalmente diferente confunde mais então você tem a

ambição naquele pow quero ser o campeão do Punho de Ferro quais os melhores né caminhos que eu tenho que tomar né Tem meninas que eu converso lá da Savassi lá e tal Óbvio nunca vou conseguir ganhar cara você consegue você faz isso faça aqui faz aqui entendeu então às vezes eu faço uns cálculos rápidos umas coisas assim né do meu dia a dia com os cara ó é ração cara é isso mesmo entendeu porque a gente trabalha com produção se você folga toda semana toda semana às vezes o cara não tem nada para fazer agora pode ter seu descanso o cara folga toda semana Às vezes a semana tem um feriado né aí vencer quatro domingos são cinco Domingos então tipo os 20 dias trabalhados viram 16 com mais uma um feriado 15 então o cara trabalhou duas semanas né então uma pessoa não tem esse cálculo de fazer Poxa eu não ganhei pouco assim só vendo no final do mês então isso eu falo muito com isso cara vocês têm policiar isso esse negócio de pegar 11 horas da manhã Ah vou pagar tudo de 11 horas da manhã vou largar oito é 3

horas se você fazer isso pelo menos duas vezes por semana são 6 horas você vai fazer isso quatro vezes é 12 horas é um dia de trabalho você deixou de ganhar um dia de trabalho então nesses detalhes que que às vezes eu consigo sobressar aí nessa questão porque eu olho isso eu tenho metas também né a gente tem que trabalhar com metas a gente tem que falar assim ó como a gente começou nada eu preciso eu preciso ter uma base no meu salário você não pode ganhar no 65 para ganhar no outro mês sete não você tem que ter uma base para isso é minha base entre 8 e 9 mil reais por mês eu vou ficar dentro disso você viu que o mês tá começando Tá faltando 10 dias você não tá conseguindo divide lá tá vendo que não tava cansando quero só um almoço almoça menos né reduz meia hora atende um cara na hora do seu café o que só depende de você cara o cliente está vindo ninguém vai fazer por você com certeza o cliente está vindo o cliente está lá você tem que corre entender né a barbearia já

já proporciona isso para você isso é muito muito mas muito interessante porque eu vejo outras barbearias e muita barbearia que não posta nada tem muita barbearia que não atrai cliente não faz uma divulgação no Google isso é muito importante então lá dentro da nossa barbearia isso eles a gente tem tudo isso é só o cara chegar e cortar o cabelo mas às vezes assim você tem que pegar pelo braço e mostrar para falar que não é fácil às vezes penso que o mar e rosa é não chega lá e vai ganhar Rios não né tudo um processo mas a pessoa também tem que se padronizar na vida não adianta sem padronização cara vai ser difícil né você conseguir alcançar muita coisa muita coisa mesmo um dos pontos mais legais né do Punho de Ferro é que vocês conseguem mostrar com clareza em que o Barbeiro precisa se desenvolver né e ele vendo outros se desenvolvendo né ele vê que isso é possível acho que é muito importante principalmente como você falou para quem tá começando com certeza tem vários meninos que ganharam né as pessoas não ganham Punho de Ferro mas ele ganha num destaque

que ele foi no caso na categoria na categoria ele foi ganhou na fidelização lá na barbearia na Pampulha lá o Zezinho que entrou tem sete meses ele ganhou de venda de produtos em cima de mim sete meses ele vendeu se eu não me engano ganhou só de venda de produto em três meses acho que ganhou mais de 1.200 cara tá vendo rapaziada para quem acha que não é possível aumentar muito as vendas aí vendendo produto você divide o Cara ganhando 400 contos por mês só com medo de produto Isso aí é um consórcio vai lá para você pensar pô se eu conseguir vender r 400 todo mês de produto final do ano pega um álcool inclusive lá sozinho ganhou seis paus só comendo esse produto as contas assim que a gente tem que fazer estabelecer suas metas né então é conseguiu ganhar os meninos outras categorias Então isso é muito importante você ver a felicidade dos Cara ganhando e tal eu ganhei o reconhecimento também é muito importante Com certeza você tá ganhando em cima da pessoa que tá lá tem nove dez anos é legal entendeu quando o Neymar ganhar em cima do Messi

eu o título do mundial porque é legal para caramba entendeu isso motiva e uma rivalidade Sadia também acaba levando para esse lado né já o Barbeiro tá se destaque Na barbearia não vou ajudar ele ou quem já é destaque falar não vou ajudar os outros porque eu já tô num outro patamar né Eu acho que essa união principalmente é muito importante também com certeza a gente a gente dentro da barbearia né a gente tem o Nossa atriz sadias né mas é a união cara você sempre apoiar né a gente quando a gente pô você não fez um Stories hoje pô você não postou nada hoje cara Calma cliente acabou de sair ele se com um produto na mão cara você esqueceu de vender fica atento né e eles aceitam essa correção né às vezes fica meio assim e tal mas depois reconhece pô verdade cara podia ser né mas atento nisso lá dentro da barbearia a gente tem um culto que a gente faz uma vez há um mês né E você qualquer religião é aberta qualquer tipo de render só você é católico participando disso não a gente só fala de Deus e né

troca uma ideia entrou como é que você tá Você tá passando alguma dificuldade cara a gente pode ajudar porque às vezes os cara fica ali dentro cara trabalhando vai tentar sorrir no 24 horas mas o caso está com problema na família com a mãe com o irmão e às vezes a gente não sabe então a gente tira né uma vez um mês e tal troca essa ideia poder ajudar né a gente recentemente agora a gente tá com um barbeiro lá novo veio da Venezuela cara veio sabe na cara na coragem tentar a vida aqui Ravier gente boa ilíssima trouxemos a família dele ajudamos a mobiliar a casa dele talvez de nosso grupo mesmo de amigos ali tal quem pode ajudar na cama quem pode ajudar no botijão de gás e a diferença que não fez na vida entendeu porque graças a Deus a gente tem essas atitudes dentro da barbearia querer ajudar o próximo queria saber da vida da pessoa né Às vezes a pessoa tá ali velho o gato a pessoa tá acabando a gente nem sabe né aí a gente precisa muito longe para ver a dificuldade né pô o cara veio da

Venezuela tava trabalhando de pôr porteiro Na barbearia vai virar barbear agora então tipo assim logo ele contou que começou a contar a história dele cara a gente a gente é rico né a gente tem um teto a gente tem comida a gente tem tudo aqui falta nada e deu essa base para ele ir ajudando ele ajudou também para caramba mas é União né e dentro da barbearia tem que ter União viu galera vocês aí que tem briga com o amigo do lado que o cliente sem você falar mal do cara não faça isso estejam mais unidos porque a barbearia cresce cara a barbearia precisa de cliente né Às vezes você faz pô meus todos esses clientes são meus cara for cortar com outro lá vou falar mal de você não fale bem cara porque você ganha o cliente percebe isso também porque depois se ele parar de cortar cabelo com você ele vai falar com outro barbeiro você falava dele então tome cuidado com isso Preserve a barbearia Preserve os amigos você tem preserve o dono no lugar o seu local de trabalho né que seja abençoado não seja um lugar de peso né você

chegava para trabalhar você procure Ter um melhor relacionamento com as pessoas procure melhor ter um relacionamento com cliente faz aquele lugar agradável você fica aí dentro tanto tempo cara né a gente tem que fazer a segunda casa com certeza a gente tem que ter essa essa regra assim dentro do nosso coração cara eu preciso cada dia ser uma pessoa melhor precisa ser melhor Na barbearia precisa ser melhor para o meu cliente porque isso só tem a gente só tem a ganhar recado muito importante também principalmente para os donos da barbearia né a valorização dos profissionais né tudo isso aqui que a gente tá falando né as bonificações e tudo mais né Por mais que eu sou barbearia às vezes não tenha o porte da seu Elias né Às vezes você consegue fazer algo que esteja dentro das suas capacidades né com sua equipe porque isso é de extrema importante o reconhecimento como a gente falou é não é só pelo dinheiro é só porque o pessoal tá ganhando é mais principalmente pelo conhecimento do profissional pelo que ele tá fazendo porque é muito importante pra sua barbearia né a seu Elias vai muito bem pelos

profissionais que ela tem né não é só pela maca porque não adianta nada ter uma marca muito boa seus não for bom né então acho que a valorização do profissional é o que a gente tem que tomar cuidado e manter sempre em Dia com certeza cara isso aí é a primeira meta Nossa sempre vai né ele está sempre valorizar o profissional porque ele se o profissional não tiver bem a barbearia não vai bem né imagina se tem no oito profissionais e todo mundo satisfeito todo mundo triste né um querendo matar o outro um falando mal do dono clientes sentou você fala mal entendeu Fala pô cara sei lá velho lá tá uma zona uma briga falando mal do outro e tal então essa valorização né da barbearia com o profissional isso é muito importante você que é dono de barbearia né E tem essa dúvida aí pô valoriza não valoriza passa um programa de premiações procure fazer isso que é muito importante a motivação do Barbeiro é muito importante pode falar ah mas aqui já tem pão já tem manteiga aqui já tem uma copa o cara sentar pô dou tudo tal beleza graças a

Deus mas não faz mal você sempre tentar fazer o melhor para o Barbeiro barbeiro vai retornar isso para você a sua barbearia vai bombar né E essa troca de informações é muito importante para o crescimento né você expandir vai abrir outras unidades né tirar um cara lá de dentro e liderar em outro lugar né que às vezes o dono o cara abriu uma barbearia mas ele olha para o lado Pô velho não tem amizade que nenhum desses cara esses caras só tem para não passar para trás como é que ele vai divulgar isso como é que ele vai conseguir dar esse passo Então procure fazer líderes dentro da barbearia né seu negócio crescer você conseguir expandir eu consegui levar além né e o Barbeiro ficar satisfeito e o dono também todo mundo ficar todo mundo sorrindo com certeza se limitem a acreditar que vocês estão fazendo suficiente e que isso daí é o máximo né a barbearia pode muito mais o profissional sempre pode muito mais né tudo a gente tá falando aqui para expandir a mente vocês que vocês têm muito mais capacidade que você às vezes acham né e é importante vocês acreditarem

nisso também até mesmo para o cenário da barbearia né a gente vem numa crescente muito grande a gente já vem de uma revolução muito grande mas que que você acha Qual que é o futuro próximo aí da barbearia né Depois dessa resolução principalmente com eles trouxe como é que você imagina no cenário daqui para frente cara eu vou ser um cenário cada dia mais competitivo né hoje antigamente a seu Elias era barbearia né do Top do Momento lá só os caras sabem fazer degradê e tal mas como eles aí expandido em cursos né Tem um bar beber a casa tem um barbear online então a galera foi superfeiçoando então o mesmo degradê mesmo corte mesmo atendimento que a gente faz muitos outros barbearias fazem hoje em dia né então a gente tem que cada dia mais ser melhor dentro da barbearia com o pessoa porque que eu penso cara hoje tem um cara na rua de baixo faz um degradê igual eu tenho um cara na rua de cima igual eu melhor mas o que que vai segurar seu cliente ali é o Network a convivência a fidelização né então a gente tem que cada

dia mais caprichar e melhorar isso porque o cliente às vezes te troca por causa que você não deu bom dia para ele cara mas o cara sentou nessa cadeira e o cara bom dia você e aí como é que vai ser o corte né então isso o cara já fica pouca Não deu nem Bom dia e tal então a gente tem que observar mais a nossa volta eh naquele negócio Ah o cliente tem sempre a razão né muita gente faz só o cliente tem sempre a razão o cliente tem sempre a razão não é que ele tem sempre a razão ele tá vindo buscar ali o melhor dentro da barbearia né e ele tá pagando aquele valor ele quer ser atingido da melhor maneira possível então a gente como barbeiro tem que fazer o melhor possível para se prender aquele cara aqui para aprender a família dele eu falo muitas meninas Às vezes o cara vem com filho ah eu não gosto de cortar cabelo de criança Poxa corta o cabelo de criança porque é a geração que tá vindo se tratar mal o filho do cara ó como se fosse você está tratando um

cara mal cara então você tem que tratar bem o filho rir atender bem porque a geração ele tá com uns quatro cinco anos de idade aqui daqui 50 tá com 10 daqui a pouco ele tá com dor com certeza eu atendo ele do pai dele então tem outra barbearia do outro lado vem cá vem cá que eu te atendo melhor que ele vem cá então a gente tem que tomar cuidado com isso né a concorrência cada dia tá aumentando né as inovações cada dia tá aumentando hoje tem barbearia toda hora cria um negócio diferente é busca sempre atrair o público de outras formas e tal fazem evento sorteia dá carro entendeu tudo para atrair mais clientes Então esse mercado tá crescendo demais né como poderia Então a gente tem que ser melhor em todas as áreas de todas as peças cara não só no corte de cabelo mas sim como pessoa né com tratamento com honestidade com a simpatia né com Network e só tem ganhar em ro dentro da área É isso aí e também eu acho que o pessoal às vezes coloca metas muito mirabolantes né ah porque agora eu vou ser o

melhor atendimento do mundo né mas comecem com pequenas metas né Principalmente metas alcançáveis né quando você alcança uma meta você sente satisfeito e busca melhorar ainda mais né então Estabeleça metas Primeiro de tudo né fundamental senão você não vai sair do lugar mas principalmente Estabeleça metas alcançáveis para você conseguir ter o seu próprio reconhecimento e também evoluir Ainda com isso mais com certeza é o passo né Primeiro passo é isso cara vamos fazer o seguinte eu atendo sete pessoas de Eu quero atender a partir semana que vem eu quero entender nove Ah eu só corto cabelo e faço nem um barbeiro só corta cabelo e faz barba às vezes eu tento falar cara aprende a fazer uma selagem Ah é difícil e tal mas você tem que quebrar esse paradigma da sua vida não é difícil é você que tá botando empecilho para isso né então vou aprender a fazer sei lá vou fazer uma selagem por semana ó semana que vem vamos fazer duas Ah eu corto de 40 minutos eu corto o cabelo de uma hora eu quero reduzir para 40 São Passos né ninguém vai ser o melhor na selagem o cara

que corta cabelo em 10 minutos não do dia para noite não tem jeito então a gente tem que ter espaço né ou ele passou e na mãe me comentou né dos cursos como é que isso vem aumentando E você também dá treinamento dentro da própria Sueli né você ensina que ensina Com certeza como é que foi essa experiência como é que o abertura do Elias para começar ali a vou te trazer para ensinar a galera como é que foi para você principalmente ganhar confiança do pessoal porque muita gente hoje quer ser educador né mas não sabe os passos não sabe como é que eu vou fazer para o pessoal realmente acreditar no que eu tô ensinando para ter credibilidade como é que foi para você essa experiência cara foi foi muito legal porque o Danilão a da barbearias eu Elias Sion mandou mensagem ao vivo tô precisando de passar um treinamento aqui para os barbeiros né de selagem e de camuflagem masculina né para cabelos grisalhos eu falei pô tô dentro cara pô vamos embora vamos marcar e tal beleza vamos marcar um domingo aí cheguei lá cara e eu nunca tinha dado treinamento dentro

da barbearia você Elias né então tipo assim a mesma coisa de você pegar assim você tá acostumado de ver os cara todos os dias e tal mas um treinamento fica esse povo eu vou treinar esse cara esse cara tá ao mesmo tempo do que eu esse cara que eu já conheço há anos e tal mas a confiança né no meu trabalho e levou fazer e os para turma 9 que entrou então foram os barbeiros novato que ele tinha como contratado e tal e a galera sabia fazer mas não sabia fazer da maneira certa foi muito legal cara porque o nego passa passa eu segurei na mão do cara você prancha assim é um cabelo mais resistente tem que pranchar de 10 a 15 vezes o cabelo mais mais leve você pode pensar de cinco a oito vezes né aí a camuflagem ó cabelo grisalhos cara eu nunca tinha feito um camuflagem lá igual eu fiz cara sempre usava touca esse negócio tal aí eu passei meu segredinho que eu não posso falar aqui então os cara Pô velho assim cara é assim cara como tipo assim ó como um flash o cara demorava uma hora

dessa uma hora e vim fazer na touca eu faço com 10 minutos né aplicação Então os cara Pô velho legal muito muito interessante tinha um cara que não sabia fazer essa Live lá sabia nem pegar na prancha direito o cara Aprendeu o cara no outro dia já abriu a agenda dele os meninos não fazer camuflagem já abriu a gente já foi comprando as tintas e tal a esposa do Danilo que que cuida dessa parte me ligou cara tô precisando de tinta aqui que eu compro que os menino tá fazendo camuflagem então tipo assim um serviço Que eu apliquei de uma hora e meia duas horas lá que eu nunca tinha feito dentro da barbearia os cara agregou para caramba os cara Não aumentou o faturamento pra eles aumentou o faturamento dentro da barbearia né a importância e e o interesse cara né porque não adianta você só ensinar também se o cara não quiser Beleza com certeza então o interesse que que ele teve em passar esse esse treinamento para barbeiros dele né e os cara interessados os cara aprendendo e disse assim fiquei feliz para caramba né porque não tinha nunca tinha dado nunca

tinha dado um treinamento dentro da seu Elias e quando esse treinamento Assim abre um leque na minha cabeça também umas coisas que eu já tinha travado aqui na mente Falei pô cara destravar isso eu quero fazer isso eu posso abrir aqui para dar esse curso aqui né através de um pequeno treinamento simples de domingo né tipo meio que um quebra a cara que eu tenho amizade com Danilo não ia negar de maneira nenhuma fiz um preço camaradaça para ele né porque é o seguinte O barbeiro tem que valorizar viu ah vou aí fazer fácil de graça não cara você tem seu preço Você tá trabalhando domingo isso é interessante né você estipular isso né e o cara vai te dar valor também nisso Pô cara tá cobrando porque é o trabalho dele o cara sair da casa dele domingo né largando a família né para não cobrar nada né se o cara quer dar de presente beleza mas o cara falou Pô vou valorizado né meu domingo e é profissão cara é uma troca já tá dando um desconto você já tá ajudando nesse desconto e o cara tá valorizando o seu trabalho né então

dá um beijo gente serviço de graça se vocês estiverem no coração se você quiser dar aí assim a gente pô quero dar aí eu já tenho várias coisas cara já foi todos os cortar o cabelo fazer a barba eu senti no coração de não cobrar cara e não cobrei tudo bem E tudo bem Entendeu então se você tá no seu coração beleza você faz e tal agora se quero cobrar cobre valoriza seu trabalho barbeiro valorize o seu trabalho isso é muito importante ainda mais um fim de semana com certeza com certeza muita gente tem essa dificuldade né Principalmente quando é um amigo né pedindo para cortar ou pedindo para fazer um serviço num dia que vai ser muito apertado para você né você esquece do seu valor próprio né então nunca esqueçam o valor de vocês Da hora de vocês do tempo de vocês e de toda a trajetória que você teve que percorrer para chegar até esse nível né com certeza são 10 anos então se eu tenho essa bagagem é porque eu plantei muito lá atrás né com certeza plantei sobre plantar sobre regar né E hoje eu tô sabendo colher não adianta

você plantar uma coisa errada torta que você não vai colher uma coisa um fruto legal é um plante da maneira certa né para você colher também da maneira certa Sadia sem atropelar ninguém sem subir degrau de ninguém sem pisar na cabeça de ninguém você sendo honesto você atinge lugares altos com certeza cara me conta qual que foi o episódio mais marcante que você teve até hoje dentro da sua carreira dentro da barbearia cara tive tanta coisa cara uma vez Vamos lá na área do futebol tava lá na atender o Robinho Edilson lá na casa lá em cima agora vem cá corta meu cabelo vai ter um churrasco aqui e tal fica aqui beleza vamos embora né cheguei lá tal e eu não sabia que a festa tava acontecendo entendeu cheguei tipo assim Ah velho eu conheço os caras Monte chinelo e tal que não sei o quê e tal vamos embora Cheguei lá cara arrumei minha roupinha bonitinha botei a capa do seu Elias que não sei o quê não sei o quê no meio do salão velho tum só que esse parecer com a turma do menor 50 pessoas todo mundo olhando para mim

assim que é isso aí velho tá acontecendo não velho vim cortar o cabelo aqui e tal não velho a festa que tá acontecendo aqui também isso daí dá o falei Pô velho que palhaçada comecei a rir tanto de mulher olhando para mim e tal e eu lá de chinelo velho velho que loucura porque a gente né com os jogadores e tal e foi um negócio assim do nada né e eu fiquei todo mundo olhando para mim eu com a máquina na mão gente que tá acontecendo aqui não velho aqui esse espaço você colocou essa tesoura esse negócio esse lugar de colocar comida velho e tal Eu falei nossa que loucura desde essas coisas também dentro da barbearia Às vezes o cara falou comigo Alvin Tem como você passar a máquina para mim na minhas costas cara olha Uai tem velho tem tem como não tem como tem velho tem é o cara então beleza então arrancou a camisa velho na cadeira que os cara começou a olhar assim eu meter na máquina nas costas do cara entendeu passando bonitinho e tal tal aí eu fui ver todo mundo olhando tô nem aí velho gente boa

meu parceiro e tal aí ele fez o peito para frente assim ó esse cabelinho Branco dobradinho sabe aí deu um grau assim tá um grau nele assim ele falou velho que top velho e tal é vamos embora cada coisa que aconteceu lá na barbearia é uma vez tem um tinha um tinha um cara que ele tinha de vez em quando epilepsia que fala né ele ele diz que andava né no tigre do irmão dele e sempre acontecia Na barbearia mas eu quero ver se o cara ficava Sentado lá na cadeira e tudo aí nesse dia eu cortei o cabelo do irmão dele e o cara que tem que dar epileps como é que fala epilepsia epilepsia isso você entrou na casa do meu amigo aí velho o cara deu cara na cadeira do cliente velho lá aí cara e tipo assim o irmão dele lá não velho fica tranquilo isso é normal e o cara velho meio assim meio que babando aí eu falei velho você é normal nossa aí o irmão dele não isso é normal pode deixar ele aí o menino o cara foi Saiu da cadeira e fui meio que caiu no

chão cara aí o irmão dele assim oh levanta isso isso é assim mesmo tipo assim todo mundo anda assustado eu olhando pro cara no chão aí o hellon é bem fria barbeiro Nossa Senhora Beleza então dá uma arredada nele para mim aí velho que eu vou que eu vou vender o próximo [Risadas] E aí você acredita velho que o Helô arredou o cara velho e começou a cortar o cabelo do outro cliente velho diante de Deus cara aí o menino voltou velho Aí eu fui fui e voltando ao normal e tal aí foi voltando ao normal o cara foi voltou na moto sentou na cadeira pediu um salgado pedir uma Coca Aí começou a comer ô falou aí gente nada aconteceu na barbearia sabe velho eu fiquei de cara velho fiquei de cara olhando aquele ali velho e eu fiquei de cara com o irmão do cara que é normal eu fiquei assim depois né Eu acho que morreu agora viu Tá geladinho eu falei velho não tem lógica o negócio desse Nossa não é normal né mas tem gente que tem né velho é cara assim velho o cara deitado no chão meio da

cadeira Ele Ei irmão como é que vai ser o próximo aí e o cara deitado no chão velho é velho diante de Deus ela não é mentira você sabe muito bem que isso é verdade cara por esse episódio cara ah vários outros episódios que tem ali na barbearia que a gente é a gente um tal de falar com uns cara seu juntar tipo uns quatro falar seu vou falar que o Álvaro hoje tá fedendo velho aí tipo assim passava tipo 20 minutos chegava assim o cara trabalha de todos ó vai sentar passa o desodorante hoje Passou velho Ah não beleza que eu tô achando que você tá meio até de boa você passou beleza aí passava tipo umas duas horas a menina decepção falava assim nó assistindo um cheiro de murrinha vocês são Gente alguém tá usando e ele sempre aperta né aí velho eles criavam fake no Instagram velho mandava mensagem tipo Elias o existiu e Na barbearia hoje à tarde cortei com algum profissional e eles estavam com um pouco de CC e tal e eu não sentia bem e tal aí eles mandava velho eles mandava no grupo gente porque não passou

desodorante aí pelo amor de Deus é coisa básica e tal aí tipo assim velho ele tipo Nossa velho Será que sou eu o cara aí tinha criado na cabeça dele velho aí ele sumiu velho aí na hora que a gente chegou no banheiro a gente já abriu a porta velho ele tipo olhando o álcool e passando assim ó o que é isso não velho que eu não tô falando que estava o cara mandou mensagem aí velho tá com CC para caramba e tal falei não velho zoação seu segurança é o pé velho mas é molhar é velho a nossa zoeira é pesada velho a nossa zoeira né a zoeira Nossa lá é pesada velho não a gente a gente pega nós gente na hora que a gente pegava pesado criar um WhatsApp entendeu tem muita coisa lá tem um menino dela assistente lá era o Andrezinho cara aí ele muito religioso e tal e ele acho que ele tinha um parente lá que vende de oração cara vem de oração e tal falei meu velho pô que doido hein velho aí criamos um WhatsApp velho uma fotinha do cara velho oh a gente tá querendo

comprar em uma oração a gente faz para estar marcando com você o André que indicou ao André ficou sabendo disso não é mesmo ó eu fui eu que indiquei mesmo eu quero ajudar a vender cara aí o cara falando na porta da barbearia caçando vender oração e não era nada disso velho então tipo assim a gente faz uns trote meio pesado sabe Era uns negócio que a gente fazer assim muito pesado hoje a gente melhorou bastante mas era meio punk velho tivesse isso às vezes todo mundo tava com canto todo mundo sério entendeu com certeza com certeza Brincadeiras à parte último recado que você tenta para dar aí pessoal principalmente para quem tá começando e quer chegar no nível de cortar cabelo de profissionais celebridades chegar onde você chegou cara diga para você do outro lado tudo tem seu tempo né tudo tem seu tempo e tudo é construído com base não tente atravessar aquele aquele rio sem você passar por cima da ponte Não tem aquela ponte você tem que passar por cima da ponte não tem que passar por baixo da ponte né hoje em dia a barbearia você tem que começar no

nível baixo é normal às vezes você quer sair de um curso e quer montar sua barbearia rápido não cara passe pelo processo né tenha esse entendimento que você consiga alcançar o seu sucesso mediante o que você plantou no começo não tente atropelar ninguém né passajos o seu nome seja um caronés seja um cara que você possa criar boas amizades criar novos vínculos passa Network né que você pode estar dentro da barbearia seu Elias a qualquer momento né a gente não olha só o corte de cabelo a gente olha o coração a gente olha A Essência né a gente sempre busca pessoas assim né se você quer estar próximo da agência seja um cara assim seja uma mulher assim a gente tem várias pessoas mulheres barbeiras lá dentro que você vai conseguir colher isso tudo no seu processo né não pensa que seu processo é lenta né o seu processo está sendo adequado que você plantou e você vai colher lei de semeadura Não Falha a lei universal que vai sempre ter o mesmo resultado o que você plantou com certeza meu querido mais uma vez muito obrigado pelo tempo merecem sua agenda é muito corrido

tirar um tempinho para vir aqui conversar com a gente é uma honra Espero que venha mais vezes foi ótimo bate-papo espero que a gente tenha uma ótima relação aí pela frente e que a gente crescer junto cada vez mais com certeza queria agradecer que a presença né A galera tá aqui nos Bastidores dando o gás Total mexe vários que vocês cresçam cada dia mais né eu tô vendo a sua caminhada tô vendo o seu espaço eu tô vendo a união de vocês aqui dentro que Deus possa abençoar que vocês possam alcançar lugares altos e que eu possa voltar aqui e ver ainda falar assim gente ó participei desses cara velho os caras já estão lá no Fantástico Os cara tão dominando no Brasil né e eu fico feliz pela sua humildade né pela pessoa que você é e que Deus abençoe todos os dias que Deus possa aumentar o seu crescimento profissional aumentar o vinho com seus amigos aí junto Vocês crescendo não honestidade no trabalho não tem como dar errado não cara isso aí você pode ter certeza que vocês já estão rompendo e vocês vão romper mais cada dia mais ainda Amém tamo

junto obrigado a todo mundo que acompanhou a gente até aqui fica aí as dicas valiosíssimas para você crescer na sua carreira se você ainda não baixou o best barbras ele vai te ajudar até a agenda cada dia mais proveitosa você vai conseguir ver lá nossa versão web espaço que estão vazio Onde você consegue encaixar uma pessoa ou outra um produto que você pode vender para o seu cliente e você vai faturar muito mais valeu um abraço para todo mundo aí tamo junto valeu [Música]`,

  summary:
    "Episódio 6 da Temporada 2 do BestBarbers Podcast. Alvaro Daniel compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
