import type { VideoContent } from "./types";

export const podcastmulher_barbeira_ep03: VideoContent = {
  slug: "podcast-mulher-barbeira-ep03",
  youtubeId: "mAyrqU54np4",
  title: "BestBarbers Podcast com Mulher Barbeira — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 3 da Temporada 1 do BestBarbers Podcast com Mulher Barbeira. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "mulher barbeira",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2022-07-21",
  duration: "1:06:38",
  category: "Podcast",
  tags: ["podcast", "temporada 1", "entrevista", "gestão", "barbeiro"],

  transcript: `é o nome da mulher bebê sujo Surgiu da seguinte maneira 1 e vai abrir sair 1:20 tá mais um best Barber podcast é sempre uma honra ter você nos assistindo nos ouvindo espero que vocês tenham gostando do nosso conteúdo até aqui que você estiver gostando já deixe nos comentários já deixe seu like é super importante para a gente continuar nosso trabalho para continuar levando esse conteúdo inédito para você barbeiro Barbeiro de todo o Brasil e para aqueles que querem conhecer um pouquinho mais sobre o mundo das barbearias bom nesse Episódio número 3 nós tivemos a honra de receber a Fran ela que a dona da mulher barbeira uma barbearia só de mulheres daqui de Belo Horizonte ela conta um pouquinho da sua história como ela entrou para o mundo da barbearia das dificuldades que ela enfrentou até ser uma grande barbearia de Belo Horizonte Então fique ligado eu tenho certeza que ela tem muita coisa para te ensinar que você vai vir bastante então Assista esse vídeo até o final e tchau obrigado era os senhores sejam bem-vindos a mais um best Barber podcast hoje nós temos a honra de receber que a Fran é

popularmente conhecida com a geladeira mas não é só uma mulher esse é o nome da barbearia dela uma bela é só de mulheres pé enfrentam apresenta um pouquinho pessoal quando um pouquinho aqui da sua história como é que foi como é que começou tudo isso da onde surgiu a ideia das mulheres bárbaras é uma história grande primeiramente eu quero agradecer vocês pelo reconhecimento né normalmente se vê pouco falar de mulher barbeira muito pouco quando a gente é notada é uma vitória muito grande e vocês notaram agente notou mulher barbeira eu tô aqui né ele falar com você Tá bom então me conta aí já falou que a história é longa mas há quanto tempo você trabalha com isso De onde surgiu a quanto tempo existe a mulher bar Beira é como ver construída essa história e eles vão a gente vai desenrolar muito papo ainda soubesse eu costumo dizer que nasce barbeiro só não sabia né a gente descobre no meio do caminho que bom que a gente descobre né Oi e eu sou do interior de Minas net mote uma cidade que fica na região do Vale do Aço eu comecei a cortar cabelo

aos 10 anos de idade anos usar cabelo do vizinho que tinha seis depois comecei cortar cabelo do irmão dele pois do pai de mim dos vizinhos da rua e aí era um hobby mesmo né isso Gil para uma influência me dê uma referência masculina muito grande que é o meu tio Geraldo ele também é profissional da área da Beleza atende os dois públicos assim o papel e ele é uma pessoa muito boa uma pessoa muito generosa Oi gente não sei não sei se aqui em Belo Horizonte tinha esse hábito antigamente É mais ela entre moto e a gente tinha um hábito familiar de ir aos domingos para casa passa com minha mãe é muito bom então a gente se reunia lá né e meu tio Generoso que era ele levava os materiais ele cortava o cabelo de segunda a sábado e domingo ele levava ainda os materiais dele cortava o cabelo dos sobrinhos dos irmãos dele e aquilo não ou quem tava lá no domingo eu aproveitava ainda saiu aproveitada saiu não é embelezada e o Parava tudo para poder ficar vendo ele corta o cabelo assim que aquele desejo né mas eu achava que

era impossível porque uma criança e era o material cortante sim ele super cuidadoso no deixava de jeito nenhum pegar naquela tesoura principalmente que eu acho que também tem uma vaidade do barbeiro você os materiais materiais rapaz não dá para deixar aí de brincadeira na mão de uma criança né E aí não sei porque cargas d'água a minha tia e a irmã dele auxiliar velho vezes o outro Na barbearia dele né então de beleza dele e ela parece que ela tinha desistido de auxiliar ela e ela me deu mas se a tesoura que era dela tesoura mundial a marca Mundial acho que é uma das marcas mais antiga ET AL a antiga e Popular né Quem é então eu acho e ela me deu essa tesoura eu fiquei feliz demais nossa grave Eu preciso de uma pessoa limpar já cortar esse cabelo hein Oi e a primeira oportunidade foi o vizinho New closet mora aqui em BH Eu vivo falando contém o pai dele disse Jesus lá em Timóteo ele ele mora em BH hoje eu falei com o pai dele dentro Supermercado fala com ele para ir lá tem que dar banho não pode deixar

de lá eu e ele tem um corte Perpétua sua vida para sempre tem uma foto né para fazer umas depois você legal que eu acho que um dia ele vai lá você não eu insistir New velho você vai assistir a gente ainda fiquei o convite Nil Martins de Moura por favor cara eu espero vocês a gente madu aqui ó a mulher barbeiro tá em filmagem o corte como corte eterna gratidão eterna Hospitalis vitalício um tecido primeiro cliente primeiro corajoso primeiro corajoso a gente teve um ar de desconfiança dele Imagino que ver ele virou e falou assim você é profissional e nem o profissional excepcional mesmo eu usei pai estufei o peito né um sobrinho você cortar cabelo você gosta nunca tinha cortado na vida que nunca tinha cortado uma hoje sabia não ele sabe era daqueles cabelo lisinho e o grau de dificuldade aumenta né eu comecei cortar o cabelo dele até salivar eu já levava vendo meu tio cortar né E aí na primeira oportunidade vai ser o meu eu vou ter um banquinho para sentar e comecei cortar o cabelo dele Oi pai feliz cada na orelha a primeira que ter né se

não tivesse um feriado o primeiro coração se não tivesse não seria primeiro pelo a gente burra no primeiro de boa já no segundo dia tão um pouquinho mais cuidado mas ele levantou [&nbsp;__&nbsp;] verdadeiro e ele falou sério você não vai quantas essa história rindo até hoje aí meu cabelo tem que terminar de cortar né é que tem medo de cortar o cabelo dele convence ele a sentava volta no mundo produto tamborete agora vamos embora não vai ficar só com lado não eu não vou contar mais não só ele não foi sem querer mesmo desculpe eu me chama de delícia claro que a resposta né atribui a responsabilidade E aí cortei o cabelo dele depois do irmão dele que acho que tinha quatro que eu creio que tinha 4 anos eu 6 a versão 14 por todo do irmão também é cortei das não depois do pai dos meninos depois os vizinhos começaram a me chamar para o cabelo do vizinho do lado que não tava do o Teco e do Denis nos dois irmãos e aí fui cortando o cabelo dos vizinhos lá e era um hobby cara nem um hobby eu não divisão não

era uma diversão eu não tinha isso como uma profissão mesmo porque eu estava enraizada em padrões sociais eu não achava que eu poderia ser barbeira aquilo poderia ser só uma brincadeira mas se eu fosse levar certo ele que você como se diz minha mãe você quer que eu pago um curso de cabeleireira é um desfazendo da profissão eu acho admiro acho que eles e muita técnica inclusive é barbearia precisa colar com os cabeleireiros para gente ir alavancar ainda mais e poder entregar melhor ainda é o trabalho que a gente faz sabe possível mesmo eu mesmo faço o curso com cabeleireiros.com é também com barbeiros conhecimento ninguém conhecimento nunca é demais né Certeza então é querido a cortar cabelo e levar naquele naquele eu falei assim cabeleireiro quero ser essa aí eu tinha certeza EA dúvida era que se eu podia realmente ser uma barbeiro início fui distanciando fiquei dos 10 aos 17 brincando de cortar cabelo Wahl 17 7 anos e 7 brancas e Hobby gostosa eu lembro que tenho acho que esse banquinho tá até hoje na casa de uma das vizinhas lá da rua era um banquinho ele já 44 perninhas de metal

e não sei se era metal ser inox e a tampa do banco era azul azul a madeira azul o bumbum pequeno mesmo aí ficava a Fran que os marmanjos raiadas tudo ao redor e 1 número tem que pôr um bom aqui desse lado espalharia toda vez quando eu vou de moto eu fico pensando em fazer uma trajetória fazer um vídeo né e é uma linha do tempo a linha do tempo de como surgiu o mostrar a Rua mostrar os meninos que eram meus clientes na época de Natal eu tenho muito desejo fazer esse aí tem que mês que eu já cheguei pegar e fazer eu falei não tá bom pera aí eu acho que eu preciso melhorar esse negócio e apresentar os meninos e aí apresentar o inclusive um senhor já que daqui a pouco vai bater as botas e eu não fiz isso com ele eu fazia uma permuta com ele e ele não tinha condição de comprar a máquina de corte e eu só tinha Tesoura o pente e uma navalha para máquina na época já era elétrica ou era aquela de há manual não não não sou tão velha você tenha muita

rua aqui nenhuma tá vendo demais interior né interior tu chega demora chegar Jé foi já chega depois beleza e aí máquina de corte era cara para minha mãe comprar na época e aí o seu Pedro eu chamei de São Pedro não ela nem viu a velha assim eu não sou é chamado seu Pedro até hoje ele tinha essa máquina eu falei com ele assim deixa eu cortar seu cabelo Oi e aí você deixa a máquina comigo você não precisa me pagar e na época eu tinha vergonha inclusive de receber o pessoal não pagava dois às vezes não me pagava era r 3 eles não me pagar e eu pegava minha gente essa questão de você ser Próspero é está muito enraizado naquele que te ensinam né a base né na base você pensa você ter vergonha de receber pelo serviço que você Estônia é porque aonde é que tá ligado está ligado à se é prazeroso eu não posso cobrar porque trabalho tem que doer isso é mentira trabalho não tem que doer trabalho tem que ser prazeroso eu tenho que estar lá em inteiro para servir o outro você executar com excelência né senão

com excelência com prazer com gozo eu sou eu e o riso muito isso não sei lá época eu tinha vergonha aí quando eu me conectei com isso pra gente por que que eu te amo antes receber e tava ligada merecimento né É Oi eu sou o Pedro tem que fazer um vídeo com ele só pede até chegar aos 90 anos de idade já Timóteo essa história aí a página não e aí os 17 anos a escola também tava inclinando muita gente ter canudo sabe uma formação superior principalmente porque na época foi quando teu aquele bumbum do Enem é faculdade mais acessível não sei se você lembra disso é pobre também podia fazer faculdade começou aquela adrenalina engrenagem ainda né e ser mais acessível na faculdade que eu pensava se na escola eu tinha muita dificuldade na escola sabe para aprender eu tinha que esforçar demais sentava na primeira cadeira e mesmo assim foi tem estranho é Mas Era óbvio que aquilo não era para mim tá se eu for quando eu estudo hoje sobre barbearia um negócio que eu gosto que eu tchau tchau Tem coisas que eu não gosto mas tem que aprender mas

a maioria das matérias eram complicadas matemática então era complicada eu ficava pensando assim gente com que o vô a minha mãe não tem condições de pagar uma faculdade para mim e a escola tá falando que isso é o mais importante na vida do ser humano ele quer conquistar alguma coisa como que eu vou chegar lá né eu vou chegar eles virar nos 30 aqui né Aí eu ficava pensando porque eu vou para BH fazer um defe MG como é que eu vou passar nosso objetivo de chamada não fala que é diferente a pena diagrama ali naquele número que vai ser isso E aí nisso eu pensei eu vou ter que fazer então curso técnico com curso técnico Eu pago a faculdade com a faculdade e aí eu consegui se alguém na vida naquele negócio de ser alguém não tinha isso deve o povo 600 km de extensão da Avenida e escrevendo seus coleguinhas tudo se preparando para o Enem para o neném para tu lá no vestibular para não eu ficando aquela preocupação até que eu fiz um curso técnico né agora minha mãe tinha oferecido cabeleireiro eu já tenho certeza que isso não te

liga aí fui me distanciando dessa dessa minha identidade natural você barbeira né loja de parede questão de padrão social eu mesmo eu tinha essa limitação de eu sou mulher homem faz certas coisas mulher em Mulheres Fazem outras coisas assim e não se mistura eu acreditava nisso né criada a ser a pensar nisso né a gente é bom que a gente se liberta né tá bom que estamos avançando com peso né as gerações vão melhorando nessa e e não para ser maior né Mas por que a gente possa quem está por igual e que todo mundo tem a liberdade sei quem é eu ia ser então eu fiz o curso técnico de segurança do trabalho segurança do tô errado caramba totalmente diferente não nossa E aí fiz estágio A ideia era fazer estágio conseguiu um emprego em Timóteo para não ter que ter um custo de vida aqui onde eu tirar se o final o dinheiro do Olimpo a Lari né falar para poder pagar a faculdade para pagar o curso de vida né só para pagar a faculdade mas a gente planeja umas coisas mas a vida te dá outras foi completamente diferente né o

bom é planejar para que de alguma maneira ela vai te dar alguma coisa jeito de hoje horas que tem um rumo né E aí ou eu não consegui emprego só consegui estágio na minha área Oi e aí eu falei não vou ficar em Timóteo preciso passa asa eu vim para BH fiquei aqui trabalhando como atendente de telemarketing até conseguir emprego na minha informação técnica de segurança trabalhos e que um período lá que oito meses durante oito meses não desisto não desisto já tinha gente que trabalhava junto comigo que ele é mais ser bobo você consegue vai conseguir emprego na sua área não eu tava ali né eu consegui assim aí depois de oito meses eu consegui aí foi trabalhar numa empresa você vá só limpeza depois fui para o Acre quem trabalha no Acre lá caramba muito lacres lacres não lá que foi bom porque lá que eu tive a oportunidade de trabalhar O que é construção civil estrutura metálica solda até para alimentar todo mundo que tudo foi ver nessa aquilo foi o estágio para mim uma aula e olha que eu nem tava mais como estagiária eu falei não é lá que eu

tenho que ir porque é lá que vai me dar bagagem para eu doar né atuar com representação de rua de estrada eu trabalhei colocação de placas de sinalização olha só que conhecia você não é para quem não sabe não tem nada a ver também mas eu trabalhava numa empresa de fiscalização e sinalização de trânsito usamos atrasei mas você não ia ser mas você tava dentro do caminhão e eu não ia para eu não era da equipe de frango aqui porque eu de regular o ali né Depende de você colocar ela aqui o cara vai dar uns Ah pode pá o que a convertam outro lugar mas ela é lá então é aí eu fiquei aí né Aí eu falei aqui hoje trecho eu e quando a gente chama fala peão o pior de três e quando você começa uma obra em determinado lugar é sobra tem tempo para acabar e você vai para outra obra se você tiver oportunidade da obra e aí eu trabalhei ela no Acre eram era fim de obra já mas nessa nesse fim de obra eu fiquei nove meses ok demotec segurança lá ela era uma amiga minha conhecida e

ela não queria mais ficar era queria voltar e o engenheiro que trabalhava com ela virou para ela falou que ela tinha aqui ó Oi gatinha que colocar uma pessoa no lugar naquela época Ninguém queria para o Acre é hoje hoje eu acredito eu morava em Cruzeiro do Sul que era a segunda cidade maior cidade né A primeira Rio Branco é a capital eu morava em Cruzeiro do Sul eu amei morar no Whats todo lá que eu fui Espírito Santo depois fiquei um período trabalhando no trecho na obra lá em Timóteo mesmos quatro meses e depois do Espírito Santo eu fui para o ar para o Itabira então aí assim deu uns aninhos a lei E aí 2012 eu fui para Itabira E aí em Itabira quando foi 2013 adoece de pressão minha vida tá sem sentido eu não quero quero fazer alguma coisa que pulsa meu coração como é que eu vou fazer acompanhamento com o psicólogo para coisa toda e eu não quero passar nessa vida eu tenho uma certeza deste eu não queria passar por essa vida tem que fazer diferença isso aí é latente era uma coisa que todo dia eu dormia

acordava pensando dormia acordava pensando eu preciso fazer algo onde o meu coração esteja conectada esse kit move né É isso que move a gente ali né o começo do segurança trabalho tudo era novidade né quando tudo é novidade né energia né mas se realmente tem aqui meu acabar energia mesmo e assim é um ser humano ele é feito de propósito né ele não tiver um propósito quando eu falo de propósito Eu tô falando de um propósito da auto-cura e normalmente a gente aqui em cara já encarei muitas vezes propósito como dentro para fora e eu entendo que o propósito Nossa medida que a gente vai caminhando E ele nos transforma então propósito da gente aqui nessa terra é com a gente mesmo é com nosso desenvolvimento e a barbearia próximo muito para mim isso desde quando eu me reconectei e todos os dias ela me traz para o propósito do meu o desenvolvimento do a franja cimento isso a Fran como pessoa o que que ela tá que que ela tá fazendo aqui nesse mundo para Que ela possa ser uma pessoa melhor reconhecer nos seus defeitos melhorando eles enxergando eles ir e aí as

pessoas que vão agregando elas vão também juntos nessa caminhada vai vai junto nessa caminhada bom então é isso aí olha que eu parei e parou na depressão isso E aí eu comecei a entender que eu tinha que fazer alguma coisa que você fazer a diferença onde meu coração estivesse conectado E eu só comecei a ter uma sensibilidade o espiritual muito aguçada sem sabe que eu falava com Deus todo dia que eu tenho que fazer é que eu tenho que fazer mais falava mesmo assim sabe me mostra me mostra me mostra comecei a fazer um clipe de fábrica de doce para distribuição meu pão não sei o que é como é que ia ser isso pesquisando máquina aí comecei vender uns docinhos na obra lá aqui é usada lá saquinho tava e isso foi oi oi morri não sabe sabe quando estava faltando tá faltando alguma coisa aqui é rentável matematicamente dá lucro Mas não é isso mas eu me propus a fazer algo que o meu coração tivesse conectado E aí nesse momento eu falei não não é isso aí mais uma vez eu falei pó Deus que que eu tenho que fazer da minha

vida Senhor e aí Nessa Hora É como se eu tivesse escutado uma voz dizendo para mim assim pensa em todas as coisas que você já fez até hoje e eu comecei a lembrar de tudo que eu já tinha feito Apesar da pouca idade na época e eu nunca gostei de ficar sem um dinheirinho ali eu aqui sempre esse teu nome sempre quis esposa disso você cria oportunidades né então eu já eu comecei a pensar como que eu poderia empreender dentro de tudo aquilo que eu já tinha feito como que eu poderia transformar aquilo que eu já tinha feito em algo que pudesse ser algo sério e eu pensei em tudo então eu já vendi meu na rua já é eu trabalhei com babá tinha Algumas casas que eu dava faxina então comecei a olhar para Aquilo é como que eu posso extrair algo aqui eu já trabalhei em cyber bar na época né lembro do sai do barco estourou quando a internet quando poucas pessoas tinha internet em casa e aí você ia para Lan House depois de lavar os virou ficou mais vou precisar saiba feliz né Cyber Café essa mesma Aí morreu aí

foi só um pouco de paz foi não esse viu né para aquela época civil Oi e aí com isso é é a última coisa que eu lembrei eu fui sabe quando tem uma nuvenzinha na sua cabeça você começa a ver a cena que você já viveu e você lá dentro do sábio pra você lá vendendo o velo de la pagina tanta eu começo a ouvir esses flashes né de momentos vividos e o último Flash foi os vizinhos me chamando para cortar o cabelo rapaz Isso foi 2014 há 2 anos e quando eu último flash que vem foi isso quando esse Flash e essa nuvenzinha do pensamento e apareceu na minha cabeça e tinha um fluxo forte energia tempo chave daqui do meu crânio da senão a gente chama ele normalmente aqui de vaca clonar e até que assim no meu peito aqui no centro do peito sim os parques faz um fluxo de energia dirige que tá acontecendo detalhe nessa época nessa época eu não tinha eu tive a sementinha que meu tio plantou lá atrás por ele ter sido a minha referência masculina e tal o tio que eu todo final de semana eu

queria estar na casa dele e me dava um real e tal aquele amor dele por mim ele se você mentir mas eu não tinha percebido essa Sementinha sabe o e naquela época Em 2014 eu não tinha influência eu não tava vivendo nada que fosse parecido caseiro aquele flash que fez sábado e nem tinha estourado um de barbear e então por isso que eu falo que esse projeto foi entregue na minha mão pelas mãos divinas não tem outra né eu querendo dar o que é claro né eu te em contato naquela época em 2014 com o engenheiro meus amigos meus colegas de trabalho Tec segurança Deus é com a supervisora de obra ciência então a gente falava de patrolamento de guindaste orçamento de carga concretagem vai liberar o concreto não vai liberar tá em regular não entendeu É se o caminhão tá com dispensa da inspecionar você não tá inspecionados e ele tem a carteirinha de liberação de entrar você não tem não tem o meu universo não era isso não era esse então eu digo sim e esse projeto foi um presente que Deus me deu a profissão não vou falar nem do projeto a

profissão porque eu me sinto muito inteira na minha semana barbearia profissão foi feito foi Deus que me deu mesmo torrado porque eu acho que o outro de poucas pessoas trabalham com aquilo que realmente gosta sabe então eu me sinto privilegiada e lugares mesmo um privilégio e conectar com você mesmo atrás mandar mensagem e a maior parte do dia da gente pensa bom e foi assim que nesse momento que eu recebi essa divindade esse 2014/2014 e comecei a olhar curso oferecerá Olha eu sou autodidata mas agora vou escolher na minha profissão eu preciso me vestir não deixe aí eu vim para BH ou da sexta-feira E aí fazer o curso sábado de Páscoa época aí fiz os cartãozinho de visita distribuir na obra e depois bate a cartão José 7:00 ou 7:30 eu só me mandava mensagem eu ia com a minha maletinha atendeu domicílio tudo que eu aprendi durante o sábado eu praticava segunda a quinta que sexta eu vinha para crer isso o projeto foi desenvolvendo foi desenvolvendo foi desenvolvendo o sonho foi crescendo e aí eu fui começando a fazer a transição eu entendi que eu precisava fazer a transição de profissão e

quando foi 2015 final de 2015 dia 26 o 28 se eu não me engano em novembro de 2015 eu sair da empresa eu tinha graças a Deus irmão gerente muito boa que era Letícia sentei com ela falei e Letícia nunca foi novidade para ninguém aqui eles Você sabe que eu tô em transição de profissão e eu preciso do acerto para poder embora eu tenho um projeto para colocar para frente Olha só virou e falou que dia que você quer ir para de ser dançarina faz um privilégio né mas um comprimento de uma gestora bicho quando quando Deus quer quando tá escrito E você faz o acabamento a sua parte importante lembrar que a parte da já nas coisas não vem né Deus abençoa vai ser precisa tirar a bunda do sofá o famoso Deus ajuda Quem cedo madruga né exatamente Então você acaba movimentando um fluxo de energia positivo quando você faz a sua parte quando você sinta e reclama mas meu pai é o dinheiro era o ar e minha mãe não sei o que não fez isso lá porque minha família é pó alimentando negativamente tá alimenta porque você entra na murmuração coração

não é um a gente que você ganha com ela reclamar não muda nada mas ação muda muita coisa Oi e aí eu eu mudei para BH dia cinco de dezembro se você sair da empresa 26 de novembro 2014 dia cinco de dezembro de2001 de 2015 dia 26/2014 Dezesseis de novembro de 2014 cinco de dezembro 2014 Então é isso cinco de dezembro 2014 eu dei para BH e aí que eu já vinha para BH pesquisar volume bom e como é que vai ser lugar uma luta né faz eu já tinha feito o movimento gigante mas na hora que foi assim para botar o pau para quebrar eu amarelei eu dei uma amarelada aí o frio na barriga né Ele foi na barriga eu vou mexer no destino Vou nada porque senão eu vou é trabalhar com barbearia eu vou procurar uma oportunidade de atender em uma barbearia aqui em Belo Horizonte e você pensa aí eu fui ali não fui lá não aqui não a visão atrás não é E aí deu ruim hein deu ruim eu achei que eu te dou não vai pensando vai a gente ainda o ser humano ele é tão terrível

a gente é tão terrível que a gente sabe bota tempo todo eu ainda achei uma outra lá então nova aquele lugar onde eu me destaquei no curso eu vou procurar um oportunidade de ser professora lá já que aquele Professor Meu Deus será que eles são ruim para caramba eu vou lá com certeza não querer para você já professora mas fui procurar oportunidade lá eu achei que achou mesmo Achei mas sempre que isso é professora Oi bom dia aí menino eu não deixei completar dois meses normal uma hora que eu tava lá na sala aí dentro de mim ficar covarde saiuu antes vida vem para cá mudou foi esse movimento o projeto que você ia fazer Cadê o Vitinho que é estudo era para isso eu vou para aí parece assim ou foi pesado nessa hora eu levantei e eu fui no a crescer RH não sei que é uma sala de administração daí negócio que eu falei eu não posso ficar aqui mesmo se alguém já né não aconteceu nada tá tudo perfeito é preciso sair daqui que eu não posso ficar nem mais um minuto grande Deus vai me dar um prazer eu falei

se semana que vem é bom para você que você quiser falar amanhã aí quando foi aí eu sair né Na próxima quando passou uma semana eu sair eu falei não não precisa nem acertar ainda não eu vou sair daqui só isso foi muito bom momento que eu vivi aqui não não ia completar dois meses já tinha passado do mês aí eu compro outra coisa mesmo e aí e aí e aí mas foi aí que eu falei assim Acho que quer saber lá naquela loja que eu tinha desenhado a gente começa do começo eu vai ser aquela loja e eu sem profissional Vai dar vai dar certo naquele lugar pronto eu não simpatizar muito com um lugar Um lugar nossa aí foi aí que eu comecei a fazer os movimentos do lugar né tal aí foi inaugurado tia e Quatro de junho de 2016 a mulher barbeira já que esse nome será que esse nome desafiador né é esse nome também foi um presente é vamos também eu costumo dizer gente tudo que acontece não é nada eu que fiz você só tá indo né só de uso eu vou aí não entendeu porque é o

nome também negócio assim mulher barbeira eu não forte é falência um nome forte ele disse constrói para coisa né E e essa piadinha de que mulher barbeira e eu escuto muito eu tenho esse uniforme aqui hoje eu vou no restaurante vou no banco vou outro lugar com ele tô aqui com ele é Oi e aí o povo fala assim mas você direito essa piadinha deve ser a que mais acontece mas é legal porque você cria um trocadilho e eu sempre você começa a fazer sem fazer esforço a pessoa pensar o Hans ele é bar Beira mesmo a profissão não faz sentido nenhum colocar como de meta uma mulher que dirige se constrói mais um desconstrói sem fazer esforço né E aí a piadinha fica sem graça né Oi e aí mas eu adoro quando eu recebi essa mensagem é porque o cara se surpreendia eu falo não eu sou barbeira mesmo no trânsito Dá até para fazer o pé é na tesoura eu sou barreira e é isso aí faz amizades cara conversa brinca ri aí no final vai lá tá na rua tal já aproveito e faço mais eu já falei você entendeu então

foi assim que nasceu para barbeiro e o nome né começou a falar do nome ou o povo que escutar isso aqui eu fiquei até mineira a gente fica aqui agora eu acho que vai ser os melhores Episódios do podcast e se acha que vai ficar muito eu acho que vão escutar primeiro ou não agora eu quero assistir Brasil aqui ó e é bem cedo é sempre desse que dê certo mesmo certeza já tá dando tá aqui eu espero que muitas mulheres Veja isso aqui porque a gente sempre acho que a grama do vizinho né até que deixei já falar isso todo mundo fala que a gente sempre acha que o outro é o sonho que o outro conseguiu conquistou está no caminho dele é para ela foi fácil e às vezes a gente coloca no lugar tão de coitado tão de vítima que a gente pensa assim eu não consigo ir eu não tenho e se isso acontecer não tenha e não vou mais sabe o que é que hoje não vejo mais tanto faz quando eu comecei a curiosidade das mulheres eram venha você sofre preconceito eu tenho medo de sofrer por conselho e

mais o trabalho da gente desconstrói isso né é através do constrói na prática na prática sim é sem diminuir o outro você mostrando aprovando né porque ainda a gente tem que provar porque ainda uma mulher já era uma dúvida se ela realmente corta bem a gente está mudando isso nós vamos dar cada vez mais e a minha ideia eu tenho sonhos e projetos mesmo da capacidade de fazê-lo acontecer de que é ser uma mulher barbeiro não seja mais uma novidade o que quando isso acontecer é porque a gente virou a chavinha Oi e aí a gente vai lá e trabalhando tranquilamente sem ficar sabendo que se provar nem provar o tempo todo ela fica eu convite a todas as mulheres que desejam ser barbeiras a mostrar que é possível e que elas estejam encorajados mesmo né Porque quanto mais mulheres quanto mais mulheres barbeiras mais fácil vai ser as mais alcançarem alcançar igualdade né nada mais do que o que todo mundo merece né e pé sossego na vida trabalhavam bater a tesoura Vamos bater vamos fazer pente corrido vão passar a máquina usar o animais se e é isso onde que eu tava o

nome não falando o nome não é o nome da mulher barbeira Surgiu da seguinte maneira O Léo foi o rapaz foi o primeiro Marcos que eu tive Oi e aí eu contratei ele Achei ele no Google aí eu falei só levo eu tô com projeto assim assado a mandar o orçamento deixei com ele aí ele é preciso de criar um nome porque eu tenho o projeto mas não tem o nome já estava em obras já estava em obra eu não tenho eu não tenho as coisas minhas contas mais ou menos assim não tem o nome eu preciso criar um nome eu preciso construir um homem criar mesmo né porque a construir um caminho criar um nome eu não sei que nome que eu vou querer E aí ele fez não contrário nós vamos fazer isso isso você vai começar a E aí gente vai começar a criar o mar beleza e ele me mandava o nome nada a parte do nome é o ele mandou o nome para mim que eu vou falar para vocês o que já era na época era na Rua do Ouro hoje na Avenida do Contorno essa a primeira loja

foi na Rua do Ouro Oi e aí ele falou comigo assim um Pensei aqui que o nome poderia ver Constantinopla constantinópolis e sem graça né aqui você gosta aqui fazer pastel de nata II o que eu falo com ele que eu não gostei vou ver aqui mas você gostar assim não é verdade empolgado porque isso não porque constante volta uma cidade com muitos ouros nas acho que na Europa Europa une-se poder se gabar muda época tal ir aí é Rua do Ouro E aí aí ficou aquela dura né se olhar você pensar mais um pouco mais de novo nenhum outro me deu o outro E aí eu aí nisso ele para desenvolver o negócio e começar a criar a rede social e tal aquela coisa toda eu falei sim Léo eu preciso botar seu Instagram há uns um uma chamada de tipo contrata-se mulher barbeira não contratos eu tenho até hoje esse folhetim a no no Instagram contrata mulher contrata-se mulher barbeira há 2 meses E aí é só que eu achei que ele ia configurar essa frase minha é uma outra maneira de entender ele vai vou fazer o foi faz o fla que

eu vou eu vou postar porque eu preciso de ter as candidatas que vai trabalhar comigo e aí ele não configurou não ele fez um Fly mandou para mim sim trata-se mulher bater do jeito que eu tinha falado para ele vai Mas foi melhor coisa que ele fez nada na hora que olhei e aquele rapaz ele não mudou nada o medo daquela crítica né rapaz ele não mudou o negócio aqui é que ficou que eu falei com ele mas era para eu perdi configurar de acordo com macho né contrata-se mulher barbeira com Simone barbeiro vai chamar mulher barbeira mandei para ele isso tô foge não é eu que faço as coisas tá vendo se ele tivesse mudado o texto em aranha não sou eu só eu sei lá indignada esse motivo de olho eu só escolho Deus vai mostrar uns painelzinho minha filha tem isso aqui ó pega vai querer o meu amor brilhou na hora eu falei Mel vai ser mulher barbeira é uma energia daqui quando você falou vou levar a vida desse tipo aí aí ele nome composto aí ele mostrou a técnica dele no nome composto não se utiliza e é para

marca a gente usa como slogan Tecnicamente falando não tá certo mas se você quiser colocar uma barreira como os logo a gente cria um nome e o slogan de baixos tipo Constantinopla mulher barbeira efeito bom maior fã linda é uma esse racha mesmo e respeitando o profissional Claro acho que eu furei a mesma né eu não pode não pode as fontes aqui nossa aí começou aquela saga de achar um nome que combinasse com o Êxodo mulher Barreto aí é uma amiga minha é muito ela é meio viajado também aí eu e aqui 30 incomodando eu ia para obra e o nome incomodando a vendo aí ele virou para mim falou assim tem outro detalhe gente coloca mulher guerreira e se você não conseguir mulher para trabalhar E aí eu fiquei é você mesmo E aí eu liguei para sua amiga e que ele come só quando tá com aquela angústia dentro do C5 você dá uma botar para fora não tá para fora aí eu fui eu liguei para ela eu falei com o senhor Oi hoje já chama a Isa é todos nós Um o negócio é o seguinte Olá estou procurando um homem

para trabalhar ir eu também não falei com ela não eu já tava ficando tímida com o nome você tá ideia então falar com os outros mais aí ela eu falei para ela funciona e eu tô precisando de um nome tal eu tô com o nome aqui tu que tá com vergonha de falar o quê fala para mim ela foi falando os outros nomes lá e agora fui Tenta me ajudar eu tô com o nome aqui ela fala qual que é o nome aí eu falei assim ó vou levar Velha ES é o que me leva a ver agora tudo bem aí eu falei mulher em bar beira E aí ou ela ficou assim ela falou assim ó E aí tudo que eu tinha falado para mim eu repliquei para ela mas não falei que ele tinha falado para não dá assim como ela ficasse contra ela entendeu Aí eu falei assim mas não é nome composto É Bem Assim Que bonito a ideia dela também porque mulher caveira também pode ser interpretado como mulher rendeira aí ela cantou a mulher rendeira e aí eu falei assim mas assim isso e se um dia eu quiser

por exemplo é vender papelaria e eu não ficar lá mais para quiser colocar uma sim tal você não conseguir colocar profissionais destas ela o da se você é mulher barbeira aí pronto é isso E você trabalha com outras pessoas quantos anos não porta você me leva a pena porque eu sou isso comigo E aí falei com olhão vai ser a ver eu levo olha olha esse lindo e pode ser que a dificuldade achar profissional se você já tá fedendo e eu não importa aí eu falei o que ela falou né eu vou levar mesmo sempre se for eu for mais e sobre as maneiras e aí foi assim que nasceu não levadeiro eu não muito forte meu nome é muito representativo né Tati sim mas e aí aí daí que você teve a ideia de contratar só mulheres então a ideia de contratação mulheres foi lá atrás quando eu comecei a receber não não não não e eu vi que existiu e iria acontecer um bom de barbearia eu vaidosa que só quero fazer aquilo que ninguém fez ontem e aí no mercado vai não tinha ainda vai surgir muito barbearia no mercado 50 e

foi um burro mesmo e aí eu não quero ser só mais um E aí eu tava no propósito fazer alguns parentes sabe O que você acha que ia por você ter né só mulheres com profissionais se tem algumas você vê alguma diferença de gestão em relação ao barbearia tem homens ou CESPE Olha eu eu nunca trabalhei em uma barbearia Na verdade eu conheço profissionais mulheres barbeiras que já trabalharam em ambiente é e onde tem profissionais homens taveiros e que relata alguns desconfortos mas também é um tipo de preconceito e tal até para o partido ao vivo às vezes muita das vezes até pelo colega de trabalho que acha que ela menos preço não é uma ameaça que às vezes bem então já vi relatos aí eu nunca vivi na Pérola 1 o parte de clientes também que às vezes tem um horário vago lá tá todos os homens atendendo e na hora que o profissional tenha um horário tem aí vem a barbeiro para agenda o sujeito lá mas eu não faço uma mulher Então já vi esses relatos assim de 12 profissionais que já trabalham comigo né conseguem falar sobre isso mas eu nunca

vivi appelez un Olá tudo isso é parte de é do patriarcado né que já vendi e muitos anos muitas gerações hoje eu posso dizer que a gente a Cameo bastante a gente tá vivendo é o melhor fase tem muitas ajustes para serem feitos bem mas é através do nosso trabalho mesmo é da nossa coragem da nossa competência técnica e atrás de um conhecimento técnico para ser cada vez melhor não pensando em competitividade mais pensando é em servir o cliente pensando no cliente pensando que ele como ser profissional entendeu bom e no começo era só você é quanto tempo você ficou cortando só você é como que foi para conquistar os primeiros clientes não estava abrir um negócio novo verde um ramo completamente diferente negócio hoje não tia seus contatos eram completamente diferentes né e é a partir daí como é que foi essa nova fase é rapaz eu faço um Oi hoje é gosto de contar inclusive os profissionais que estão chegando hoje eu costumo Principalmente quando chego lá na barbearia Aí tem que fazer cartela de clientes isso é um processo eu conta minha história para poder engajar elas para poder encorajá-las também para

poder mostrar para elas que um dia você vai atender um cliente porque você não vai entender que ler e outro dia você vai ter três clientes e aí você aquele que ele que sentou na cadeira você vai ter lá focada em fazer com que ele volte porque a cada Pingo Zinho que tá indo ali você vai encher o balde grande em grão que a galinha enche o papo então início era eu e uma outra profissional que eu tinha você já viu então vocês duas eu fiz não eu fiz uma obra estava acontecendo E aí eu fiz você lembra daquele encarte do Fly contrata-se mulher barbeira verdade né então TV os candidatos na época e aí e dessas 3 uma foi selecionada e ela começou comigo ela ficou comigo durante acho que uma semana duas semanas na terceira semana Nossa tentou aí eu fiquei no período aí alguns meses sozinho até achar uma outra profissional e EA maior parte dos profissionais que começaram comigo ou pode falar que 95 porcentos eu quis a informação delas potente disorder oportunidade tem aqui a cadeira traz o modelo eu vou te ensinar nós vamos fazer esse vai ser barbeiro

importantíssimo né Isso é e esse trabalho às vezes ainda acontece é por isso que existiam Eu tenho um desejo projetos improviso Oi e para mim é muito gratificante e quando eu abrir a barbearia eu tinha horário para abrir disciplinadamente um horário para fechar E aí e é o que eu falar mas eu não tenho que você entrando tem profissional que entra no barbearia hoje quer ir embora ele é o toner pode ir mas ele quer ir embora não tem cliente não fez carteira de clientes daqui é gozar de 15 horas de horário e um benefício sem sem ter conquistado ainda vai dar 5:00 um barco atendendo ninguém não você tem que chegar pensando que aquele dia você pode atender ninguém e Como já aconteceu de eu fechar a porta tem muitas vezes de atender um cliente instalar eu na época eu abria 8:00 Chapa 8:30 é urgente atende já chegou 8:30 mais cedo né ouvir o fazem bom então eu eu chegava a Bia eu tava tudo tava tudo um tava lá na época não tinha eu criei meu uniforme na época que era uma gravata calça jeans mesmo filho eu suspensórios e era gravata

borboleta gravata borboleta e suspensório aí ficava ali esperando o cliente sendo tu não vai vir vai vir aquela vibração ele dia que eu não atendi ninguém mas Fechei as portas no mesmo horário e tá escrito lá de fechamento 8:30 e 8:30 e onde atendia um era uma vitória não podia desanimado é claro que tinha os momentos que você falar qualquer coisa é a sua vida né chegar como é que eu vou pagar essas contas a vida do empreendedor brasileiro né sem dinheiro e agora jeito mas quando você tem um E você tá no fogo ko3 IV cliente entregar o seu melhor eu aquele aquele sentido assim de que você vai eu não nunca pensava que você tá fazendo favor porque no momento que você começa a pensar que você tá fazendo um favor para o cliente você tá guardado apagar acabou o seu negócio por Comerciantes deixar aqui em ali cada cliente é o seu melhor né então é melhoria tem que ser continuar cada vez melhor para servir Oi e aí aparecia muito curioso Aprecia os gás mesa é maravilha mesmo necessário hoje fecha o menino lá atrás é o primeiro set profissional mas

hoje você acredita né que vocês Já conseguiram mostrar que o diferencial ele não tem nada ele falou que ia ser uma barbearia diferente das outras né É acho que o pessoal hoje ver o diferencial pelo risco vocês prestam ou ainda tem muita gente que acha é pelo gênero deixa eu te falar no centro e clientes um deles meu bastante perfil né Graças a Deus você é fruto de trabalho a gente tem aquele cliente que é desprendido de qualquer tipo de preconceito diferença que o homem ou a mulher faz melhor ou pior acha que tanto homens quanto mulheres quanto a mulher segue é desde que tenham é conhecimento técnico a regra de Gol para infectar de igual para igual e também essa questão da competição seja próxima e na cabeça do parafuso ele já vai espontaneamente vai desprendido para relaxar senta dentro da relaxar na cadeira e tal o outro perfil de cliente é o cliente e vai desconfiar de Será que você faz Olha esse é o que eu quero isso eu creio mais gosto é através dele que eu consigo gerar transformação o que já tá como se diz curado já tá já procurado

ele vai ajudar a gente mas para gerar transformação é o cliente e tem aquela pulga na orelha aquele cliente que tem aquela desconfiança é o cliente que tem aquele preconceito não é vivido essa experiência aquele cliente que tá dentro ainda enraizado naquele padrão social né mas sinceramente eu não preocupo com isso não porque eu tô lá para isso só essa missão é E aí viu o que que eu gosto esse mês pois era a transformação tipo o disco tava hoje eu não escuto tanto mas de ter escutado várias vezes o cliente no final do atendimento falou assim eu vi porque eu tava curioso Mas eu sabia que você ia pegar na minha barba no meu cabelo mas foi a melhor paga o melhor é cabelo que eu já fiz na minha vida então isso você pensa no nível disse tá tá tá curando [Música] é um produto você só tá piorando uma quebrando paradigmas quebrando paradigmas é então meu barbeiro veio para quebrar paradigmas e o outro perfil de cliente aquele cliente que ele tá no lado oposto do negócio se ele acha que o homem não sabe fazer hahaha ele acha que mulher tem

a mão mais delicado pode ser que tenha mesmo mas também tem mulher que tem mão pesada entendeu tem mulher que tem suas dificuldades com qualquer outra pessoa sabe Pensa a gente começa a olhar para esse lado também do e a mulher é isso aqui né Faz melhor eu não sei o que a gente pode ter uma algumas características femininas é e trazem alguns benefícios Mas isso não pode ser porque senão a gente vira pode ser taxado nessa fora aí você tem que vir e também fazer esse trabalho O que é uma questão de competição tá comparação naturalmente o ser humano a relação de inclinar É tem que tomar muito cuidado com essa comparação eu vou ser de merece todo uma luta não é só por isso né as pessoas como vocês. Esse merece a luta do barbeiro que tava lá atrás se você é quantas décadas tecla em SC é só chegar Ah tá hoje você sabe e não pode virar para poder acabar não pode não não pode virar para poder acabar o preconceito não posso criar um outro preconceito agora você comentou aí né que tinha alguns planos aí para o futuro liga

ela vai perguntar o que que você pode dar spoiler aí para gente tem spoiler eu posso dar spoiler a quem quem assistiu esse podcast aqui E aí dá tempo e quem assistir os podcast que deve ter percebido a nossa também certeza hahaha mas então vamos deixar aí as cenas percurso nunca vi você me convida de novo e a gente nos próximos vai ser o nosso próximo cada dois quem estava em cama aí deixa eu te falar para a gente encerrar então é comentou do seu tio Geraldo F geral acredito que ele tenha sido uma das suas maiores inspirações é mais quem são suas outras maiores inspirações aí a visão que a minha maior inspiração hoje todas as barreiras que querem ser barbeiro elas são as minhas maiores inspirações e as minhas maiores inspirações depois delas são os barbeiros que já são bárbaras as que trabalham comigo muito legal é com certeza mas um time de guerreiras né e cada vez Vamos formamos mais times né a farda tá aí não é à toa né dá para você verem minha mãe sempre elogiou esse uniforme Você acredita as mulheres param a gente na rua para falar

nesse vídeo mais aqui no nome dela é lindo demais ele foi construído pela gente elas mas eles trabalham com a gente Eu sempre tive vontade de ter um uniforme como macacão então quando eu mudei de loja expandir eu falei quando a gente for criar um outro uniforme vai ser o órgão E aí começam pegar algumas referências e aí não gostamos de nenhuma referência não a gente gostou de uma referência mês tinha coisas nele que a gente não gostava e a gente foi construído junto então eu mandava para costureira palavra senhor' a gente tem um negócio assim mas quero que paciência e ela foi montando ele a gente falava nós aqui é bom Daqui é bom aí As meninas falaram Não é isso aqui tá legal esse aqui não tá a gente construir juntos é por isso que todo mundo para né além de ser muito bonito tentando uma energia uma história e por trás né bom Francis mais uma vez te agradecer pelo seu tempo é que história incrível é espero que realmente é esse podcast ajude a encorajar né muitas outras barbeiros net chegue a muitas outras maneiras também e também os barbeiros né

Para a gente é legal eles entenderem o outro lado da moeda deles eles são é um é uma Peça importante para ajudar a gente com certeza tanto para tratar a colega de trabalho é para ter mais atenção o tratamento entender que nós só por exemplo se existe uma barbearia Onde tem um homem e mulher trabalhando eu não preciso ter receio de ter uma mulher trabalhando porque se tem 100 clientes e se a gente fidelizem se sente clientes são 100 clientes que pode ser distribuído entre os profissionais que todos os seus dependentes do gênero certeza bom mas contamos com vocês barbeiros contamos com você bar Beiras é que essa luta seja cada vez mas perto da vitória nem e que possa encorajar mesmo muita gente é mais uma vez muito obrigado e o cortar cabelo lá em rotas ponta sobrando as barbearias aí de BH ele a terceira lá que marca lá que deixou a festa daqui é um prazer atender eu quero agradecer também o pelo convite como falei no início uma grande ser notada uma vez que tem muito Muitas evidências mostrado muito muito barbeiros muito mais grandes cargueiros e quando a gente é

convidado assim a gente fica honrada mesmo essa porta Siena é isso eu espero que o nosso papo aqui e se espalha aí que as pessoas se inspiram que gere também uma transformação insistiu em tem um sonho aí para realizar o [Música]`,

  summary:
    "Episódio 3 da Temporada 1 do BestBarbers Podcast. Mulher Barbeira compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
