import type { VideoContent } from "./types";

export const podcastrapha_da_barbearia_ep01: VideoContent = {
  slug: "podcast-rapha-da-barbearia-ep01",
  youtubeId: "hClgBiL8t3s",
  title: "BestBarbers Podcast com Rapha da Barbearia — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 1 da Temporada 1 do BestBarbers Podcast com Rapha da Barbearia. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "rapha da barbearia",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2022-07-07",
  duration: "41:39",
  category: "Podcast",
  tags: ["podcast", "temporada 1", "entrevista", "gestão", "barbeiro"],

  transcript: `a única coisa que é kappagen da liberdade para quem está empreendendo é um e fala Barbie Seja bem vindo ao best babys podcast o seu podcast do ramo de barbearias que promete muito nessa primeira temporada eu sou Gabriel um dos fundadores aqui do best babys o melhor aplicativo de gestão para sua barbearia então tem esse primeiro episódio vou estar entrevistando o Rafa da barbearia ele quer uma das maiores influências hoje no país nesse segmento ele que se destaca nas redes sociais já tem várias unidades do seu negócio e ele vai tá dando dicas muito preciosas para você fica então é um episódio que você não pode perder e não somente essa Episódio mas toda a nossa Temporada tá com convidados que vocês nem imaginam então semanalmente se manter ligado com a gente e vamos juntos escutar até o final esse primeiro episódio que promete muito senhoras e senhores bar vídeos de todo o Brasil barbeiras também estamos aqui com o famoso Rafa mas o episódio do nosso best Bass podcast Rafa seja muito bem vindo Obrigado o famoso Desde quando ele desligado Oi para todo mundo né que tá vendo ouvindo né não não sei

como que você tá aí nesse outro lado nesse prazer tá aqui obrigado pelo convite estamos honrados com a sua presença você que hoje é um dos maiores influências do Brasil aí na área da barbearia e para gente conversar quando um pouco aí da sua história conta um pouco da sua trajetória como é que você caiu nesse mundo a barbearia que que você tá fazendo hoje pessoal é Cai Na barbearia para mim foi de paraquedas não né na verdade eu não tive muitão não mano de de que eu iria fazer eles a gente fica falando assim ah eu amo barbearia tudo eu sou o cara que eu aprendi a amar B ali mas eu não amava você barbeiro nunca foi meu sonho mas aquele negócio na família já tinha barbeiro eu não queria saber de estudar sim como muito saber também que eu sei viu gente ó tá errado viu pode não é eu não queria saber de estudar aí pô tava com meu aqui tá bom assim também ouvindo bem né tá beleza então tá bom né Olá meus 15 anos de idade fazendo absolutamente nada da vida querendo nada com a dureza aí meu

pai falou com ele só vai ficar tô não vai trabalhar Vai fazer alguma coisa minha mãe conversou com meu tio me deu a primeira oportunidade que todo mundo sabe né minha família já tem muitas vezes desde 1992 a minha família já tá no ramo de barbearia Então são muitos anos por aí né E aí eu comecei cara com 15 anos eu lembro muito bem que eu tava fazendo o curso e a chave não tinha virado eu ia no curso muitas e arrastado cara na marra mesmo pela força do ódio né quando eu comecei cortar cabelo no salão do meu tio do mesmo jeito eu não tinha prazer nenhum eu lembro muito bem do dia que eu comecei a ter prazer de trabalhar que foi quando eu comprei um Playstation cara eu era louco para ter um Playstation muito tempo e minha mãe não tinha como me dar nem meu pai e aí eu lembro que meu tio falou se não se você quiser eu compro Playstation ali para você no cheque você vai me dar o dinheiro a partir do momento que o cara eu consigo comprar alguma coisa com o meu esforço né Então

a partir daí virou a chave eu comecei a trabalhar muito no início grava r 3 por corte de cabelo e ela numa região mais periférica então Tinha que trabalhar para caramba e preguiça de trabalhar a partir do momento que eu entendi o que que o trabalho poderia fazer me proporcionar eu posso dizer que nunca mais eu tive até hoje né E aí nessa Isso foi em 2009 que eu comecei né isso aí já vou para 13 anos já tô com 13 anos de profissão que passa muito rápido muito tempo passa rápido mesmo e hoje você tem vários Empreendimentos vamos dizer assim é hoje hoje é sim principal empreendimento né sem ser papo de conte né gente mas eu falo que o principal empreendimento sempre na gente né cara porque se você for uma pessoa inteligente uma pessoa bem relacionada à estrutura aqui da sua empresa pode falir Mas se você tiver tudo na sua mente você começa tudo de novo e faço melhor ainda por causa da experiência né mas hoje eu tenho eu queria do Rafa que hoje é uma rede nós já temos duas unidades já com planos da terceira unidade e também

um projeto todo criado para franquias então em breve se Deus quiser também vários lugares aí do Brasil né a gente eu quero que tenha barbearia do Rafa todo lugar do Brasil mas os principais lugares vão fazer isso até na praia viu que ele sempre Então a gente tem a barbearia do Rafa aqui vai completar três anos no dia doze de junho de 2022 não sei se quem tiver vendo depois da outra época né um completar três anos e foi muito legal porque quando eu fui montar a barbearia do Rafa eu não tinha o dinheiro todo que eu investir de carro no primeiro momento a investir lá 250.000 eu tinha só 70 o restante foi tudo através de cheque cartão de crédito e era para eu estar quitando a barbearia agora em junho então com 3 anos era para estar quitando cara e graças a Deus nesses três anos já aconteceu muito mais coisas do que só que a primeira unidade né Nós já estamos quitando a segunda unidade que essa desgraçada de conseguir fazer em seis meses a gente tá tá finalizando E aí nós temos na Savassi e temos também na região do Vila

da Serra que é que em Nova Lima na cidade vizinha e além disso também tem o Barbeiro em web que é a escola de para barbeiros e lá dentro nós temos vários braços né então nós temos o workshop curso prático palestras mentoria cê o curso online assim Total já foram mais de 40 mil pessoas estudando com a gente ao longo de sete anos e agora também mais recentemente o btw Shop que é o e como esse que nós vendemos máquinas tesouras absolutamente tudo então comecei como um barbeiro colaborador e hoje graças a Deus podemos crer conseguimos crescer e conseguimos também hoje empregar pessoas né gerar renda aí para é realmente pegar essa transformação que teve na minha vida e levar para os outros também cara tô por aí foi bem legal e depois que eu atingir a empreendedora eu percebi o tanto que dá para vocês ficar lá cara com barbearia né Porque até então a gente tinha muita televisão né que o Barbeiro ele era aquele cara Queria fazer só para comer ele só para pagar as contas mas que nunca poderia talvez ter uma vida abundante né vamos dizer assim né a gente

via e pensava que isso era só por um médico só para um advogado um engenheiro e guardar para um barbeiro também tem uma vida assim como um médico advogado Engenheiro Mas ele tem que se esforçar na mesma medida não tem como você querer ter as mesmas coisas sem ter sem percorrer o mesmo caminho também cara é praticamente o médico Engenheiro advogado fica ele cinco seis até mais anos estudar não se aperfeiçoando às vezes muitas vezes não só na área específica mas em áreas Gerais né e o Barbeiro além do conhecimento técnico do corte que abriu também precisa do conhecimento da administração do negócio em si e você eu vejo como um dos poucos barbeiros Há muitos sobre os aspectos da administração do negócio né E como você vê que isso é importante além do corte além do dia a dia cê acha que justamente isso e pode levar o Barbeiro para esse patamar de ter uma mesma vida né do que é o médico advogado Engenheiro Gonçalo É com certeza porque a primeira coisa que eu gosto deixar claro é que eu sou bom aqui no que eu faço mas eu não sou melhor eu

tenho ciência disso De que eu corto o cabelo muito bem mas se Sem muitas pessoas que corta o cabelo melhor do que eu mesmo das pessoas que cortam o cabelo melhor do que eu muitos não chegam a fazer a metade do que eu tenho feito por quê Porque tem o mesmo comportamento que eu também tinha alguns anos atrás de focar só no corte de cabelo e achar que aquilo ali a transformar minha vida quando eu era colaborador eu ganhava muito bem mas eu nunca conseguia ver a cor do meu dinheiro quando eu montei o meu negócio no primeiro ano eu atendi muitos clientes mas eu não vi a crescimento quanto mais eu ou menos dinheiro tinha no caixa da empresa e eu percebi que tinha alguma coisa de errado e eu não sou o cara que teve um estudo tradicional eu estudei até a oitava série tomei quatro bombas foi reprovado quatro vezes no último ano eu fui convidado a retirar e cara eu eu pensava assim ah não vai me fazer falta estudo sei cortar cabelo é isso que vou fazer para o resto da vida mas fez muita falta fez muita falta quando

eu quis ser mais do que só barbeiro e não que tem um problema a pessoa que ele se só barbeiro nem todo mundo precisa ter essa vontade de abrir própria empresa dá para você crescer trabalhando para alguém enviar a prova disso que eu trabalhando para o Elias eu cresci muito eu não montei o meu próprio negócio para ganhar dinheiro eu ganhava muito bem que eu trabalhava lá com tudo aquilo que eu fazia mas eu queria começar a ter um pouco mais de independência um pouco mais de liberdade quando eu trabalhava eu lembro que teve um mês que como colaborador lá os dias eu cheguei a fazer r 30000 não r 30000 de comissão Na barbearia mas tipo assim poxa eu fiz meu 67 mil reais lá de comissão aí vende mais uns curso prático mas o shopping fiz tudo cara mas eu lembro que quando eu cheguei no final do mês para fazer as contas eu fiz as contas viu nos diz assim sabe tipo desanimado cara você quer sim caramba velho Será que eu ganhei esse tanto eu vou ter que ficar assim trabalhando de domingo a domingo não consigo ir na igreja não

tenho tempo para ver minha esposa a gente quer ter filho mas se eu tiver filho eu não vou nem conseguir levar meu filho na escola um dia eu preciso dar um jeito de ganhar o mesmo tanto que eu ganho hoje mas tendo liberdade a única coisa que é kappagen da liberdade para quem está empreendendo é uma equipe é a equipe é aquilo que aquela que te dá a liberdade de ideias porque muita das vezes você tem uma ideia muito boa mas você sozinho não consegue executar te dar a liberdade de tempo porque você não precisa tá dentro da empresa para O Som da Liberdade geográfica de você poder estar em qualquer lugar do mundo e continuar ali também com seu plano rodando Liberdade financeira de você ganhar dinheiro sem ter que trabalhar é especificamente ele fisicamente óbvio que você tem que trabalhar muito né a sua mente para isso né E aí eu pensei assim cara eu quero isso para minha vida e eu sabia que não seria do dia para noite que algumas pessoas pensam assim ah tô trabalhando muito para os outros eu vou montar meu próprio negócio que eu vou ficar tranquilo

não cara você precisar fica comigo é você vai ficar tranquilo mas depois que ia sim Sugar Até sua alma nessa escrever sabe aquelas vaquinhas que tá gordinho não passa depois Era magra com o olho fundo dela medo é isso aí então costumo ver o Gabriel para a gente poder ilustrar bem isso cara é o seguinte é uma vez eu até fiz umas contas eu não vou me lembrar o certo agora então vou dar um exemplo Tá mas suponhamos que todo mundo ao longo da vida vai ter que trabalhar 80 mil horas Ah então você só vai ficar tranquilo depois que trabalhar 80 mil horas se você trabalha 8 horas por dia você vai demorar um certo tempo para chegar 80 mil horas se você trabalhar 16 horas por dia você vai chegar nas 80 mil horas muito mais rápido então empreendedor ele dá um gás muito grande agora para que ele possa atingir essa meta de horas trabalhadas mais rápido do que a pessoa que não está empreendendo então o que que eu falo às vezes as pessoas falam assim ah não eu quero ficar um pouco mais tranquilo eu falo cara eu quero ficar

com mais tranquilo mas eu quero ficar mais tranquila chegando nos 40 45 E aí quem não quer dar o gás agora eu vou estar 45 já como eu espero tá lá nas Maldivas se você tinha do tal e aí muita gente infelizmente para alguns né Não Para todos ficaram não sabe o que quer para si mas para alguns que deixaram de fazer não produção mas por preguiça Essas pessoas vão ter que trabalhar até os 60 70 anos de idade do mesmo ritmo de quando tinha é porque não quiseram dar um gás enquanto era mais novo né cara Abrir abrir realmente mão de algumas coisas momentâneas para ter esse esse plano a longo prazo né caro e eu percebi que só apenas conhecimento de gestão e que eu ia conseguir aplicar e fazer isso crescer e eu fiquei com muito medo no início muito muito medo e muitas vezes eu quis existir muitas vezes eu errei porque as pessoas pensam assim ah para o Rafa foi fácil para ele trabalhou muito tempo lá do lado do Elias então ele já sabia de gestão gente eu não sabia de gestão o que eu sabia lá no Elias

era cortar cabelo e atender cliente porque eu não ficava lá dentro do escritório da injeção né eu vou fazer isso e mesmo que eu ficasse do lado uma coisa você vê outra você viver é porque cada empresa vai ter o seu caminho a seguir né então por isso que eu gosto de compartilhar muito essa questão do empreendedorismo e da gestão nas minhas redes sociais como você for que eu sou um dos poucos que compartilhe esse conteúdo e mais do que isso gente modéstia à parte Tem muita gente que compartilha vai compartilha isso e eu gosto compartilhar mesmo só que eu penso assim cara não tem problema compartilhar com o que é meu é meu ninguém vai tomar e eu gostaria muito de ter escutado as coisas que eu falo para os outros quando eu fui começar meu próprio negócio né Eu acho que teria evitado que eu tivesse passado nunca pisca negão e falando um pouco dessa questão do empreendedor é tomar essa liderança e passar assim a gerir a equipe né Isso é legal porque vamos assim eu comprei um pouco de perto lá na sua barbearia você faz e não sabe a cliente

né foi desde cortar ali para o meu casamento até você parar de cortar entre aspas no dia a dia isso é muito interessante que eu vejo acompanhando ali do seu Instagram que você mostra a rotina e você falou transparente né e é eu acho legal essa que essa visão de você como agora dono do negócio e não são mais o Barbeiro também ali é você levando elevando os seus colaboradores né o canal para o fim de metas quem tá vendendo mais e tudo mais e justamente você fala da importância dessa administração da equipe e com metas e traça nesses objetivos bem claros e como você vê que isso impacta a barbearia né quem não fazem quem faz qualquer diferença principal é que se vão Vamos por partes Primeiro de tudo ele falou que eu cortei o cabelo casamento não é isso eu acho que foi a primeira vez que eu cortei seu cabelo aqui ela não foi meu e deixar viu gente o Gabriel chegou com mais de uma hora de atraso porque tava chovendo não foi mais uma coisa terrível e ele ligou e falou assim que era aquela chuva a gente tem que

testar ele tava caindo o mundo aqui em BH eu falei ele falou cara é para o meu casamento você consegue esperar e eu esperei ele lá cortei o cabelo dele por que que eu esperei que o Gabriel é gente boa não porque não é que eu nem conhecia o Gabriel óbvio que o fato de ser casamento você fica assim com um pouco mais de empatia pela proposto é casamento vou me esforçar mas eu esperei muito porque naquele é que a gente tava na época de sobrevivência então eu não comecei montando o meu negócio e já fui para a gestão e ele é muito as fases da empresa No início eu aprendi muito mais do que todo mundo eu trabalhava assim de domingo a domingo literalmente porquê de segunda a sábado eu tava lá cortando o cabelo e Eu cortava no mínimo 15 cabelos todo santo dia vendia muita coisa e domingo eu ainda tentava dar uns cursos práticos alguma coisa a conta não fechava né então eu tinha que dar um jeito de arrumar esse dinheiro então tem que entender primeira fase a fase a sobrevivência você não vai conseguir montar um negócio e já

chegar não gente eu sou gestor você está Não cara início você tem que fazer o que ganhar o máximo possível economizar o máximo possível para isso você tem que fazer um negócio muito bem feito Mas também você vira recepcionista você vira gestor financeiro servirá marketing ser vira faxineiro você vira tudo Você faz tudo sozinho começamos ao passar essa fase da Sobrevivência nós começamos a traseira equipe trouxemos a primeira equipe não deu certo por erros da equipe e erros meu com o bom então foram erros de várias partes mas os erros deles eu não tinha poder para mudar cada um sabe o que quer para ser agora os meus erros eu fiz um cara eu não posso errar novamente da forma que eu errei eu errei para caramba o que você pensa assim se tem uma pessoa ruim dentro da sua empresa Quem colocou ela lá então pior ainda é que em contratou e ali foi a primeira visão que eu tive E aí eu comecei o que a trazer um time melhor consegui arrumar formas fui entender um pouco mais sobre gestão de pessoas sobre como criar uma equipe e consegui isso conseguir pessoas boas

que estiveram comigo no momento mais difícil eu sou muito grato por todos da minha equipe aí deixar um abraço especial para o Tiago que é quem tá comigo desde o início para o Arlei para o Alef que entraram na barbearia passou um pouquinho começou Lock Down então assim os caras não me deixaram na mão na estiveram aí com a gente e depois a equipe a barbearia foi crescendo e eu percebi o que que os caras eles eu tava melhorando o faturamento o número de clientes só que mesmo assim quando você vai depender do tempo para melhorar e não importa Você pode ter um marketing mais [&nbsp;__&nbsp;] do mundo que ainda se você vai depender do tempo que é um fator muito importante eu percebi que o tempo Às vezes eu não tinha o tempo que precisava da eu não tinha eu ficar eu preciso eu não posso ficar esperando cair do céu 12 clientes por dia quantos que os meninos têm hoje aí tem cinco quilos Beleza se fosse 12 clientes quanto que esses doze iriam gerar a vai gerar aqui x de faturamento r 800 faturamento Então vão dividir 800 por cinco e ver

mais ou menos quanto que cliente teria que gastar aí é daqui uma média de 100 reais r 120 r 150 vai depender Mas o fez eu tenho que começar a fazer com que cada cliente gasta demais então não precisa de muitos clientes eu falo com a minha equipa não quero que ele fica em cortando 20 cabelos por dia eu eu quero que eles corta em 56 cabelos por dia mais fácil r 1000 cada um é isso que eu quero então pensei como aumentar o tíquete médio Vamos criar metas em cima de venda então primeiro passo que eu tive que fazer para conseguir fazer isso bem feito é o que as pessoas elas querem ter profissionais Acima da Média pagando o mínimo possível não tem como a gente não tem como você quer ter um profissional Acima da Média ele tem que receber Acima da Média então primeiro você quer ter um time de vendedores tá tem barbearia que pagam uns 50 de comissão uma pomada Como que o cara vai ficar motivado de um trabalhão para ganhar uns 50 não vai então foi assim eu quero pagar r 15 comissão então eu pago uns 15

ai eu tenho certeza que eu sou a barbearia ou uma das que mais paga no Brasil condução mas eu não tenho condições de pagar essa comissão assim no meu bolso o que produzir conteúdo com mais inteligência para conseguir fechar parceria com uma marca de pomadas Eu tenho um bônus lá com essa empresa eu pego esse produto que ele sai uma parte desse produto que sai para mim sem custo eu consigo repassar esse melhorar pra galera criamos essas metas além do barbeiro ganhar bastante dinheiro vendendo produtos a cada dez ele ganha as r 150 só que Quanto tempo você demora para reinar a pomada dois minutos um minuto então Quanto tempo você demora cortar um cabelo 30 40 você ganha mais dinheiro vendendo a pomada do que é do que cortando o cabelo sim Além disso Nós criamos essas metas para pessoa poder realmente é ter um foco de tipo assim cara porque senão gasta assim a já vem de 17 Tá bom já vendi muito não pera aí vem de 17 mas a meta é 20 se eu vender 20 ainda vou ganhar mais x então eu ainda pago mais 150 para quem vem de

20 se o carro vender 40 O mãe ele é duas vezes a meta tanto que eu tinha barbeiro eu já tive barbeiro que em dois meses vendeu uma pomada hoje meu barbeiro que vende menos mas ele vem de 15 18 eu já tive lá vez que vender os 60 produtos no mês então assim nós saímos de 30 pomadas para 150 pomadas vendidas no mês e isso consequentemente Impacto nosso faturamento também nós temos um custo de 30 mil e a barbearia faturava 25/28 todo mês estava vermelho quando eu comecei a isso já tendo muitos clientes tá quando eu comecei aplicar as estratégias nós diminuímos o nosso custo de 30 para 25 mil e saímos do faturamento de 30 de 28 mil mais ou menos ficava nessa faca para 75 mil reais em menos de um ano nós aumentamos né tipo as mais do que dobramos o nosso faturamento uma estratégia simples mas que realmente funcionam é e vai equipe isso aí é algo muito importante e quem sobre o último detalhe que você falou sobre a importância de você capacitar o seu time é muito importante porque tem a teoria do Milhão você já deve ter

me visto a sobre ela mas para quem não viu Nunca ouviu Vou falar que é o que seus primeiros r 1000 você só consegue com trabalho duro então todo mundo lembra dos primeiros r 1000 que ganhou na vida eu lembro ela para eu fazer r 1000 e três em três reais era muito cabelo tinha cortar chegando sete horas da manhã e sai nas 10 e 40 da noite seus primeiros 100 mil você ganha com trabalho inteligente então lê meus medos sem nenhum foi como Estudando bastante sobre lançamento sobre Coop criando o produto novo e fui lá e fiz um lançamento trabalho inteligente mas o seu primeiro milhão você só Conquista com pessoas mais inteligentes que você trabalhando com você então não pode existir essa de Ah não vou ensinar tudo para o cara não se ele me abandona né o que você treinar uma pessoa e ela sair é você não treinar e ela ficar então principal realmente é você capacitar sua equipe para que eles sejam melhores do que você e assim você vai conseguir ter esses resultados que eu considero extraordinário principalmente pelo pouco tempo que nós que eu tenho empreendendo e que

tem também a barbearia do Rafa Com certeza não só na primeira unidade mais uma segunda também né e Rafa quente acompanha também ver muito eu acho que é não só o seu caso mas o caso de muitos barbeiros pelo Brasil que trabalham junto com com a esposa né Hum E como é que esse dia a dia lá como é que ela te ajuda na administração como é que vocês fazem para conciliar isso tudo enfim Cara me mandou falar que é ótimo trabalhar com ela olha assim é eu fico eu fico com medo às vezes de falar muito bem da minha esposa e ficar com esse casal camisolão lá né A esposa tá mandando ele falar isso mas é isso não e eu passo lamento só tenho a falar bem é difícil é difícil com qualquer outro é difícil às vezes eu trabalhar com o Tiago é difícil Tiago trabalhar comigo é difícil do meu pai tá trabalhando aí comigo é difícil para o Alasca trabalhar com gel Todo mundo vai ter momentos bons momentos ruins Mas eu escuto muitas pessoas falaram seguinte não eu e minha esposa nós podemos trabalhar juntos não se a gente

ficar junto aqui no serviço a gente mata uma outra a gente separa o cara tem um problema muito grave que vai muito além do trabalho aí um problema Raiz um negócio crônico que tá lá no coração assim que precisa ser tratado ser curado cara isso é espiritual Porque como que eu não consigo conviver o meu dia com a pessoa que eu escolhi para passar o resto da minha vida não tem problema muito grande isso e eu particularmente consigo conviver e convivo com a minha esposa muitas vezes 24 horas por dia em 24 horas por dia tem só que a gente tem que saber impor limites para tudo no início foi um pouco mais complicado ao invés de desistir A gente buscou estratégia de fazer dar certo porque tem gente que simplesmente elas tão brigando demais vai dar certo não vai lá o seu serviço que eu fico no meu nós decidimos fazer o quê Olha nós estamos brigando demais vamos ver porque que a gente tá brigando para que a gente conseguiu evitar aí você Respeitar o espaço então então algumas coisas que fazem de errado primeiro você não respeita a autonomia que a pessoa

tem dentro daquele trabalho mano hoje é a Taila trabalho administrativo de dos três negócios mas ela começou como recepcionista Fazia tudo mais a função dela para esperar recepcionista e o que que acontecia muita das vezes ela tava recepcionando uma pessoa e eu não tava gostando muito do ritmo que ela tava eu tava cortando o cabelo eu saia de lá e cá o amigão beleza tudo bem como que eu tirava autoridade dela Total ela é autoridade naquele caso bom então eu constrange a minha esposa o cliente perdi o respeito por ela muita das vezes o cliente meu que tava na minha cadeira Ficava muito porque Pô cara deixa cortar meu cabelo tem lá para recepção então quê que a gente começou a fazer Respeitar o espaço Então hoje nós trabalhamos da seguinte forma nós somos extremamente profissionais e lá dentro e muita das vezes as pessoas que se como separar o pessoal não tem jeito eu falo de trabalho em casa e eu falo a minha vida amorosa no serviço só que tem momentos então às vezes eu tô indo para casa eu não vou chegar e descarregar um tanto de problemas de trabalho na cabeça

dela se eu sei que eu já saí do trabalho fala assim amor eu sei que já saiu do trabalho eu tava querendo te falar sobre aquela questão que aconteceu Líder equipe pode falar rapidinho ela fala pode pode eu também tá querendo falar sobre isso E aí cara a gente vai até meia-noite toma banho falando disso janta falando disso mas tem dia que ela simplesmente fala assim amor hoje minha cabeça não tá boa para problema vamos deixar para amanhã e eu não ficar de raivinha sabe entender se não tá bom amanhã a gente conversa da mesma forma tem vez que ela vem nosso amor não sei o que você é conta é problema é que eu não quero saber porque eu tô muito estressada e agora já são nove meio da noite eu não vou conseguir resolver deixa você me fala amanhã então a gente respeita essa questão de espaço e nós definimos também a função de cada um eu cuido hoje nos negócios do RH então eu faço contratação eu faço o recrutamento eu faço demissão eu creio os treinamentos Acompanho a satisfação do cliente eu cuido de pessoas Essa é a minha função A

minha esposa ela cuida do administrativo o que é que tem contra a gente confunde administrativo com financeiro né administrativo ele tem a função de ver o bom andamento de todos os setores então ela vai olhar a quem que eu responsável pelo marketing se o Marco está ruim ela vai lá e vai dar um show de orelha se as Finanças nós temos gestor financeiro você não tá sendo feito certo ela vai lá e vai buscar entender que que aconteceu então a minha esposa é responsável por fiscalizar porque eu sou um setor de dentro da empresa então às vezes quando está com um problema da recepção e ela fala assim amor pré-seleção eu já te falei três vezes que as meninas ali estava fazendo esses você já resolveu se você não resolveu vamos lá vamos ver seu trabalho e a gente fala literalmente assim com muito amor mas cla é porque ali precisa ser sim né E aí a gente entende isso não é da mesma maneira ela também respeita o meu espaço nós fizemos o que tem os cabeças nas redes de cada área e tem uns conselhos então na minha área de equipe a última

palavra é sempre minha é a única coisa que eu posso fazer me dá um conselho como por exemplo eu tava lá olha só cheguei para ela e trouxe uma situação esse esse barbeiro Tô sentindo que não está se desenvolvendo na forma que eu gostaria e eu tô pensando em dispensar por esse esse motivo eu queria entender se você vê da mesma forma que eu E se ela falar que vem da mesma forma que eu Ótimo tava confirmação se ela falar que não vê da mesma forma aqui ó ela só vai para uma pulga atrás da minha William Mas quem vai falar se manda embora eu não sou eu porque aquela ali é minha e se eu errar e a culpa é minha da mesma forma no financeiro eu não sabia Respeitar o espaço dela às vezes eu chegava nossa tem 10 mil na conta aqui e tenho 20 mil para pagar não paga essa aqui primeiro porque essa pessoa que assim assim paga essa essa eu ficava assim não hoje quem decidia ela amor Tem quanto tem tanto aqui que que a gente conta paga aquilo que você achar melhor se você acertar o mérito

é seu se você é errar a culpa é sua mas eu estou aqui para te aconselhar a casa caso você quer uma opinião então o primeiro passo profissionalmente falou que nós fizemos para fazer dar certo Respeitar o espaço um do outro mas isso também trouxe muita maturidade para gente do nosso relacionamento aggregor muito no serviço tem uma pessoa que eu confio cuidando de tudo junto comigo e nem economizou muito também porque no início caso tivesse que pagar marketing recepcionista faxina tudo a minha da conta dela me ajudou de todas as formas e continua fazendo muito e até mais do que eu hoje o povo brinca que não trabalho meu trabalho eu trabalho tá é mas também no nosso relacionamento Isso mudou muito porque eu era um cara muito impulsivo estourado por mais que eu sou muito brincalhão Quem me conhece sabe que o brinco para caramba que eu sou divertido mas a mesma proporção que eu brinco eu me irrito e me estresso e fala aquilo que vem sem pensar você vai machucar o a outra pessoa não e isso acontecia também dentro do relacionamento Às vezes a Taila tava chateada e eu chegar Bela

quê que foi e ela não queria me falar na hora não sabia Respeitar o espaço dela a partir do momento que eu comecei a lidar com várias pessoas um serviço eu comecei a entender que cada uma tem um jeito eu comecei a respeitar mais também o jeito da minha esposa e ela respeitar mais o meu jeito então hoje para a gente dar super certo e até dentro da nossa casa nós administramos também como uma empresa cara é muito legal e dentro de casa por exemplo eu não tem sua função definida um dia desse a Tália tá o Luan ciosa cara tava tava com insono três dias sem dormir direito eu falei que foi amor que que você tem a nossa tô preocupada porque tem que pagar uma conta eu falei daqui quantos dia sem pagar a conta a daqui uns 10 dias e claro a gente tava bem no limite que a gente tava Investindo na outra loja a daqui uns 10 dias eu falei escutar a conta daqui 10 dias aí por que você tá preocupado que não tem dinheiro foi assim qual que é sua função aqui dentro de casa só função e

ganhar dinheiro não qual que é a sua função administrar o dinheiro então tá então para de pensar isso sabe o que que eu faço fala só quando chegar no dia o dinheiro vai estar lá quem tem que se preocupar em ficar sem dormir de como que tinha vai aparecer sou eu a partir do momento que eu coloco o dinheiro na mão dela eu não sei para onde vai esse dinheiro se essa meta vocês um caixa dois você era muito para já ia bater a sabe porque eu vou te contar uma história aqui para mim desde que eu cheguei em casa minha conta de luz estava cortada gente é a cortar minha luz eu vai se porque sabe o que aconteceu ela pulou Miss ela pagou tipo assim dezembro pagou fevereiro pagou mas esqueceu Janeiro por esquecer simplesmente aí o que eu falo gente é minhas contas não tiver você não paga nem sei sabe porque eu confio 100% na gestão que ela faça eu não sei se tem dinheiro na minha conta se tem sim tem dia que eu fico assim não eu queria comprar um pãozinho de mel mas eu não vou comprar não

porque minha conta tinha r 2 ontem aí aqui dois A moça tá com cheio de dinheiro lá na conta ou até mesmo Da mesma forma tem dia que eu fico assim nossa vou comprar aqui comprar com meu filho tem dinheiro não paguei eu não olho Cara eu confio de olhos fechados e da mesma forma ela aprendeu a confiar de olhos fechados em mim naquele nem tudo aquilo que eu faça esse companheirismo é muito importante Se você não conseguir ter essa cumplicidade na vida nos negócios espiritualmente também porque não tem como separar cara não tem como você parar pessoal e profissional Nós não somos um robô o que eu O que é o segredo para fazer dar certo é você buscar tá bem em todas as áreas da sua vida esse uma tiver mal é igual mundinho que é o menor possível mas quando eu medi tá doendo seu corpo todo sente é então para a gente tem dado muito certo muito bacana tem tem sido legal a experiência ela mandou falar isso Rafa você já deu o dicas preciosíssimas aí para o pessoal de casamento e gestão do negócio de junto com a esposa ou

se encontrar também você também já deu dicas essenciais sobre liderança gestão do negócio e equipe por fim para a gente fechar o pessoal como é que você vê e como você vê que é importante essa questão de posicionamento na rede social e eu não vou falar que só do Rafa que quem acompanha também o Instagram da barbearia do Rafa sabe o quanto que é divertido lá ver o pessoal como é que é isso é importante assim tanto como pessoa quanto para o negócio você vê que é necessário a barbearia ter esse tipo de movimentação vamos e é esse é um dos assuntos que a gente mais fala sobre as pessoas mais escutam e que menos praticam é então a gente tá sempre dando uma dica sobre isso e pouquíssimas pessoas realmente coloca em prática é por isso que pouquíssimas pessoas se destacam aquele negócio de que o futuro vai ser o digital passou gente passado já tá digital digital começou há cinco anos atrás dez anos atrás e as pessoas não estão acompanhando e o que eu acredito é o seguinte daqui a pouco ou você tá na internet ou você não existe basicamente é

isso porque o comportamento Mudou as pessoas que seguiram somente as mídias tradicionais ela já são pessoas mais velhas mas ela que falam de idade mas ela que eu faço na mentalidade porque hoje até os idosos já tem muito se atualizando né E quem ficar nessa de só esperar o cliente de porta vai ter mais dificuldade porque e o povo hoje está muito desconfiado cara de tudo eu acho que essa questão de cancelamento que existe aí esse medo de tudo que pode acontecer deixar as pessoas mais desconfiados então por exemplo eu tenho pessoas que moram em frente a minha barbearia há três anos que ela tá lá e que nunca foram Na barbearia nem para chegar na porta para ver se essa pessoa não ver algo na internet que faça lavar se o cara que legal deixa eu ver onde que é Ai aquela Barbieri tem aqui na porta não sabia que era desse nível porque tem cliente que falam isso para gente Nossa vocês estão aqui há quanto tempo aí eu tô aqui é dois anos que é isso eu moro na rua de cima eu só vim aqui hoje porque eu vi um traço

igual aparecendo para mim bom então se você não tiver um posicionamento realmente original uma comunicação na sua empresa humanizada o seu negócio ele não vai ter espaço no mercado Então esse é o meu pensamento primeiro sobre empresas têm um perfil humanizado que tem gente vai assim ah mas eu faço marketing para minha barbearia aí você entra lá o cara tem 50 fotos de corte de cabelo postar forte forte abraço vai fazer marketing fazer marketing é você se conectar é você educar o seu público para levar ele a venda né de alguma coisa E aí quando você vai ver só postar foto de corte de cabelo só atrás barbeiro não quero barbeiro na página da barbearia do Rafa eu quero clientes e para isso eu tenho que pensar o que que o cliente fala quer ver um exemplo disso big brother eu não sou o cara que fica ligado nem Big Brother a verdade eu assistir Big Brother por tabela Quando eu abro o Instagram está cheio de notícias do Big Brother mas eu não assisto Big Brother mas Nós criamos no Bic barbearia Brasil nós postamos em que é sobre o Big Brother porque tem

o que o cliente está vendo cara E aí a gente faz umas postagens todas em cima disso agora sobre a importância de você como profissional se posicionar nas redes sociais aqui de um grande detalhe É muito difícil você sabe bem disso também como prender o que é muito difícil achar mão de obra qualificada E como você tá correndo atrás de um jovem você tá sempre atrás você nunca vai estar à frente um passo à frente realmente para poder ter uma boa visão e 15 Já é difícil você encontrar imagina quando as pessoas correm de você então o que que hoje foi um grande diferencial isso é que eu falo até para quem não tem vontade de ser é Talvez um educador ou ser famoso nas redes sociais Mas quem somente Quer Ser um empreendedor do dia a dia aquele mesmo digitar atendendo um cliente ainda ser importante ser uma referência sabe porque as pessoas querem trabalhar com os melhores sabe por quê que tem muita barbearia que o Barbeiro ele não sabe nada o cara vai lá dar uma chance aí quando o cara aprende a profissão ele vai embora porque talvez ninguém tem um

sonho de trabalhar naquele lugar aí a pessoa só vê que ele como um trampolim para ela se capacitar e consegui tentar uma oportunidade na onde ela tem o sonho de realmente tá o que que eu falo para todo mundo pensa hoje você teria um sonho se você tá fazendo na sua faculdade você tem que colocar lá na resposta qual empresa você gostaria de trabalhar um dia você colocaria Aço a empresa a sua barbearia se não tem algo de errado então hoje eu tenho certeza que se você pegasse aí mil barbeiros qual barbearia você gostaria de trabalhar muito cedo eu colocar barbearia do Rafa a gente se torna um imã de colaboradores logo eu não preciso mais correr atrás de ninguém as pessoas são as pessoas que correm atrás de mim e quando as pessoas corre atrás de mim eu tenho opção para escolher o melhor e não tá colocar qualquer um só para tapar um buraco que às vezes fica assim nossa não tô conseguindo nenhum essa menina é muito bom mas tá chegando o carnaval aí eu vou colocar ele aqui só para mim não ficar vazio então tem esse posicionamento saber se vender

se vestir bem tem um carro legal postar foto legais da sua barbearia tudo isso faz com que a pessoa olhe para você que assim caramba barbearia do cara tá bombando velho tem alguma coisa de bom ali todo mundo que chega ali cresce melhor fica mais inteligente conversa mais bonito alguma coisa diferente tá e eu quero esse diferencial para minha vida então é importância mais do que fama status vaidade e reconhecimento de tapinha nas costas no tanto de gente que nem gosta de você é realmente você tá fazendo mais pelo seu negócio partir do momento que você se tornar um ímã de colaboradores você coloca a qualidade da sua empresa no outro patamar como diz o Bruno Henrique é o último amarga eu que a gente está conseguindo viver hoje por isso nossos banners são tão bons muito bacana muito legal bom Rafa te agradeço imensamente pela sua presença aqui no México babys podcast se você está ouvindo vendo aí a gente ainda não conhece o veste Barbie e a gente vai deixar o link para você baixar o aplicativo também temos versão web para você administrar o seu negócio fazer Marketing com seu cliente administrar

agendamento tudo isso na nossa plataforma por enquanto por apenas 6990 tá bom mesma coisa muito barata Você tem na sua barbearia eu E aí Rafa Valeu negão tamo junto demais tá olha só vou agradecer mas antes agradecer só falar uma coisa OK essencial para a nossa organização exatamente a questão do sistema online né o Gabriel nós tivemos uma conversa há um tempo atrás sobre tudo que eu acho que ele poderia melhorar agregar no veste Barbie e ele foi anotando tudo e colocando ali tim-tim por tim-tim para tubete Vale realmente pudesse ter tudo que a gente precisa né cara tudo no aplicativo porque gente não existe negócio ficar no caderninho mais não e assim setenta reais por mês menos de setenta reais por mês que você pagar cara você já pensou o quanto que isso ele vai organizar o seu dia a dia vai te trazer controle de um cadastro de clientes que você tem vai trazer um controle financeiro melhor então de setenta reais no final das contas vai pagar 70 vai ganhar 700 a mais ali dormindo né Isso é investimento investir é plantar para colher ser plantas e mentir ver uma árvore lá

a ideia Exatamente é e obrigado Gabriel cara que eu gosto muito gente eu gosto dele tá falando que tá na frente dele que nem que ele me pediu nos Bastidores só não é o seguinte eu o Gabriel ele é empreendedor como a gente né cara assim cara novo esforçado para caramba já tem um negócio muito diferenciado né que eu serve netos né E aí dentro disso O best Barber né que é um braço fortíssima ali ele veio para o lado da barbearia exatamente ele sempre falou comigo desse carinho tanto que ele gosta de barbearia que ele gostaria de estar ajudando aí também os barbeiros a se desenvolverem né e a forma que ele tem de colocar o conhecimento e experiência dele ao nosso favor então fiquei feliz demais por vez projeto aqui tá rodando né e agora só tem o seguinte né Gente eu faço um Gabriel ali ele atende um tanto de barbeiro vocês tudo pode virar cliente dele mas não vem tomar meu querido Valeu meu amigo valeu obrigado valeu vê gente o E aí [Música]`,

  summary:
    "Episódio 1 da Temporada 1 do BestBarbers Podcast. Rapha da Barbearia compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
