import type { VideoContent } from "./types";

export const podcastmax_visual_ep07: VideoContent = {
  slug: "podcast-max-visual-ep07",
  youtubeId: "3ehvVECZZ-A",
  title: "BestBarbers Podcast com Max Visual — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 7 da Temporada 1 do BestBarbers Podcast com Max Visual. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "max visual",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2022-08-18",
  duration: "56:16",
  category: "Podcast",
  tags: ["podcast", "temporada 1", "entrevista", "gestão", "barbeiro"],

  transcript: `é o segredo mesmo primeira coisa e fala Abrir filme ainda mais um best Barber podcast meu nome é André nós tivemos a honra de receber o maxilar de areia maxvisual nesse Episódio de número 7 ele contou um pouquinho da sua história como ele iniciou a sua trajetória no mundo da barbearia das dificuldades que enfrentou no meio do caminho frio que realmente fez diferença para ele se tornar um dos grandes barbeiros de Belo Horizonte Além disso ele deu uma série de dicas de como você pode alavancar a sua carreira elevar o seu nível com o Barbeiro prestando um serviço muito mais qualitativo e menos quantitativo e se você também sonha em ser um grande barbeiro o dono de uma grande barbearia nesse Episódio nós temos dicas valiosíssimas para você então eu te convido a assistir esse vídeo até o final e tchau obrigado senhoras e senhores sejam bem-vindos a mais um best Barbies podcast hoje nós temos a honra de receber ele com Max também conhecida aí muito pelo nome maxvisual né referência no cenário das barbearias brasileiras Bom Max bom primeiro eu queria que seja em contato para um pouquinho quem é o Max né

De onde surgiu mais visual como é que foi essa trajetória ou um pouquinho para gente aí Bom primeiramente é um prazer aí participando aqui do podcast do assistir Barbie a história ela começou com uma história de freio da maioria né a história humana mesmo ninguém nasce grande faz uma semente ela deve ser plantada O que é um solo fértil deve ser regada e cuidada aquela vem a crescer para o seguinte cara é pela necessidade mesmo eu tenho 44 anos parece uma coisa de pouco na Guiné tá liso ainda eles graças a Deus 44 anos e eu tenho 21 anos que eu estou barbeiro e resolvam a pouco você não não não é barbeiro não estou Barbie é que o Barbeiro uma profissão aquilo que você faz não define quem você é aquilo que você é definir aquilo que você irá fazer pelo resto da sua vida eu me descobri né é tão Lu barbeiro a Band 2000 eu fiz o meu percurso né eu corto cabelo desde os e da adolescência ele 17 anos eu em família muito pobre vamos ao tão boa graças a Deus tá são muito trabalho também A paz de Deus

trabalho é essa eu dando meus cem porcento eu dou cem porcento dele tá duzentos por cento então não tem como dar errado mano tem como dar errado para você que deseja algo na sua vida e sem por cento mas acredito em Deus também 100% é a receita de bolo não adianta nem falar para um lado nem para o outro né senão a receita não sai boa né é outro dia me perguntaram se eu era Direita ou esquerda foi não sou centro pode nem ser muito nem para direito certeza Sempre lhe entender que equilíbrio né libra se você é uma pessoa equilibrada é muito importante eu comecei no ano fiz um curso no ano de 22 mil porém Eu cortava o cabelo em casa pelo necessidade conta rapidinho para você entender como é que nasceu empreendedorismo minha vida afloram muito cedo é eu creio muito que necessidades ela geram grandes oportunidades nossas vidas tem a pandemia cara branca tecnologia cresceu aplicativos aí ó até um podcast isso mesmo né na forma de se comunicarem como as pessoas mudou mesmo né E hoje nós temos a inteligência artificial muita coisa que aconteceu falam que curiosos aí que

o Brasil ele vai evoluir em cinco anos cinquenta anos em cinco imagino o que que é isso eu não precisei projeto que ia sair da gaveta lá atrás que saíram rápido pela necessidade da vacina de viver de acontecer bebê que hoje o digital ele é muito mais forte do que o presencial eu tenho curso plataformas digitais e salvou na academia mano então é porque eu tô contando isso que quando você coloca pressão é alguém ela cresce a zona de conforto não é lugar de crescimento e eu oito filhos meu pai é trabalhava como o pedreiro faz tudo né pedreiro soldador minha mãe dona de casa e eu digo eu é da família de oito filhos em cima para baixo era segundo mais novo né hoje tem meu irmão que era barbeiro também mas infelizmente a entrar gente mais então cara eu vi a história do meu pai e da minha família foi mano conseguiu mesmo caminho do que eu vou obter os mesmos resultados eu falei os resultados deles eu não quero eu quero resultados melhores para minha vida o cara no início eu lembro que eu tinha uns a 15 de 15 a 17

anos eu nem neta para quem é mais ou menos umidade vai entender é bombava na época do Street Fighter fliperama fliperama né Street Fighter Mortal Kombat também quando lançou e a gente cara eu queria jogar aquilo só que meu pai ele não me dava dinheiro que não tinha eu cresspom para o colégio já começou a aparecer as meninas para namorar aí meu pai falava assim como é que você vai namorar com a menina ninguém paga não picolé Play caramba eu tenho mais tal de dinheiro mas pelo menos foi o picolé normalmente o picolé né porque eu vou dar uns beijinho nas Beleza não tem como aí eu eu virei eu fui virei e eu tive uma ideia cara uma ideia relacionada a barbearia eu dois amigos meus esperem vendo potinho Ricardo com certeza vai ver ficar dois maiores Estados Unidos até vindo aí para conversar agora em folha e o Fábio que eu pai do Ricardo trabalhava na medula e o pai do Fábio tinha um caminhão desde que tinha mais condição eram os únicos que os pais dava dinheiro para cortar o cabelo é o ser humano guardar dinheiro então vou dar um jeito

nesse cabelo esse cara quer utilizar uma você não sabe cortar cabelo lá em casa tinha uma máquina velha que o meu irmão ganhou e uma tesoura lá tá mano não sei não mas se o tiozinho cortava o cabelo sim cortar cabelo longo de mais de uma hora mais demora quase uma cabelo velho uma hora traz uma hora e meia para cortar um cabelo cortar muito na tesoura a máquina era ruim por isso que muita gente acha que máquina está cabelo não é as máquinas de antigamente que eram ruins na hora de cortar elas é em casa oito né não passa suave Fala galera que acha cortar cabelo com massa que não engrossa cara Tira esse mesmo aí tu vem pegar eu portanto não têm e vou até Dom dá uma dentro aqui é o seguinte o que define é o dentro que é o político capilar ali ou capilar ele se ele é redondo cabelo nascer liso se ele é oval cabelo nasce encaracolado E se ele é um do lado nas crenças do meu o resto vai misturando ali então passou máquina de fora não tem poder nenhum de engrossar o cabelo aquela tem

que entender isso aí E aí eu peguei essa máquina e fui cortar o cabelo do Ricardo e do Fábio lê mano nosso a seguinte hora mais ou menos tanta nós jogar Fliperama Tira aqui para nós dá um Alex precisar médias e remédio contra impotência corta o cabelo distante tanto tempo ontem isso aí eu tinha não lembro dele melhor de 15 e 17 anos ali onde que eu ia lá e como cada demorava muito ficava olhando ele cortar Eu sou um cara muito metódico eu acredito muito em talento mas eu sou mais fã do método o processo sim mas quem tem talento pode destacar Pode mas que não tem talento e é um Cristiano Ronaldo super aplicado vai voar vai voar mais alto e vai voar mais tempo que tem mais combustível e o cara que tem um talento fez um minha coisa que eu não sou um cara talentoso o cara metódico aqui pensa muito para que gasta massa cefálica para alcançar os objetivos esse inclusive evita muito retrabalho né economiza muita energia justamente para aplicar nas outras coisas mas com certeza né o julgar sua galera pira que eu faço um corte Isso é

coisa cabelo comigo no dia não tava gripado mas com a cabelo e 20 minutos rapido eu divido em processos cara então é eu gosto muito disso voltando falar que aconteceu E aí começo deu certo velho deu certo cortei cabelo dos dois um tempo a mãe dele ficou sabendo que eu não sabia nele mas mesmo assim que eu te dou me pagando eu falei pô cara tem dar certo não é novo aí foi fui trabalhando e chegou um ponto que a vizinhança começou cortar cabelo comigo eu era muito novo eu tô raiva o dinheiro todo liberando é e agora mais algumas coisas né aí para pagar e tudo carrinho de rolimã tudo tudo a gente gastava o dinheiro estava nas nuvens os empreendedores nasceu de uma necessidade e para quem tá passando nesse necessidade agora assim como aconteceu na pandemia e cidade ela abre grandes portas de oportunidade para todo mundo aqueles que entendem o tempo que a gente tá vivendo aquilo que você está vivendo é muito importante ele 6.000 tempo que você está vivendo elas nós somos um tempo do dar não é nem do dia e tal mas agora já tá indo pro

inteligência Me prometa né meta é um já é um mudou daqui a pouco vai vai ter um arranjo o pessoal vai escutar esse podcast falar estava lá no médico ainda já mano o passei hoje eu tava próximo ao BH Shopping ali passei de moto assim poder bastante hoje eu passo um Tesla perto de mim o cara não estava dirigindo o carro não velho o cara tava dirigindo sozinho e o cara lá dentro do carro falei mano coisa que há uns 10 anos atrás da gente nem achava impossível então carta voando mano ela foi buscar tão voando aí que aconteceu passar um ano eu fui trabalhei bem de picolé fiz de tudo mano família Pobre tem que fazer porque eu gostei de ganhar dinheiro então depois daquele daquele tempo o meu pai não me dava foi cara vou me virar e é vamos virar o fazer isso acontecer eu consegui a pela necessidade família de oito filhos é meu pai não tinha condição de me dar nada ele dava o feijão com arroz o básico o pai o pai tão do céu que deus obrigado pela família que o o grata a Deus por tudo não

nasci na família errada com você já falou para você também não se não nasceu na família errada não ninguém nasceu na família errada eu tenho motivo né Deus é bom é bom em todo tempo eu tenho motivo tá aí cara passaram-se anos e anos e anos aí um tempo depois eu fui trabalhar numa empresa uma Leroy Merlin fui Entrei como repositor bom antes seis meses eu virei vendedor era minha meta eu vou entrar por baixo depois eu Oi subindo os degraus beleza aí virei vendedor vendia muito cara aí essas técnicas que eu uso hoje venda meu aberto eu aprendi em fazendo muitos curso lá ninguém queria fazer curso que era chata eu fazia todos e venda e atendimento pós-venda O que é barbeiro aí mano grande sacada do negócio não está no corte cabelo Oi tá na venda nem todo mundo entende você não vender Oi aqui é vamos ver propaganda não tá gente mas tá aqui ó o energético famoso para não adianta você não vender essa empresa quebra Ah e não fazer propaganda propaganda [&nbsp;__&nbsp;] não adianta aos meios deles comunicação se a Ferrari laferrari a vermelhona não vender quebra é a posse

não vender quebra o McDonald's não vender quebra a Grande Virada deixava na minha mente que eu vou nós vamos falar sobre isso também é a questão da venda enxerga barbearia totalmente diferente do que a maioria dos profissionais enxergam os grandes players enxergam Isso é só cada um trabalho é só forma depois vou te dar um dois lados eu perguntar mais como você enxerga Bárbara e hoje eu vou te falar depois chegou um tempo que eu fiz não eu fazia paralelo né fazer Paralelos é um site aí para quem quer trabalhar numa barbearia quer viver da barbearia pagar só 50 CV bem que barbearia Se você souber trabalhar paga bem depois que você faz uma cartela de clientes você cuida daquela cartela Tá bem na praça tá eu vários treinamentos falando sobre isso se é hoje eu tenho a tendo uma pegada que eu chamo 10 por um depois a gente vai falar sobre isso também chega um tempo Oi e eu tava ganhando mais cortando o cabelo do que trabalhando essa empresa que eu trabalhava que é Leroy Merlin na época não tava pareado velho mas isso você começou a cortar cabelo onde enquanto você

tava na Leroy Merlin você já tinha alguma coisa cortava na varanda da minha casa meu quarto na sua casa a domicílio ou a domicílio existe há muito tempo só não era visto como é nosso hoje né Eu cortava cabelo tomava café na casa do cara de almoçar vou sair até mais barato um pensava ele e ainda treinava no cara eu não sabia cortar cabelo só aqui no ano de2005 licença mano de dois mil eu resolvi fazer um curso ou menos para viver na barbearia eu que acontece você pode dois mil aí eu fui um amigo meu chama Gilson Gilson Gonçalves Lima Marília Miranda flor faz um curso que você vai longe eu já tava ganhando dinheiro em casa eu quero fazer um curso e vou montar minha barbearia e daí o Gilson e na época que você falasse com cara que você ia virar barbeiro ele fechava a porta de aço na sua casa é mesmo não tivesse compartilhamento de tiro pimento né os vídeos era tudo Gringo é o fizeram todos os gringos acham pouco não tinha aí social que tem hoje né aconteceu em outubro Instagram medicação ela completamente diferente limitada não errado

hoje o cara me chama no Instagram eu dou uma consultoria para ele para o encaixe pergunta pergunta eu respondo não era assim o conhecimento era só pra quem tinha eu falei com o rapaz que eu queria fazer um curso e me deu eu tomei encarada não falar não dele não são porque eu vou falar os pouquinho me ajudou e irei pronto para minha irmã ela só faz o curso foi não tem não tem dinheiro mano dinheiro eu mandei falar só quero fazer um curso com você mas eu não tenho dinheiro mano quando você pensar que você não atender você nunca vai ter dinheiro o seu pensamento que você pensa que ele você fala se torna realidade tempo todo tô começando declarar coisas boas na sua vida pode Três Passos muito simples para que as coisas aconteça é creio na palavra declara a palavra e viva a palavra crê a declarar e viva muda tudo muda o seu marca é muda toda essa eu morro né rede cara ruim vai para cima buscar essa energia desejo cara imagina andando no carro você quer morar na casa que você quer saber e que você quer Deus ele

é poderoso para fazer isso nessa vida meu irmão e o poder já tá dentro de nós eu falei lá no começo daí ao invés de falar não tenho dinheiro né pensar o que que eu preciso fazer para ter dinheiro para fazer tal coisa é um certeza que eu preciso de fazer mano já já já fiz tanta coisa fora da barbearia ele se eu falar aqui vai dar dessa negócio não dá desculpa velho desculpa não muda nada ações mudam tudo as pessoas que dão desculpa não canso nada em suas vidas pessoas que não não desculpa mas que sonham e buscam realizar estão dispostas a pagar o preço o alcance alcance bom hoje eu fui fazer trilha a gente vir para cá eu gosto muito de bicicleta e bike eu queria chegar no lugar o tão para mim ver a vista humano não haja canela velho já que ela é o osso velho e muita gente quer chegar no topo as vontades postular a sofrendo a subida e nem o porquê que você quer subir lá por que que você tá fazendo isso né todo mundo que eu estou ninguém nasceu para ser fracassado Mas por que

que você outros não e poucos Estão dispostos a pagar o preço Episódio aí daí Cara eu fiz o curso Eu tenho um quadro devia ter trago ele eu tenho um quadro tem minha primeira na Vale que alguém toda enferrujada e a primeira Tesoura o Gilson me deu a primeira navalha primeira capa minha irmã me deu uma primeira tesoura lá eu fiz um quadro Memorial O que é importante as pessoas serem gratuitas Estão lá em Vida pessoas que ajudaram ela o ramo da barbearia Cara infelizmente e hoje eu faço um trabalho para mudar isso estou aqui gravando com você a barbearia maxlock não é minha é Nossa esses profissionais lá eles cuidam dela com suas em deles essa mentalidade tem que mudar na mente dos profissionais da barbearia era tão lá trabalhando mani cuidando fizeram compras Ontem foi uma pessoa para limpar o mais belo hoje ele ficar o que ficou eles limparam organizaram tudo atende os clientes dentro de um padrão eles cuidam da barbela e como se fosse deles eles têm tarefas lá dentro não só corta o cabelo e daqui a pouco eu vou multiplicar meu negócio quem tu vai ser o gerente

quem que vai cuidar da barbearia é um cara mano se o cara fala Marcos eu quero sair mano sai sabendo não só cortar cabelo porque eu treino meus lábios desde cortar o cabelo atender o cliente venda pós-venda todo de pena que dá na barbearia ele sabe resolver você sabe abrir Kesha curso de malha financeiro a mim fazer tudo mano então a barbearia não é minha eu treinos cara e é muito importante isso e eu sou muito grato às pessoas que me ajudaram a começo pessoas que me ajuda você a ninguém sei lá a gente acha que gravei uma recebeu com muito carinho aqui e grato a todos aqueles que fizeram parte que passaram para minha barbearia o e contribuirá com o meu crescimento fala Maxi mas se tem problema na justiça os cara te levarão a justiça e treinou o cara para o meu cunhado nas costas e mesmo assim você tá agradecendo os cara mano eu não tivesse passado que eu passei eu não teria eu não teria o alicerce que eu tenho hoje não teria conhecimento que o senhor eu sou grato a Deus por tudo que eu passei cara cliente que já

entrou numa empresa que hoje já não faz parte né da fala da cartela de clientes e foram eles que meu os meus amigos que cortei mais orelha desse que cabelo na comida tudo isso te ajudou por isso então é né hoje Luiz pode fácil do crescimento cara tudo isso aí galera é colher no Instagram cara Começou agora que corta cabelo bom cara que tem 20 anos Vai mano vai no seus passos sobre o legal de cada vez até que não eu tenho aprendido uma coisa que é desistir de desistir e a palavra só falar mais calma frases para motivar uma pessoa alcança alguma coisa na vida dela exista existir Onde existem você não desista dos seus sonhos seus planos seus projetos a porque meu irmão Deus nunca desiste da gente mais que a gente tem até lá em cima tem hora que tá lá embaixo a gente tá mais embaixo Aqui em cima Deus ele é constante Deus é linear e quer o nosso bem então a nossa linda vamos fazer como Deus existir existir da gente mesmo isso é muito importante ainda que eu vi muito viu presente na planta é minha mana eu

tinha aqui para barbearia em expansão fechou tudo os meninos optaram por sair o escolha dele daqui a pouco eu fiquei sozinho mano Trabalhei na pandemia Porta Fechada vou deitar o nome da barbearia barbearia mais virou clandestinos hahaha porque o cara chegar você abrir ele entrava chegava abrir ele entrava mas por um tempo que a gente viu era necessidade necessário e muito importante é e muito e não só da barbearia mas do Nicolau também não todo aí cara é fiz esse curso em 2000 abriu uma barbearia em uma garagem a Karina coragem não é porque minha filha nasceu minha filha tem 21 anos ela tem o tempo que eu pensei que era de barbearia legal pequenininha eu tinha um carro aqui nesse desafio nem mais esse desafio é pai é cara bora para cima aí graças a Deus deu certo porque nessa garagem 1 ano né é ele é um ano e seis meses até recebeu o décimo terceiro ali para dar aquela segurada e sabe como eu tinha aprendido muita coisa no herói como captação de clientes o grande segredo tá no comercial né velho eu em segredo de toda empresa tá no comercial galera

do comercial comercialmente você o bom comunicar bem Vai dar tudo certo se você tem o Flávio Augusto falando assim e que ele pode errar tanto no começo caminhada dele porque eu vendia muito quando você vende muitos tem muito dinheiro em caixa dá para você ir concertando você vai Randy vai consertar quando você não vende nada você quebra é um pão tá no departamento comercial eu ouvindo isso para mim dos maiores empreendedores no Brasil eu te falar que eu não enxergo barbearia somente barbearia ele é uma referência para mim né Flávio Augusto geração de valor é para quem ainda não segue ele é um cara morre não é não nega nominal têm influenciado os grandes players no mercado tentamos da barbearia e fora seu Elias mesmo eu falou que ele é uma referência dele é e tem um cara que eu acompanho para pena ou não e depois disso cara É mudei para outro local e mais visível a visibilidade ela faz importante ela é importante talvez não no tempo da internet porque na época era muito importante eu tive eu tive que mudar para uma avenida movimentada eu quero é MSN ou e-mail que não

era lembrado né A internet era discada eu lembro que a gente não tinha Grande a gente tinha que possa e meia noite a noite hoje eu tiro meu celular aqui qualquer hora né Qualquer hora eu posso mano e a Galera ainda tem que cuidar de postar aí Fui para uma loja uma avenida do bairro que eu que hoje eu moro ainda e eu peço Avenida O que é lógico pequenininho e tá no morro cara entendia nada de beijinho de posicionamento da marca o funcionamento do negócio entendia nada disso não entendi sobre localização do negócio público-alvo que é muito importante montei lá na cara e na coragem minerais humano veio e foi cortando só que eu tinha sempre diferencial e sempre is químicas desde o começo eu fazia muito muita luz muito relaxamento Eu fiz curso eu sou eu me formei cabeleireiro eu era acabei E é porque eu me tornei barbeiro em 2015 com esse bom aí Lu tá pegado a Barbie chove tudo mais negócio virada E aí eu virada de chave que deu aí cara eu fui e peguei meu irmão ele nós pagamos um curso para ele é ele foi vem trabalhar

comigo depois Minha sobrinha já virou minha primeira recepcionista em 2002 e já tinha recepcionista 2002 Eu já queria eu já trabalhava de horário marcado desde o início desde o início viu veio vingar mesmo horário marcado em 2017 velho muito tem várias e velho 15 educar o cliente não é fácil é uma das mais difíceis mas mais difícil mas já trabalhei de sete horas até meia-noite até o carnaval todo mundo tinha um feriado eu não tinha mas hoje eu não faço não precisa caso esse procedimento que eu creio que eu falei para você que eu desço por uma das um pouco dele mas você atende o cliente eu tinha que falar no Altar já tem um dois três frentes Bora velho a vida tô 44 anos com base na venda Neve com base na venda do atendimento ao cliente né escolha do público-alvo do público certo é muito mais assertivo nem mais assertivo é daí cara eu fui bem meu irmão trabalhar comigo depois ela passaram Não Vou abreviar Depois dessa lá eu mudei para uma maior Depois de dois anos depois vamos mudar para uma muito grande onde eu salão ir salão e barbearia tive

alguns problemas lá que não tinha essa lei salão parceiro O barbeiro que hoje trabalha não trabalha por base da amizade essa assertivo você vai ter problema onde entra dinheiro mano as coisas mudam da problema com família né dá problema imagina com que o processo na justiça pa quebrei duas vezes no mesmo local não tem vergonha nenhuma de falar isso é muito importante falar isso é muita gente inclusive não ver né esse lado tudo né todo esforço toda caminhada todos os perrengues aí até chegar aí né só vê lá hoje Há muitos seguidores né e acha que que vai ser assim né um tempo que eu não podia postar nada estava não podia postar nada aqui e se caísse a mão da Justiça não sou se eu posso que eu tô com iPhone para o cara tem um iPhone tem dinheiro pagar eu fiquei sem carro cinco anos eu comprei uma rapidinha e cinco anos sem capa acreditar no meu sonho eu andei de moto emprestado mais de dois anos o Bruno tá vendo podcast mano obrigado mais uma moto mais uma camada do aí tá vendo mano quem tem amigo tem tudo Minhas irmãs Marília

Marília que me ajudou no começo né dando a primeira 18 minha irmã Mary Lúcia mano eu recomendo abelha Todo cartão de crédito mas vendia álcool gel de noite eu trabalho até 10 depois da cesariana para entregar o que joga pandemia lutando foi no meu sonho não vai mano mas não vai me calar nunca graças a Deus lançamento do curso online agradecer o Pedro também cara acreditou em mim é lançado no curso online e esse curso ajudou a pagar as parcelas ajuste Olá meu nome é hoje eu tô a ponto de bala de maior agora é só tchau obrigado né uma escala hoje Na barbearia roda tudo certinho dentro da Lei salão parceiro para aplicar não vai na base da amizade vai dar ruim não vai na base da amizade sabe mas o fazer antes de chegar lá falou mas todo um primo meu ali que ele ele tá leva jeito para cortar cabelo eu pagava um curso para o cara treinando ele dentro do padrão que ela cabelo para trabalhar para que passamos um ano eu tava brigando comigo era direi não né não é porque eu queria padronizar e o cara de trabalhar do

jeito dele padronização ela demorou hoje além da padronização divisão é missão visão e valores da empresa tem cartilha de procedimentos na minha Margaridas a entrada do cliente até a saída é e em cronograma de atendimento tem um catálogo digital de fotos para o cliente ver o que ele quer o atendimento totalmente diferenciado só que você demorou mais de 2 mil a2021 e entrou em 2012 começou a entrar em 2017 em 2020 com essa moda equipe que eu tenho é São dois barbeiros que é o Souza e o França e Rodolfo Souza eu treinei ele dois anos ele desde o início prender eles né eu pescoço online comigo ele veio fazer parte da minha equipe de curso treinar ele de pé quando o que que ele tava pão de barco que quando você vem mano tem problema tanto que eu te pago tanto vem trabalhar comigo você não corta nenhum cabelo eu te pago não mano beleza Tá mas eu sabia que ele acorda Gabriel quer saber que acompanha ele de perto né sabia o France pelo curso comigo também vai trabalhar comigo só foi um pouco também porque a mentalidade dele era de cortar cabelo

e para arte é muito bom os barbeiros artista não ganho dinheiro Me desculpa falar isso aí é uma opinião minha pelo menos a minha região gás duas horas para cortar um cabelo cara te paga r 30 mas você paga uma selagem gasta 15 20 minutos também vai jogar 80 você comentou na região o tipo do público né tudo isso vai influenciar muito né é quando hoje né Marcos onde que você vai plantar uma semente semente a barbearia tá Cara eu tenho que ir tem que ver onde essa semente que eu vou plantar Qual que é o solo ideal Qual que é o clima ideal para aquela brindes conexões as condições fala muito do público mano tem que você quer atender ela falou comigo outro dia mais como que eu faço a balançar o produto entendeu lançar um produto para vender ou abrir um negócio escolhe o público Primeira coisa eu fui lá o público quem vai comprar seu negócio depois que você escolhe quem vai comprar e sul da região Aí você olha qual que é a forma de consumo daquele culto e como é como é que eu escolhi eu carro aí eu quero

cobrar 50 raiz o meu corte de cabelo vai tomar café na padaria lá perto do almoço ele é doido velho mano o cara que paga desconto no café com leite e no pão de queijo ele vai pagar as minhas redes com as cabelo o cara que paga r 2 um pão de queijo no café com leite e não vai pagar as contas aí um corte de cabelo tá é tudo velho os prédios que tem lugar é o carro Galera ainda não tem mistério não é simples a galera modifica muita coisa que não precisa modificar velho olha simples pega a semente é semente a coco na se coco nas Grande no Rio não mano coco na areia e precisa de sal nome do Nordeste explicando tem que deu muito certo os cocos que tem no Nordeste vieram os barcos da é é é quem sabe da África não ver nada aí vieram para cá caiu aqui como é que tem muito sal eles gostam de sal cresceram rápido tá tudo mano tudo é semente velho a lei mais válida hoje a lei da semeadura ela vale levar Levar o resto aquilo que você planta você vai

correr para você tem que saber plantar aonde plantar a esperar o tempo dele lá é importante também que a gente que uma barbearia hoje o dinheiro que era o carro cara que o dia todo compra um carro não espera esfarela do ano que vem carro velho cinco anos sem carro o meu negócio morre comprar um agora Ah entendeu depois disso né Já tô na Meu quinto empreendimento montei barbearia Monte salão não deu certo trabalhei com aluguel de cadeira quem trabalha com aluguel de cadeira não tem padrão não tem escala para chegando a hora que quer vai embora na hora que quem faz o que quer e está disposto para trabalhar assim beleza na forma eu quero trabalhar era o padrão Ou no McDonald's colocar ela mais não trabalhar todo mundo arrumadinho quando Burger King ficou olhando a galera trabalhar eu vou lá no Outback escolha galera trabalhar como é que eles atendem é no tudo velho Pega um site tudo mais cara com vestido e que eles falam os processo eu sou o skar eu gosto de te pegar nalitico análise depois vim trabalhar né deixei essa barba grande barbearia caraís primeira e depois primeiro

aluguel segundo aluguel depois ao Barbeiro é bem grande é bem grande mesmo de barbearia lá em grande que era dividida manda ela era barbearia salão uma escola em cima entrar ama né e agora é só uma barbearia bem menor é numa região pouco melhor porque eu tava com dois barbeiros a gente fatura mais que quando eu tinha 12 caramba para tudo mais eu tinha 12 para Max Mas o que aconteceu qual que é o segredo aí para o segredo mesmo primeira coisa as pessoas processos e produtos as três coisas três vezes qualquer negócio pessoas essa escolha seu público ou você escolheu o público as outras pessoas irão trabalhar com você que tenha perfil para atender esse público muito importante pessoas você quer atender depois as outras pessoas que irão atender esse público o que eu vou te contar uma história de um barbeiro que cortava cabelo demais mano ele demais onde eu cheguei lá de desenhou uma flor no cabelo na cabeça advogado José nunca mais o cara voltou velho porque não é que ele tava errado ele era um barbeiro mais artístico e os barbeiros para trabalhar comigo não são barbeiros artísticos vocês podem

dele era totalmente diferente velho é porque o cara corta muito cabelo que ele sai para atender esse público não é nem tava errado né de causar aquele jeito só não era o que ele é essência do cara é outra eu que contato errado a culpa foi minha mãe esses dois tipos de pessoas né pessoas que você irá atender primeiro depois as pessoas viram a equipe escolha pelo perfil que treinar você treina tem nada morei dois anos para treinar um agora tem um tenho que tá lá um ano comigo é meu gerente trabalha comigo lá na Vera e fica na mão dele só manda um WhatsApp para ele tomar tudo certo certo mando e de onde eu consigo fazer depois produtos que são os produtos que você vem na sua matéria é tudo aquilo que você vende é é um absurdo o cliente cortar o cabelo Na barbearia é e em outra barbearia para relaxar o cabelo relaxamento é um produto está vendendo também é um produto que eu me lembro é um serviço mais rendimento serviço ou produto físico né tudo isso é uma envolvem a venda né é um absurdo você cortar o cabelo

e o cara em uma loja no mar ó numa loja para comprar um shampoo velho eu tenho que deixar para o cara lá velho se você me perguntar como você enxerga a barbearia hoje eu enxergo a barbearia a minha barbearia as grandes barbearias tem mais de uma cadeira até que tem uma cadeira tem uma cadeira como um grande Shopping o Mack um grande shopping sim Grande shopping onde eu tenho a minha loja é a minha loja minha bancada fazer um ponto de venda a loja do outro barbeiro eu tô bancada que há também Outro ponto de venda onde tem outro vendedor é a terceira EA quarta quinta a pessoa entender isso como um shopping e também com mal como uma loja grande conveniência onde conveniência significa o cliente lá e achar tudo o que que eu aprendi muito quando eu trabalho na Leroy Leroy a mais barata não não é mais barato e não não mais barato Leroy ela certinho melhor atendimento ao mês mais ou menos o que é o celular bricolage faça você mesmo é o vendedor é um assessor de venda e não é um vendedor aqui né que eu trabalhar não

ganhava ganhava comissão é mais uma escola tá mas palavra francesa que é uma loja francesa porém ela fica pega essa sacada ela fica aberto o horário que não tem ninguém aberto lá e dias que ninguém abre para o Canadá maiores dores né ela alcança o público tá e o mesmo comprei muito mais heróis Quanto tá o informando a barbearia o apartamento só porque eu chegava lá na obra o cara tava trabalhando na cor empreitada eu chegava lá 8 horas da noite vai falava comigo assim tá faltando 5 m de fio onde é que 9 horas da noite mano eu vou comprar segunda de frio eu entrado entrado no carro pega a bunda na moto vazar para herói se acha que eu chegar lá e perguntar o cara o preço do fio eu queria acabar com a minha obra dorme da ursinho mesmo e tchau então e outro né Igual a você pensar né no setor de tinta e já tem ali o pincel perto rolinho perto né a lona enfim em todas as conveniências ali justamente envolvidos aquele produto né com certeza fora as estratégias de ver o strass Às vezes a tinta branca o

cara vai pintar ela tá com preço menor do que todo mundo mas o pincel tá dez vezes mais caro atualizar de lavar o rolo gerar né uma venda casada venda casada o mal hoje da barbearia e muitos profissionais no plano de todo seu trabalho muito para mudar isso cara eu preocupa demais com corte de cabelo quando você vai numa loja para comprar determinado produto falar para comprar um tênis Você já nome é senhor já sabe o tenho sequer cor que quer o papel tamanho e coloca no pé para ver se é bom a vendedora Não vai tentar defender o tênis não é hora de tentar te vender um casaco que ele tá fazendo frio você não foi para comprar o casaco tu tá Porque mano O tênis já tá garantido para quê que você tenta vender o tempo para o cara os cara só para comprar um tênis a galera preocupa só em cortar cabelo tá errado ela já tá ali ah já falei para nossa família fez muita gente então mas eu tenho poucos clientes eu tenho eu tenho eu não preciso de muitos clientes cliente paga muito eu preciso de vender muito para

o mesmo cliente porque as lojas hoje não tô da pandemia mudou isso que você tinha que entrar nas lojas de conveniência e o caixa de pagar o cartão dela lá na hora que você dentro ele é lá no fundo da loja passar por que passar por tudo de a coleção produto e as colocar uma pelo menos a cueca eu amei o cara leva velho estratégia tudo a estratégia intencionalidade só tem lendo um livro é falar dele aqui a galera comprar um livro muito legal sua intencionalidade o apóstolo Marcelo a um amigão meu show a um líder um líder Nato aí e fala que resultados são intencionais ou lendo esse livro pois vou te presentear com é legal demais fica aí a dica viu pessoal intencionalidade não sei que deve que quer crescer cresça de forma intencional do apóstolo Marcelo dente muito top muito top isso e você for um pouco da minha caminhada né até chegar já depois intencionalmente eu mudei para esse local forma tem uma nova forma de atendimento que escolhendo público-alvo Max atende todo mundo todo mundo que pagar pelo meu serviço meu irmão tu tem o preço o famoso Pagando bem

de novo isso elimina tudo quando você sabe é quem você é dentro do seu próprio negócio pelo que você vai atender o cliente para de chegar e perguntar crente que chega na barbearia e fala assim quanto que é o corte eu não Rio que tem ar condicionado ele não viu que tá na cadeira de massagem e não viu nada e não viu que sinalizou ele quer saber só quando que é o corte Esse é o cliente um por um ao falar do dessa foram agora cliente um por um aquele que a gente só corta cabelo cara o cara corta cabelo compra um prestobarba ruim para caramba e em sangue no rosto não mano o cara tem que sair da barbearia nem que o Barbeiro de a primeira babá terapia para ele ele viver a experiência ele tem que sair com a barba feita porque quando você para de vender corte de cabelo começa a vender preocupar com a experiência do cliente o cliente volta e compra galera preocupou muito no corte de cabelo corte de cabelo além de não dá dinheiro dá muito trabalho tá muito a base era muito esforço não é muito fofo

princípio de Pareto 80/20 Vinte por cento de força oitenta por cento e resultado mano Quem é essa que a pegar trabalhar mesmo forma inteligente exemplo um pagamento trabalho muito meu trabalho mais inteligente que o que nos deixa cansado não é trabalha muito é trabalhar e não tem resultado trabalhar muito de ter resultados e Continuo trabalhando pesado a ver quando você trabalha muito não tem resultados incríveis animado cansado e desanimado desanimado aí eu criei com a com essa mudança de 12 barbeiros eu tinha duas pessoas separar comigo na verdade era o nosso barbeiro três recepcionistas a perna duas recepcionistas e um eu sou calmo organizando tudo e com essa mudança eu contratar um gestor comercial com Nilton e daí meu irmão ó abração para você e você tiver vender podcast o grande abraço aí Espero que tenha um contrato aí o cara vai ver sim que ele é top contratei ele clama nós vamos padronizar achei que choque de gestão choque de gestão jogos restantes agradar todo mundo virei foi galera seguinte ficar para vocês como é que vai funcionar a partir de hoje as novas não damos mais sobrancelha para o cliente não porque o

cara tava lá no cara 20 minutos para compensar da Vila sobrancelha perdeu 15 conto o teu trata do cliente achando que ganhou tá aí não pode dar mais sobrancelha para cortar um cabelo é tanto tempo para ver um relaxamento tanto tempo para dormir o tempo de tudo e ao mesmo tempo que o Max gasta eu sou super rápido nó aí os cara foi lá na força e também só tem um paninho não vai começar a valer hoje não começa a valer daqui dois meses Max vai treinar você pegava todo dia 7:00 a barbearia nova para dar treinamento de barbeiro tá por quantos quilos um só os Mobs não queria era Luciano O que aconteceu a galera saiu é sai e com solos em trabalham comigo mano o primeiro mês só dá um dá um número aqui não lembro foi senão a gente faturava 19.000 a barbearia com dois barbeiro Eu Luciana fator o 21 no primeiro mês para o meio tá trabalhando errado sempre sentava escancarado na tá vendo tava errado né eu fui você de gestor comercial haha seu contrato Maio mais um fatura aí vamos lá 20 mil / 2 10 mil contratar

não vai para 30 mais outra para 40 Matemática Simples de padaria mano E aí beleza aí eu mudei para esse outro lugar e hoje eu trabalho assim cliente só corta cabelo cliente um por um cortou e fez barba 2 x 1 cortou fez baixo sobrancelha três por um cortou fez barba sobrancelha e fez mais um outro procedimento relaxamento já pula para cinco por um relaxamento da quase é mais caro cortou três barba relaxou pelo da sobrancelha e fez uma selagem da Vila 7 por um se ele levar um shampoo condicionador e o creme um cliente 10 por você faturou pés eu precisava ter faturado 10 10 clientes e um só atendimento é um aumento seu valor hora a gente vai lá para o alto mano macho Mas você demora para fazer isso não aí tem outra questão que eu explico muito que a dinâmica de atendimento dos barbeiros sabem o que que eles devem fazer a hora de fazer quando fazer para não perder tempo vamos bom cara chegou para selar o cabelo não selagem você chegou lá para selar a gente não vai cortar seu cabelo é que você tá tá na minha na

minha cadeira marcou só de cortar eu tenho só o tempo do corte 45 minutos para cortar seu cabelo ou 30 ou 40 de encaixa é 30 normal 45 eu tenho só esse 45 minutos para cortar seu cabelo dessa selagem o corte você já é vendido né Se eu tiver na cadeira eu paro na hora lá para o cabelo aparecer lá e sela o primeiro porque o que o cavaco já tiver aí eu fui para comprar só o tempo pegou a visão aí tem uma dinâmica forma certo o cara por relaxar você for pintar então e uma forma também de você trabalha é esse cliente para que se chegar outro entrar para dentro do horário dele esse cliente fica na espera para conversa Franco aí mano eu como a gente encaixa um serviço seu que prezo muito pela qualidade do seu do seu tempo duas canções do seu tempo o cara pô vem mesmo não pode atrasar o que ele crédito no meu tempo tem que sem falar na primeira pessoa isso é muito importante ainda é o cara pensa assim Pô mano E aí é [&nbsp;__&nbsp;] mesmo está zelando pelo meu tempo se eu tiver

sentado no lugar do cara não ia me atrasar ele pegasse atendeu o que a gente entra numa parada que chama Efeito Bola de Neve é uma coisa mais louca ainda quando eu eu tenho várias cores da barbearia ou no cliente está atrasado eu faço dinâmica Efeito Bola de Neve É porque eu tenho um barbeiro que tá atrasado dentro de uma dinâmica de atendimento e tem outro barbeiro à toa eles barbeiro vai lá e lava o cabelo do outro gente não trabalha eu vou cortar só meu cabelo sabe não que enche nosso valendo tudo para barbearia trabalhamos um todo time campeão Perguntaram assim para o Jorge Jesus como é que ele fez aquele time do Flamengo jogar ele falou assim eu só mostrei para ele que a marca Flamengo é maior do que a individualidade e se o Flamengo alcança o objetivo na época era ser campeão brasileiro da Libertadores todo mundo está é uma bela e amazônica não estou Nutella dentro grande mano barbearia José grande junto no mundo é grande junto então essa quer pegar dá trabalho tá foram vinte anos para chegar até aqui mas do dia para a noite eu achei que

a galera não quer você quer né É mas a de que exista e desistir de você mesmo com certeza Essa é a grande sacada e bom a gente falando disso tudo nessa passou um pouquinho ele da visão que você tem da barbearia hoje é o que que você indica então para quem está começando né sempre uma jornada aí extensa passou por muita coisa muito perrengue aprendeu muito na prática né sofrendo ali mas o que que você pode contar para rapaziada aí que tá começando quais são ele é um seus principais conselhos aí para o Max lá de trás que tava começando o cara primeiro comércio o papel magia quando você E aí começa você começa a coisa e tal primeiro planejamento eu começo faltou planejamento estude né ser Barbeiro é uma coisa se você for estudar para trabalhar dentro de uma barbearia e vem trabalhar comigo tudo sua cabelo quando chegar aqui só que lembre as outras coisas mas você for dono quiser ser dona de si só para barbearia só para frisar bem que eu nunca trabalhei outra barbearia não o trabalho 20 anos fala comigo e com as pessoas com Deus comigo minha

família com as pessoas são do meu lado eu nunca trabalhei não aprende nada trabalha no meu trabalhar estudar Mc Braz veio muito lugar isso daí também principalmente na escola da vida o primeiro planejamento cara hoje foi muita gente que pode ajudar eu já tenho vários cursos aí e para ajudar as pessoas alcançar seus objetivos Não tenha pressa às vezes o caminho mais longo para alcançar os objetos caminho mais longo para você chegar no seu objetivo ou atalho com muita gente acha né que o comentário vai acabar melhor aquela história né da lebre e da Tartaruga verdade eu mesma de baixas eu pego um ataque aí um buraco Aí das tudo que aconteceu para mim não vou cortar por aqui porque os meninos foi para ali tentei pegar umas ali só que eu não sabia passa por aí e evite a Thales revista katálysis estude muito estou de todo o tempo que já seja eu nunca cai na zona de conforto esteja ciente no mercado do tempo todo não tem mentalidade CLT como empreendedor é muito importante acho que muitas pessoas um trabalho dentro da barbearia porque eles pensam assim o pensamento muito errado que eu

tô inquieta não sei no meu patrão a Anna margarina por isso que eu não sou patrão dos não tenho patrão não sou patrão e o que eles não têm muita Leão tinha o nosso grupo chamou os galácticos eu falo com ele que eles são os melhores em farmácias são os melhores mas não bateu Ronaldinho do outro lado prático do que qualquer um de voltar não faz muito importante isso cara é outra coisa Constância Constância Constância Constância cara faça um curso de iniciante abre que você levasse a faixa branca não tá preparado para montar uma barbearia não tá mano e depois vá trabalhar numa barbearia importante lá você vai definir se você vai querer ser dono ou não os dois barbeiros trabalham comigo ele era o caminho inverso desmontaram a barbearia deles e eu fiz uma proposta melhor para ele se ele vir trabalhar comigo então muito muita gente acha que é fácil né Você tem uma empresa se abrir você comandar nessa tirar certamente gerenciar pessoas né Tem muitas coisas eram financeira só tem dia que atende atende Se não tem em vc pode gastar não tem você não tem dia que entre vários clientes

tem dia que entra um nenhum né vai passar por tudo isso raça muito principalmente no começo até você pegar essa pegada 10 por um os meninos não preocupando eles atendem dois clientes vai embora e não até aqui é um cliente 1200 1300 1500 contos no dia no dia não sei naquele montão eu tô na felizes com lá brincando que vendo conteúdo que eu cobro deles também quando eu tinha sinuca e jogavam sinuca aí vai a primeira coisa o cara faça um curso bacana tá e depois é tenha Constância naquele que você vai fazer esse disposto a mudar quando o mercado mudar a gente fala assim já tive esse pensamento Pois eu vou mandar o Robério porque eu não vou trabalhar para ninguém e ninguém vai mandar em mim eu não vou ter patrão com três vezes que que a gente comete eu cara ele ele é empreendedor já não é mais se ele tem carteira ele não foi trabalhar não tem dinheiro tá eu não vou trabalhar mais para ninguém então que foi conta Acabei de quem quem trabalha para o cliente é outra coisa ninguém vai mandar em mim é um cara que uma

mercado vai digitar o dono o meu pulmão ele vai ser forçar eu não vou ter patrão seu patrão também o mercado o mercado Muda você não muda eu te mando embora táxi de táxi a sua de Uber Uber Total mercado mudou galera do táxi não se a tentou aconteceu o mercado tá fez aqui tentaram parar na marra ainda e o mercado engole mercado em vendo ó essas três coisas simples é se eu preparar persistir né E sabe preparar para esse dia está tendo as mudanças mais rápida dançar com música né muda mano mercado muda o mesmo muito né Igual o que me salvou nessa pandemia também dentro Na barbearia que eu falo foi a gestão dessa por um e quando você tem a cara tem poucos clientes cara a gente compra de Formação experiência eu comecei vender informação para o cliente viu lá que eu expliquei escrito seu cabelo de cortei o cabelo Por quê que eu fazia e tal e tal que eu tava usando a tesoura dentada porque dá uma selagem porque disse Porquê daquilo ele me respondeu os porquês do cliente e outra coisa cliente ele tem estacionamento tem água tem café

tem passagem aqui monte de coisa tão cara tem uma belíssima Palmeira comprar essas 32 procedimento vamos tem como o cara não sai de lá sem gastar o dinheiro não velho munição tem né Tem mano eu tenho uma munição você tem lá calibre 12 eu vou retirar calibre 12 metralhadora e tá sempre com 22 na mão mano 22 É só cortar o cabelo do cliente mano seja municiado seja profissional completa de um barbeiro completo você não for Madeiro quanto mais completo você for menos clientes você perde essa que era na sua casa que incompleto da Desculpa quem completo não dá desculpa e grandinha já tá preparado é e que a galera tá começando gasto mais tempo amolando o machado para poder uma chave ela dá uma só fui dormir tava preocupado já pegar uma chave e sair batendo né mas aí sai dando machadada tu gasta me enviar agora não tem resultado a árvore não cai o jogo não vira não vi não é bom Max para a gente fechar falar um pouquinho das suas influências das suas inspirações seja falou algumas mas dentro da sua trajetória Também quem foram os maiores inspiradores em um cara

o mar inspirador de todos Jesus Cristo né mano e aqui empreendedor para quem quer viver a minha um cara que mais influenciou a pessoa sem influenciam até hoje para mim o cara e da Bola da Vez bola da sempre Jesus Cristo cara para mim olha influência que eu tenho na minha vida Oi Jesus Cristo talvez a palavra dele desde cabeça dele legal demais bom isso é falou aí né foram tantas mudanças ao longo do tempo Na barbearia com quem trabalhava né Hoje você tá aí de envolvendo esses métodos e que que você conta pra gente também de próximos passos aí né pro final do ano para esse próximo semestre para o ano que vem cara o meu projeto tomar projeto é Fruit Ficar velho é muito Passos longos para frente não mas mas o que que é frutificar para e melhorar com pessoa o pai para minha filha uma Líder na minha empresa e um bom gestor é onde estou até estão de tudo de sugerir minha vida meus sentimentos aí eu creio que os vai acontecer a questão é frente ficar velho se tornar uma pessoa melhor em constante evolução né mas apaixonado pelo

senhor amado por Deus e o verão que ele tem para minha vida estava trabalhando duro falhando trabalhando certo aprendendo cada dia mais e a simplicidade Eu não tenho muitos planos haha vai deixando acontecer também não um pouquinho é de leite a palavra diz que deleita de funciona satisfará o desejo do meu coração são 37 Versículo 54 Então são cara que meu preocupação tava no reino fé em Deus mano o resto Buscai primeiramente o reino de Deus suas despesas justiça e as demais coisas tudo que a gente busca comida bebida moradia vestimenta sucesso vai ser acrescentadas vai buscar a Deus acima de tudo e o reino dele é paz justiça e alegria tá o resto mano tudo certo haha Marcos queria agradecer mais uma vez né Para a gente a uma honra um privilégio né Tati recebendo aqui você ter disponibilizado em um tempinho para bater esse papo com a gente um papo super bacana Espero que muita gente possa gostar aí também que o pessoal né aprenda muita coisa com que a gente possa ter conseguido compartilhar aqui um pouquinho nem mudar um pouquinho e a visão sobre a areia também né foi um prazer

enorme e bom a gente o presenteado os nossos convidados morte da primeira temporada Opa vim aqui também é que a gente preparou para você um kitzinho nosso para ficar de lembrança você usar ela também né só tem agradecer mesmo por vou abrir aqui mas eu quero um rato bem É o Gilson cara que me ajudou no começo mas referência tá e o são minha irmã Marília a meu pai e minha mãe que não tá entre a gente minha mãe era uma mulher que ela leva marmita para mim não é porque não conseguiu almoçar tanto que vem do seu time no canal do YouTube tem tá Maxwell dá uma olhada lá que tem história o meu pai mano Meu pai foi um cara velho que tudo que a gente eu tenho de galo herdei dele foi muito parecido com meu pai meu pai era um cara que ele tinha o zíper quando não tem mais para trabalhar não tinha igual não guardei isso dele a geração vai trabalhar bora trabalhar tá eu também meus vídeos beijos e passaram sobre a minha vida principalmente na igreja né que eu sou um cara Cristão aprende muito a igreja

mudou muito a minha vida os livros que eu tenho hoje a nos sentar não são muitos é mas é me ajuda o pensamento aí nós temos data do dia mais mais a minha equipe também da barbearia em maxxisol todos aqueles passaram por lá pois tem seu próprio negócio todos os clientes os parceiros aí que fazem parte 01 parte da minha vida e minha equipe atual é que é o Francis é o Souza o Edmundo tem um amigo velho ganha um irmão nessa pandemia pode abraço para todos vocês Legal tem certeza que tá todo mundo muito orgulhoso espero que ela fez negócio tem um kitzinho aí para você também tem aí tem Caneca tem adesivo tem até um doce de leite aí também agradecer o pessoal aí nossos amigos dá um capim limão né o pessoal do doce Leite diretamente lá de Santo Antônio do Grama né um bolo de leite com café Espero que você gosta aí também Red Bull Caneca camisa seu demais receba receba adesivos aqui aqui beleza show demais é obrigada Tá fazendo o quê oi oi [Música]`,

  summary:
    "Episódio 7 da Temporada 1 do BestBarbers Podcast. Max Visual compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
