import type { VideoContent } from "./types";

export const podcastelisandro_oliveira_S2_ep04: VideoContent = {
  slug: "podcast-elisandro-oliveira-s2-ep04",
  youtubeId: "W2VZmin0zKk",
  title: "BestBarbers Podcast com Elisandro Oliveira — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 4 da Temporada 2 do BestBarbers Podcast com Elisandro Oliveira. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "elisandro oliveira",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2023-02-20",
  duration: "1:13:23",
  category: "Podcast",
  tags: ["podcast", "temporada 2", "entrevista", "gestão", "barbeiro"],

  transcript: `[Música] senhoras e senhores sejam bem-vindos a mais um best podcast é sempre uma honra ter você nos acompanhando eu tenho aonde receber aqui o Elissandro hoje parceiro ele de longa data né a gente se conhece há um tempinho já vem acompanhando a trajetória dele também cara não vou enrolar muito pessoal que é mesmo essa vida sua história saber como é que foi a sua trajetória Então se apresenta rapidinho para o pessoal conta como é que foi a Conceito Barber Club como é que surgiu um pouquinho como é que foi até chegar lá é bacana primeiramente Andreia Obrigado viu um prazer estar aqui com vocês é podendo compartilhar um pouquinho do da minha história da minha trajetória do que eu fiz para chegar até aqui porque tem dado certo também do que tem dado errado e para ensinar os barbeiros aí a desenvolverem na área da barbearia galera eu já começo a contar uma coisa que eu às vezes poucas pessoas sabem né que eu nasci no Ceará eu nasci em Caucaia no Ceará então quando eu vim para cá foi 1998 eu tinha cinco anos de idade Foi meu pai arrumou uma proposta melhor de

emprego sou de família simples é meus minha mãe diarista meu pai é Metalúrgico então nunca tive luxo mas graças a Deus meus pais são muito trabalhadores nunca passei nenhum tipo de dificuldade é nunca passei fome isso são muito grato a eles por causa disso E desde novo né a minha expectativa era tipo assim eu via meu pai metal luxo minha mãe diarista eu pensava assim nossa eu era Será que eu eu acho que eu consigo ter uma vida às vezes melhor que eles proporcionar para eles uma velhice legal então foi isso que que eu comecei a trajetória para entrar na vida da barbearia e pensando nisso ter o meu negócio que às vezes me motivou porque você fala assim ó eu via né os exemplos de pessoas que tinha um próprio negócio eram pessoas bem sucedidas e eu não era um cara que vinha de berço de ouro então eu não tinha aquela grana ali para montar uma estrutura muito top um negócio então eu tinha começado de baixo e um curso de barbeiro era uma oportunidade para ter meu próprio negócio Quem sabe um dia ter uma equipe e crescer e ter o meu

próprio negócio né então foi assim comecei com a maioria dos barbeiros começam garagem de casa garagem não porque lá em casa nunca teve carro né eu começava foi no terreiro de casa cobrando ali só o preço da lâmina é às vezes r 5 e fui crescendo e tinha mais ou menos quantos anos eu tinha na época 21 21 20 anos eu namorava ainda com a minha esposa era minha namorada na época acho que eu tinha 20 anos Isso foi a foi em 2000 foi 2013 não 2012 final de 2012 Então eu tinha uns 20 anos ali mas eu estava em 2023 eu fiz 30 ontem né ontem meu aniversário e fiz 30 ontem então é isso mesmo 2002 tinha 20 anos de idade quando eu comecei na área da barbearia já tinha trabalhado já de carreira quase né 10 anos de carreira cara já tinha trabalhado ali em outras coisas mas é aquele negócio desde os 14 anos já trabalhava lá fui lá ver queijo é pra você ver lavador de lavava embalava que vinha da roça para vender depois trabalhei numa empresa que dava manutenção na impressora ficava limpando as peças de impressora para

os técnicos arrumarem então foi assim e com 20 anos de entrar no no ramo da barbearia aí e aí você começou a sua trajetória ali só cobrando o corte só cobrando material e como foi a sua primeira experiência ali de no Agora É realmente Vou começar a me profissionalizar nisso daqui eu vou começar a investir nessa carreira realmente né eu vou começar a trazer isso pra minha vida Entender que meu futuro vai ser baseado nisso Olha eu quando atendi em casa no terreiro de casa ali e cobrava r 5 quando eu ganhava muito r 5 e desde de novinho já tinha aquela questão do que os cara que chegaram lá pagava r 5 mas tinha outros que não pagava tinha outros falava que ia pagar na próxima Mas a gente nunca via e isso Começou a despertar e falar assim no meu coração assim poxa cara eu tenho que ir trabalhar para alguém eu tenho que montar minha própria barbearia para me realmente começar a os primeiros passos a realização do meu sonho né que é ter uma empresa e nesse esquema aí eu lembro que eu trabalhei tipo assim seis meses mais ou menos

em casa atendendo um terreiro de casa ali só os amigos os parceiros aí eu até uma coisa legal para para os barbeiros que estão vendo aí o nosso podcast Às vezes você fica pensando o que que é melhor eu trabalhar para alguém ou montar minha própria barbearia e eu tava com esse dilema na cabeça o que que seria melhor para mim aí eu peguei e falei isso não Eu sempre pensei uma vez eu até escutei uma história que é legal para caramba que é a questão de quando é muito difícil você crescer o seu nome no mercado mas é muito fácil você se queimar então se eu era um cara inexperiente ia montar sua barbearia de cara aí ia estar lá no nome da barbeariando é barbeiro e Alessandro a chance de eu cortar o cabelo errado e às vezes dá um vacilo ali de não saber atender legal porque porque eu sou inexperiente quando a gente ainda experiente a gente erra mesmo a chance de eu errar e queimar meu nome e já entrar no mercado com o nome queimado era muito grande depois para reverter isso daí é o nosso trabalho em dobro

né É muito difícil e é por isso que é importante você ter um mentor para tudo na vida você tem que ter um mentor no começo da sua da sua infância é seu pai e sua mãe quando você entra no na área profissional é o seu chefe ali é então eu procurava um mentor então eu pensei assim não eu não vou montar a minha barbearia eu vou trabalhar para alguém primeiro então eu saí do terreiro de casa e fui buscar a barbearia bati na porta de todas as barbearias que você imaginar não recebeu oportunidade eu escutei até uma vez eu fui numa barbearia o cara virou para mim e falou assim você é louco você tá maluco como é que eu vou por um cara inexperiente igual a você aí para aqui dentro da minha barbearia aqui você vai desculpa passo ele falou assim você vai fazer cagada na cabeça das pessoas e eu fiquei triste para caramba com aquilo mas não não desisti falei sinal eu vou eu vou continuar batalhando continuar me me esforço até arrumar aí fiquei seis meses em casa cortando o cabelo dos amigos cobrando r 5 arrumei uma barbearia

pra mim trabalhar que chama Studio 9 mês e foi muito legal cara eram três barbeiros eles estavam precisando de mais um comecei a trabalhar ali com os caras e foram os meus primeiros mentores eu fiz muita coisa errada na cabeça dos clientes do jeito de atender E falar alguma coisa que eu não deveria falar então e tudo isso ele toda hora o cliente ir embora ele sabe vacilou no corte pézinho ficou torto cabelo ficou mal cortado você não arrumou o cabeção lavou o cabelo do cara orelha tá toda suja de cabelo então foram Meus Primeiros mentores ali e esses puxões de orelha me fizeram melhorar como profissional isso foi legal demais foi minha primeira experiência trabalhando em uma barbearia e foi muito legal eu fiquei lá um ano um ano e meio um ano e meio fiquei um ano e meio nessa barbearia foi importante a paciência deles terem né te dado os toques ali mesmo serrando né ele ainda assim tinha acompanhado eu sou muito grato a eles eh por toda a vida né eu vou ser grato a eles poderiam ser me ajudado Nessas questões porque às vezes a gente fala assim quando

quando eu falo isso do nosso pai às vezes quando nosso pai puxa nosso Leão você não vai pra tal lugar você não vai fazer tal coisa a gente acha ruim a gente fica assim nossa meu pé é chato pra caramba Ai meu chefe é chato pra caramba mas às vezes ele quer só o seu bem eu vou botar já depois eu vou contar mais histórias pra vocês que puxou de orelha que eu recebi de grandes players do mercado aí mas que me fizeram tipo assim crescendo na profissão hoje eu olho para Na época eu falava assim cara chato quem ensinar eu trabalhar mas é aquilo ali me fez crescer profissionalmente me fez eu me desenvolver profissionalmente E aí depois dessa barbearia você chegou a trabalhar em outra eu trabalhei eu fiquei no studio of Mans um ano e um ano e meio ali eh no estúdio of Men aí mais ou menos um ano e meio mais ou menos que eu fiquei ali o tempo correto Aí como eu falei com você eu trabalhava num terreiro de casa e eu precisava trabalhar para alguém primeiro para não queimar o nome da barbearia para não queimar

o meu número no mercado Então esse 1 ano e meio foi só experiência apanhando Para quê Para aprender a me tornar um bom profissional e uma coisa uma coisa legal até que eu queria compartilhar duas estúdios de of mens uma coisa que eu aprendi eu acho que seria muito legal para vocês Barbie eles estão assistindo a a Live aí é a questão de quando eu comecei no terreiro de casa muitos caras que cortavam comigo eram os meus amigos que jogavam bola pessoas próximas parentes e amigos e eles me davam r 5 às vezes o preço da lâmina e quando eu fui para o estúdio o filme mês lá eu trabalhava para pessoas então lá tinha um preço diferenciado e o diferenciado era outro era 15 reais você acha que essa galera que cortava com r 5 em casa me acompanhou porque 15 reais pouquíssimos né tem condição negócio desse r 10 só a diferença mas não me acompanhou muitos queriam que lá no lugar de r 15 eu cobrasse Eles apenas cinco Pô eu te dei moral Foi eu que te dei moral quando você começou as pessoas não entendem que você tá evoluindo e

uma coisa que eu fiquei muito chateado foi aqui muitos deixaram de cortar comigo muitos barbeiros estão vendo essa Live aí vai falar assim nossa eu tô você tá falando eu tô pensando é meu meu cunhado do quarto comigo meu tio não corta comigo meus primos meus amigos próximos joga bola pelada comigo todo dia não corta comigo que que eu faço eu fico triste e eu ficava triste também só que uma vez no estúdio de of memes como essas pessoas que eu trabalhei lá uma vez eles me ensinaram uma coisa que ele sabe eu ficava assim Poxa velho os caras não não gostam de mim por isso que ele não corta meu cabelo Nossa eu ficava pensando não eu corto mal por isso que eles não estão cortando comigo eu não eu não o meu trabalho não vale r 15 é por isso que eles concorda comigo mas não é eles falaram assim eles falaram comigo assim sério o negócio é eles não não é que eles não gostam de você é que eles gostavam muito do seu preço ele só estavam Ali pela comodidade que você dava para eles um pouquinho que você aumenta ele

sai fora mas não preocupa não cara daqui um ano um ano e meio você vai estar com uma clientela que você não vai sentir nem falta dessas pessoas e dito e feito fiquei lá um ano e meio cara quando eu saí de lá minha agenda tá bom lotada tocando mesmo ganhando dinheiro é ganhando dinheiro em bacana e foi uma época que eu investi muito em cursos aí você me perguntou quanto tempo que eu fui lá fiquei lá um ano e meio e depois esse ano e meio olha para você ver como é que é as oportunidades eu me dediquei muito a a estudar né a buscar conhecimento eu tinha para mim sempre e isso foi um curso que eu fui eu escutei seja o melhor barbeiro do mundo para o seu cliente quando o cliente é o melhor barbeiro do mundo tem que ser você quando ele tiver sentado na sua cadeira você vai atender ele bem você vai trocar uma ideia com ele ali vai entender o que que ele quer entregar o bom corte dá o seu melhor buscar tá sempre Ó melhor máquina Olha a estrutura linda que a gente tá aqui

hoje isso aqui é bom demais é gostoso ficar tenho certeza e o cliente também ele sente isso quando ele entra dentro da sua barbearia tudo limpinho tudo organizado você coloca uma capa bonitinha nele limpinha cheirosa o espelho Limpo para ele poder tirar uma foto postar nas redes sociais que o cliente gosta disso então desde novo esse um ano e meio eu aprendi tudo isso e isso me proporcionou aí trabalhar nas maiores barbearias do Brasil que eu querendo ou não tanto uma barbearia de bairro barbearia simples Eu chamei a atenção do homem uma das mais referências do Brasil que é o seu Elias e foi para onde eu fui depois desse um ano e meio eu já tava você sincero para você eu já tava preparado para montar minha barbearia é já tava me juntando uma grana já tava me falava com a minha namorada minha esposa hoje namorada na época fala assim amor tá na hora da minha barbearia um ano e meio eu já quero fazer as coisas do meu jeito porque os meninos aqui me ajudaram muito e tal mas eu tenho meu estilo de trabalho eu quero colocar isso implementais dentro da

minha barbearia e já estava pronto para montar a barbearia ali apareceu a oportunidade de trabalhar no seu Elias olha lá atrás ele Sandro trabalhando no terreiro um lugar para pegar uma experiência aí cai no meu colo depois de um ano e meio cai no meu colo a experiência do seu Elias da vida melhor oportunidade que eu poderia ter um ano com Elias ali cara é 10 anos e muitos lugares eu ia pegar muito padrão muito isso aquilo coisas que me ajudariam muito e sem contar tá do lado grande e isso foi top demais para mim top isso foi sensacional e uma coisa também eu até minha esposa tá aqui vocês não estão vendo que ela tá lendo quietinha ali mas uma coisa até legal nessa época eu tava no estúdio of me antes de ir para o seu Elias o seu Elias ele não caiu no meu colo foi eu acredito muito que foi pela persistência que eu tinha dedicação em buscar cursos cara eu tinha um ano e meio de profissão eu tinha mais de 20 certificado todo final de semana eu ia fazer workshop e foi um momento aí eu é outra dica

que eu dou para você barbeiro que está assistindo essa Live veja quem é que são as pessoas que estão do seu lado São pessoas que colocam pra frente coloca para trás eu vou te dar um exemplo Hoje eu e o André somos vamos a gente é o melhor amigo só anda junto o dia todo só que o André ele é um cara que a todo momento tá usando droga todo momento dando exemplo a chance de eu não usar droga é muito pequena porque se eu tô com cara com ele a chance eu vou fazer as mesmas coisas que ele faz é muito grande você tá cercado de gente que usa droga dificilmente você não vai usar Você tá cercado de gente aqui não cresce na vida como é que você vai crescer gente é difícil demais e graças a Deus Deus colocou na minha vida uma pessoa muito especial que é minha esposa é era um momento que eu trabalhava a semana toda aí os cursos são domingo domingo minha folga o que que a namorada quer curtir sair passear aí amor hoje tem o curso do seu Elias não tá r 200 tá r

300 a oportunidade nós divide para mim no cartão o amor hoje tem o curso do Eduardo Miller hoje ó eu vou passar o fim de semana lá no Rio de Janeiro porque vai estar vindo o Celso barbeiro lá de Portugal queria muito fazer um curso com ele cara eu fiz com todo mundo que você imaginar esses 20 certificados era aí com todo mundo e se ela fosse uma mulher que me jogasse para baixo Sabe aquela falaria porque tem muita mulher gente você aí que é barbeiro tá namorando sua namorada ali ou sua esposa não coloca você para frente sua namorada é aquela namorada de balada que só quer o fim de semana só presta você para o fim de semana testa um dia falar com ela que você não tem dinheiro umas duas três semanas que você falar que você não pode sair com ela ela vai te dar um pé na bunda infelizmente é pessoas quando a gente põe para frente a minha esposa a minha esposa Não amor vai fazer o curso eu fazia curso até de feminino o Rodrigo Cintra Quantas coisas eu já fui nos três a hoje do Rodrigo Cintra

uns três Rodrigo Cintra os barbeiros Na época eu sou muito grata a eles mas eles zoavam comigo que era eu que mais correr atrás eu lembro na semana que eu vou fazer o curso com o Rodrigo Cintra todo mundo da barbearia ele ficou me zoando eles e os clientes a zoeira e era assim ó gente a partir de semana que veio ele vai estar fazendo unha aí também Na barbearia viu é pode falar com suas esposas porque ele tá indo pro curso de feminino a brincadeirinha mas eu não ligava cara eu tava lá esposa sou muito grata ela porque ela foi uma pessoa que sempre me apoiou e falou vai estuda e quando você tem pessoas assim da sua vida galera vocês voam porque pessoas que te colocam para frente quando você tá vendo que você tá esforçando você tá correndo atrás e te dar moral não fica te puxando não não faz isso não sô eu tinha muito cara falar velho você fica dando dinheiro para esses barbeiros que tão rico faz isso não deixa de ser bobo não fica dando dinheiro preso não cara isso tudo a minha esposa me apoiar eu sou

um cara dedicado da minha profissão me proporcionou a trabalhar das maiores barbearias do Brasil que é realista certeza e como é que foi a experiência de trabalhar lá no Elias nossa cara é foi mágico e uma coisa que eu tenho que botar para vocês também todo mundo que fala assim se eu falar agora com você você vai ter que trabalhar com Elias eu acho na sua cabeça a primeira coisa que vai passar é que sua cabeça barbeiro vai a primeira coisa que vai passar é assim ó eu vou trabalhar com eles agora os meus cortes vão ficar top eu degradê Vai ser top o meu Barba vai ser incrível não é cara a minha mudança de mentalidade Lógico eu aprendi muito questão de técnica com Mas o que eu mais aprendi lá foi Pilares que hoje eu levo para minha vida levo para os meus cursos ensino para os meus alunos são Pilares que me fez desenvolver como profissional são o atendimento lá cara você tá nessa Face então você não pode atender de qualquer jeito o corte era r 50 eu tinha muito um trade Ô Zé Ô mano não existe isso chamar o

cliente de zeide Mano uma vez eu chamei o cliente Zé ele virou para mim e falou assim meu nome não é Zé Não meu nome é tal aí Pronto né aí pronto então são atende mesmo eu desenvolvi muito do atendimento e melhorei muito além do Elias tive grandes professores que é as pessoas que trabalhavam lá não tem como é o que eu falei com você agora a questão da minha esposa ser uma pessoa que colocou pra frente eu tava no Elias aí eu olhava para o lado e você Elias eu olhava para o outro Rafael que foi uma pessoa eu fiquei muito próxima virou um dos meus melhores amigos do lado Rafael aí da autoridade quando a gente se encontrava Josiel Luís aí tinha um Highlander ele ou a gente olhava para os lados Danilo o Danilo Barbie que hoje está nos Estados Unidos eu olhava para o para o lado era só referência eu aprendi a todo momento ó eu quero atender igual o Daniel atende o Daniel era um atendimento excelente o Aldo aqui nosso atendimento do áudio que era aí eu aprendi eu atendimento com eles Aí o Rafael e o Elias

tinha uma tecla excepcional eu ficava de olho na terra deles Então olha o seu redor só pessoa boa como é que você fica ruim não tem jeito só se você quiser se você quiser então isso foram meus maiores aprendizados o atendimento que eu mudei muito as teclas lógico mas o maior atendemento marketing o jeito que eu comecei a fazer meu Marte o jeito que eu comecei a me posicionar nas redes sociais cara eu comecei a ganhar seguidor assim ó alavanca seguidor a gestão lá você vê numa grande barbearia como ela é gerida você começa a olhar para sua vida não cara eu a gestão do meu dinheiro tá errada você começa a melhorar sua gestão então e a postura profissional eu acho que é muito importante muitos barbeiros que estão vendo esse podcast aqui é às vezes Pessoal vocês não não o devido valor a postura profissional que você tem que ter dia do cliente isso é muito importante o cliente ele é a tal da Liberdade o cliente Ele só faz uma coisa que você porque ele vê que você dessa Liberdade ele te pede desconto Às vezes a culpa é sua mesmo porque

você não se comporta como um profissional Cara você não entra numa empresa top gigante aí pede o desconto é igual aqui ó cheguei aqui na estrutura do mash Barbies aqui vou fechar o aplicativo deles lá na minha barbearia lá como que eu não tenho coragem de pedir desculpa pela estrutura que vocês têm pelo gasto que vocês têm mensal aqui só de ver eu não tenho eu tenho vergonha de pedir um desconto Com certeza Então é isso que as pessoas têm que ter na mente o jeito que você veste qual que é a roupa que você veste antes de ser o cliente tá de bermuda de chinelo camiseta cara a grande chance de você atender pessoas desse jeito é a chance também uma coisa que eu sempre falo com meus alunos no curso é quem atende de chinelo dificilmente atender alguém de terno e a coisa mais real da vida porque você eu sempre falo os clientes eles se parecem muito com barbeiro Os clientes são vacaiados é porque o Barbeiro também é um pouco vai Caiado se o Barbeiro ele é sério ele começa a trair a galera mais séria então é isso que a

gente tem que ter em mente O Elias cara foi uma um negócio de Deus na minha vida estava entre os grandes fiquei entre os grandes ali é estar entre os grandes me proporcionou aprendizado muito grande de atendimento de Marte digestão de postura profissional e de técnicas então isso tudo me proporcionou a ser um profissional melhor foi um grande aprendizado na minha vida foi um ano que eu fiquei lá eu entrei e eu entrei focado eu entrei no dia 27 de novembro de 2015 saindo do dia 27 de novembro de 2016 exato porque eu já tinha ficado um ano e meio é numa outra barbearia pega na experiência quando eu entrei no Elia e eu falei isso com ele era uma experiência que eu queria ter para estar montando minha barbearia que o meu sonho é minha barbearia então foi o tempo que eu fiquei lá foi esse tempo legal demais e é deixando claro aí para muita gente né muita gente acha que é milagroso né vou trabalhar com isso vou virar um melhor barbeiro do mundo uma hora para outra né mas como ser bem colocou aí foi tudo muito fruto do seu esforço

né de você correr atrás de você querer né evoluir ali de absolver tudo que o pessoal tinha te oferecer mas depois desse um ano como é que foi abrir a barbearia a gente tem um sonho né mas não vamos ver é tudo muito diferente do que a gente pensa né é diferente cara eu eu na época que eu abri a minha esposa até Falou fica um pouquinho mais no Elias para você juntar mais dinheiro para você fazer uma coisa mais bacana só que eu estava desesperado para realizar meu sonho então eu queria ter minha própria barbearia aí eu falei assim meu amor eu vou fazer um empréstimo mesmo eu vou Peguei pouco peguei na época 10 mil reais só que eu botei uma barbearia muito simples mesmo muito simples uma barbeariazinha de bairro simples tudo branco a cadeira um espelho então foi tudo muito simples mas aquilo ali me proporcionou já começar a atender alguns clientes e montei minha barbearia com esse empréstimo de 10.000 Quem pegou empréstimo Foi meu pai que pegou empréstimo no nome dele porque nem nome para ele certinho aí não é no mercado aí fui pagando ele aos pouquinhos e

montei a minha barbearia aí graças a Deus As coisas deram certo depois de dois anos ou foi dois anos se eu não me engano isso eu montei o final do ano de 2016 final do ano de 2018 eu saí da linha dia 27 novembro de 2016 no dia 9 de Dezembro de 2016 poucos dias depois eu inaugurei minha barbearia e passado esse dois anos aí eu já tinha peguei 20 mil de empréstimo e fiz mais uma uma reforma lá e uma reforma mais top para melhorar esse lugar sempre no mesmo lugar e muita pessoa fala assim ah é outra dúvida que às vezes muito barbeiro tem aquela questão não é um outro nome Avenida ou morto numa rua morta ou numa rua mais para lugar mais barato Cara eu tô do lado no cemitério numa rua que não tem nada não tem nada mesmo eu tenho frete lá que leva produtos para mim lá e ele fala assim velho eu todo dia que eu cheguei aqui na sua barbearia eu não sei como é que você tem cliente na sua agenda porque sua barbear e todo o curso que a gente vai ele fala isso

para os outros vem esse cara barbearia dele no buraco e ele atende cliente para caramba Então não é um lugar é o profissional é o que a gente tem que pensar lógico e se eu eu tivesse a oportunidade de pegar uma loja num ponto muito bacana com aluguel legal eu não vou mentir para vocês que seria muito bom só que o ponto sem o profissionalismo não dá às vezes você tá no ponto muito bacana que você é bem visto mas você é um profissional ruim você ter uma má digestão você não atende bem você vai se queimar com certeza então às vezes é melhor você estar no ponto mais escondido foi o que eu fiz é rua de trás da onde eu morava é aluguel barato não tem ali e graças a Deus muitos clientes meus que eram do seu Elias foram para lá é outro clientes que eram de Contagem começaram a contar comigo graças a a tua agenda é muito bacana hoje a barbearia crescendo cada dia mais e tá Tá legal demais cara e muita gente tem medo disso também né quando eu abrir minha barbearia o pessoal não vai me acompanhar

os meus clientes não vão vou ter que começar tudo de novo e o que que você acha que é fundamental a pessoa ter Antes de abrir uma barbearia o que que é fundamental ela saber para abrir a barbearia e não passar muitos apertos eu acho que é experiência ela manda muito a experiência de ter trabalhado em um local porque tem umas coisinhas que é muito simples mas que fazem muita diferença na hora de você montar uma barbearia eu falo isso porque eu vou falar isso aqui eu tenho certeza que muitos barbeiros que estão vendo isso aqui vou falar assim não acontece comigo O cara tá cortando o cabelo e tal tal aí ele vai fazer o pezinho ele abre a gaveta não tem lâmina aí ele Nossa não tem lama como é que vai fazer o pezinho do cara errou ele tá fazendo pezinho ali ele tá atendendo a criança e tá fazendo corta no cabelo a criança vai lá e por alguma coisa tá tomando alguma coisa molha a capa toda aí ele vai olhar dentro da gaveta ele não tem uma outra capa Então são são coisinhas simples que você aprende quando você

trabalha para os outros porque quando você trabalha para os outros você vê não o cara tem duas capa o cara ele ele uma vez por mês ele faz as compras da barbearia para não faltar nada imagina você tá fazendo uma química no cabelo do cliente não tem a química porque acabou e sendo reparou não tem o relaxamento Ô meu amigo não vou poder fazer o relaxamento você não porque eu não tenho ou então Faz igual muitos profissionais fazem quer sair correndo no supermercado para comprar coisa mais feia do mundo deixa o cliente Espero que eu vou comprar a tinta que eu vou comprar um relaxamento Cara isso não dá então esses essas bobeirinhas é que fazem falta e uma outra coisa também a questão do do de ter um mentor Ah ele sabe eu não quero passar por esse processo eu quero abrir a minha barbearia logo de cara beleza Abra Mas ele aumentou por exemplo me siga lá nas redes sociais siga o BA árvore siga pessoas que já tem Para quê Para você aprender com essas pessoas hoje tem muito conteúdo gratuito nas redes sociais tem cursos legais pagos também então busca aprender

com essas pessoas mas a experiência de estar no lugar vivenciando o dia a dia é muito importante para você pegar essas maldadezinhas é tem muita gente falar você tem que ter seis meses de dinheiro guardado velho O Elias não tinha quando ele botou a dele eu não tinha quando eu montei a minha então é difícil cara vamos ter gente que são consegue guardar dinheiro tem tem gente que consegue fazer esse planejamento tem mas é muito raro então você que é barbeiro Quer ter sua própria barbearia cara Desenrola ali corre atrás de pegar experiência que isso tudo vai te ajudar na hora de montar sua barbearia todas essas pessoas aí principalmente barbearias grandes né já passaram por muitos erros né E ela já sabem ali o Caminho das Pedras e podem Principalmente te ajudar Principalmente quando você abre a barbearia você tá com a cabeça tão cheia de coisa né E esses pequenos detalhes aí que gosta de fogo podem queimar seu nome né tinha prejudicando por nada né e no começo você abriu a barbearia E como que era o seu modelo de trabalho você pensava falou não eu tenho que cortar cabelo para caramba

não eu vou focar aqui em valorizar o meu produto qualquer a sua estratégia ali no início a minha sempre desde o começo que eu abri meu é a minha estratégia era qualidade buscar sempre qualidade Porque ontem eu até fiz um post sobre isso é questão de Às vezes você fica assim ah eu quero cortar não sei quantos cabelos por dia ah o cara bate no peito e fala assim eu corto 50 cabelos por dia eu fui um curso uma vez em Patos de Minas se eu não me engano fui dar um curso lá e tinha um Senhorzinho lá que eu corto não sei quantos cabelos por dia eu faço cabelo e cinco minutos eu não sei o que eu não sei o que lá aí a gente não fala porque a gente é muito educada né mas a minha visão dele era o Senhorzinho de quase uns 50 60 anos e a aí na hora que eu comecei a falar um outro assunto lá eu tenho dor aqui eu tenho dor aqui eu tenho doido ali o cara com 60 anos de idade batendo batendo tesoura atrás uma cadeira Às vezes eu não sei não

conheço a vida dele mas muitos eu sei que tem muitos que eu conheço pessoas assim é que o cara viveu a vida toda cortando o cabelo não tem nada eu adquiriu nada é porque cortar Eu queria ganhar sábado de noite então é muito complicado essas questão eu lembro da época esse ozinho ele ralava mas na hora que eu comecei a falar de dor ele tinha todas as dor possível vale a pena será que vale a pena e eu fico eu fico pensando assim você Será que vale a pena ser bater bater tesoura não ter conquistado nada ou então bater cocô eu corto 50 cabelos por dia mas que que isso proporciona na sua vida financeiramente porque velho barbearia não é ONG barbearia você tem que ganhar dinheiro é um negócio então você tem que ganhar dinheiro não tem essa de ar vou dar moral para o meu amigo não vou cobrar dele Ah vou demorar para não sei o que eu não vou cobrar dele se acontecer alguma coisa sua barbearia fechar esses cara não vão te dar r 1 para salvar a sua empresa Então você tem que pensar na empresa como um negócio

se você é do cara que é muito gente boa não consegue dizer não nem monta barbearia porque senão você vai sobrar você vai sobrar ou então Faz igual eu fiz já muitas vezes eu jogava a culpa pra minha esposa falava assim o cara me pediu desculpa alguma coisa assim nossa cara minha esposa aqui comanda barbearia Você joga responsabilidade com outra pessoa e aprendi isso com os grandes viu quando acontece alguma coisa eu sempre jogo responsabilidade responsabilidade para outra pessoa Cara não posso fazer isso não posso fazer aquilo por causa de porque eu não sou odor Às vezes o cara é o dono eu tenho muita empresa que você vai que o cara é o dono E ele fala que não é ele é o gente boa ali da Galera ali mas ele é que manda tudo ali é o cliente ele não pode ficar com raiva de você né da sua esposa Talvez né Isso mesmo então eu sempre pensei que a qualidade é melhor do que a quantidade é você ali eu comecei a atender com meu método com tudo que eu aprendi no seu Elias com tudo que eu aprendi no estúdio de

ofens com as meninas que eu trabalhei com tudo que eu aprendi no terreiro de casa quando Eu cortava o cabelo eu peguei um método o método de trabalho ó cortar de 40 minutos é que a minha média de corte quando é dois procedimento aí fica tremenda para cada uma hora deixando uma hora é horário agendado política de atendimento cliente chegou atrasado eu tenho uma política lá que eu tenho um limite de tolerância após esse limite de tolerância a gente não garante mais o atendimento e responsabilidade do cliente então todos esses detalhes padronizaram foram processos para padronizar a minha empresa e fazer ela funcionar legal e sempre focando no que da qualidade eu quero que o cliente sente na minha carreira fique à vontade Tenha um bom atendimento Me acompanhe nas redes sociais interaja comigo é veja que eu tenho uma postura profissional legal e o cara quando ele vê isso num profissional ele indica E é isso que eu mais é o que me faz crescer cada dia mais as indicações que eu recebo meus clientes ele sabe que ó se eu indicar Ou eles sa- Tatar o cara que essa sistemático com o horário

eles não vão atrasar se eu indicar ele tacar o cara que é chato com estrutura o cara vai chegar lá vai gostar da estrutura dele sabe se eu indicar ele sangrando para um cara ali que é chato com a teclando vai saber entregar o bom trabalho agora tem muitos clientes seus aquele que estou assistindo aí que às vezes tem vontade de indicar você mas não indico causa alguma coisa não indica porque às vezes o a sua estrutura não é tão legal assim ele fica com vergonha de indicar ele não indica porque às vezes você tem uma maniazinha que ele suporta mas alguns amigos deles não suportam então é tudo tudo é o conjunto E eu sempre presente a qualidade a qualidade ao invés de quantidade porque quantidade a gente não é máquina cara uma hora ou outra o cara cortar igual muita gente na internet Ah corte 50 cabelos por dia é ou 50 sei lá corta 50 cabelos por dia ou faça sem serviços não sei o quê Eu já vi gente corta se cortou mais de 70 cabelo cara velho ô André não mano eu falo isso como cliente Se eu sentar na

cadeira de alguém e isso sou eu barbeiro ele sabe da cadeira de alguém o cara gastar 7 minutos para cortar meu cabelo pode ter ficado perfeito mas eu vou sair de lá encarando tudo para buscando erro você sabe buscando erro você está desconfiando aí e esse cara eu falo tem muitos clientes que gostam do atendimento rápido só que esses clientes que gostam do atendimento rápido ou se não gosta de pagar infelizmente é gosto de atendimento rápido mas o cara não quer fazer uma barba de terapia O cara não quer fazer aqui o cara quer chegar cortar o cabelo corta de qualquer jeito E quem corta de qualquer jeito corta em qualquer lugar cuidado viu vocês barbeiros que estão assistindo aí OK gosta do corte de qualquer jeito corta qualquer lugar Ah Dois clique é bom que ele gosta de qualquer jeito ele toda toda semana ele senta na cadeira logo menos ele tá te abandonando logo menos ele tá te abandonando a questão do preço Também quem cobra muito barato que aí por preço velho por preço vai embora às vezes você atrai o cliente aí pelo preço do seu trabalho cobrando baratear aqui todo

mundo cobra r 20 eu vou começar a cobrar 15 pra atrair os clientes você atrai mas quando aparecer um menino que formou o outro cobrando 10 todo mundo vai te abandonar vai acontecer aumentar o seu para 20 quando você precisa aumentar uma galera também agora então a galera pensa isso então desde o começo da minha da minha carreira e da minha barbearia a qualidade é primordial porque a qualidade me proporcionou de cobrar r 40 do corte e olha que eu cobro barato eu tô do bairro numa rua Mota do lado do cemitério r 40 no corte graças a Deus a minha agenda cheia aí minha média de atendimento é 40 40 minutos eu corto uma média de 12 a 15 clientes por dia tem vez que venha às vezes eu corto 10 8 clientes quando os clientes fazem muito procedimento porque tem cliente que faz corte barba sobrancelha química então o cara fica uma hora na minha cadeira uma hora e meia então mas o que eu até que eu fiz o post lá te falei cara tem cliente e um cliente eu consigo te dizer 150 200 reais então é r 200 e uma

hora ali de serviço ali Às vezes tem cara que fica nessa intenção de quantidade quantidade o cara não faz isso no dia porque ele cobra r 10 ele cobra 15 ele cobra 20 25 ele não consegue ele tem que fritar de trabalhar e repara para você ver um cara ele tem que ter muitos clientes para ter o faturamento grande eu não preciso ter muitos clientes eu preciso ter os clientes certos exatamente se eu tiver os clientes certo eu vou crescer eu acho que é fundamental né todo mundo entender primeiro o tipo de cliente que você quer ter na sua barbearia né Você tocou num ponto muito importante que o pessoal não acredita muitas vezes na força da indicação né é muito mais barato inclusive né você conquistar um cliente através de indicação do que você conquistar um cliente que você nunca viu né nunca viu sua barbearia é como se fosse um restaurante né você nunca vai indicar um restaurante onde a comida sempre chega atrasada sempre chega fria né onde você não é bem servido agora você vai no restaurante que tem o garçom tá ali tipo proporcionando uma experiência bacana de Serve Bem

net se inscreve no horário que você pediu ela vai te deixar te esperando você vai com certeza indicar esse pessoal né e Cara eu acho que assim uma dificuldade muito grande que o pessoal tem também é enxergar isso né de que não é simplesmente o volume né entender essa questão do seu valor ora né quanto você conseguir aumentar o seu valor hora né você vai conseguir com menos esforço atingir objetivos maiores né Qualquer dica que você dá para aumentar o ticket médio Aí Na barbearia Olha eu uma coisa que eu faço e que eu comecei a fazer ainda mais e estudar ainda tá vendo cara você tá com cliente na sua cadeira o corte de cabelo ele já tá vendido você não precisa oferecer nada você não vai oferecer nada para ele ele agendou com você ele vai cortar o cabelo com você só que o cara ele tem a sobrancelha dele inteira Ele é cheio de cabelo no meio da sobrancelha oferece limpar a sobrancelha dele mesmo que na primeira vez você não cobre nas próximas ele vai querer fazer porque ele vai chegar em casa a esposa vai ver a diferença os familiares

vai ver vai elogiar melhor Bárbaro cara nunca mal feita dá uma alinhada na barba do cara ou não eu faço a barba aí o valor da barba é tanto aí o cara ah não cara eu não acho que não compensa pra mim ou não então hoje eu vou fazer de graça pra você ver na próxima vez se você gostar você faz comigo cara eu tenho certeza que ele vai conversar fazer bala com você porque dá diferente eu tenho cliente meu que tem menos barba que eu e os fazem barba Na barbearia comigo faça isso tem jeito não velho você quando você faz fica diferente e fica meio que a gente que é profissional é diferente eu atendo muitos barbeiros que fazem barba comigo que não consegue fazer a própria barba porque não é a mesma coisa parece que a coordenação motora ali atrapalha e tal então É isso eu achei a venda de produtos a venda de serviços essas aí essencial e a venda de produtos também é essencial eu tenho cliente que eu chego lá o cliente senta na minha cadeira o cabelo do cara oleoso para caramba cheio de espinha na cabeça caspa

aí você que é barbeiro mas é um barbeiro que não quer crescer credo que nojo desse cara velho eu vou cortar rapidão para ele ir embora aí você vira pra ele e fala assim dá o seu nome mesmo ô André você tem um cabelo um pouquinho oleoso não tem estico mole um pouco ele não acabe me incomode mais eu fico uma caspa danada dependendo da época não cara porque tem um shampoo anticas foi muito legal eu acho que se você usasse diminuiria muita oleosidade do seu cabelo que gera caspa é a oleosidade também como que a gente tá é um fator importante mas se eu usar um shampoo combate oleosidade vai te ajudar muito aí o cara leva o shampoo vem o shampoo ele busca o shampoo legal com o preço acessível que você consiga vender ali que é homem realmente o cara não vai pegar 100 conto no shampoo mas tem shampoo bom de 25 de 40 então que você pode vender aí você vende o shampoo para ele aí ele tem a sobrancelha grande também aí você vai lá limpa essa sobrancelha dele o que era r 40 no meu caso né eu

vou dar um exemplo que a maioria das vezes o que era r 20 você vendeu o shampoo de mais 20 já virou 40 e meia hora 40 minutos hein você não aumentou o tempo você vendeu um produto aí você vai lá e fez a sobrancelha do cara a sobrancelha ele é dois minutos no máximo pra tirar o excesso aí você já vendeu a sobrancelha r 10 r 5 r 10 já está faturando 50 por cliente chega no final do dia ser uns dois três clientes você faz isso você vende produto você vende serviços extras Você cortou um dois cabelo a mais Então é isso que a galera deixa na mesa é ontem um cara respondeu um post que eu fiz questão qualidade quantidade o cara falou assim você tem que entender que você deixa dinheiro na mesa quando você não atende muitos clientes você tem que atender muitos clientes e o dinheiro que ele tá deixando na mesa quando ele não vende o produto quando ele não faz o serviço extra porque ele trabalha igual um louco ele não tem tempo para conversar com ele se ele corta em 10 minutos em 15 minutos ele

não tem tempo para vender serviço não consegue entender imagina o dinheiro que ele deixa na mesa por causa disso então é isso que a galera não vira a chave a questão de tá ali quer aumentar o faturamento começa a vender produtos estúdio de venda de produtos estude eu até acrescentei os meus cursos agora uma palestra sobre vendas porque eu acho isso importante e muitos barbeiros não sabem vender e é simples única coisa que você gasta saliva é abrir a boca é oferecer entender a dor do cara e oferecer aquilo legal pra ele Senhorzinho de 60 70 anos todos os meus clientes que são de idade acima de 50 anos compra o creme de pentear na minha mão todos a maioria eu pego de toda a cartela de clientes Nessa idade que eu tenho uns dois três não compram nada na minha mão os outros como um creme e creme ele dura um mês dois meses Então você compra porque são gente de pedir o cabelo para trás é de eu gosto de usar nada do cabelo o creme eu sempre falo o creme é para hidratar o seu cabelo e realmente hidrata protege o cabelo

dele ali legal e acho que o pessoal fica muito nessa viseira né de não não atinar para isso e eu acho que vender né muita gente também ficava mas eu não sei vender mas eu não tenho peeling para isso né Eu não nasci para vender né cortar cabelo pra mim muito mais fácil e da mesma forma como a gente aprende a cortar cabelo né aprende qualquer profissão né você também aprende a vender né então é a mais uma coisa que é importante fazer cursos né buscar se especializar buscar aprimorar as vendas Porque como eles tanto falou é um dinheiro que você tá deixando na mesa né um dinheiro que você poderia estar ganhando a mais em poucos minutos ali de você abrir a sua visão né para o seu cliente entender as dores dele e evoluir cara você falou também do marketing nas vendas agora se associou ao seu curso e eu vejo muito barbeiro também ainda é não entender na força que as redes sociais têm né para que esse crescimento ocorre e o que que você tem visto em relação a isso que o pessoal ainda tá muito receoso e muito fechado em

relação a isso aparecer a investir no Instagram investir nas redes sociais eu muita gente cara eu converso com pessoas e eu falo assim cara você tem um grande potencial você corta bem para caramba Você tem muito cliente mas ninguém te conhece se divulga e não é visto é a frase clássica o que não é visto não é lembrado o tanto de gente boa que ninguém conhece e o tanto de gente ruim que é conhecido no Brasil todo porque os caras sabem fazer e eu não julgo o cara que ele é ruim e ele faz um Walmart Esse é o inteligente sabe porque ele tem uma dificuldade às vezes numa técnica ali ele tem uma dificuldade numa gestão financeira mas o cara é bom demais e tá crescendo E tá ganhando dinheiro e tá vendendo curso bobo é quem fica julgando esse cara que fica ali perdendo seu tempo julgando uma coisa que eu sempre falei ninguém é burro suficiente para ter uma viseira sem falar assim ah eu não sei fazer eu não vou fazer cara aprenda a gente aprende você sabe você nasceu sabendo uma empresa fazer best barbras crescer você sabe fazer eu

tenho certeza que até hoje você já tá todo solto consegue fazer uma uma entrevista legal mas no começo eu tenho certeza que sua barriga deve ter esfriado né Será que eu vou conseguir Será que eu vou conseguir gravar para o carro novo vou ficar sem graça de perguntar isso e aquilo então muitas pessoas na hora de fazer mais falar eu não sei mexer com esse trem de Instagram não aprenda pessoal ninguém sabe fazer nada você tem que aprender você acha que eu eu comecei sabendo gravar um vídeo gravar uns Stories conversar não eu tinha dificuldade porque eu era um cara simples é quando eu fui trabalhar principalmente no seu Elias eu eu notei que eu era um cara que tinha um vocabulário muito ruim falava muita bobagem o Zé humano tem coisa que eu não posso nem falar demais mas era meu jeito era as pessoas que eu convivia então estude uma arte busca e marketing digital como atrair clientes em barbearia o que postar você não precisa aprender às vezes com um barbeiro Lógico que tem pessoas que ensinam isso eu penso eu tenho um treinamento que chama Insta de barbeiro eu ensino o

cara desde o nome de usuário desde a biografia como montar ali um perfil otimizado para atrair pessoas atrai clientes tem gente eu vou falar isso teve eu vou falar isso de mim mesmo Eu Já Quis em algum lugar e entrei no Instagram da pessoa e não tinha o endereço e não tinha um link de WhatsApp como que você vai conversar com essa pessoa então é muito ruim é um Marte é muito ruim que alguns fazem então é buscar e estudar eu tenho missa de barbeiro que é um curso você que tá vendo esse vídeo aí me procura é para estar fazendo esse treinamento para estar conseguindo melhorar o seu Mac na nas redes sociais principalmente no Instagram e galera tem muito conteúdo gratuito também no YouTube vai lá no YouTube Não precisa pesquisar assim como como barbeiro como como barbeiro pode fazer um Stories não vai ter isso mas vai ter assim o que postar nos Stories aí uma uma digital influência ensinando Pega aquele conteúdo ali e traz ele para sua área fáceis demais meus posts no Instagram muitos eu vejo em outros lugares é dou alterado e fala assim não eu vou trazer

isso para minha área engajam muito engajam muito então façam isso busquem ter referências ali de Marte e estudar Marte também porque é muito importante na minha vida é tudo que eu conquistei cursos que eu vou ministrar a minha o crescimento que minha barbearia teve que foi através dos clientes que começaram a cortar comigo é Muitas das coisas que eu conquistei Foi por causa do Instagram o Instagram Ele me trouxe muito resultado fazer um bom Marte estudar eu já paguei curso caro de Marte para mim tá aprendendo e tá trazendo para minha área então isso aí cara me fez crescer demais vocês não tem noção você é barbeiro não tem noção o que que você tá deixando na mesa de não postar de não se divulgar eu tô aqui hoje aqui no best aqui no podcast eu já posso dar ele nas minhas redes sociais estou aqui e tal muita gente tá vendo uma coisa que é até um cliente falou comigo que é engraçado esses dias para trás mesmo o cara eu tava em casa de bobeira aí eu vi um Stories eu lembrei que eu tinha que cortar cabelo tem condição O que deve

isso você falou tudo e como é que foi no começo né a gente tá falando aqui que dá muito resultado e tudo mais mas como é que foi para você ali como você falou não agora eu preciso postar agora eu preciso até mesmo na venda dos cursos né você teve resultados bom na logo de início você passou dificuldade deu uma desanimada como é que foi Ah cara difícil acho no começo até você começar a se posicionar é difícil mas uma coisa que me facilitou e eu até dou uma dica para você que quer ser um educador um dia você primeiro você tem que ser referência para os seus clientes para depois você se refere as suas barbeiros Tem muita gente que ao contrário o cara não tem a agenda lotada o cara ele não é um bom ele não é ele não tem agenda lotada ele é um cara que peca muito no atendimento ele é o cara que não tem uma boa gestão financeira que é ensinar como que você vai ensinar e uma coisa cara é natural quem dá curso não é porque hoje eu sou um barbeiro e vou começar a dar

curso não é natural as pessoas que tem que te procurar se você quiser forçar os cursos Atenção galera igual vejo muito é tal dia vai ter curso comigo garanto já sua vaga ninguém fecha velho as pessoas que têm te procurar procurou um fechou aí ó galera tal dia vai ter curso Se você não se você não vender você já vai ter um aluno então comigo foi assim comigo foi natural eu comecei a criar conteúdo para clientes o meu foco sempre foi clientes eu postava fotos de cortes eu postava fotos minhas eu postava fotos com clientes da barbearia e que com os barbeiros via Poxa ele é um cara que ele tem hacker cheia ele co- ele faz uns cortes legais eu vou fazer curso ele é natural todo mundo é assim com o Elias foi assim comigo foi assim com muitos players no mercado foi assim então seja o mais natural possível se hoje você quer ser o educador seja referência hoje para os seus clientes poste fotos de corte poste fotos suas clientes isso tudo vai fazer com que chame a atenção dos barbeiros porque você vai começar a ter resultado e os barbeiros

ele fala assim eu quero os resultados que eles têm e que que você acha que foi importante para você conseguir né ganhar essa confiança né primeiro dos clientes e depois dos barbeiros né além de Eles já verem seu resultado ali o que que mais você acha que foi fundamental para você ter essa notoriedade no nome da sua marca e do da sua barbearia eu sempre desde antes de ser barbeiro sempre foi um cara muito comunicativo gostava muito de pessoas era o cercado pelas pessoas tinha muitas Areias da época da escola era um cara que gostava do futebol Ali era cercado de amigos e essa questão de ser comunicativo foi uma coisa legal quando eu entrei Na barbearia porque o cliente sempre na minha cadeira eu não consigo ficar calado Sabe aqueles clientes e o cão mais detesta ter cliente calado porque tem muito clientes que não gosta Aí eu respeito Eu Fico calado só que minha boca coça minha boca fica assim hum não sei o quê igual a outra coisa que eu ri demais é quando você tá sem papo com o cliente aí você a TV tá assim nó se uma baleia ele

Puxando papo com o cliente se uma atire outra baleia a chamada vai ser Baleia muito ruim velho mas minha cara é isso é minha cara é isso se eu tivesse aí eu tentei até cuidado que se eu tivesse sem assunto com cliente eu eu vou tentar puxar alguma coisa assim às vezes você fala alguma coisa que não deve entendeu então você tem que ter muito cuidado com isso então eu sou um cara que sempre foi comunicativo e essa questão da comunicação acho que me ajudou muito a ser um atrair as pessoas a atrair clientes o cara senta na minha cadeira eu tento conversar com ele e uma coisa que eu aprendi que é fundamental eu quero que vocês barbeiro leve pro seu dia a dia escute mais o que você fala é muito importante você escutar as pessoas eu atendo muitas pessoas Já atendi atendo aí a pessoas que só fala dela tudo se você se você tiver conversando muito com o cliente mais do que ele com você é capaz dele não tá gostando do assunto você tem que escutar mais deixa eu fluir cara deixa a conversa fluir eu eu uma vez eu

atendi o cliente que era economista ele ele era formou a economia era economia e eu tava assim e ele falou de Economia o que que eu André acende a economia cara nada nada aí eu lembrei que no naquele jornal de meia-noite na globo lá tem um tal de não sei o quê sabem BR eu não esqueci o nome se você quer não sei o que sabem br E ele fala sobre economia a economia do país como que tá aí eu falei assim não sei nada de Economia falei não não eu sou um cara que eu não sou eu não sou não sei muito do assunto mas eu lembro que aí eu falei com ele não eu gosto de assistir aquele Jornal da Noite para ver o que aconteceu durante o dia e ter usado em Mega lá que eu fala muito bem de Economia eu consigo entender o jeito que ele fala é fácil para quê cara o cara ficou uma hora falando sobre essa ideia sobre a história não sei o quê e eu calado eu fiquei uma hora calado ele uma hora contando a história de vida aí ele foi embora eu tenho

certeza que esse cara foi embora na rua assim ó que barbeiro legal velho barbeiro trocou uma ideia comigo Eu não abri a boca é futebol velho vocês que gosta de futebol como eu o cara gosta de futebol ele é bobo sabe porque ele é bobo eu tinha um amigo que vou ver e falou assim ó eu vou eu não sei nada de futebol e eu vou conversar com aquele cara ali um tempão sobre futebol aí chegou caiu o Fábio pega demais o pega pega fogo que o Cruzeiro fez com ele não sei o quê aí depois ele Ah sim o Fábio é goleiro né o Senhor o Fábio goleiro do Brasil ô o cara quando ele gosta de futebol ele empolga ele começa a conversar a pessoa nem sabe do assunto ela tem papo com ele é a mesma coisa que o cliente escute mais do que você fala sempre quando você escuta mais e o cliente tá falando mais o cliente está gostando do assunto agora se você fala muito às vezes tentam gostando do papo ele fica só te escutando ele inverso né Essa questão da comunicação do atendimento eu acho até que

você saber o que você falar Ah não tem vergonha eu sou tímido cara tenta melhorar isso aí faz um curso recursos para para isso você procura pessoas que te ajudam psicólogo tem várias pessoas que podem te ajudar curso de oratória isso vai fazer o que o cara que não conversa não abre a boca ele não consegue vender o cara que não abre a boca ele não consegue ter um papo Um Bom atendimento e ele acha isso normal só que isso impede ele de crescer então a comunicação acredito que seja um fator que me ajudou muito a desenvolver e a fazer a minha barbearia crescer as redes sociais crescer também que se você gosta de falar para os outros você gosta de falar para uma pessoa você fala pra mim então isso foi muito legal a gente já falou alguns erros aqui que a gente vê né o pessoal deixando dinheiro na mesa a questão do da não presença nas redes sociais é um erro que você tem visto também muito pessoal aí comentando olha um erro grande na área da barbearia eu acho que hoje essas questões de curso né cresceu muito todo mundo da

curso só que muitos barbeiros se fecharam para isso Ou assim não cara tem tanta gente dando curso que é difícil você saber qual curso é bom só que quando você se fecha por conhecimento é difícil você crescer e eu falo isso por experiência própria da pandemia eu eu foi um cara não parou os cursos parou os eventos e eu desde eu com igual falei com você como um ano e meio de barbearia eu tinha 20 certificados hoje Se eu te contar você acha é mentira por causas online dos presenciais mas eu tenho 10 anos de profissão Eu nunca parei de fazer curso nunca parei e nunca vou parar porque no dia que eu parar de estudar eu paro de crescer eu vou te dar o exemplo da pandemia da pandemia acabou os cursos presenciais e eu gosto muito dos cursos presenciais porque né work ele faz o Network com cliente ali com outros barbeiros com players grandes no mercado e acabou na pandemia como isso Acabou a pandemia parou os cursos presenciais eu foquei no online só que como a minha barbearia teve que fechar uma época foi um momento muito difícil um momento difícil

é financeiramente para muita gente eu dei uma pausa em cursos também eu fiquei tipo assim uns quase um ano sem fazer um curso eu eu acho que parece que eu andei para trás porque eu sou um cara que eu tava acostumado toda hora eu tava aprendendo uma coisa nova tava lançando um trem Na barbearia tava fazendo treinamento novo vi uma coisa legal que alguém tava fazendo em otária começava a fazer na minha é igual agora eu comecei com as ações é o sorteio de máquina coisa para barbeiro que muita gente faz com o carro com isso com aquilo eu comecei a fazer para barbeiro aí tá dando super certo ontem eu consegui abençoar um cara lá do Rio Grande do Sul fizeram um pisquei então para ele ele ficou grato demais é então parece que esse tempo que eu não estudei Eu parei no tempo e o erro que a maioria dos barbeiros Cometa é isso a maioria eu acredito que seja por causa desse tanto de curso eles estão com medo de fazer curso e fazer o curso ruim e não estou o cara que não estuda e para no tempo não tem jeito

Tem gente que bate no peito que o orgulho fala assim tudo que eu faço na minha barbearia eu aprendi sozinho cara isso não é orgulho velho zero orgulho sabe porque porque então você pegue muita coisa que você nem sabe eu tenho certeza que se uma pessoa passa um dia com ele analisando o tipo de trabalho dele Ela tem umas seis dicas para ele melhorar agora quando você tá no curso você escuta de você escuta de outro aqui eu acho conversando com você ou você já falou umas coisas que foi mó legal que já abriu primeiramente Olha isso aí que ele falou é verdade mesmo então tudo a todo momento a gente tem que estar aprendendo porque senão a gente não desenvolve a gente já começou a sua criança e para o resto da vida tem que ser você tem que ter a mente aberta para aprender muitos barbeiros não estão com essa mente aberta e é por isso que estão parados o tempo não consegue crescer uma arte não consegue se desenvolver a barbearia não consegue se desenvolver profissionalmente como pessoa porque é tão fechado eu sempre mente aberta para tudo o melhor curso que

eu fiz na minha vida foi um curso de desenvolvimento pessoal como ele ou Carvalho é protagon o hino Carvalho ele é um cara que eu tinha ranço dele que eu achava ele mala porque o cara Carrão ele é o tipo de cara que eu odeio postando foto de carrão é todo bombadão o negócio de academia eu detesto esse cara eu não gosto de academia eu faço um funcional Você morou de academia gosto de bola não gosta de academia é esse negócio de carro eu nunca fui um cara pegada carro eu gosto de moto e tal mas eu dou sua pegada esses três materiais eu quero ter meu sonho é ter uma casa muito bonita mas eu não sou aí tem uma BMW Carrão igual muito sonho e o cavalo era um post eu não vi ele como referência e ele é um cara que fala sobre desenvolver pro pessoal não sei se você conhece ele ele é o cara muito top aí eu fui desse pro apagou foi a minha esposa minha esposa insistiu para mim e tal a gente estava num momento que que relacionamento a gente não estava no momento legal também mas

uma vez jogando ele para cima né mas uma vez a gente foi eu saí de lá no final do curso você cria um negócio lá que eu esqueci o nome você lembra como é que é o nome é arquétipo você cria um arquétipo que é um exemplo de homem de ser humano de Deus que você quer ser você cria por exemplo o arquétipo do Deus grego Eco do Hércules não sei o que lá aí você cria o arquétipo E você tem que são atitudes que essa pessoa toma coisas que ela faz na vida que você tem que fazer igual para você desenvolver como ela sabe quem foi meu arquétipo o Wendell Carvalho por quê cheguei lá o cara velho tudo que ele falava era só tapa na cara só tá eu achava que eu conhecia muito a gente tem que se desenvolver eu tenho muita vontade de fazer um acompanhamento com psicólogo que eu vejo que muitas pessoas que fazem são pessoas claramente muito aberta pra muitas coisas ou ainda o cavalo ele me ensinou muita coisa ele é aquele dia lá eu saí de lá um novo homem pra minha esposa eu saí de

lá o cara mudado profissionalmente as coisas que eu tinha que travavam ele fala muito sobre crianças limitantes as crianças que me travavam aquela questão da Cipó morrer pobre não existe cara você tem que correr atrás ele era pobre a esposa dele era pobre e eles conseguiram se desenvolver e essa questão dos cursos galera barbeiros abram a mente de vocês não parem de estudar minha vida mudou por causa dos cursos Ah ele saiu da sua vida mudou porque você trabalhou com seu Elias sua vida mudou porque você trabalhou do swing você recebeu a oportunidade sua vida mudou por causa disso por causa daquilo sua vida mudou posso falar marca aqui sua vida mudou porque a força semente patrocinava você ganhava não sei o que lá na força a galera que gosta de você te coloca nos cursos não cara minha vida mudou por causa de mim eu sou grato ao seu Elias eu sou grato Alexandre a Joyce bem pela sua oportunidade eu sou grata todo mundo que passou na sua minha vida eu sou grata a minha esposa tudo que ela fez na minha vida mas se não fosse eu tem muita gente que trabalhou

com seu Elias e ninguém conhece Tem muita gente que foi no curso do Wendel igual eu fui e não absorveu o conhecimento com absorve lá e tá na vida ruim até hoje tem muita gente que a força meio patrocinou foi um educador da força e ninguém sabe mas ninguém sabe onde é que tá então as coisas são por barbeiros que trabalharam comigo e saíram montaram sua própria barbearia imagina se lá no futuro esse cara tem isso por causa do Elisandro não ele tem isso por causa dele o mérito é dele então o mérito é meu de tudo que eu sou grato a todas as pessoas passaram na minha vida me ajudar mas o mérito é meu então você barbeiro se sua vida tá ruim a culpa é sua irmão agora se você quer que sua vida melhor dá tempo independente da idade que você tem corra atrás estude faça curso que você vai se desenvolver demais com profissional Só depende de você né como o Alessandro falou eu acho que também muitos ficam aí procrastinando né falando Ah não vou deixar para o mês que vem eu fazer Ah não Ano que vem eu faço

né aí começa o ano cheio de Beta não esse ano vou fazer isso vou fazer aquilo vou fazer um monte de curso e tal tal e só vai adiando né só vai postergando e não se limitem também a fazer só cursos de técnica né como você falou aí um dos principais né Talvez o principal aí da sua vida falando de desenvolvimento pessoal então provavelmente também para isso né de vocês crescerem como pessoa que isso com certeza vai refletir na vida de vocês cara eu acho que Outro fator muito importante que a gente tem visto né além de tudo isso que a gente já falou né que o pessoal às vezes fica muito invejando né os outros né O vamos dizer desqualificando o seu sucesso né Igual você comentou aí para andar não só porque ele trabalhou no seu Elias que ele que ele agora tá desse jeito e tudo mais que ele é conhecido né E mais uma vez eu queria reforçar isso não tenho inveja né Principalmente do colega de profissão de vocês né entendam o ciclo de barbearia Entenda os barbeiros né como colegas que estão ajudando a evoluir a profissão ajudando a

elevar o nível né do setor levando mesmo tudo que vocês têm para fazer é só agregar mesmo então compartilhe mesmo conhecimento estejam juntos né deem as mãos mesmo para que todo mundo possa evoluir junto cara para você o que é ser barbeiro cara eu eu sou um cara que eu sempre amei a barbearia Sempre fui apaixonado por barbearia deixa eu comecei o curso de barbeiro comecei a ver vídeo no YouTube comecei me apaixonar ficava horas e horas e vendo cabelo cabelo na rua olhando cabelos a gente cabelo tá ruim cabelo tá bom encarando o cabelo dos outros cara ser barbeiro para mim é uma realização de sonho de conquistar sonhos e a gente tem que ter isso na nossa profissão tem gente que corta cabelo e não gosta não vai por outra área cara sabe por quê Porque quando você não você faz o que você não gosta você faz mal feito Ah mas eu tenho que fazer para sustentar minha família Cara tenta fazer uma renda extra e outra coisa até essa outra coisa dá certo você sair da barbearia mas não fica não que é pior para você é pior pro barbeiros muito

desses barbeiros que desqualifica outras pessoas são gente que não consegue crescer e querem criticar e não consegue crescer às vezes porque não gosta da área velho para gente qualificar alguém porque você não gosta daquilo ali então ser barbeiro para mim hoje é a realização realização de um sonho e tem gente falando assim ah é sonhar ser barbeiro cara eu vou não vou mentir para você quando eu era eu tinha eu era novo meu sonho era ser barbeiro eu tinha outro sonhos só que a vida me colocou na barbearia quando ela me colocou eu prometi para mim que eu seria o melhor barbeiro do mundo com meus clientes e me dediquei me dedico pra isso e é isso que tu transformou na minha vida se você não ia entrar no negócio de cabeça pular de ponta e entrar de cabeça no negócio nem entra porque senão é pior para você tem gente que eu vejo o cara é barbeiro hoje amanhã ele roda no Uber depois ele roda Ele trabalha com outra coisa depois ele tá trabalhando fechado o cara nunca para como é que esse cara vai crescer e nunca vai se sentir realizado né

nunca vai sentir realizado e sabe o que que é pior o tempo passa passa e passa chega um momento que esse cara ele pulou de galiná ele pulou tanto de galho em alho que ele não conseguiu se desenvolver ele não tem raiz em lugar nenhum que que esse cara vai ser provavelmente ele vai o cara ele pode ter 50 anos de idade se ele cada e ficou no lugar se ele for para o outro lugar ele vai chegar lá ganhando a base ele vai chegar no lugar no começo mesmo ele tendo 50 anos de idade Então mas se você é um barbeiro igual uma muito barbeiro faz isso sem barbeiro que hoje tá no barbearia amanhã ele tá de outra depois ele tá de outra Ele não cria raiz em lugar nenhum cara não fica pulando de galho ligado nãoutro a sua logo se você não tá satisfeito com aqui aí você foi pra outro você foi para a Rua você o problema não é as pessoas as barbearias que você trabalhou o problema é você monta a sua para você fazer do seu jeito e criar raiz ali porque cada pulo que você dá

assim você anda dois anos para trás Então você não vai crescer então Barbie sem barbeiro pra mim é uma realização cara é uma realização foi onde eu consegui comprar meu apartamento foi eu consegui ter o meu próprio negócio consigo sustentar minha família minha esposa a minha filha dá o que minha filha precisa então eu sou grato demais a barbearia eu sou grato mas por ser barbeiro você colocar na sua oportunidade na minha vida e tem certeza que que a barbearia vai me dar muita coisa muita coisa mesmo cara eu tenho 30 anos de idade eu tô eu acredito que eu tô começando tem muita coisa para realizar ainda eu eu imagino isso é bom demais se viver a sua vida imaginando que quando eu tiver com 50 nós eu vou estar vou ter conquistado muitas coisas tem gente que tá com com já nessa idade e tá pulando de galho ligado Então comece não tem idade cara se você tiver 50 40 70 anos você gosta de barbearia entra com de cabeça ou que que vai dar tudo certo aquela empresa tem uma empresa de de frango aí que é famosão esqueci o nome dela

que tem sedes aí até aqui no Brasil o dono dela começou a empreender com mais de 60 então mais de 60 hoje o cara é milionário ele ficou milionário depois de 60 até isso ele era um cortador de frango normal então dá para acreditar acredito se eu sou isso você é novo se você barbeiro você tem 18 17 anos é agora é sua hora que ele é a raiz cara vai com tudo tem cara boa aí com 17 anos fico imaginando esse cara com 20 vai ser um monstro da barbearia e cara não perco tempo né hoje a coisa mais valiosa que a gente tem na vida é tempo né então quanto mais você ficar adiando quanto mais você ficar por ter postergando né Quanto mais você ficar perdendo tempo você tá perdendo grandes oportunidades de crescer na vida de evoluir de ser grande de alcançar os seus sonhos e falando de sonhos novamente né Quais são os seus próximos sonhos aí suas metas o que que você quer é concurso com a barbearia você pensa em Abrir oportunidade ou não olha eu eu tinha muitas coisas mudaram nos últimos meses aí tá vendo muita

coisa legal é mudança de vida mesmo que vai ser muito bacana a gente não pode falar nada ainda né amor mas tem muita coisa legal que vai vir aí novidades vocês podem podem esperar que nos próximos meses aí vocês vão escutar falar muito do meu nome e de uma coisa muito legal que vai acontecer nos nossas vidas aí a gente tá se planejando como tudo da vida a gente se planeja para as coisas eh a barbearia hoje atualmente Estou trabalhando sozinho porque o Barbeiro estava trabalhando comigo saiu chegou o final do ano eu tentei arrumar outra pessoa infelizmente eu não consegui um barbeiro nos padrões que a gente que a gente preza né apareceu alguns mas não deu certo é aí eu fiquei fechei o ano sozinha porque eu falei assim ah vou fechar o ano sozinho porque eu não vou ter tempo para treinar alguém então fechou mano sozinho é minha esposa que cuida da injeção da barbearia a gente vai começar o ano e vamos procurar um outro barbeiro pra pra tá trabalhando comigo é mas a gente tem um projeto de fazer barbearia crescer quem sabe montar realmente outras unidades da da

conceito mas pra ser bem sincero No momento eu não penso em ter muitas unidades eu na minha visão de negócio eu acredito que eu posso um dia mudar essa cabeça mas eu prefiro ter um lugar top uma estrutura show de bola em um local só do que ter várias unidades mais ou menos o que que é isso eu vejo muito muito mesmo barbearia que tem cinco unidades as cinco unidade com duas cadeiras o três cadeiras às vezes dá mais dor de cabeça para o dono do que se ele tivesse uma unidade com 10 então eu acredito que na minha visão de negócio você gerenciar uma empresa muito difícil imagina se gerenciar cinco você não consegue estar em todos os lugares ao mesmo tempo então na minha visão eu posso estar errado tá galera isso é minha opinião eu com questão de opinião eu sou meio polêmica vocês vê lá no Instagram lá que direto eu posto o negócio mas é aquele negócio é minha visão Às vezes a minha visão ajuda uma pessoa que tem dúvida não é isso tem duas cadeiras não a tua autoridade não cara vai para terceira para quarta muda do

local vai para o ambiente maior montanha estrutura top para caramba Então essa é a minha visão de negócio eu na minha cabeça hoje eu quero ter só uma barbearia mas uma barbearia top referência sem contar e graças a Deus hoje a gente já somos referências em contagem é uma barbearia reconhecido pelos clientes como uma das melhores reportagem isso para minha gratificante é então eu quero fazer com que a empresa cresça é que essa a Conceito Barber Club amplie mais no mesmo local ali eu quero ter ajudado Pessoas igual a gente já ajudou muitas pessoas a decorrer tinha Carina que trabalhava com a gente na recepção agora Ela saiu há poucos dias foi para a área dela que ela tava fazendo faculdade então foi uma pessoa que a gente ajudou conseguiu ajudar muito é tem outras pessoas outros barbeiros que passaram pela barbearia é a gente conseguiu ajudar a conseguir moldar ele a ser um profissional melhor e hoje estão ganhando dinheiro e outros lugares estão com a própria barbearia eu ganhando dinheiro em outros lugares eu fico muito feliz de poder ajudar pessoas as pessoas que a gente ajuda nos cursos eu quero continuar fazendo

isso ajudando pessoas a se desenvolver quando você recebe uma mensagem no cara falando assim poxa lição é aquela dica que você me deu cara foi um diferencial na minha vida você acredita que agora os clientes estão ouvindo mais tô conquistando mais Clientes estão crescendo isso é gratificante mais coração né Essas reações as ações que a gente tá fazendo o sorteio lá a gente cobra 40 centavos que é o valor mínimo com a empresa para a gente não tomar prejuízo mas a ideia é dar um brinde para o cliente aí você manda mensagem para o cara liguei para ele de vídeo amigo você ganhou e tal ele eu ganhei Eita eu quero dinheiro quinhentão não sei o que que eu já tenho uma máquina aí fiz o pix para ele da hora a felicidade das pessoas e saber que tipo assim com a vida uma decisão uma atitude que foi a minha há tempos atrás e continua sendo hoje tá impactando a vida de várias pessoas isso é gratificante mais e é isso eu quero continuar nos próximos meses aí mas tem muita coisa legal vindo a gente tá com muitas novidades pra 2023 aí você

que não me acompanha me acompanha lá no arroba barbeiro Elisandro é a gente vai postar muita coisa legal eu tenho certeza que nos próximos meses e os próximos anos aí eu vou ajudar ainda mais barbeiros a realizar os sonhos deles show demais eu acho que muita gente também fica é receoso até com raiva né quando um barbeiro sai vai abrir a própria barbearia né mas eu acho que é muito legal essa visão sua né de ajudar e transformar a vida das pessoas né que passam ali com você e tudo e voltando então um pouquinho só até a barbearia ali né você pensa em expandir mas primeiro tá com tudo rodando 100% né E quais seriam os outros Pilares a gente comentou da Excelência né de sempre prestar um serviço de qualidade Quais são os outros Pilares que você tem ali dentro da barbearia padrões processos pessoas eu acho os três pesos aí são importantes aprendi esses três pesos assistindo série o sócio não sei se vocês barbeiros já viram aí o sócio ele chega numa empresa ele é um cara que ele chega ao investidor ele entra dentro da empresa e ele chega e fala

assim ó ele fica um dia lá na empresa e vê tudo de errado que tem na empresa no final do dia se ele gostar da empresa ele fala assim ó eu quero eu quero eu dou 300 mil nessa empresa por 51% dela ou por 49%. mas a gestão vai ser toda minha pessoas processo e produto ele chega ele muda essas três coisas o que eu faço a minha empresa hoje não tão eu agora eu já tenho que dar o médico para quem faz melhor que a minha esposa gleisiane ela é a gessoura da barbearia as pessoas a gente procura ter os melhor time possível e é por isso que eu não coloquei um barbeiro ainda apareceu pessoas mas apareceu apareceu muita gente que não tem um perfil que não atende as expectativas eu brinco muito com os meus clientes Na barbearia os caras nem acreditam mas igual eu falo já teve caso de barbeiro que queria trabalhar comigo mas falou que não trabalhava sábado mas tranquilo é adventista do sétimo dia né Deve ser questão de religião é religião né não é que eu gosto de dar um rolezinho sexta-feira sério mesmo é piada né

é piada então não existe isso então as pessoas são muito importantes é a gente foca nisso e tem as melhores pessoas possível é processo Olha a importância de você ter um local pequenininho e desenvolver nesse local não adianta eu colocar um milhão na sua conta hoje 500 mil e sem montar barbearia dos seus sonhos então tinha muita gente falando assim Alexandre nesse final de ano se eu ganhar na mega-sena eu vou te dar uma barbearia os clientes brincando comigo vou te dar barbearia mais top para você pensar hoje se o cara me dar a barbearia mais top que eu imaginar eu consigo gerir Sabe porque a minha pequenininha Ela é bem ingerida ela tem uma boa gestão ela além de gestão ela tem produtos legais que é o produto dentro da barbearia é o corte de cabelo é o atendimento é os produtos que vendem Então esse é o produto da barbearia os produtos são bem ingeridos A gestão da barbearia é muito legal que a minha esposa que faz ela é formada de administração ela for boa administração para cuidar da barbearia e até as pessoas eu ela hoje no caso e a gente

vai arrumar mais pessoas que sejam boas tudo isso perfeito então se eu monto a barbearia com 10 cadeiras hoje eu consigo administrar Mas sendo bem sincera se fosse há uns anos atrás há uns cinco anos atrás eu iria quebrar porque eu não ia saber lidar com pessoas eu não ia saber eu não teria processo que os processos a gente vai desenvolver com o tempo hoje eu tenho então você que tem uma barbearia quer crescer quer se desenvolver foca nessas três pessoas se tiver uma pessoa maçã podres no seu time cara ele já mata seu time corta essa maçã e o Personal atrapalha muito seu time vai crescer segundo os processos que que é os processos é padrão ao cliente chegou atrasado como é que é atende não atende fica na dúvida ou tem um padrão a empresa né deixar bem fácil na mensagem do WhatsApp a gente já explica pro cliente ó 10 minutos após 10 minutos não não é não garantimos o atendimento então ele sabe se ele chegar depois de 10 minutos Talvez ele não vai ser atendido vai depender do tempo vai depender da pessoa se eu consigo fazer ela e não

atrasar o próximo porque senão você não tem padrão Aí você o cliente chegou ele tá marcando 3 horas ele chegou três e 20 se atendeu 20 minutos só que você não consegue cortar o cabelo 20 minutos aí você atrasou mais 20 minutos o próximo que é a primeira vez que o cara tá aí na barbearia chega lá e você demora 20 minutos para atender ele tinha um compromisso depois e aí já queimo o filme então é até padrão o processo dentro da empresa hoje a gente poderia ser a da empresa isso aí processo de pagamento de conta padrão de atendimento aí eu tenho até listado assim ó como atender o cliente primeira coisa que eu vou falar como que eu vou fazer quais assuntos eu vou abordar Então você tem que ter isso o processo do corte de cabelo quem faz curso comigo sabe eu tenho cinco passos por onde eu começo um corte por onde eu termino que ele faz curso comigo sabe que eu tenho um processo e isso me ajuda a fazer o corte mais rápido então você tem que ter isso em produto que é a questão que a gente falou

os pilares atende minha postura gestão Marte Isso é o que você entrega para o cliente o produto tem que ser top Então você tem que focar nisso aí pra pra você desenvolver barbearia e é o que é o foco e é o que faz a minha barbearia crescer bastante aí legal show demais então pra gente finalizar Qual que é o último conselho aí que você tem para dar para os barbeiros seja tá começando seja para quem já tá aí qual que é a última lição aí que você tem entrada pessoal barbeiros busquem se desenvolver cada dia mais não somos burros com viseira que a gente tem que olhar só para frente você tem que olhar amplo você tem que ter uma visão Ampla de conhecimento de buscar conhecimento é eu como eu falei no podcast aqui que o curso de desenvolvimento pessoal que eu fiz foi o que mais mudou a minha vida eu não foco só no cabelo não foco só no cabelo eu não foco só no Marketing eu não foco só no atendimento eu não foco só na postura eu foco é o conjunto você tem que desenvolver cada dia mais hoje

você tá Você tá Qual que é a sua maior dificuldade é a técnica então vá buscar curso de técnica vai fazer curso com pessoas que fazem bem um corte de cabelo Ah elissa não consigo fazer um marketing é o que você falou não estude só uma coisa busca estudar Marte busca estudar marketing digital ali entender o que postar Como postar é ah minha dificuldade Alexander é a gestão eu ganho dinheiro mas eu não sei lidar com meu dinheiro então faça com gestão tem o SEBRAE que ajuda a gente para caramba cursos gratuitos Então pessoal a dica que eu dou para você desenvolva os pilares que vão fazer a sua vida mudar da minha visão os maiores Pilares que me fez o desenvolver foi meu corte de cabelo a minha técnica o meu atendimento meu Marte a minha gestão é a minha postura profissional desenvolver esses Pilares me fez crescer muito profissionalmente e se você desenvolver eles também você vai crescer muito como barbeiro show demais bom Pessoal esse foi mais um episódio do best burges podcast espero que vocês tenham gostado dicas valiosíssimas aí com Elisandro espero que vocês cresçam mesmo que vocês escutem a

mensagem né são coisas que vão ajudar mesmo na vida de vocês ajudar vocês a alcançar o sucesso profissional e também na vida pessoal irmão mais uma vez obrigado e eu agradeço obrigado por todos aí Claro a gente tá aqui hoje na estrutura muito legal que a do best Barbie você pode Cash aqui maravilhoso que está ajudando muito eles a crescer e uma coisa que eu queria falar com vocês eu conheço essa empresa não é de hoje conheço essa empresa já bastante tempo e uma empresa que não ajuda você é somente a agendar clientes da sua cadeira a fazer uma gestão ali de agendamentos ela é uma empresa que te ajuda financeiramente também e eu vejo que muitos barbeiros pecam nessa questão financeira cara você às vezes não consegue Ah eu trabalho sozinho ele senão não tem tempo Olha esse aplicativo aqui ó Dá uma pesquisada lá best Barbies ele não te ajuda somente a agendar cliente até uma gestão de agenda ali ele também te ajuda na questão financeira tem ou é um aplicativo completo que pode ajudar você a desenvolver então pesquisa lá sobre o best Barbies é uma empresa top é uma empresa

com o conceito porque a gente conhece não é de hoje que os caras estão começando então é uma coisa que eu indico você quer crescer quer desenvolver essa barbearia o lado financeiro e a organização é muito importante e o best Barbie está aí para ajudar vocês viu parabéns pelo trabalho que vocês fazem a gente agradece aí os elogios as indicações estamos aí realmente para ajudar vocês a alcançar um nível além do que vocês podem Na barbearia né auxiliar e vocês Nas questões é para vocês não perderem tempo inclusive né ali ou o dinheiro né então a gente tá aqui para auxiliar mesmo e ajudar vocês a alcançarem o nível bem maior Matheus pra gente fechar pega essa caixinha aí pra gente oh oh pode Vamos abrir aí ó você vê com a galera tem um quadrinho aí pra você pendurar lá na barbearia wear the best barbers são os melhores barbeiros mesmo a caneca aí para você tomar um café da manhã camisa adesivo é show demais Lembrar sempre da gente também lá na barbearia Valeu Eu que agradeço bom pessoal então a gente fica por aqui espero que vocês tenham gostado nos acompanhem nos

assista no YouTube Spotify e tamo junto Valeu pessoal sucesso para vocês tamo junto Come comigo [Música]`,

  summary:
    "Episódio 4 da Temporada 2 do BestBarbers Podcast. Elisandro Oliveira compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
