import type { VideoContent } from "./types";

export const podcastmoises_nazare_ep06: VideoContent = {
  slug: "podcast-moises-nazare-ep06",
  youtubeId: "eYhmwx8yHrI",
  title: "BestBarbers Podcast com Moises Nazaré — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 6 da Temporada 1 do BestBarbers Podcast com Moises Nazaré. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "moises nazaré",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2022-08-11",
  duration: "48:56",
  category: "Podcast",
  tags: ["podcast", "temporada 1", "entrevista", "gestão", "barbeiro"],

  transcript: `Oi eu tava no momento financeiro tão difícil na minha vida e teve um dia que eu cheguei em casa sim Liguei meu apartamento e Olá senhoras e senhores caríssimos ouvintes do best vines podcast sejam muito bem-vindos ao nosso sexto Episódio da nossa primeira temporada eu sou Gabriel Rangel um dos donos aqui do dente da Lei e tive o prazer de entrevistar nesse episódio Moisés Nazaré ele quer um dos principais gestores do grupo seu Elias tem muita mas muita informação valiosíssimos que eu acredito que vai mudar a sua vida foram testemunhas em tremendo de vida eu acredito que vai impactar você muito também e olha que ele vai ter descontos especiais para você então escute até o final e eu espero você escutando com a gente esse sexto Episódio da nossa primeira temporada Senhor e senhores barbeiros de barbeiras de todo o Brasil sejam bem-vindos a mais um podcast aqui do mestre palavras hoje eu tô aqui com Moisés Pois é seja muito bem vindo uma honra ter você aqui com a gente eu acho que para o pessoal se contextualiza de tudo que você faz é bom ser apresentar a música a mulher e algumas

coisas lá no seu Elias da palestras Então é bom pessoal te conhecer melhor Fala galera beleza bem eu sou o Moisés Moisés Nazaré meu nome eu falo olhando para lá eu posso falar olhando para você ela também apresentando e talvez lá mas eu hoje né trabalho na no grupo seu Elias né Eu sou produtor do seu eles vamos dizer sim eu vendo eu vendo uma realidade da música né eu venho ajudar e são músico profissional né É hoje eu já não existo mais essa parte mas investir grande parte da minha vida na música e no interior de Minas sobre a cidade chama Lavras do interior de Minas em vim para cá em 2003 cara quando eu passei na UFMG na época sou formado em música sorteio música lá na UFMG vir para cá eu falei com uma parte da música durante muito tempo muitos anos para que eu migrei o aniversário é hoje hoje eu sou produtor do seu Elias e fazendo a produção de ser linhas a gente vamos assim eu acumulo funções né eu faço mais coisas né eu faço a parte da produção dos eventos menores participou também na produção dos eventos

maiores igual barba dei com a fez aquele sempre perguntou mesmo que foi o Barber Day driving né pra galera chegando de carros e tal e faça o parte também da organização não sou os dos eventos maiores não sei o que o grande sozinho e organiza os eventos menores Mas além disso eu trabalho na parte das estratégias de vendas dos cursos presenciais e negociação de palestras enfim da venda do próprio seu Elias mesmo né do nome seu Elisa ele quando alguém eu quero ir para o shopping tem quem faz todo esse processo de negociação sou eu ninguém faz esse filtro Na verdade essa para saber se realmente cola de eu não se você é um cara que vale a pena sou eu em resumo e sou eu é o cara que ver e da música migrou para da barbearia e graças a Deus cresci na área da barbearia e tem feito bastante coisa e desde o Conselho Nacional da barbearia Olha já tem 16 anos cara seis ou sete na cama por aí é por aí então toda ascensão aí do seu Elias você teve praticamente presente grande parte não é gay no começo peguei no

começo legal bom então o homem vai revelar e também o segredo das vendas o mestre da cenas bíblicas você vai Elias vai falar um pouquinho para gente hoje mas antes da gente ir para essa parte mais específica mas técnica Moisés é esse mundo vamos dizer assim da barbearia ele é um mundo muito grande hoje arrumando as pessoas com mais relevância delas é o seu Elias e o grupo você trabalha e essa parte da organização dos eventos como é que funciona ali no grupo Como é que você trabalha ali no seu dia a dia como é que tá ali organizando cada workshop organizando cada evento presencial como é que o pessoal também pode ir a nesses eventos Eu acho que é uma questão ou a ser explicar Aí que muita gente tem interesse né Sim claro bem é e vamos dizer assim a gente a gente mudou um pouco das estratégias né antes a gente organizava o nosso próprio evento O que que a gente fazer isso porque não sei a ver no mercado ainda pessoas com a capacidade técnica de organização de eventos na área da barbearia e o Elisa um cara muito exigente cara

ele detesta Gambiarra Gambiarra não é com eles ele é um cara assim bastante focado na qualidade e isso é verdade viu você avisa galera olha o Elias por fora essas aquilo ali é Marcos não é só uma reunião só o marqueteiro não ele realmente um cara aquilo que se preocupa muito com a qualidade e entrega às vezes vamos supor o evento Estava dando um pouco lucro né vamos assim dizer e ele não faz querer não esquenta a cabeça a colocação da grana ele esquenta a cabeça com a experiência do aluno que tá lá então não começo nós organizávamos os nossos próprios eventos então a gente que escolher o hotel Ideal a sala de hotel Ideal porque nós o público e era a galera você veio antes que realmente estava com muita vontade de aprender quando o começou na verdade os as ideias de workshop e o nosso custo ele era um era um custo alto o cara para vim fazer o shopping com seu eles na época ela quando eu entrei lá começo lá atrás que é onde tudo começou gostava r 800 é o cara participar porque aquele tipo de informação Quando ele estava

dando ali pra galera eu quero tipo de informação que não se havia tão fácil no mercado assim dá para ver areia tá ainda não se é tão fácil ter esse tipo de informação com a autoridade que o Elias entrega nos orquishop dele que o Elias não é só bom Tecnicamente Ele É extraordinário Tecnicamente mas ele é um empreendedor nato bom então assim desde trás quando a gente organizava esses eventos a gente escolhia a sala ideal o hotel Ideal o tipo de cadeira para tá na sala ideal a gente sempre preocupou com isso o tipo de buffet que a gente ia entregar para os alunos que imagina só você vai pagar r 800 para tar no evento você não quer sentar na cadeirinha de plástico né que tá só fazendo mas tipo você não vai sentar na cadeirinha de placa não você não pode chegar no evento você tá pagando r 800 e quando uma coxinha fala assim coxa coxinha velha você não pode você não pode oferecer esse tipo de produto coerente com preço que você cobra então assim a gente aumentar o nível para gente conseguir estabelecer um nível do negócio lá atrás nós

organizávamos nossos próprios eventos e ficava muito atento a esse detalhe por exemplo muita gente e em várias Octopus naquela época mas às vezes tinha lá 300 pessoas na sala a sala uma sala curtinha e p e Quem sentou dos 50 para trás não enxerga mais nada não chegava né Mas nada a gente que veio com essa ideia de botar televisão negócio colocar painel de LED no negócio botar uma transmissão ali próximo ali o cara conseguir entender melhorar a experiência do cara limitar a quantidade de pessoas botar preço botar o tipo de material que vai ser entregue personalizado então a gente veio trazendo Essa realidade quando começou a ter no mercado mais galera organizando evento na área da barbearia foi aonde a gente começou a aceitar algumas contratações mas para isso a gente filtrava porque eu quero precisava estabelecendo uma conexão com a gente e mostrar também que ele conseguia fazer no formato na verdade não que ele conseguia fazer conseguir fazer fase possa que ele tinha disposição para fazer no mesmo nível que a gente entregava antes de uma Seresta e a pessoa começou a conseguir ofertar a oferecer na verdade esse tipo de qualidade

na organização do evento a gente começou a aceitar algumas contratações Bacana Então assim esse mercado a barbearia foi crescendo lá atrás a gente foi Pioneiro nessa questão então a gente lançou muitas coisas que a gente viu hoje o sendo usado no shopping de barbearia pra gente que lançou a ideia da experiência do carro então a gente vem com essa essa crescente organizar isso é muito legal é muito bom porque você não se trata só de você ter uma pessoa ideal organizar sala tipo de viver de buffet do mar se trata de todo um contexto uma percepção de todo um contexto aonde você vai entregar uma experiência do aluno que tá ali ele tava conversando sobre copyright né Isso tudo é Coca sim é o a experiência do cliente a forma com que o cara vai comprar o seu evento a gente hoje nós usamos o sim e a verdade agora quem tá me ligando para ir buscar é uma plataforma já de educado de mais complexa um pouco né mas antigamente por exemplo a galera da barbearia não sabia nem qual plataforma para poder ir se usar para ver se fazia ali na caneta na

mão então às vezes botaram só no computador é para você fazer é mas compra aumentar essa experiência do aluno a gente já implantou o nosso sistema não plataforma essa ideia da plataforma essa ideia de formado e venda do painel de LED câmera isso toda a gente veio a gente que viu lançando essa ideia no mercado barbearia aí Lan É assim É uma sensação exclusividade uma sensação assim eu posso falar porque o Barbie dry vir eu fui Oi e aí desde o momento que você ali na fila você já sente o negócio diferente é o clima negativo já é diferente aí quando você entra assim ver aquele palco todo iluminado animação do pessoal assim é uma experiência única mesmo para quem vai e vale cada centavo né então o pessoal aí que conhece todos os ar Medeiros outros dizer assim né É acho que não tem noção né do que que envolve desde como você falou o buffet ou o brindezinho também tinha até eu acho que era um perfume para o carro tem esse é o nível de detalhes da experiência se entregam então fazendo e ainda fazem né já fizeram e ainda fazem essa

ruptura muito grande a competitiva né Vamos colocar assim diferencial muito grande nesse mercado muito legal e o que que levou você assim um pouco antes a sair do mercado da música transicionar e para esse mercado da barbearia cara eu vou responder brincadeira obviamente mas acho que a ideia a ideia eu acredito em ciclos Eu acredito em Eu acredito na nos propósitos de Deus o crente acredito nessa nessa ação de Deus na vida da gente apesar de ter me formado em música é tocada com muita gente famosa deixa eu dar um spoiler aqui ok éh aqui com André Valadão durante de 12 anos se não me engano gravei os principais alvos do André Valadão grava com Diante do Trono Gravei com Thalles Roberto aquele aquele DVD Uma História Escrita pelo Dedo de Deus né Não só ele deve acho uns três alvos com o contato é Gravei com Matheus e Kauan aquela música o nosso Santo bateu o amor da sua vida sou eu os trompetes aquela música ali o nosso trio de metais né era o Brasa Trio na época e a gente gravou cara Jota Quest já vamos com Jota Quest também a último

do último álbum deles acústico ao vivo acústico a gente tá lá além de outros álbuns que nós gravamos também estude com ele agora vamos até a tela especial de Natal Roberto Carlos 2015 pela metade ficou muito muita coisa legal e antes de agir também como com César Menotti e Fabiano enfim eu vivi muito essa parte da música assim de um jeito bastante intenso sabe da minha vida inteira foi na vida inteira não né a grande parte da minha vida foi construída focada nisso nós temos um trio de metais é que chamava Brasa Trio era eu o Diego Fabrício sax trompete trombone e Trio de metais não é um negócio que você acha sim fácil no mercado é porque envolve muita muito muita conexão envolve muito bem fim envolve muita coisa para você conseguir formar um trio de metais e nosso time decidiu de metais então acaba que a gente tinha uma demanda de trabalho porque não é apesar de ser pouco usada nas metais era uma demanda grande era uma demanda Teoricamente grande porque a galera focava na gente chamava a gente pra gravar por isso que gravou que você monte de gente mas eu

entendi num certo momento da minha vida que o meu ciclo na música tinha encerrado é só que eu não tava sabendo como eu acho que é até eu até uma história interessante eu vou contar já com podcast a igreja foi o livro né que vai ser coisa na temperatura não é que seria o meu testemunho de vida eu tenho um testemunho de vida muito forte nessa nessa Nesse quesito vesti grande parte da minha vida na música vem lá de trás Ok só que não determinado momento da minha vida eu tava passando por uma situação financeira muito complicado quando a gente vê quando as pessoas de fora olha para músicas leve ele e eles arrumadão bonitão tocando instrumentos do palco tá em evidência né a alusão que as pessoas fazem é de que ele é um cara bem sucedido por tá bem tá dando dinheiro famoso a gente não é famoso o o dono do negócio é o que é o cara famoso quando eu tocava com André Valadão André Valadão o cara famoso eu tocava com Jota Quest galera do J que a galera famosa é melhor a gente que ficava nos Bastidores às vezes

passar por algumas situações um pouco difícil para mim eu tava passando no momento financeiro da minha vida muito difícil e foi junto com isso foi meu primeiro ano de casamento cara você é casado você sabe como é que é isso no meu primeiro ano de casamento acho que foi onde eu tive Umas das minhas maiores experiência planta minha vida pessoal quanto com Deus também foi onde ir as coisas começaram a ficar um pouco difícil para mim pouco não bastante difícil cheguei numa situação da minha vida que eu tava com tudo eu tava eu tava todo endividada o meu apartamento que eu tinha comprado na época eu já tava com selagem quatro prestações atrasado tem quem tem que apartamento financiado sabe o que que significa você tá correndo risco de a qualquer momento o oficial de justiça bater na sua porta e falar cara Perdeu você sabe disso é eu tava chegando uma situação de Bola de Neve de dívida um pequeno estava ficar um pouco se proporcional e Olha só tudo isso no meu primeiro ano de casamento cara é aquele ano ali que adaptação né você vive você vive flores né mas você vive

no meu caso houve um inferno com flores é tipo isso o momento mais difícil então eu tava com a prestação do apartamento atrasado conta de luz já tava atrasada minha internet estava para ser cortada eu tava no momento financeiro tão difícil na minha vida e teve um dia que eu cheguei em casa sim Liguei meu apartamento e abrir a porta eu pensei comigo assim pra caramba se eu chegar aí Larissa minha esposa e a Larissa tiver com a mala dela pronta querendo ir embora para não vou poder falar nada eu cheguei nesse nível falei que não vou poder falar nada eu vou ter que pegar e vou ter que levar Larissa de volta para o pai dela porque eu não tô dando conta de cuidar dela e eu não tenho dinheiro não tô tentavam cara tava uma situação difícil tá conseguindo dormir direito enfim faz um totalmente preocupado foi quando eu comecei a orar eu acho que é Deus permite Às vezes a gente passar para os momentos desse para você crescer e foi onde eu tive um crescimento muito forte cara muito forte porque quando eu cheguei nesse fundo do poço o meu primeiro

ano de casamento estudo na área da música hein estou te contando uma coisa lá atrás é de quando eu era música só música né É no primeiro as casamento financeiramente estava tudo ruim e aí cara eu tava orando aqui dentro de mim vivendo todo esse momento eu tinha uma insatisfação que eu não eu não tava sabendo direcionar eu tava sim fé em Deus é engraçado eu sou músico eu eu gosto do que eu faço eu amo que eu faço mas eu não tô conseguindo colocar para fora 100% eu tenho a oferecer parece que parece que não é isso que o Senhor tem para mim e comecei a orar e esquisito apesar de sermos gostar da música ter vivido um sucesso entre aspas na parte da música eu comecei a orar e foi Deus muda minha vida muda minha história cara e comecei a orar mesmo e eu tava todo preocupado é todo completo todo engraçado né cara então Teve um dia que eu fui orar pelado cara entrei no meu quarto eu fui orar pelado por que que eu fui orar pelado cara eu fui orar pelado para que talvez não é para que Deus

souber de alguma coisa que Deus sabe de todas as coisas que era para espera eu mesmo saber que eu era um bosta e que se Deus não me abençoasse cara desculpa o tempo que Deus me abençoasse eu tava [&nbsp;__&nbsp;] por que que eu tô falando isso porque nesse dia vai ser meu quatro eu cheguei a minha porta fiquei pelado cara deitado no chão e orando a Deus foi e eu falei essas palavras meu Deus não adianta eu querer conversar com o senhor uma coisa que é o senhor sabe qual que é a palavra que tá no meu coração então eu vou ser totalmente aberto com o senhor aqui e só me perdoa se eu for errado com o senhor vai para o senhor não me abençoar se o senhor não abre a porta para mim Deus eu tô [&nbsp;__&nbsp;] essa que a palavra falei desse jeito com Deus Deus é essa que a palavra tá no meu coração não vou mentir para o senhor se o senhor não me abençoasse o seu não abriu a porta para mim eu tô tentando eu não sei o que quer eu tô perdido me encontro perdido nesse momento

pai preocupado eu falei a Deus olha a minha vida como que tá acabei de casar não tem a minha esposa para poder cuidar não tô conseguindo cuidar da minha esposa ou com uma parcela de prestação do meu apartamento atrasado conta de luz atrasada internet está cortado para o dinheiro que tá entrando para mim agora é só para poder conseguir pagar o cartão de crédito porque eu gastei no mês anterior para poder comprar comida e agora tá virando uma bola de neve e eu não sei mais o que fazer a Jesus muda a minha história eu tô aqui pelado para você entender que eu não tenho nada para te oferecer e que se o senhor ou uma abençoar eu tô [&nbsp;__&nbsp;] eu falei desse jeito Desculpa aí galera o podcast mas eu falei desse jeito com Deus não adianta você querer mentir para aquele que te criou e sabe exatamente o que que você tá pensando que você tá sentindo E aí cara não desistir é a minha esposa também é uma mulher de Deus também a gente tava orando e começamos a orar começando filme esse propósito ou enfim cara quando você quer muito uma

coisa eu acho que ninguém te segura velho que eu acho que Deus já lançou isso no universo não querendo ser né aqui é entra onda Mística nada disso mas eu acho que Deus já lançou esse universo e a gente entende isso como fé a Bíblia explica isso como fé Então quando você realmente quer alguma coisa que ela ninguém segura ninguém segura uma pessoa que tá afim de fazer uma parada que quer mesmo fazer entra de cabeça eu como tava todo ferrado entrei a Deus em nome de Jesus muda minha história ao mesmo tempo em que eu vivi uma insatisfação no meu coração no sentido assim cara eu não sei o que que eu tenho para fazer eu só músico Mas eu sinto que Deus tem um algo diferente para mim que Deus permitiu chegar nesse fundo do poço para que eu conseguisse me transformar ou melhor é que ele conseguisse me transformar então quando eu cheguei no fundo desse poço comecei a orar desse jeito eu fui enfático nisso eu e minha esposa falando vamos orar vou morar morar aí teve um dia que eu era no meu quarto sozinho e Deus falou comigo que

Deus falou que era para já começar agradecer por quê Porque Deus estava já mudando a minha história eu pensei comigo fala alguma coisa minha cabeça não ée fiquei quieta e quer não falei nada com a Larissa nada no outro dia e quando a gente tava orando de novo a Larissa esposa falou assim amor engraçado Deus falou comigo parece que já está para acontecer alguma coisa que é para gente começar agradecer Agora vamos começar ela me falou isso foi assim amor então é verdade então Deus só testificando porque o Anderson falou Exatamente isso comigo que já era para começar agradecer porque deu já começou a mudar nossa história mas não tinha visto nada acontecer ainda eu falei vamos começar agradecer mas eu não vou parar de orar não vou parar de buscar enquanto não encontrar E aí cara a gente começou agradecer mas eu continue buscando continue orando mais três dias depois é o Elias Me liga seu eles me liga é só que pagar entender o contexto aqui eu voltar um pouquinho aqui rebobina na fita né Aconteceu uma situação na música uma vez numa reunião Nossa lá na época do escritório e que para

mim naquele contexto eu tô voltando no tempo aqui só para contextualizar foi aonde eu disse para mim sim cara para mim não dá mais na música Um aconteceu aconteceu lá no escritório falei cara para mim não dá mais não foi para mim foi a gota d'água e lá no escritório mesmo a época eu peguei e pensei comigo quem são os empresários que eu conheço eu conheci o seu Elias que o empresário foi seus amigos um amigo meu na verdade lá no Rio de Janeiro e também empresários amigos meus de São Paulo o empresário mandei mensagem para todos eles cara na tora e o Elias ele já era amigo meu Antes também e para o eles fica diferente quando eu tenho afinidade maior eu conheci o eles na verdade tocando a gente tocava junto uma big benchmark Celestial Big Ben e aí eu mandei uma mensagem para eles desse jeito assim freio fala chegado chamei e eu falo chegado eu vou direto ao ponto cara mano eu tô precisando de trabalhar a [&nbsp;__&nbsp;] tem alguma coisa que eu posso fazer na sua barbearia aí essa mensagem que eu mandei para ele e velho eu mandei na

real mandei a real mesmo assim eu já tava vindo orando né eu no tempo passado ainda então para vocês entender o Elias já estava ciente eu não vou mentir para vocês não cara eu precisava fazer dinheiro entrar na minha casa eu não tava tendo como eu tava disposto a lavar o banheiro da barbearia né varrer o chão da barbearia enfim velho fazer qualquer coisa é porque eu sabia que por qualquer lado que eu começasse eu sei da capacidade que Deus me deu eu sabia eu sabia da se eu começasse por qualquer lado Deus iria me fazer crescer eu eu sabia que eu disse muito sério dentro de mim mas por aquele momento eu precisava começar por qualquer lado e eu falei com ele eu falei cara eu lavo o chão da sua barbearia se precisar limpar o banheiro e eu e eu tô falando de verdade eu não tenho treta com isso não cara lá na casa do mesmo que eu trabalho eu tive que fazer várias vezes não tenho problema nenhum com isso E aí agora voltando ao momento em que eu parei esse aqui foi só para contextualizar já tinha mandado essa mensagem

para eles eu tinha conversado com ele aqui nessa época ele tinha fala para mim se nossa chegada a hora que você pelo menos fosse barbeiro eu dava um jeito de ir lá de colocar você de assistente enfim máscara nesse tempo agora não tenho nada que você pode fazer ou não tem problema não chegar nós valeu só pelo toque já valeu obrigado né eu não contei as passado ainda já tinha rolado essa e com eles e aí beleza agora voltando para aquele momento em que eu falei que Deus já tava falando com a gente agora lá na frente da história três dias depois daquele contexto onde eu e minha esposa tivermos experiências com Deus Deus fala com a gente para começar agradecer o eles me liga aí fala assim que chegar onde você tá Ah então negócio para mim cara é um negócio bacana eu acredito que seja de Deus para você e eu acho legal Cara mandei preservar eu falei para o telefone onde você da Fran você vem onde eu tô aqui não que eu tô na Savassi tá muito longe daí vamos encontrar agora fui vamos agora lá na língua até gol gol

Sushi um negócio Shirley que tem na região ali da da do Mineirão ali negócio gostoso ali posso cara rapaz e ele falou assim vamos encontrar lá eu sei que você tá quebrado de grana preocupa não eu vou pagar olha a Larissa também tá beleza e ele ele vem sabia que eu tava duro é mano ele levou a gente foi levou a gente tal deixou bastante à vontade eles não era sensacional cara E aí lá nessa a gente conversando ele me explicou o que que era para ser feita e na época era só workshop que fazer o Maicon e antes aqui negócio começou aqui a criar uma demanda e o Marco gerenciável barbearia fazer um monte de coisa eu tinha como ele fazer tudo e gerenciar a galera que tava procurando para fazer vendas tudo mais a gente precisa de alguém para produzir os eventos como eu vim da área da música Apesar de eu não ter sido trabalhado né eu não trabalhei na verdade como produção de eventos na área da música eu vivi a produção de evento Então eu tinha uma experiência do que eu tinha vivido Ele explicou para mim agora eu trabalho

é esse a gente faz lookshop é preciso de alguém para produzir os orkshopp para mim fazer as vendas e tudo mais ele ele tava dando tiro no escuro ele não sabia que que no quê que ia dar ele queria não Sinceramente me ajudar e E aí ele me disse assim cara e a gente já tem um evento agora marcado para semana isso era em Janeiro Isso é essa minha conversa se deu no dia Dezessete de Janeiro de 2016 Esse é de Janeiro eles Oi de Janeiro onde eu comecei assim eu é chegado para mim beleza mano eu tô dentro e de como é que essas como é que que dia que você quer que a gente que eu vá lá não sei me fala aí foi cara minhas coisas geralmente é meio para ontem e o Elisa assim mesmo as coisas para ele é meio para ontem ele me disse assim tá na minhas coisas também para ontem cara eu falei beleza então amanhã de manhã então acho amanhã de manhã a Monalisa que a menina que fazia lá vai explicar tudo direitinho tudo mais outro dia nove horas da manhã eu tava lá já

com a Mona Lisa já era me explicando e ele sabia que eu tava ruim de grana ele falou aí esse evento que vai rolar agora a gente tá fazendo o vento do mais quantos por cento ali eu vão da grana que já vai tá entrando nesse eu cara aí começou o meu novo universo na parte da barbearia só que eu ainda vivia parte da música Deus nesse momento que tem que eu falei que eu tava ali para a cura na diz que eu tava todo ferrado cara de repente Deus eu acho que Deus precisou com que eu chegasse esse fundo do poço não sei se para eu quebrar alguma outra vez que eu tinha ou qualquer outra coisa alguma soberba não sei mas Deus permitiu com que eu chegasse lá no fundo do poço acho que era para entender isso é pode fazer qualquer coisa se Deus não te abençoar meu irmão não pode ser o melhor barbeiro do mundo se Deus não te abençoar você não vai dar certo em nada eu posso o melhor cara que vende do mundo e Deus não te abençoar senão vai dar certo em nada agora você pode

ser o pior cara do mundo se Deus tiver com você e te abençoar você vai dar certo ele vai te capacitar ser melhor então a gente precisa baixar nossa bola baixar nossa TVs botar Nossa carinha no pó e entender que quem é grande aqui é Deus estou Quem faz o sua vida não é você é Deus é Deus quem te capacita é Deus quem abre a porta para você é Deus que te faz dar certo eu acho que essa mensagem que eu teria que dar aqui nesse momento começou essa mensagem depois de desligar negócio foi cara só sei que nessa em um mês que passou um dinheiro na minha mão e foi assim nessa mesma época ele chamou para poder fazer Jota Quest me ligou para gente começar a fazer um trabalho de produção que horas fez um bumbum Deus abre uma porta grande passa na minha vida assim e passou uma grana na minha mão tipo assim três vezes maior do que do que eu já tinha ganhado na música em um mês em um mês eu consegui quitar todas as minhas dicas Olha só você vem um mês quando Deus abriu resolveu abrir

as comportas do céu para mim comprei o que tava precisando de comprar que ter o cartão é claro que tem tudo sobre o dinheiro e olha só para você ver que Deus faz as coisas que sobrou grana velho aí eu só tive conhecimento nós estamos em 2015/2016 para cá eu só tive crescimento Deus foi a pessoa que fez tudo essa essa transformação toda e usou a vida do Elias para isso eu gosto de deixar isso bastante Claro Deus é quem faz as coisas mas sabemos muito disso mas eu tenho a dívida de gratidão enorme com o seu eles a galera Às vezes bate o olho ver velha assim grande fala muito que marketeiros tudo mais mas não é só não é só isso não mano o cara é [&nbsp;__&nbsp;] mesmo foi com ele que eu adquiri uma nova mentalidade de vida é com ele que adquire novas habilidades para crescer foi com ele que eu consegui mudar até mesmo a minha forma de me relacionar com dinheiro cara porque tem duas formas do dinheiro pelo menos duas formas do dinheiro de presidir te aprisionar o cara aqui ganha bem e só quer saber de ganhar

mais eu não Vivi e o cara que tem pouco dinheiro e tem medo de perder o pouco que tem é o dinheiro que está governando do mesmo jeito eu era esse cara e vamos assim de certa forma Avarento né E quem me moldou a minha forma de pensar de agir me deu mudou meu Mike sete né Acho que essa é uma palavra muito em alta hoje que falar mais 7 aqui não é nada de novo para ninguém mas quem mudou meu mais 7 para uma série de crescimento por seu eles e uma forma muito tranquila uma forma muito amigável eu estando junto com ele aquele lance né que aprender a voar da Águia né e eu aprendi voando com seu Elias então assim eu tenho uma dívida de gratidão enorme com esse cara ele realmente foi um canal de Deus tem sido né Não só foi ele foi tem sido um canal de Deus e mudança na minha vida profissional pessoal mesmo minha vida minha a minha carreira hoje eu tenho uma dívida de gratidão muito grande com Deus obviamente mas também com Elias Elias para mim foi um cara eu eu sou uma prova

social da transformação é de crescimento através da do conteúdo do seu eles através da forma dele de pensar de agir ensinar a galera então assim é que até aqui eu consegui te responder à primeira pergunta se fosse pode pensões e começar aqui vai esperar mudou muita vida e acessórios antigos hoje cara muita coisa para muita gente tá ouvindo a gente faz coisas agora a gente passou esse contexto todo do do seu ele resumo da história você hoje no grupo né Tá inserido ali na parte do curso para educadores né você pode compartilhar um pouco com o de barbeiro hoje sonha né só em cima educador sonho ser famoso só entrada por shopping pelo Brasil pelo mundo e que você tem dica para esse pessoal tudo bem sobre o curso de formação de educadores que você falou é som é só um dos braços né são os cursos presenciais que nós temos só que nesse curso de formação de educadores a Barbie de educators Eu sou um dos palestrantes são um dos educadores vão falar palestrante não que dá uma ideia de distância né sim barulho do que dizendo o curso pequeno para poucas pessoas para

exatamente ficar nessa nesse com essa com esse ar informal né de proximidade mesmo ali com o educador tudo mais eu sou um dos educadores esse curso nesse curso a gente ensina é o Barbeiro que quer ser educador desde a parte da mentalidade que ele precisa adquirir porque eu vou te falar não adianta nada se seu cara para guardar cabelo mas tem uma mentalidade errada na hora de ser educador o cara passa educador é preciso pensar diferente ele tem que agir diferente então a gente nesse curso de formação de educadores a gente vai ter uma sacada muito forte deles porque muita gente chamava gente querendo saber como eles foram educador ah ah mas esse curso que vocês dão um por exemplo presencial ele me ele me e prepara para ser um educador muito barbeiro ser educador para ter uma renda extra né obviamente é legal realmente lucrativo mas tem muita gente ruim no mercado quero muita gente ruim mesmo tem muita gente que acabou de sair de um curso básico agora e cada aula para o nível da barbearia no Brasil tá lá em cima velho Além disso um cara você tem pessoas como seu Elias

que tem pessoas como o Danilo Moreti que é extremamente técnico o cara é [&nbsp;__&nbsp;] né na técnica você tem um Luiz Gustavo que você tem um Rafa e já que já conhecido de você ser cliente de vocês caro tem um Marconi eu vou geral hoje tão nível cara do conceito do técnico da barbearia cara ele não tá aqui em baixo aqui para o cara acabou de sair para um cara que acabou de sair um curso básico querida aula o nível técnico está em cima velho o mesmo de verdade então o que a gente fez a gente criou um curso aonde a gente prepara desde a mentalidade do caro a Como que o cara vai pensar do jeito certo é eu tô aqui até um psicólogo quem dessa aula é o Lucas Ferraz o Lucas ele fala muito sobre essa essa questão da mentalidade ele ele te ajuda a você é a como você alcançar essa mentalidade certa para você ser um educador então assim o que que te limita que todos nós todos nós temos algumas crenças que vamos limitando ao longo da vida né e ele te mostra como que você consegue romper com

isso porque às vezes e não tá dando certo como educador ele consegue mostrar venda psicologia ali as ferramentas necessárias para isso a gente começa trabalha na mentalidade do caro depois a gente ensina o cara como que ele vai criar uma metodologia muita gente acha aqui para cortar para ensinar os nunca cortar cabelo é só você botar a galera até assistindo fazer não eca E como que você vai transmitir isso pode estratégia que você vai fazer isso cara essa metodologia que você está criando faz sentido para quem tá tive está assistindo em coisas que foi você é muito fácil você passa por cima sem perceber mas quem está te vendo Fala cara você tão complicado cara eu não consigo entender como que você explica o complexo que você faz para uma criança né você não foi capaz de explicar para uma criança é quase inútil acho que foi Albert Einstein que falou falou isso alguma coisa do tipo então assim a gente criou a mentalidade o cara a gente Ensina ele como criar uma metodologia a gente explica para ele o propósito de disse o educador e não é só ganhar dinheiro ganhar dinheiro cara é

uma é uma é uma contrapartida de um trabalho o resultado de você entrega muita gente é dinheiro está né O barbeiro muita das vezes é muito dinheiro lista quem tem uma mentalidade mais elevado já não é mas não tenho muita gente Oi Erica dinheiro está imediatista a quanto que eu vou ganhar de lucros aqui se eu fizer isso não é bem assim que o dinheiro é resultado Vitória entender quase que uma transformação na vida da pessoa de fato não é isso que a gente tava até conversando pouco a gente conversar para que realmente não quer confiança de comprar o teu pulso Europa em Sim claro porque todo mundo é movido pelo seu próprio interesse né Isso aí é fato todo mundo é movido pelo próprio interesse então quando o cara pensa em fazer um curso educador como esse porque o cara vem vem por quê Porque a gente trabalha a mentalidade o cara a gente Ensina ele quer aula metodologia a gente dá estratégias de performance na fala eu quero saber se presente Tem muita gente que é bom Tecnicamente e se você pegar e colocar ele no palco a dar aula ele vai travar

ele não vai saber se posicionar ele não vai saber se vestir ele não vai saber o que falar ele não vai saber como gesticula ele não vai saber em que parte do palco ele pode cara tudo ih Ou seja é oratória é recuperar nl né programação neurolinguística então a gente traz um pouco dessa performance de palco um pouco pnl isso tudo não curte formação de educadores E aí vem eu trazendo as estratégias de venda todo mundo a cria uma mentalidade ensinou o cara que é uma metodologia trabalhou a capacidade de performance o cara agora a gente se o cara vender tudo isso no curso de formação de educadores é onde eu entro eu ensino o cara como termo como negociar e as estratégias de negociação e venda porque o cara às vezes quer vender um curso ali mas ele não sabe nem o que que é vinda mano ele não sabe gerar valor pro outro cara eu não sabe enxergar pela perspectiva do cliente ele é dinheiro lista ele quer aí ele acha que ele vai criar um produto e depois ele se vira para pessoas comprar esse produto não peca aqui um produto dependem

conforme a demanda você faz você faz alguma coisa com forma a perspectiva do cliente então a gente no curso de a formação de educadores que o Babidi educators né A gente trabalha essa mentalidade o cara ensina o cara como se vender tem até um fato legal foi na nossa penúltima turma eu expliquei todos os processos eu explico desde a parte do que que é vendas e que a negociação para o cara entender o que que é esse processo ensino ele a Como criar uma estratégia de venda para ele então cara sai dali sabendo qual estratégia que ele vai usar para ele ele vai trabalhar com iniciantes qualquer linguagem que ele deve ter ele vai trabalhar como modelo avançado como que ele deve te dar com isso aonde que ele vai vender onde é o pulo do gato Qual é o canal Qual a forma que ele vai falar qual que é a estratégia certa o abordagem Qual que é o Real preço que era tudo está relacionado com venda e teve um fato interessante Nossa penúltima edição foram os alunos que tava lá na hora enquanto eu falava e ele ficava sendo quem sabe quando

você tá é dependendo absorvendo a ideia como se fosse na acho que eu vendo ele pudesse traduzir a expressão dele Seria tipo assim Ah então é assim ah é assim e ali ele criou coragem cara venda estratégia que a gente criou ele ofertou concurso de um curso intermediário Aline me conta tava na aula mesmo final da aula ele pegou usou a estratégia ali no Instagram dele sim e não é que o cara me vende 66 é isso ali de imediato ele vendeu o 66 inscrições para o curso dele que ele entendeu o processo das vendas depois ele fez e ele não parou de hoje cara E aí nessa primeira turma dele fecha o 10 aluno depois Fechou mais 10 e foi fechando até hoje não parou ele entendeu os processos das Mesas ou seja ele investiu 3500 reais para tá ali no curso exige esses três r 1500 que ele mentiu para tá ali ele já ele já saiu dali com esse valor que esse investimento pago o ou seja o curso não custou nada para ele ele entendeu o processo aplicou só na primeira turma que ele ofereceu enquanto estava ali na minha aula

ele ele já vendeu já pagou o curso só com essa só dele tenha entendido Isso ele já pagou o curso e aí depois a gente finaliza compra com a própria aula do seu eles falando sobre a o empreendedorismo na área de educação pronto cara o cara sai dali assim Se ele vier com a vontade pode exposição de entender colocar em prática parada que ele ah entendi entendi ali ele se torna realmente o educador eu preciso que disposição mas ele sai com a mentalidade pronto pronto para agir na mentalidade ponto de entender como que é uma metodologia pronto para saber como que vai se comportar no palco. Para saber vender e pronto saber como que ele vai empreender cara é basicamente pegar na mão do cara e falar velho faz isso faz isso faz isso faz aquilo' 3500 se acha o cara inverso ele entende vira dinheiro de bala É isso aí ele consegue recuperar rapidamente muito bacana Moisés A gente fechar que se fosse sintetizar um ensinamento sobre vendas enxergue pela perspectiva do seu cliente não pela sua vamos se não seja dinheiro lista imediatista enxergue pela perspectiva do seu cliente tem o seu produto

pela perspectiva dele por exemplo na hora da barbearia mesmo o cara que é barbeiro não não tô falando do cara que quer se tornar educador e vou dar um exemplo do cara que tá no dia a dia dele Na barbearia e ele no mesmo tempo que ele tá atendendo aquele cliente ele consegue mudar o ticket dele naquele mesmo tempo o cliente deve tá sentado numa média de 30 40 minutos uma hora dependendo do procedimento que ele tá fazendo com o cliente o cliente vai ser cortar cabelo 30 40 minutos se o cliente faz cabelo e barba já vai ficar uns 50 minutos a uma hora também cliente que vai faz o cabelo faz a barba faz selagem faz tudo cara ele ele gastou ali uma hora uma hora e 20 com aquele cliente se ele usar uma estratégia sétima ao invés de Lilo CRAS em Reais ele consegue lucrar r 150 ele ou seja tem um aumento de Ticket de aproximadamente cinquenta por cento usando o mesmo tempo usando estratégias certo por exemplo você souber oferecer um produto que faça sentido para o cliente ele souber resolver esse problema do cliente ele consegue aumentar o

faturamento dele de um jeito com que ele não precisou de mentir nada ele só criou uma uma um caminho de resolver um problema do cliente ou seja o cliente saiu satisfeito porque resolver um problema e o Barbeiro vai sair satisfeito porque vai ter um louco maior então quando ele entende apenas pela perspectiva do cliente ele consegue aumentar o ticket médio dele ele fatura mais o mundo sai ganhando seu cliente a ganhar porque se resolver um problema dele pagar para ele não é problema dinheiro não é problema eu conheci o satisfeito que você resolver um problema dele você aumentou o seu ticket gastando mesmo tempo Manteve gastar mais tempo para isso é foi inteligente o cliente ficou satisfeito Ele usou Isso volta ou seja enxergue pela perspectiva do seu cliente acho que se fosse parar aqui para poder falar só senhor resume tudo enxergo pelo perspectiva do cliente oferece e vende para ele o que ele quer comprar ou enfiar goela abaixo um produto que você quer vender Mas vendi para ele um produto que ele quer comprar um efeito muito bacana Pois é isso pessoal que tem interesse de do Barber Day conference tá chegando

no próximo agora em agosto de 2022 eu vou deixar a data aqui primeiro porque tem pessoal pode escutar depois eu tenho um desconto especial você pode deixar alguma coisa aí para eles Olha o Bari compras talvez até na hora que eles podcast aqui que tiver lá eu acredito que já vai ter esgotado para vender com três cara é um evento é a conferência Nossa conferência internacional para bebês aonde a gente traz assuntos que está relacionado Na barbearia mundial em podem conferir só para dar só para você entender é o maior workshop para barbeiros do mundo no mundo o barba de contas aqui em Belo Horizonte Minas Gerais o evento que nós organizamos é o maior workshop para barbeiros do mundo a gente coloca ali no Palácio das Artes uma média de 1600 1700 pessoas em de hoje a gente traz novidade E aí fora A gente traz muito conteúdo técnico e o tema Todo ano a gente tem um tema esse tema está relacionado com o momento em que a barbearia do Brasil tá vivendo e nesse momento agora o tema é oxigênio porque oxigênio galera todo mundo agora passando por um processo pós paneme

ia muita gente quebrou muita gente que se endividou muita gente precisa entender que o mercado mudou então precisa dar uma oxigenada na sua mentalidade eu te dou uma oxigenada especial cara tá afundada ali velho tipo assim naquela realidade precisa sair para tora a respirar e que significa essa oxigenação entender qual estratégia nova que você pode usar para poder atrair audiência para o seu público Ah tá como você tratar melhor esse cliente como você fidelizar melhores clientes a como você criar uma estratégia para sua empresa que seja mais eficiente Olha só tô falando só sobre o negócio por causa do tema junto com isso não vai beber compras a gente vai ter a parte técnica que esse ano estamos trazendo de volta para o Brasil o número um do mundo que é o Josh lamonaca era sensacional lugar é sensacional Então a gente vai ter ali seu Elias Jorge lamônica Sky Salon não tô lembrando de todos aqui agora mas você pode dar uma conferida lá www barby de e [Música] academy.com/conference 2022 pode tá com fresas 2022 ali no Google também e em todas as informações lá então a gente vai ter uma vai ser

um momento de dar uma oxigenada na mesa do barbeiro se o cara que quer entender da da barbearia em que nível se encontra da barbearia aqui no Brasil é um mês de quiser dar uma oxigenada fazendo Network sabem que nível se encontra tempo confio nesse dia quinze e dezesseis de agosto corre lá e as inscrições está rolando e a gente está caminhando pelas últimas vagas em não perde não agora vamos já que você deu a deixa aqui espero que você deu a deixa aqui deixa fazer uma mexa e você que viu aqui o podcast do best Barber entre em contato com a gente aqui no 31 DDD 31 8459 fala que assistiu esse podcast aqui e eu vou ter uma condição interessante se você tiver interesse em fazer o Barber Day Academy ou Barber Day educators até mesmo bar beber Business também eu entro em contato comigo lá e 31 991 29 8459 fala que assistiu o podcast do best Barber e eu vou dar uma condição especial para você é curiosa né Entra lá se você quer fazer parte desses cursos em vai deixar também o link aqui o número na descrição e também

pra gente finalizar você ainda que não conhece o best Barber se o melhor aplicativo de gestão de barbearias de agendamento para seus clientes gestão financeira gestão de comissão vários relatórios e entender como é que tá aí no seu negócio o link também tá aqui para fazer o download você fez um aplicativo uma versão própria para sua barbearia a gente também tem essa novidade em breve muito mais pois é obrigado a situação que o cara obrigado aí pela oportunidade pode sempre Ficamos muito feliz com sua participação Valeu demais querido acabam na hora que ela olhava tempo para poder cortar mandar por averiguar aguardar agora pessoal Valeu galera um abraço e E aí [Música]`,

  summary:
    "Episódio 6 da Temporada 1 do BestBarbers Podcast. Moises Nazaré compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
