import type { VideoContent } from "./types";

export const podcastkennedy_ricardo_S2_ep07: VideoContent = {
  slug: "podcast-kennedy-ricardo-s2-ep07",
  youtubeId: "bWd1EkHPPrY",
  title: "BestBarbers Podcast com Kennedy Ricardo — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 7 da Temporada 2 do BestBarbers Podcast com Kennedy Ricardo. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "kennedy ricardo",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2023-03-13",
  duration: "1:07:40",
  category: "Podcast",
  tags: ["podcast", "temporada 2", "entrevista", "gestão", "barbeiro"],

  transcript: `[Música] senhoras e senhores sejam bem-vindos a mais um best barbras podcast é um prazer ter você nos acompanhando no último episódio da nossa segunda temporada para quem ainda não me conhece meu nome é André eu sou um dos donos aqui do best barbras e hoje eu tenho um prazer de receber mais essa fera aqui do mundo das barbearias Obrigado André aceitado cada convite para quem ainda não conhece Kennedy Ricardo se você ainda não segue no Instagram o nosso Instagram é best barros.weppe e do Kennedy Kennedy Ricardo com dois ossos no final 29 segue a gente lá sem mais delongas vou pedir para vocês apresentar rapidamente pessoal contar um pouquinho quem é o Kennedy sua história como é que começou essa história aí no mundo das barbearias Obrigado André primeiramente eu quero agradecer pelo convite eu fiquei muito honrado tô muito feliz ansioso assim preocupado ainda mas é rapaz Ei Marconi responsa Ah meu nome é Kennedy cara né Eu sou natural ou de Pará de Minas Pará de Minas tá de boa mas criado em Contagem vizinhas aqui na cidade vizinha comecei cortar cabelo com 15 anos de idade 15 anos 15 anos oi não

foi não foi algo assim a primeira a um amor assim de cara não né nada nada estranho primeiro foi o meu tio né que sempre cortou o cabelo ele tinha uma parceria ele a esposa dele que é tipo um estúdio que é uma de um lado era barbearia para atender masculina em cima mulheres escova tudo corte e sei lá e por aí vai que as mulher gosta de fazer é E aí eu sempre cortava bem com ele ele falava cara faz o curso só tem jeito para isso não para cabelo eu eu quero ser músico porque eu sou músico né Eu quero tocar baquera não quero virar um ácido Roque nem era barbeiro era cabeleireiro né não ele é o outro você desenha isso eu tenho aquele toque artístico hoje né tem que colocar porque será Não vejo não fui embora do salão do meu tio ensinando isso não qual que é o nome do seu tio Daniel Daniel Hoje ele mora nos Estados Unidos hoje para cá nos Estados Unidos ó top abençoa vai ser massa o meu tipo assim um cara que além da minha família foi o principal Pilar que me incentivou

onde eu conquistei hoje através do cabelo né onde estava em casa mas antes não se você gosta tocar vai ser bom que você monta sua própria agenda e dá uma flexibilidade ali da igreja ou tocar fora algum lugar sendo que você tá trabalhando no horário não tem como eu falei verdade fui embora pensando nisso né bem assim uma época que ele tinha ido dormir no emprego tinha mandado ele embora ficou desempregado Aí tem uns acertos da empresa né e tal ele pagou algumas contas e comprou algumas coisas para para casa e sobrou um dinheirinho eu nem sabia que sobrava falei o cara fez um curso para fazer um curso de cabeleireiro acho que é legal uma profissão a mais para fazer vai ser legal ele é mesmo você quer fazer vamos embora então vamos fazer então meu salário era ele tudo era o pai e mãe eu lembro que ele a gente foi lá cara encontrou os maquinários e tudo muito custo né porque nada nada fácil ainda mais na época né Na época na época assim ele comprou e não sobrou mais nada para não mais cara falei não e agora não relaxa Deus

proverá proverá a gente é um Fabi de muita fé é um de Deus tem que sustentar da gente cada dia mais até hoje né E aí ele falou assim não vamos comprar você quer fazer lembra meu tio falou assim não uns três primeiros meses do curso eu vou passar pra você era cinco meses mais ou menos onde ele fez o curso antigamente Engraçado que é pouco assim escolas que duram muito né naquela época até hoje tem essa escola lá lá no Eldorado pelo João César levou embora então Tio vamos lá me levou antes ele precisava pegar no tesoura tal colocar guardar eu gostava muito difícil isso aqui ó virar isso eu falei como é que faz isso aqui não é fácil guarda aqui hoje Guarda para cá né agora Marconi que né hoje tudo evoluiu eu falei vamos lá então se eu pegar a tesoura cortar mexerzinha pra trás Eu lembro que eu fui falei e ele me incentivava não só vai gostar eu tô fazendo porque eu acho que vai ser uma coisa boa sei lá se não der certo eu vou do meu pai do meu irmão de graça pelo menos isso não

vão pagar você vai gostar assim olha aqui qualquer lugar que você for no mundo tu tem trabalho com cabelo todo mundo Precisa cortar cabelo né e outra se o médico falou para fora eu falei tem que especializar naquela área lá né porque a realidade é uma coisa que é legislação é outra coisa né cabeleireiro dia onde que você entrasse para cabelo não tem outra coisa verdade e sempre colocando a semente na minha cabeça porque eu tava desinteressado eu fiz assim eu comecei a fazer por uma pressão dele sempre chegar lá e falar e eu pensei pô mas pode ser interessante para mim eu te dando pontos ali de interesse velho consegue ganhar a pessoa na conversa ela é muito fugiu a palavra que vocês vão entender eu não marqueteiro não é outra coisa e sua ação né Isso mesmo aí foi lembrando foi colocando feliz aí eu lembro que a gente não lá nessa escola cara era uma criancinha agora pequenininha primeiro dia mexendo mas para mim tudo novidade sabe que é TIM aí eu cheguei em casa uma vez as crianças a mãe e tinha um senhor muito muito velhinho deve estar vivo hoje

Tomara que esteja né E aí que rolou assim ó ele chorando O vovô tá aqui do lado não chora não o cara me cutuco assim ó primeiro dia primeiro cliente meu para atender lá na escola amigão suavô dele não sou o pai dele Nossa que vontade de abrir [Música] vou voltar nunca mais aqui mas aí eu comunicar comunicava muito assim a galera não vou voltar aqui vamos embora Relaxa eu vou daqui vai te dar uma balinha ali e rolou aí cara foi só treta só Desastre eu fui fazer um pezinho na nuca no cliente tipo assim de ruim aqui atrás voltou com o pezinho aqui parecendo um Avatar assim sabe que ele vê cara assim na nuca e para mostrar ele depois para mostrar ele com um espelho aqui agora eu peguei o espelho falei ó isso aqui tá você tem um monte de Moinho aqui eu não vou entrar mais muito não viu mas já te pega tudo porque entrando então vou deixar aqui natural que natural aí ele pegou jeitinho eu falei Caraca cara depois dessa história toda como é que foi aí sua experiência né se teve era sua expectativa ali no

início apesar do seu tio ter te convencido ter precisado de vários argumentos aí para realmente encaminhar pro mundo da barbearia e quanto tempo você ficou nesse primeiro emprego vamos lá a intenção era para trabalhar com ele né porque assim a gente sai do curso a gente só pega experiência mesmo de fato cortar cabelo quando você tá na prática todo dia no mercado onde não é só você não é só aluno agora são profissional mesmo assim e meu tipo não e eu lembro de trabalhar com ele no salão eu tinha muitos clientes que amigos dele lá do bairro alguns amigos meus mas antes eu já treinava já nos meus amigos fazia uns estrago e fazer risquinho e duas pista ainda mas assim foi aprender não é errando a gente vai foi errando muito que eu fui aprendendo Acho que até hoje né gente a gente aprende nos erros mesmo aí para não cometer mais e eu ficava assim cem dia sem nenhum trabalhar nenhum nenhum dia dois sem trabalhar sem contar nem um cabelo só vendo não calma calma que é assim mesmo no começo tudo é assim mesmo querido cara meu tio foi assim a

é maior incentivo assim para entrar foi ele um livro muito a vida pela vida dele louva-a-deus pela vida dele meu tio pelos processos dele mesmo porque é um cara que colocou eu no mercado me aconselhava em tudo como pessoa a comunicar não você tem comunicar com clientes você tem que falar mais com ele tu botar o cabelo caladão eu praticamente um me não eu vou ficar focado aqui para eu não errar a gente às vezes no começo assim né muita gente fica assim nem olha pra lá né aqui ia embora eu era assim um contrato cliente o cara embora ele falou não só converso com o cara vai aqui no salão para você conhecer pessoas nem sabia que era networking já sabia que era ah conhecer pessoas cara eu conheci muita gente na no salão do meu tio até hoje com clientes meus até hoje fiéis mas assim quando eu passei a apaixonar pela profissão foi foi um episódio que eu fui entender um cara uma vez lá no meu bairro tem uma tem uma empresa que chama minerador de mineradora que é muito muito grande lá então tipo assim muitos trabalhadores do bairro da

região trabalham lá E aí o cara era um dos chefes lá da empresa foi para caber lá no salão precisava achou eu falei era eu agora eu acabei dele e eu sempre ficava assim vendo vídeos de alguma coisa aprender de tinha muita coisa assim de vídeos de aula alguma hoje tem então era poucas pessoas que tinha algumas barbeiros que fazia mesmo assim na no salão dia a dia dele fazia e eu lembro até do do Eduardo Miller que eu vi um maquininha vai fazendo um degradê como maquininha amarelinha de fio assim eu não antes eu não conhecia o Elisa antes né Para 2012 teve que conhecer o Elias e aí eu entendi esse cara e o cara achataram muito cabisbaixo em cara não quer falar nada então fiquei quietinho porque antes era eu ia forçando Pô eu tenho que falar eu tenho que falar com alguém Eu tenho que contar com o cara não fica caladão fiquei na minha E aí ele tava muito tristezinho não sei o que aconteceu na vida dele aí quando eu falei mano tudo bem Tá legal assim o cabelo tá legal ele do nada mudou a feição do cara

assim pressão nele ai ficou bom demais cara que isso olha aí ele mudou falei cara ficou feliz ele falou a gente tem um poder nas nossas mãos de mudar o dia da pessoa né um simples corte de cabelo às vezes um auto-estima muda muito isso aí Avisa o cara tá sentindo mal porque às vezes o cabelo tá sentindo tá mal cortado tá não tá não precisa proporção É isso mesmo eu falei gente eu acho que eu nasci pra isso então eu vou fazer isso E aí na época tinha muitos freestyle de um moleque faz para mim uma Nike aqui faz uma pena eu falei ah agora desenho parou de brilhar agora né então eu fazia os desenhos nos meninos assim eu tinha não tinha maquininha eu fazia tesoura e vinha sangrava o camarada e no couro falei ah nasci para isso mesmo então eu fui sabendo muitos elogios disso e meu time me orienta não vai por aqui aqui no cabelo aqui para poder guardadinho deixa quadradinho Não hoje eu sempre falo isso negócio quadradinho não porque quando o cara virar vai ficar um poltrona corta a quininha ficou bonitinha eu já falava isso comigo

não corta aqui aquela época um cara muito detalhista assim Ah legal tipo fazendo né porque tinha aquele negócio de da costeleta fininha né fininha né a bolinha não sei se vocês lembra da figurinha é não tem que fazer aqui seguir com a barba e quando crescer cabelo parecia uma mata serradinha a gente fazia falando muito não cara vem por aqui só que isso é afim então eu falei fui aprendendo muita coisa meu tio a maldade da do cabelo foi com o meu tio dando ali o Caminho das Pedras né Foi aonde E aí ele foi assim a concretiza não você nasceu em fazer isso você não pode fazer outra coisa mas eu sempre considerando as coisas com a música eu dava música lá em Barbacena que é uma universidade de música popular brasileira a gente foi muitos cara legal lá é bituca porque o Milton é o padrinho da essa Universidade né minha cabeça não deixava esse sonho de lado sem saber que eu não ia ser eu ia ser uma barbeiro eu tenho orgulho de mãe de ser barbeiro Eu amo que eu faço e ele falava não barbeiro legal não precisa pão de

forma então a gente assim o visagismo meu tio falava sem saber sem entender ela tava entrando assim não você tem que andar limpinho arrumadinho assim uma pita legal vai trabalhar organizado limpinho não tem chefe nenhum para poder falar nada contigo é isso que ele falava comigo falei cara eles convencia nisso né mas tipo assim no começo não foi o que eu pensava não entendeu Ó vou ficar rico então o corte era r 5 na época ele corta cabelo demais eu lembro de uma vez que eu cortei se eu não me engano foi 13 cabelos uma na parte da manhã caramba a da manhã eu falei cara deu muito dinheiro fui contacto assim cara não deu não deu tanto dinheiro né hoje a gente corta sim o cabelo já arruma uma comissão amar é maior porque o valor maior mas assim aí eu fui criando essa expectativa de não eu posso melhorar nisso aqui para ver meu time me incentivando e a partir daí você foi se envolver né estúdio free Life Cabeleireiros até hoje tem até hoje lá e fica Cabeleireiros hoje é minha tia que trabalha lá e aí você trabalhou por lá por

quanto tempo fiquei com meu tio ele disse isso fiquei com meu tio é até 2013 em 2009 início de 2009 comecei a fazer o curso no meio de 2008 terminei em novembro e aí eu tava trabalhando com ele já 2009 que até 2013 14 anos me engano foi até 2013 deu que deu uns quatro anos quatro anos quatro anos aí eu saí porque eu fiquei frustrado também o que não foi altos e baixos por mais que eu falei não nasci para isso mas sempre a gente tem um vai uma fraquejada você vai coisas vão acontecendo para você ficar mais para baixo tentei trabalhar cara uma vez em 2013 era totalmente ao contrário de tudo que ele cara te convenceu e e não tem como a galera que quer fazer curso de barbearia aí hoje vale a pena demais fazer porque hoje tá não tá tá melhor do que antes tá melhor né bem mais difusa tem mais recursos para você ser um barbeiro tem pessoas que faz curso é uma de barbearia corta cabelo cara excelente não tem tempo mas quando eles tem uns cursos dele que é um baita de mais material hoje você

comentou na sua época não tinha vendido de nada nem muito tinha não tinha E aí eu fui lá de frentista Mas voltando aqui aquela que fazer curso faz o curso mais uma coisa para lembrar é um caminho sem volta sem volta o cara conheceu o cabelo Acabou cara ele pode tentar outra coisa ele vai voltar para barbeiro velho não tem como não fui falar de frentista e que em uma semana só cara também de fazer né Anchieta e abrir o capô tocava lá e descontavam uns estouro meus amigos vai ver vai lembrar eles vão morrer porque eu tenho sempre medo cara se você nunca viu coloca no YouTube é estouro de gás GNV na praça cimento que era um tipo uma borrachinha que ficava mas tinha desgastava então ele soltava ela soltou uma vez e nós João César ali perto um posto do BR ali bem perto próximo décima oitava a galera aí vai saber ainda que é e tinha um ponto de ônibus em frente o posto cara quando estourar vamos sair correndo achava que era tiro meu amigo era um touro não tem noção e eu passei mal cara falei não tinha respondido

eu voltei ele falou tá vendo aí você falou para trabalhar com ele fiquei mais um tempinho com ele a gente foi nas feiras nas feiras de cabeleireiro aqui da tinha muita que não tinha muita coisa de barbeiro cara era só cabeleireiro mesmo a demanda Na época era muito até hoje mas hoje o homem tá mais demorando para barbeiro do que antes no mercado né Meu tio quatro anos é 2013 Tá aí uma semana voltei depois foi bem isso aí que tava ali minha jornada com meu tio e aí encerrou em você ficou mais quanto tempo com ele depois eu voltei fiquei porque o ano de 2013 totalmente com ele né depois da semana aí em 2014 Isso foi em 2016 [Música] já conheceu o Elias já conhecia o Felipe que trabalha com Elias ou sem problema com eles nas primeiras equipe dele junto com Qual vinho e com ela foi onde ele vendendo feliz por indicação dele isso tem quanto tempo que você tá lá no Elias já vou fazer 3 anos antes do Elisa trabalhar um tempo no Corel surprima de vagas fiz o teste e passei Graças a Deus não sei andou bastante

aí para o BH com tudo tipo de público todo tipo de situação mas é bom né é bom para a gente aprender tudo mas como você falou né a gente errando aprende muita coisa né Principalmente a gente tem hoje né você teve o privilégio ainda de ter um mentor ali que já sabia o Caminho das Pedras né privilegiando privilegiado né privilegiando ali durante essa trajetória né tipo poupando de muitos e muitas coisas é verdade falou já te trazendo desde lá de trás uma vivência ali com visagismo e tudo mais né mas cara além da técnica né se desenvolveu ali na técnica comentou aqui dos cursos né a gente tem muito material realmente hoje mas que mais que além da técnica você acha que um barbeiro precisa desenvolver porque eu acho que a técnica hoje é o mínimo né É o mínimo cara tem uma boa técnica apresentar um bom corte ali que é mais você acha que os barbeiros precisam cara eu creio que a relação entre profissional e cliente ou a comunicação porque Igual eu falei assim não conversa com o cliente cara interage com ele o que ele você vai saber o que

o cara precisa não fosse uma consultoria mesmo a necessidade né Então pessoal tem muito cliente hoje graças a Deus por essa cidade comunicar com eles cara eu brinco com os cara então isso vai trazer ele além do cara ser bom gostar do corte não cara uma praça boa cara tem uma conversa legal cara me trata bem é uma experiência tentando ser feliz é uma experiência tipo cara eu tentar aqui sentir em casa não ter timidez de falar alguma coisa sei lá ou vergonha não fica em casa não tinha uma coisa ainda em cima dele a vontade né e eu faço ser assim você conhece o Vitor Samuel um abraço Vitor Samuel beijo para eles eu amo esses cara demais virou Além de que a gente virou amigo cara esse cara foi esse que trouxe o depois não falaram o vídeo Espanha para cá e eu acho que além da técnica isso aí essa comunicação entre profissional e cliente também além da brincadeira o profissionalismo manter o profissionalismo acho que ela tem que ser isso show de bola então já fica aí ó mais uma dica para vocês né a comunicação e principalmente transmitir confiança sobre

o seu cliente também né para ele chegar ali e ficar à vontade e ter uma boa comunicação com você e principalmente Fica aí uma dica pra quem quer aproveitar o atendimento né ter um atendimento personalizado ali para os seus clientes no best bárbaros a gente tem a funcionalidade de você colocar ali observações do seu cliente então a cada corte que você faz você pode tirar uma foto pô o cara só gosta de cortar Aqui máquina dois do lado gosto de fazer o Face sempre na zero você pode anotar ali você tem um histórico no próprio aplicativo exatamente no aplicativo você chegar ali já ter tudo porque muita gente também para você lembrar de tudo né então fica aí mais um auxílio que o best Barbie pode te dar aquele atendimento melhor cara eu acho que muito barbeiros né a gente então ele transmite a confiança passou ele já tá com uma técnica boa já consegue ali oferecer um atendimento de qualidade mas eu vejo que muitos quando chegam nesse patamar Eles já sentem satisfeito ali né Muito bem de uma realidade às vezes até humilde né E aí quando eles alcançam isso Um Bom atendimento

já alcança o volume bom de clientes né Já tô conseguindo ter um faturamento bacana ele se acomodam e acabam deixando de enxergar mesmo né o potencial que eles ainda possibilidade né tem muito mais ali pra frente né que vocês podem ainda mais E como que você viu né depois desse tempo todo você entrou no ele ia ser ele começou a ganhar bem começou a realmente transmitir essa confiança pro público e também pros gestores quando você viu que era a hora ele falou não agora eu preciso evoluir mais né Eu acho que o visagismo pode ter te auxiliado muito eu falo que o Além do meu tio se é um cara que me incentivou o Marconi foi um das peças chaves para mim nessa Nesse quesito e quando ele mora em Betim sempre embora com ele assim a gente sempre conversava tudo de tudo e ele estava estudando já o visagismo já ele falava com ninguém você tem comunicação boa para falar com os clientes Ah legal cara de ser bom autoestima primeira o verdadeiro é melhor primeira coisa é melhorar é a gente mesmo entendeu para se vestir bem se comportar bem até uma uma

fala melhor com o próprio cliente não é uma coisa assim mais contar um Senhorzinho assim não é falar um caranguejeira pro Senhorzinho falar um cara mais normal com ele um cara mais bolado outra coisa então o que me incentivou a mudar porque eu sempre fui um cara assim não fico satisfeito com nada nunca não eu preciso eu preciso melhorar eu quero mais quero mais eu posso mais mas também respeitando os processos né a gente não pode passar no limite também tem um propósito sempre propósito mas o visagismo Foi algo assim que nossa isso aqui acho que pode aumentar faturamento comunicação abrindo as mortes que cara Network é muito bom e é sim muitas portas de vida mesmo cara e o louva-a-deus filho de do Marconi que foi um cara que olhou ali ninguém não todo dia era todo dia mas faz faz bom vai dar bom e tá aí hoje né referência aí no visagismo né Um abraço Marcone aí já marcou presença aqui duas vezes contribuindo aí pra gente e a gente fica muito feliz né de ver os frutos aí do trabalho dele também né E você provavelmente vai ter os seus frutos

aí logo cara Graças a Deus eu já fiz já há mais de cinco consultorias cara caramba eu fico feliz e ele sem falar não vou fazer mais não vou fazer mais e é o cara que me incentivando a crescer mesmo cara e como é que foi para você realmente entrar ali no visagismo né a gente tá como às vezes muito barbeiros né querem também passar por esse lado né Não eu quero também alcançar isso eu quero ter essa mudança de vida perspectiva e novaspostas abertas como é que foi para você esse processo né Qual foi o seu primeiro passo ali o que que você procurou né de curso e tudo mais a gente está comentando muito sobre isso quais foram os primeiros passos você deu ali até chegar onde você tá hoje é o primeiro curso foi o que o físico Marconi né por estar próximo ele Na barbearia Então eu vi os frutos dele Através disso eu falei cara vai vingar mesmo é bom cara é a gente sempre foi meio que computador como é que fala é automático que a gente não entende eu quero fazer uma degradê faz para mim quadradinho aqui

e boa mas às vezes eu era legal o sol degradê para ele e deixar um pouco mais cheinho mesmo cara um pouco topete para calma dar uma sombra na testa a gente não tinha essa percepção então trouxe isso para galera e o cliente ficou assim cara realmente nunca pensei nisso isso aqui ó chama Tempra né sim tem gente que tem isso aqui é muito aprofundado André então o cara fazia degradê clareava então trazia muita luz então mostrava mais evidências que fundo então quando eu vi o Marconi falar sobre isso aí interessante Vou fazer o curso Marconi fiz o curso com ele tava estudando mas antes de fazer o curso com ele procurar alguém lá o seu Elise não eu quero fazer uma barba com visagista e alguém sabe não tava no dia e Marconi Rogério né primeiro aí a Brenda né Vamos lá vou falar com ele e aí foi aonde Assim não vou fazer o curso mas vai dar certo é onde compra o curso do Marconi tem estudado com ele ainda a gente pega em alguns livros né muitos livros do Felipe Baruel que é um cara é o pai de referência mesmo

então foi essa a trajetória mesmo do visagismo Marconi foi o cara intrínsecos inicia ele injetava em mim isso aí e foi aonde eu fui criando assim eu fui vendo umas imagens pô isso aqui vai dar certo cara é bom para o cliente tá em tudo né tá tá no cinema tá Tá Na música é muito muito top show demais e engraçado né que lá atrás né você já tinha tido um sentimento relacionado ao visualismo né da mudança de experiência que você trouxe ali para o seu cliente seu cliente né então trazendo já os laços aí principalmente né Eu acho que como você comentou o seu a sua habilidade ele com Deus com desenho né facilitar ainda mais mas cara Além disso né Eu acho que muitos ainda vão desacreditar né Desse caminho mas como você falou acho que o principal fato tá em você não está acomodado é não está é satisfeito ali com o sol que você já alcançou né está sendo Buscando Novas portas Eu acho que isso é uma dica que todos podem pegar né estejam sempre almejando mais né se alcançou uma meta que você tinha colocado Coloca mais uma né

e assim a gente vai sempre mantendo a evolução não é errado né cara exatamente muitas pessoas né inclusive devem estar jogando aí é quem tá no em alta no mercado né quem tá conseguindo entregar mais valor no seu serviço né e muitos fazem isso às vezes por inveja né Por falar em pôr o cara fez isso E aí tá cobrando não sei quando né Ninguém sabe né tudo que o cara precisou passar ali para alcançar aqueles aqueles resultados mas pô falando em visagismo conta pra gente aí né o seu cabelo que tinha uma proporção maravilhosa vai assustar mas Conta aí pra gente como é que foi essa história Então é eu nunca rapei a cabeça cara Não não sempre deixa ele mais cheinho mas nunca cacheado foi na pandemia mesmo falei ah não vou cortar não hoje a gente veio que não vai rolar aí cara eu gostei falei não que legal a galera gostava de Luanzinho do Galo aí porque [&nbsp;__&nbsp;] não cara sacanagem eu queria só Jesus Luz era bonitão não é não Astro de cinema é alguns fala Nossa será que é o Luanzinho mesmo Achei que crescer nunca cortei raspadinho você

corte era moleque minha mãe né mãe sempre faz cagada mas eu raspei agora desculpa recentemente terça-feira do carnaval porque tem um amigo nosso cara que vai passando por um processo de quimioterapia para bater um câncer né já tirou já um nódulo já não é claro né isso e embora tem que fazer quimioterapia que tem que matar células né que fica no sangue cancerígenas alguns amigos novos um abraço potável Otávio Deus abençoe sua vida meu querido está com você nessa aí você vai vencer estamos juntos e levar uma [&nbsp;__&nbsp;] acho Boa tarde vale a pena né cara nosso amigo então amigo nosso bem feliz do Felipe tá lá também a rapou também mas eu falo que eu foi o único que se lascou essa história aí mano É porque eu era um cabeludo todo mundo com o cabelinho mais ou menos três vezes era quase calmo já já estava querendo mais Felipe tem cabelo mas assim fininho um pouquinho bonitinho eu loguinho do Guaraná né cara falei nossa era para passar zero na na no cabelo é mais ainda cara eu lembro que carnaval eu fui para tirar dentes e eu e a minha noiva né

vai ficar bonitinho vai ficar lindinho demais e eu não tenho testa [&nbsp;__&nbsp;] eu não tenho testa e não tem testa evidencia mais aqui essa parte mais intuitiva minha aqui fica mais maior então o cabelo ele controlava aqui o meu rosto tava lindo né até que até aqui rapou mas era passar zero aí eu lembro que ninguém levou a máquina porque quando decidiu Ah vamos estar o dia a gente sai da barbearia tá fechada carnaval falei nossa aí pegou uma Barbie a maquininha com algum vizinho lá e tal alguém levar a máquina nem sei que ele levou a máquina perdida lá na máquina ainda E aí tinha um pente um e a zero e zero aí ele falou assim vamos passar a zero não porque agarrando a máquina e eu tava enfiadinha assim tá pode machucar é machucar não era para Moer mesmo o negócio é porque tava machucando agarrando só tirando lasquinha eu falei graças a Deus passar uma vai ficar menos feio cara mas não adiantou não parece que era Febem assim realmente todo mundo saindo junto ainda no Instagram no vídeo Todo mundo Carequinha assim cara teria seis Carequinha vai ser resolvo né

É mas a a o propósito foi para a gente levar isso para uma mensagem potável a gente tá com ele nesse aí em nome de Jesus você vai vencer isso aí show de bola pra isso não foi por causa disso não isso é conto exagero completamente contra né para mim né Tem pessoas que combina legal demais exatamente você estava com a proporção ali certinha no azeite mas show de bola eu acho que se envolve Principalmente uma uma capacidade muito importante não só na vida aí com de barbeiros né e etc que é subdual próximo né você deixar a empatia ali né deixar de lado aí né até a vaidade né é um barbeiro deixando de lado da vaidade galera Então não é pouca coisa não né mais uma causa Nobre né Vamos torcer pro seu amigo que a Vitória esteja na vida dele mas cara bora lá me conta aí dois pontos que te fizeram mudar de vida assim completamente dois pontos primeiro foi a necessidade né necessidade fazer o homem é verdade não vem de família boa cara assim pai me deu pai e mãe me deu uma educação excelente graças a Deus um

é no bairro lá falar quem é quente não é um cara legal família eu nunca tomei um batido de polícia cara não me parar assim nada graças a Deus tomara que ele né só quando você aparecer de Ferrari aí vamos parar Vai parar tirar uma foto sei lá vai entrar mas assim a necessidade e também aquela ambição boa de de poder crescer pô quero dar uma vida melhor para minha família para minha esposa os meus futuros filhos uma coisa que meu pai não pode minha mãe me dar entre matéria né assim financeiro eu quero dar para os meus filhos e aí ia levar para os netos acho que essa foi os dois pontos que instalou assim pô vamos mudar algo melhor para família e já tem dado vários frutos aí graças a Deus cara conta pra gente aí da sua experiência lá no seu Elias acho que todo mundo tem curiosidade de saber né muitos contaram aí Ah eu comecei lá do seu Elias desde o começo não né E aí como é que foi a sua experiência primeiro quando eu conheci o elismos né voltando lá foi em 2012 para 2013 assim acho bem

no auge dele ele apareceu na tela de esporte do atlético- nome de referência para barbeiro Na época eu conheci ele pra cabeleireiro sempre minha tia sempre a gente fazia alguns cursos de Embelleze e a lojazinha a gente faz dava alguns cursinhos assim uns workshop na época mas para feminino para masculino não tinha descobriu ele falou aí eu passei a ver algumas coisas do Elias assim Facebook se eu não me engano na época ele fez Facebook E aí a gente O Elias tinha um maior grande [Risadas] mas aí foi sim conheci o livro não cara que legal isso aí é interessante o que esse cara vai trazer para barbearia vai ser algo muito grande só que antes do Elias também lá em Contagem tinha uns barbeiros de Contagem mais antiga vamos lembrar do estúdio R tudo o r já fazia isso de vários barbeiros num lugar mas eu não via isso eu só via rede assim de mulheres trabalhando e algum homem lá para cortar é cabelo masculino aí salão unissex né entre os dois lá Então tinha esse estúdio R que até fizeram o gel cara gel Cola gel Cola e não é o gel

parece uma amoeba né e ficava mesmo durinho durinho o meu não era lisão então não ficava não ficava durinho e nem usava mas assim já tinha essa rede já de do Studio R com ele veio trazendo para BH conheci o Felipe tava lá então fiquei bom tempo sendo amigo do Felipe sem pedir ele olha o Felipe coloca eu lá no Eliana nunca pedi isso cara de interesse não mas eu não pedi ele falou Felipe um dia falou assim você tem vontade de trabalhar no Elias falei que é isso cara eu tiro do Flamengo do Cruzeiro do Atlético todo mundo quer trabalhar lá e disse assim vou te indicar você beleza eu já tô trabalhando já nessa barbearia Santa Teresa que um bom tempo aqui em BH E aí eu falei assim não ele não tá tendo vaga cara ninguém quer sair eu falei cara vou orar para alguém sair então vou orar para alguém que queimar seu celular né tipo assim essa música falei eu vou torcer para alguém sair então relaxa sua hora vai falar assim a sua hora vai chegar nem que saia todo mundo mas a sua hora vai chegar esperei quando

2020 cara 2020 é Felipe é um cara que canta também sabe eles tem muitos músicos lá cara e eu toco bate bate na igreja e onde a gente tava gravado uma música dele no estúdio ó ele mentiu né telefone de pessoas diferentes não tô entendendo não tem um monte de banco me ligando aí um monte de operador operadora aí me cobrando aí vou entender não cara se não falar que não não atende só alguém de aí ele falou eu falei porque não pode ser tal Fulano do estúdio tipo sei lá marcar o dia pra você gravar a matéria para nós olha não Beleza então amanhã é amanhã vai é mãe dá para ligar mas essa semana eu falei beleza então aí eu lembro que eu tava de folga na segunda-feira ele falou assim no domingo tava Domingo já um diferente 31 sei lá três sete seis número de banco cara vai me cobrar e não entender cara desceu do estúdio também [Música] é claro que hora 8 horas nossa beleza vamos lá levei meu irmão como como o modelo meu eu não queria eu não queria levar meu irmão porque ele não é muito osso

para cortar cara e cabelo pouquinho passadinho pode ser algo legal que vai ver que dificuldade do cabelo e vai dar certo e aí conheci a galera já o Felipe o Álvaro já sensacional Felipe com seu violão também já antes de entrar Luiz Paulo Luiz que a gente tocava ninguém lá e aí então enfim senti em casa tava nervoso nesse dia na Pampulha que foi oito barbeiros e era quatro quatro vagas duas para salvar e duas sim certinho o Douglas falou ah eu eu e o Lucas tá lá hoje E aí eu tava nervoso eles não fica à vontade Você tá em casa cara avó Elias examinando Luiz desceu todos os líderes das unidades para ver hoje é Prova de Fogo total na salinha lá eu e ele ou não é todo mundo e tinha uma hora fazer corte de barba vamos lá faz você não precisa fazer nada diferente não faz o que você sabe fazer deixou nós muito bem assim muito mais confortável realizar o serviço eu fiz para mim na minha cabeça Nossa lindão a mina na minha cabeça tava lindão eles é um cara que é perigoso né detalhe demais tá certo

né hoje esse ramo essa marca enorme porque ele é um cara que foi sempre da lista e Caprichoso em tudo é sempre em busca da perfeição perfeccionista mas eu fiz legalzinho bonitinho aí no dia falou gente ó agora pessoal do RH vai entrar em contato com quem passou Quem não passou não fica triste fica triste não porque vai ter mais chance ah Deus eu fiz o meu melhor tua vontade eu tô aqui Desligou o gerente né o Ramon você passou para o próprio seleção é agora marcamos você o psicólogo falei que isso precisa que isso nem quando eu trabalhei no posto não precisa ir no psicólogo Não por isso que eu acho que foi errado que eu assustei com a bomba né ficou agora Nossa meu será que vai dar certo ah não falei não é possível agora vai vai conhecer né Aí eu entendi que era para conhecer como é que funciona cada perfil aí no dia beleza eu chorei cara é engraçado porque coisa que nunca abri primeiro o pai cara psicólogo e eu fui embora assim nossa já me lascou errado era Deus aí era o dia de entrevista geral assim ó

individual eu Elias Mike que é o diretor né o Ramon o gerente de duas unidades e o Luiz que era o Barbeiro Líder geral Eles colocaram no meio cara todo mundo assim meu Deus do céu a gente vai entrar aqui é difícil assim mesmo e você faz como é que você é o Elisa tem tudo sobre isso aqui na pasta entendeu tudo mesmo aí foi para conhecer mesmo né aí falou onde contratei pro é porque não se você foi todos foi muito foi muita quem o que a gente pega que isso mas eu contrato não por técnica porque até que a gente eu tenho a gente ensina eu vou dar o treinamento tem na sua cara o barbear a carne que é um dos melhores do Brasil ou melhor do Brasil um dos melhores do mundo só tem fera lá dando aula e a gente aprende agora caráter isso aí não tem como ele falou assim comigo a Renata não tem como ensinar Espero que você tenha caráter também na hora que ela mandou assim o que já decepcionei com muitas com muitos né achando você pessoas boas não foram e Flor já admito aquilo

e também falou para tal Ramon o Maicon uma família realmente o seu Elisa é uma família cara ali eu quando eu saí da Savassi para poder ir para sua oportunidade cara também fizeram baquete de café da manhã acolhe-me uma galera e eu fui muito bem recebido neste lugar quando eu trabalhei nos outros barbearia assim fora feliz eu nem tinha muita rixa de barbeiro Caraí queria mostrar que corta mais um para o outro entendeu não tinha aquela União ali não cara no seu Elisa todo mundo me abraçou não aqui tá junto precisar de mim Toquinho o Jack do lado lá o João que o Barbeiro Líder lá pra te amar aqui a equipe se apoia o Marconi cara assim os cara que eu vi como um espelho assim cara super bem cara assim sabe como família mesmo cara O barbeiro que está no seu Elias cara ele vai entrar sabe bem tá entrando numa família realmente não é porque eu tô lá não porque realmente ali é uma cultura de abraçar todo mundo tá todo mundo no barco todo mundo no mesmo processo e elevar o nível da barbearia e levar mais um livro do seu

Elias mais né então foi assim que eu entrei em sua Elias e a experiência que tá lá cara de falar né Eu amo aquela maca lá Caraca ali se formou assim ó vou abrir uma barbearia no meio do mato do nada só você que é de mais uma cadeira eu vou cara tá lá brincadeira eu vou porque aquela marca lá cara é acho que eles Abrir aquilo ali vai É suscencecional eu acho que fundamental aí foi você saber esperar né o seu tempo realmente né talvez se você tivesse pedido antes né uma chance pedir para entrar talvez atrapalharia você a entrar né ou talvez você nem teria entrado é então você realmente construiu esse sua bagagem né provou o seu valor ali Apesar dele ter falado que ficou aquele negócio Aí você provou o seu valor de vida mesmo né ele conseguiu reconhecer ele através de você o caráter né que você não tenha passado por cima de ninguém principalmente na estrada e nunca postei uma outra cara do candioso espontâneo É sim os amigos meu conhecem assim eu sou energético mesmo purinho mesmo então eu sempre faz o seu trabalho seja você seja você

mesmo [Música] tem que gostar de você pelo jeito que você é essa não pode se mudar sei eu não consigo mostrar uma coisa que eu não sou eu acho que isso vai vendo isso aí e me deu oportunidade de hoje ser barbeiro líder da Amizade Santo Agostinho e tem sido uma experiência muito boa lidar com pessoas um aprendizado Esperança estou estudando muito liderança para poder essa relação é interpessoal que fala né com outras cara é muita mente diferente cultura de barbeiro E aí eu tenho que ir lá fazer lá uma coisa assim mas os meninos são muito bons e eu tô feliz demais meu Deus cara e qual que é o segredo de liderança vai ficar um ponto importantíssimo hoje né em qualquer empresa principalmente Mas eu deixei você faz cada vez mais necessário uma boa liderança nas barbearias e muita gente tem dificuldade nesse ponto né Quais são os aspectos fundamentais aí que você tem buscado treinar né que você tem buscado valorizar para que você tem um retorno de liderança com o seu liderados a gente faz lá muita reunião One que fala né que em prática né aumentou o meu Alexandre Loureiro

que tá na liderança bloqueio legal para você conhecer a necessidade de cada barbeiro porque você com essa necessidade de cada barbeiro você saber o ponto fraco e o ponto forte aonde você pode ocultar ajudar ele não transparecer o lado o lado fraco que pode gerar conflitos entre outros barbeiros que fiquei querendo não a gente passa mais tempo ali do que em casa então manter aquela reunião todo mundo gente bonitinho sendo alinhado respeitando você não gosta de ninguém cara eu não eu não tenho de você eu tenho que te respeitar sim então eu tenho feito isso a reunião com ele pega cortando coletas o que que ele acha feedbacks que pode melhorar e pedindo a confiança deles Olha gente preciso confiar que vocês Confiam em mim respeito pra gente ter o nosso dia saudável que cada um ganhasse dinheiro e moro na casa de boa então acho que o ponto chave é conversar muito com eles entender o que eles precisam necessidades deles entendeu show demais aí ó fica mais uma dica sobre liderança do Kennedy né para quem ainda não sabe o que que é uma One One por exemplo é uma reunião que você

faz aí periodicamente você pode fazer aí pelo menos uma vez por mês com sua equipe né para você justamente entender os pontos fracos os pontos fortes de feedbacks para ele sempre positivos e negativos e peça eles feedbacks também a respeito da sua liderança para que vocês estejam sempre muito bem alinhados né os seus objetos né para vocês terem comparativos ali de um mês para o outro ah você foi melhor nisso e mais nisso daqui você teve um resultado um pouco pior do que mês passado né e conseguir identificar mais fácil de melhorar né O que que tá bom de concentrar mais energia acho que e na prática também se mostrar Exemplo né Exatamente porque se você mostrar exemplo eles vão ver cara eu quero ser assim eu sou muito amigo deles a gente liderança não é mandar não é nada a gente se respeitar e entender A Hierarquia de querer não eu só tenho um arquivo entre eu passo aqui eu passo para o Daniel que é o gerente e depois ele vai saber Então se amigo deles começar muito com eles e mostrar o resultados meus que eles podem ter não você pode ter

na prática acho que o exemplo é o principal assim de começo para um líder né tô aprendendo ainda viu quem sabe até um curso aí futuramente né de liderança O Luiz é muito muito bom nisso bom referência né liderança e cultura né a gente bateu esse papo aí se você ainda não assistiu o episódio do Luiz também fica aí no nosso mais um episódio na segunda temporada então para você ter a confiança dos seus barbeiros é fundamental e você demonstre pra eles né que você seja exemplo em primeiro lugar show de bola liderança liderando mais uma das equipes aí do seu Elias já passou por bastante coisa mas para quem não sabe o que é barbeiro do primeiro civil primeiro brasileiro civil a ir para o espaço né Vitor Espanha é o nome dele conhecido nosso aqui também né conta pra gente como é que foi essa experiência como é que foi lá no começo quando ele chegou Vai contando cara vou para o espaço Você é o primeiro brasileiro civil aí como é que foi essa novidade foi assim eu atendo os primos Os primos dele né na verdade é primo da Marcela que

a esposa dele vocês conhecem que amigos tudo bem O Samuel entendeu aquela relação de amigos para mim assim é meu amigo não é meu amigo toma café comigo aqui vem cá chama para eles bom vamos dar um rolé vão já sair com alguns amigos já assim de criar Na barbearia sendo cliente e aí eu falei ele falou assim vai ter um primo meu cara que tá indo pro espaço mentira eu vi no Instagram dele aí publicano o Vitor Cunha cara esse cara aqui a primeira vai para o espaço eu falei Caraca ele então meu espaço mesmo é espaço de que isso é o que não cara ele vai vai para cima eu falei que isso como ele astronauta primeira coisa é isso a gente pensa né ou ela ou ela musky é irmão do musky parente ele falou não sou esse cara aqui em 22 comprou uma moeda acho que não engano ele tá indo falei cara esse cara aqui não conhecia o Vitor ainda Espanha mano vou falar para ele então ele mora pertinho Santo Savassi cara eu vou entender o vídeo que legal na minha amiga pois é muito bom para mim bom

demais Quem Entendeu eu não sei quem Entendeu Marcos Pontes mas ele vai entender o Vitor quem vai atender um cara com espaço a gente foi fazer o Moral de lá no quarto você encontra no meio do Messi tchau não Neymar todo mundo e emocionada melhorou assim eu chamei ele falou não eu vou marcar para ir lá aí ele veio como é que foi isso aí falei não cara eu vou pra lá pra pra bruxa né exatamente que eu acho que é nessa expedição política Olha que legal cara você pagou quanto milhões no mundo já pensou no mundo inteiro cara eu falei como é que foi você ganhou mesmo ganhei eu falei 9 então eu não dou sorte em nada de sorte cara eu e você eu pego o número 1 você pega o número dois vai cair o dois ou pode ser só eu eu não vou ganhar eu não tenho sorte cara você ganhou foi sorte cara foi sorte foi o primeiro clipe tonalta do mundo ou do Brasil do mundo primeiro se viu do Brasil brasileiro fora da terra né então somos extraterrestre pois assim conhecer o Vitor através do primo dele que

é o outro Vítor vou chegar nesse cara aqui desde então tenho coragem dele ele trouxe para nós um boné da expedição da expedição né cara ele falou assim sério vou fazer um quadro para pôr aqui então tudo que a gente vai lá conhece cara nós cara falei é cliente melhor eu cortei foi bonitão primeiro corte aí pros cara aí a gente eu tava nessa vassoura quando ele foi e a gente viu foi num sábado de manhã até hoje eu lembro sabe de manhã a gente colocou Vamos colocar o cabelo colocou cada um colocou celular ali sei lá todo mundo vê cara esse cara aqui cliente nosso aqui ó os cara quer e daqui pro espaço ele é rico hein cara ele é rico mesmo mas ele ganhou ele ganhou cara que legal mano então foi assim que eu conheci o Vitor até hoje um abraço Vítor é um baita de bem do músico né cara show demais né E mais uma vez aí a gente demonstrando a importância do Network se não você nunca teria se conectado isso e você ficasse ali só no corte de cabelo né só calada bem comunicar um primo dele

que eu conheci e fui e levou para lá então foi muito legal inclusive o Samuel também foi lá assistir né Foi show demais né para ele também inclusive usou do Network dele também né para ir ali assistir lançamento quando o Vitor Foi parece que teve uma alguma falha parece lá e teve que voltar você conhece e também então ele depois ele foi mas a Marcela e aí surgiu uma vaga parecendo um convidado E aí pessoal mexe com essa Gol trabalha na GOL na GOL exatamente com aviação isso acho que seria alguma coisa legal para acrescentar para ele então ele foi demais e a mulher é um cara muito inteligente também muito cara que fez aí a pilotagem do avião da Harry Potter né aquilo ali Foi show demais amigo eu uso isso cara meu cliente fez isso aqui cara é rapaz essa cadeira aqui sinto muito importante eu ia te perguntar Essa era minha próxima pergunta né como é que tudo isso mudou sua vida né Mas você já respondendo aí eu acho que trouxe muito mais representatividade né trouxe uma notoriedade né como barbeiro acho que deve ter agregado muito né demais aí eu

fico feliz demais conhecer essa galera a galera boa lição demais bom demais cara e me conta aí além desses vários episódios que a gente contou né qual que é uma das experiências mais marcantes que você teve aí durante toda a sua trajetória Na barbearia eu acho como eu falei no primeiro lá no comecinho uma marcante foi essa do cliente que eu tive ele mudar a expressão ali e eu falei assim é de mostrar para mim que eu gente eu tenho uma uma habilidade de Mudar em frente do cara através de um corte e a outra foi uma experiência assim que eu tenho até hoje que eu lembro foi dessa do menino do vô né Engraçado era pai mas era vô era pai e eu já gravou às vezes fala até demais né a comunicação Até sobressai em alguns momentos mas marcante boa uma boa uma mas é constrangedora né cara todas todas pensa Legal cara a gente conhece muita coisa pessoas legais tem cliente que desabafa contigo mesmo a gente parece aqueles cara acha que nós vamos psicólogo né Realmente Pode ser que seja Talvez um corte bom dá uma palavra aí a gente tá

lá também pra levar Harmonia levar alegria né assim eu não deixo aparecer se eu tô mal assim num dia cliente ou pouco pra minha equipe que trabalha comigo meus companheiros sempre me ver a gente bem mais claro lá dentro tá mal mas não é bem bacana as pessoas positivamente alegria nesse pacto me fala aí cara você contou muito da sua vida né Principalmente do seu lado pessoal ali do seu caráter né como isso foi se construir ao longo do tempo mas me conta na íntegra qual que é o seu propósito de vida né no propósito de vida o André eu tenho para mim levar além de levar a gente é cristão levar a palavra de Deus né Independente de onde for tem que lembrar a gente nasceu para que esse propósito de levar a palavra a gente eu sou cristão não sei quem tá vendo é cristão se tem a mesma fé que eu mas eu não posso deixar de falar isso né uma coisa que eu sou criado e além de mim mas de levar também a alegria para as pessoas sendo fazendo uma gracinha eu sou um cara muito brincalhão mas eu quero

levar alegria para todo mundo além de levar a palavra de Deus para galera show demais se você quiser mandar uma palavrinha para todos os seus clientes aí um palavrinha incentivo a uma mensagem para o pessoal no vestibular mas nós também temos uma funcionalidade de você disparar uma push notification ou seja aquela notificação do próprio aplicativo ali para todos os seus clientes então se você quiser mandar um bondinho um alô uma promoção cliente que gosta de promoção dá para fazer isso aí dá para fazer isso aí também pelo aplicativo então fica mais umas funcionalidade do best Barbies para você construir uma boa relação aí com seus clientes eu mandaria eles voltar mais vezes você tá atrasado hein e 15 dias já se não vem cara que isso vamos embora essa baba tá espigando aí cara show demais e me conta né além já contou alguma das suas referências né da sua vida mas além do seu tio e do Marconi Me conta aí mais duas referências importantíssimas na sua vida profissional na área profissional pessoal cara uma referência profissional além de meu tio do Marconi e o Elisa não Pode dizer a referência número um profissional

e pessoal acho que não vou falar uma pessoa eu acho minha família é minha referência três pessoas especificamente assim minha mãe e meu pai e minha avó as pessoas é fundamentais aí no meu Caráter na minha pessoa e quem é o que é de hoje que foi o que conquistou inclusive seu Elias uma coisa aí conquistando a outra né seus principais referências né Eu acho que todos os referências que você colocou aí foram as pessoas que realmente guiaram né sempre te colocaram para frente né Eu acho que é muito importante você Estar atento a quem você anda né esteja sempre com pessoas que estejam preocupadas em evoluir né junto com você em ver o seu bem ver você crescendo né ao invés de sugar ao invés de te deixar ali estagnado na sua loja de conforto né Eu acho que isso é fundamental para que a gente esteja constante naquele momento uma mensagem legal que eu queria mandar aqui uma coisa que eu te falava assim sobre estagnar sempre achar que é o melhor cara nunca seja assim sempre degrauzinho vou te falar assim de onde é que você mais que você seja bom onde

você vai ter alguém melhor que você sempre com certeza você é bom aqui mas você vai no outro lugar tem alguém melhor que você lá então cara Não seja picuinha não seja inveja Cola Qual é melhor que você cola nele então eu aprendi isso aí pô eu quero andar com pessoas melhores que eu com certeza igual a mim ou melhor que eu melhor melhor que eu tenho um ano de pessoas melhores que você sendo um bom pai um bom marido um bom amigo um bom cristão um profissional então Mande com pessoas seja melhor que você que tu tem que agregar dele e falar a gente a média das cinco pessoas que a gente convive exatamente se eu conviver com uma pessoa chorona vou ficar chorando mas que eu não sou eu convivo com pessoa triste mas sou muito alegre eu vou passar a ficar triste então a gente tem que saber falar com quem a gente quer conviver né com certeza fundamental para o crescimento né não sou profissional como na vida pessoal né Eu acho que para a vida toda eu acho que ficaram aí várias lições de vida aí com Kennedy nela tem

certeza que deu para agregar muito aí para galera eu tenho certeza que muita gente vai impactada por esse vídeo né muita gente vai passar a buscar novas portas né como você buscou o visagismo para crescer na profissão né nunca se limite ao que você acha que está bom esteja em constante evolução sempre buscando mais né o Kennedy aí é prova de que vocês podem mais né Principalmente vocês barbeiros Kennedy o Marconi é vem trazendo aí uma revolução também Rogério Rogério Araújo Araújo também não pode deixar de falar que um cara que me ajudou muito e conversando Esses caras são sensacionais sensacionais cara mais uma vez obrigado eu te agradeço né o papo foi bom demais eu acho que deu para a gente passar para o pessoal um pouquinho desse né Um pouquinho dessa trajetória muita gente vê o Kenny de hoje lá nas redes sociais né Nem imagina isso tudo que aconteceu na sua trajetória né Nem imagina o caminho que você percorreu até seu O barbeiro do primeiro astronauta se viu brasileira ali né a gente vendo aí que tudo que que você plantou né durante toda essa trajetória você vem colhendo né Eu

acho que isso daí é a prova viva de que tudo que a gente plantar a gente vai colher né Não adianta vocês quererem plantar hoje eu não vou estudar ah hoje eu não vou aprender uma técnica nova né Porque isso pode ter certeza que no futuro você não vai colher nada diferente do que você está plantando né E tenha certeza que se no dia que você não quiser falar hoje eu não vou me aprimorar não vai ter 10 ali do seu lado aprimorando né o mundo da barbearia tá cada dia mais intenso né as pessoas estão cada vez é mais capacitadas né apresentando um serviço cada vez uma qualidade maior então a corrida é grande não é igual antes né Que legal saiu uma semana fora da barbearia Hoje não dá para sair mais não dá isso aí né mas a recompensa vem né não é à toa que você transmite essa confiança né para os seus liderados não é à toa que você conquistou a liderança dos seus líderes né Para que você tivesse essa responsabilidade hoje né não só como barbearia mas com vidas eu acho que o mais importante é isso Você

já demonstrou a sua capacidade de se doar o próximo né com seu amigo aí mais uma vez um abraço para ele então ficou um abraço para todos mais uma vez muito obrigado muito obrigado foi ótimo prazer meu amigo um recadinho legal aqui para vocês aí que quer fazer que já são barbeiros e uns que vão entrar estão pensando em entrar se tão passando entrar cara pensa bem ó porque não tem volta não é babela quando o cabelo te pegar rapaz é apaixonado pode demorar um pouquinho igual eu demorei mas vai apaixonar então espero que a galera aí Estude bastante hoje tem muito material mas você não tem condição de vir fazer um curso com com a sua referência com Elias cara hoje tem hoje tem YouTube um monte de ideia que hoje tem até Rios mostrando algumas técnicas legais então esteja ciente assim seja pronto para poder aprender se quiser aprender vocês vão longe cara tem gente que tá indo longe alto de data Então vale a pena então foco nos estudos e que Deus abençoe todos vocês muito bem esse foram as palavras do nosso futuro palestrante é tipo Cid Moreira né tomara que

Deus te abençoe aí que você me disse muitos cursos né que se for da tua vontade também né Eu acredito que você tem muito potencial né Tá cercado de pessoas aí que podem te ajudar a alavancar isso também né um futuro aí de muito sucesso para você meu amigo muito obrigado André mais uma vez estamos juntos obrigado abraço para todo mundo que nos acompanhou até o final desse Episódio até o final da segunda temporada do best Barbie Esse foi um prazer estar aí com vocês se você quer melhorar seu atendimento melhorar seus agendamentos proporcionar uma experiência personalizada para os seus clientes baixas tá aí o QR Code na tela e um abraço valeu [Música]`,

  summary:
    "Episódio 7 da Temporada 2 do BestBarbers Podcast. Kennedy Ricardo compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
