import type { VideoContent } from "./types";

export const podcastalldrik_silva_S2_ep03: VideoContent = {
  slug: "podcast-alldrik-silva-s2-ep03",
  youtubeId: "2LnAZixSIQI",
  title: "BestBarbers Podcast com Alldrik Silva — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 3 da Temporada 2 do BestBarbers Podcast com Alldrik Silva. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "alldrik silva",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2023-02-13",
  duration: "1:18:57",
  category: "Podcast",
  tags: ["podcast", "temporada 2", "entrevista", "gestão", "barbeiro"],

  transcript: `[Música] senhoras e senhores sejam bem-vindos a mais um best barbras podcast é sempre uma honra ter você aqui conosco para quem ainda não me conhece eu sou o André um dos donos aqui do best barbers e hoje eu tô aqui com o convidado mais que especial para quem conhece esse cara sabe o tanto que ele é diferenciado É uma honra tá te recebendo aqui hoje obrigado por ter aceitado um convite cara a gente tá aqui com o áudio que hoje dono da folk barbearia queria que você Contasse um pouquinho Quem que é o Walter que dá onde surgiu essa vontade de ser barbeiro quando surgiu um pouquinho da sua história lá então Bom dia pessoal como ele já disse meu nome é Audrey Obrigado pelo convite mano fiquei muito feliz de estar aqui espero que agrega alguma coisa aí beleza vamos lá pessoal eu tenho 27 anos brincando 34 é só para dar descontraída aqui parece ter menos né tenho 34 anos sou casado casado há sete anos tem uma filha de 5 aninhos e um enteado de 17 anos e cara a minha história é um pouco até engraçado assim porque me desafiou o

tempo inteiro a ter decisões em times em tempos corretos sabe eu aos 27 anos estava prestes a casar e tive que tomar uma decisão cabulosa na minha vida porque eu simplesmente acordei num dia e falei assim cara não tô feliz tô feliz aí você imagina cara de 27 anos Crise existencial né não tô feliz mano que que eu faço aí fui dar uma analisada na minha vida 27 anos formado em design gráfico eu trabalhei cinco anos seis sete anos meu pai tem uma gráfica então quis fazer o curso para ajudar o meu pai e aproveitar também que eu gostava muito essa questão de fazer arte de ajudar as pessoas de alguma forma que trabalhava com ele com seu pai trabalhava com meu pai fica no longe da minha casa barato tudo bonitinho e tal mas ela não gosta da minha gata você imagina folga inclusive pegar uma hora da tarde aí eu acordei e falei assim Deus eu não tô feliz não tô feliz que que eu faço e eu percebi cara que eu não eu não estava feliz por causa da minha profissão eu amava o que eu fazia como eu te disse eu

tenho tda e então acabou que eu ficava muito disperso para mim isso era muito ruim porque o que eu gastaria normalmente uma hora 30 minutos para produzir ou demorava um dia inteiro para produzir porque tudo chamava minha atenção né E nesse dia eu acordei e falei assim eu preciso fazer alguma coisa preciso fazer alguma coisa tomei um banho e Deus muda minha história não tô aguentando mais trabalhar com esse jeito eu queria trabalhar com pessoas eu queria lidar com gente eu não consigo lidar com computador direito feliz um banho cheguei no escritório né telefone foi muito come cara porque eu sentei o Telefone Tocou falei assim Estrela da Manhã Boa tarde Boa tarde praticamente pegava nove tava lá quase meio-dia e cheguei atendi o telefone era um amigo meu e até psicólogo hoje e que Gandra e ele falou comigo assim tava pensando aqui em você cara tem uma coisa para poder te falar eu preciso que você escute até o final sem falar nada eu falei nossa difícil aí eu falei não pode falar mano vou ir para isso pode falar e ele começou cara a falar de uma vez que eu já tinha

cortado o cabelo dele falou cara vamos lá Você cortou meu cabelo uma vez e foi o melhor corte que eu fiz na vida e você nem sabe cortar velho você nem é profissional da área você não pensa em fazer um curso aproveitando E você já corta no seu Elias cortava nessa época o inicio dele mesmo tinha uma loja inimíssima e aproveita esse time que você conhece o seu Elias faz um curso é um cara comunicativo você vai conseguir eu falei cara não penso não quero e não vai dar certo isso você trabalhava ainda na gráfica trabalhava na gráfica Você trabalhava na gráfica e já tinha começado a trabalhar com seu Elias não é nessa época eu trabalhava na gráfica e não era mais nada né Não era ninguém não tinha uma segunda opção aí cara no final da conversa eu sei que no final da conversa eu já tava com um curso marcado por outro dia eu falei ah preciso marcar preciso fazer esse trem mesmo para eu ver se vai dar certo cara eu encarei aquilo como uma resposta de Deus mesmo sabe porque cara porém três horas antes depois de três horas um

cara me liga me oferecendo uma nova profissão me dando uma perspectiva totalmente diferente da que eu tinha aí só pode ser Deus né condição talvez não era resposta que você esperava mas exatamente né não era mesmo tipo assim você estava totalmente fora de cogitação da minha cabeça meus pensamentos aí eu sei que no final da conversa eu tava com um curso marcado para outro dia e comecei a fazer esse curso cara comecei a perceber assim que ele dá com gente era meu chamado mesmo sabe ele tá com pessoas eu gosto aí eu fiz o curso comentei com seu Elias cara que que você acha se um dia fosse barbeiro Olha me deu ao apoio mano falou comigo cara seria fantástico é um cara comunicativo ser um cara tenho certeza que se daria bem e vai dar certo cara vai dar certo mais ou menos uns cinco anos atrás mais ou menos uns nove anos atrás meus nove anos atrás E aí eu me empolguei cara de fazer o curso na metade do curso eu tava voltando para casa Fui descer uma rua ali no centro um carro passou em cima do meu pé então eu

tive que é que mudaram a direção do trânsito lá não tinha sinalização aí eu fui atravessar a Rua Pau Ferro aí no final das contas eu só acalmei meu ônibus e falei assim bom se for de Deus vai ser tá certo aí eu consegui recuperar terminei meu curso terminando o curso eu lembro que o Elias falou comigo assim cara vou abrir a unidade no Belvedere não na Santa Rita Durão na Savassi se você quiser fazer o teste você pode fazer o teste e se você passar vai ser por mérito não porque você me conhece ele Bom agora vamos forçar mais ainda além de tudo me desafiou eu não sou nem um pouco competitiva Putz velho eu vou ter que esperar lá ainda mais quente desafiando né eu falei não tem jeito velho vou tentar ser o melhor vou tentar não eu vou ser o melhor aí cara eu lembro que tudo foi encaminhando assim para eu poder seguir essa profissão e tal Eu lembro que nessa época tinha muito preconceito né famílias que já não iniciavam nessa profissão depois se tornar essa profissão eu não era nem por questão de preconceito mesmo era porque são

de capacidade tipo assim eu nunca imaginei que eu fosse capaz cortar um cabelo ele não acreditava não acreditava Total Eu sei que eu sou bom manualmente um cara competitivo eu encareço como desafio aí eu fui e fiz o teste cara fiz o teste e eu lembro inclusive que tinha 12 pessoas para poder fazer o teste eu fiz o teste eu acho que era até mais eu passei no teste e como que eu soube que eu passei no teste porque eu cheguei em casa cara depois do que eu fiz teste cortar dois cabelos degradê de zero e o outro todo a tesoura ele dava nota na hora assim 7:30 meu Deus do céu Parece que minha nota foi uma das maiores sabe não foi a maior e eu falei então tô no caminho velho aí ele falou que ia abrir a barbearia lá e que ia demorar um tempo aí eu falei assim bom durante esse tempo eu não vou fazer nada só morrer e tal e depois talvez surgir ali do lado e mesmo quando está fazendo curso ainda continuada trabalhando na gráfica eu continuar trabalhando na gráfica e paralelo cortava o cabelo de todos

os meus clientes eu sou cristão congrego na igreja debaixo eu tinha muito amigo lá né eu era do louvor e tal fazer teatro e o pessoal me conhecia então tipo assim todo mundo começou a me dar moral velho ah corta o meu cabelo corta o meu cabelo ai quanto que você paga para cortar cabelo assim quanto que eu cobro né quanto que você cobra pra cortar cabelo eu falei Ah velho r 30 tá bom o cara falou não vou te pagar 50 porque eu pago aonde eu ó aí eu começava a cortar cabelo cortava do pai dos filhos os amigos do grupo de amigos todos e eu falei assim bom já tá dando certo já legal na frente né coisa que para mim é quase impossível Eu vivo o momento ali vivo na hora ali cheio de ansiedade aí cara é paralelo gráfica e senha do barbeiro eu tive que casar eu já tava no processo ali no trâmite para poder casar aí eu lembro que chegou no dia do meu casamento O Elias foi lá no meu casamento e tudo mais aí no final do casamento ele falou assim cara falar logo que eu

tirei uns seis Nossa meu cara sacanagem tá querendo frustrar na cara de mel é isso mesmo né Aí ele falou não mano eu estou aqui para poder falar que você passou cara bem vindo a equipe revoltada da lua de mel passa na barbearia pra gente trocar ideia foi foi um presente de casamento e essa questão da barbearia né era cheio de preconceito preconceito tipo assim ah abre uma portinha ali corta cabelo você consegue pagar suas contas e não é bem assim cara é eu consegui perceber que essa profissão é a profissão que ela te dá sonhos ela te traz pessoas incríveis na sua vida é você consegue ajudar pessoas incríveis que aparecem na sua vida então assim Resumindo mano eu consegui entrar nessa profissão me apaixonar por ela assim de uma forma extraordinária porque eu me descobri né Essa profissão que eu descobri que eu quero lidar com pessoas gosto de gente e quando você tava ali no seu Elias você já imaginava que você teria todo essa mudança na sua vida que vocês chegarem cara Eu Assim de verdade coração eu tenho 30% da minha caminhada dos sonhos sabe tudo que eu planejo se

tudo der certo a gente vai longe em nome de Jesus eu acredito que vai dar né eu vou fazer da depende de mim e que depender de mim eu vou fazer dar certo mas eu já entrei lá sabendo que eu faria algo diferente a pessoa muito grato inclusive isso confiado no meu trabalho tão novo eu era o Barbeiro mais novo que ele tinha tinha seis cinco meses de profissão quando eu comecei de fato trabalhar com ele você tinha mais ou menos quantos anos ela época eu tinha acho que 27 e meio tudo muito rápido e eu tinha cinco meses de profissão então isso me limitava bastante né pelo fato de ser novo na profissão trabalhando na barbearia mais top de Belo Horizonte e um dos mais novos lá dentro né também todo mundo lá tinha 12 17 anos de barbeiro eu tinha 5 meses e eu lembro de uma reunião antes de inaugurar a barbearia dele e ele fez uma reunião e falou assim Bom eu não sei porque que a agenda do waldric preencheu o mês inteiro mas a agenda dele antes de abrir a barbearia já tá cheia já tá lotada Mas eu

sabia cara ele para mim era uma resposta de que ia dar certo sim era uma resposta exata é uma resposta de que algo grande estava por vir primeiro porque eu tenho total consciência de que o que eu quiser eu sou capaz é eu sou capaz de aprender o que eu quiser sou capaz de fazer o que eu quiser depende de mim aí eu não tenho Barreiras contra isso e segundo que Deus está na frente de tudo para mim vai dar tudo certo e nessa reunião foi engraçado cara que a gente estava discutindo e falando assim Nossa será que é porque o nome dele começa com a o nome dele é diferente ainda para mim não é isso para mim Deus ele encaminhou as coisas tudo certinho e durante toda a minha trajetória do seu Elias Foi algo assim milagre atrás de milagre mesmo porque eu lembro de várias vezes em que eu fui para sala de química joelhei Lá Chorei falei Deus eu não aprender esse trem rápido eu tô ferrado eu vou é uma bomba aqui então dá um salve aqui agora porque senão não tá dando Como que eu faço um degradê naquele

cara ali o cara bonitão saiu daqui pior do que entrou Então qual é o meu objetivo Deus meu objetivo é transformar a vida das pessoas Então eu quero que elas saem daqui mais bonitas pelo menos né exato e a experiência que eu tinha era tão engraçado que tipo assim é uma pessoa que também me ajudou muito na trajetória eu não poderia de mim deixar de mencionar que foi o Rafa o ele me ajudou muito ele falava assim Ah então agora você vai querer fazer um pompador Ah agora você vai querer fazer um midfage falava alto para eu poder ouvir e eu ficava muito de perto lá vendo que ele fazia e ele começou um cara muito visual eu aprendi a fazer as coisas né e me ajudou muito nessa trajetória e para mim cara foi assim extremamente importante ter essas pessoas do meu lado e eu lembro que a gente tinha tipo um código de falando assim ah tem um caminhão parado na sombra ali porque tinha um degradê com sombra e o que faziam as pessoas voltar no início trabalhava lá Não era nem meu corte cara era tipo assim era o tanto que

eu conversava com os caras era tanto que eu dava ouvido para os caras não tipo assim além de tudo essa profissão você percebe tipo assim eu vou ter sucesso vou ter sucesso que que você precisa ser um bom ouvinte de ser um bom vinte em primeiro lugar né em primeiro lugar você precisa ser um bom ouvinte porque você vai primeiro você vai entender o que a pessoa precisa né e traduzir o que ele precisa no rosto dele ali visagismo toda ali uma composição logo cara mais difícil ainda então tipo assim era um desafio era mas eu consegui entender a profissão de design me trouxe muito esse feeling praga essa essa percepção então assim eu sou muito grato inclusive pelo meu curso eu fui preparado na vida aí para poder chegar nisso né foi tudo milimetricamente preparado no futuro exatamente aí como é que foi né pô acho que deve ser a curiosidade de muita gente aí como deve ser trabalhar dentro do seu Elias ainda mais que você pegou ali desde o começo você acompanhou com o Rafa com a equipe ela desde o começo também como que foi essa experiência você comentou um pouquinho

do Rafa da experiência que a gente ajudou também e a experiência com Elias e trabalhar na barbearia em si como é que foi então eu nunca tive problema em trabalhar para as pessoas eu acho que isso é normal vai dar para e a experiência que eu tive trabalhando trabalhando no seu Elias foi a melhor experiências a melhor experiência que eu pude ter no ramo porque foi a primeira e única que eu assim eu não tive tanta referência assim para poder comparar mas a minha experiência foi o seguinte eu entrei cara eu entrei com a cabeça do seguinte ó eu entendo a proposta que ele tá me fazendo e eu aceito a proposta que ele está me fazendo nunca pensei em sair de lá e fazer algum mal sabe fazer alguma coisa que várias pessoas fizeram né várias pessoas fazem inclusive já entram querendo fazer e o meu propósito era ajudar mano ajudar e ser ajudado e obviamente a aprender era o meu propósito principal tanto com o cliente quanto com Elias quanto com tudo né e eu me propunha assim a ser uma pessoa que se precisasse eu tava ali toda hora eu lembro que

várias vezes por exemplo a a faxineira faltava às vezes às vezes eu mesmo ia lá limpava o banheiro fraco porque meus clientes iam usar o banho o tempo todo em busca de serviço também busca de serviço né para poder ajudar as pessoas então tipo assim o lidar com Elias era legal porque eu via que ele era referência do ramo né o cara da referência em Belo Horizonte e tal e obviamente eu já conseguia perceber que ele ia ser referência mundo inteiro e tá do lado daquele cara ali que eu me inspirava muito que eu via cortando o cabelo e fala caramba cara anja mesmo o cara é bom e me inspirar nele sabe então tipo assim tá do lado dessa pessoa tá do lado dos melhores que tem glamourinha que tem visibilidade para várias barbeiros queriam estar no meu lugar ali para mim foi muito legal é muito bom estar vivendo aquilo ali e poder experimentar inclusive poder separar o que eu queria do que eu não queria ali você teve oportunidade de ver na prática né exatamente então tipo assim eu vi alguma situação falando assim bom um dia eu vou ter minha barbearia

eu entrei lá com essa convicção inclusive você já sabia já sabia que eu terei minha barbearia Um dia vou ter minha barbearia e eu não quero isso não quero isso era aquilo eu quero muito isso Poxa velho isso aqui eu quero para lá é absorver faria sentido então assim no final das contas é a minha estadia lá no Elias foi foi boa para caramba aprendi muito a minha base inteira de lá é tudo que eu sei tudo que eu aprendi tudo que eu pude pesar na balança ali foi lá eu trabalho lá quanto tempo trabalhei dois anos e meio pouquinho e ajudar muita gente e foi experiência assim resumindo foi foi ótimo cara imagina que ter uma pessoa como seu Elias como mentor como exemplo né como alguém a se espelhar né ali do seu lado foi fundamental para depois você abrir a sua barbearia Fundamental e uma coisa que ele fala que ele falava ele falava que ele fala não sei se ele fala mais é certeiro é o seguinte você pode fazer o que você quiser da forma que você quiser e as pessoas sempre vão reclamar é as pessoas elas sempre reclamam

Isso é do ser humano essa questão de reclamar às vezes de se sentir injustiçado de se sentir abortado ali Isso é do homem isso é do ser humano mas como eu disse eu já entrei sabendo de todas as propostas para mim foi bem tranquilo lidar com isso né mas o que eu aprendi além de tudo né é o ser humano vai reclamar em qualquer situação é que não importa que as pessoas vão dizer que você sobre você sabe importa de fato é sua intenção tem intenção de ajudar tensão e ser bom errar você vai errar mesmo todo mundo né Assim como os outros erram até mesmo Você às vezes é de reclamar de ficar ali só murmurando é pa pa no final das contas o que vai importar cara é o que você tá levando de legado que você aprende e e o que você tá fazendo É acho que se a sua intenção for boa de fato e se tiver ajudando de fato quem entrar lá entra dentro desse molde sabendo e no final das contas todo mundo vai reclamar eu vou reclamar todo mundo reclama então tipo assim Isso não sai da minha

cabeça sabe assim e não importa como que você é se você é bom se você é mal se você é ruim se você é um Carrasco se você é um gente boa ou sempre vão reclamar então assim o que eu faço é independente de reclamarem ou não eu faço é porque eu quero fazer e é o meu propósito é um propósito muito claro muito bem definido né independente os outros vão falar você vai se entregar ele realmente senta pregar me fazer o que eu posso ou que barbearia Há quanto tempo que tá aberta cara fogo que tem quatro anos já cara fiquei dois anos sozinho para entender do mercado para poder entender de empresa né entender de do meio é porque quando eu trabalhei no Sueli eu entendi de barbearia de forma operacional ali quesito corte de cabelo visão como barbeiro né e paralela conseguia pegar uma coisa outra ali de Dona né mas eu me preocupava mais em ser bom primeiro como barbeiro depois eu tinha meta de pensar em como gerir em ser um bom gestor né e na folk quando eu fiquei dois anos lá sozinho lá [&nbsp;__&nbsp;] tá no cabelo comecei

Além de estudar sobre isso eu comecei a perceber que se eu continuasse daquela forma eu seria só um barbeiro cara aí eu falei assim gente várias crises né são várias crises Aí eu falei que que eu vou fazer para eu não ser só um barbeiro e quando eu montei estrutura lá e que pareça tinham três cadeiras mas eu nunca Corri atrás de barbeiro para poder trabalhar lá eu queria primeiro misturar ele primeiro montar ali Uma mega estrutura quesito conhecimento né para eu poder entender como é que funcionava mesmo e depois até pensei em contratar barbeiro até tive duas tentativas lá fracassadas porque acho que mais por causa do local onde eu abri na Galeria né e eu lembro que além de tudo cara ainda vem a pandemia mano a pandemia me deu uma quebrada assim cabulosa Há muitos né Muito acho que todos na verdade de alguma forma foram prejudicados com isso eu lembro que eu falei assim meu Deus aí que eu particularmente obviamente ninguém mas eu tava falando de mim é eu não consigo ver o que tá ali na frente não consigo ver Exato eu consigo ver essa catástrofe como que vai

ser não consigo saber se eu vou morrer ou não se alguém da minha família vai morrer então eu fiquei assim desesperados o que que eu faço não Continuo trabalhando Vou para casa corta cabelo aonde vou na casa dos clientes então acaba que eu fiquei assim enloucaço mesmo ontem de um dia tá voltando para casa e parar o carro e chorar cara assim umas duas horas direto totalmente sem rumo ao chegar em casa e minha esposa não perceber que eu tava norteado a minha filha e tal e eu lembro que nesse dia eu dormi de boa e tal aí falei assim nossa cara eu acordei pior do que eu levantei ontem hoje eu vou fazer possível para chegar o mais tarde possível em casa para eu chorar a noite inteira descarregar tudo que eu tenho para descarregar para atender os clientes no outro dia de boa e parar sozinho né Aí eu lembro que eu atendi o pastor Léo Lá da IBC pastor dos jovens lá eu atendi ele fez um Stories tal e falar Galera tô aqui com o audrick eu cortando o cabelo aqui esse cara que sempre me deixa bonito papá uma propaganda

e eu já tava com agenda lotada me ajuda graças ao bom Deus ela fica lotada assim se eu mental do dia da semana aí ele fez e eu tava atendendo todos os dias assim com muito medo muito receio mas a pandemia e beleza esse dia a gente tava lotado ele fez os Stories e tal ele ligou um cara eu acho que era umas 5 horas da tarde ele ligou e falou assim cara eu vi um Stories do Léo do pastor Léo ele corta cabelo com você eu tô precisando cortar cabelo Você tem horário hoje eu parei pensei em dois segundos assim Bom eu tô querendo chegar tarde em casa chorar a noite toda Eu tô querendo ganhar dinheiro porque eu tô atolado de dívida e eu não tava conseguindo pagar velho tô chorando porque eu tô sem dinheiro por causa de tudo mas tipo assim eu vou atender esse cara velho de qualquer coisa eu vou chegar mais tarde então tá bom vou atender ele não cara chegar 8 horas aí meu horário termina 8 horas ele falou não 8 horas para mim é perfeito eu quero chegar assim aí eu falei velho Demorou então

fechou aí chega lá um cara velho pequenininho lá e tal bonitinho lá 8 horas Ah você quer o audre que eu falei sim cara então eu vi sua história lá no no Insta do Leo e tal Eu falei não cara prazer falou prazer meu nome é Vinícius falei assim pô mano prazer ter você aqui Que honra Obrigado vamos lá aí ele sentou na cadeira e eu cortei o cabelo dele pá ele tinha uma barba ali mas meio que por fazer sabe eu falei cara você não vai fazer não ele falou não não quero fazer não porque minha barba não tem jeito aí ele falou cara não aceita esse desafio eu falei mano vou fazer sua barba de graça você vê que tem jeito sim cara melhor sei lá com as vidas lá eu terminei a barba do cara e ele usava óculos né Aí ele colocou óculos falou assim no cara que isso ficou ótimo a minha barba nunca imaginei que minha barba fosse ficar desse jeito aí eu falei ah mano fica assim isso é porque eu não trabalho no ramo então tipo assim você não consegue ter essa visão né mas deu para

ver que teria muito potencial sua barba Tem jeito sim ele falou assim Ô Pois é mano Adorei Muito obrigado por tudo fiquei super feliz eu nunca tive esse corte de cabelo minha barba ficou fantástica pa pa eu vou casar eu quero que você corta meu cabelo mas Deus mandou te falar uma parada aí eu já gelei né mais uma o cara vai me expor que agora tô brincando eu falei ah é um abraço mas vem cá um abraço aqui aí ele falou assim não cara não é um abraço não mano ele mandou te falar uma parada aí eu falei tá Fala logo pelo amor de Deus ele falou primeiro Deus mandou eu pagar r 500 no meu corte aí ele falou que só vou ter que baixar aqui o dinheiro resgatar o dinheiro né e te pagar e segundo cara que Deus mandou falar que quer para você ficar calmo mano para você se acalmar porque ele não vai deixar faltar alimento na sua mesa e que nenhuma da sua descendência vai mendigar o pão Isso é uma promessa eu falei assim ele falou Não cara é a primeira vez que eu vi o cara

primeira vez que eu vi a primeira vez que eu cortei o cabelo dele eu fiz a barba e o cara já falou algo tão íntimo meu ali aí você desabou chorar de novo eu comecei a chorar cara eu falei assim tudo que eu ia chorar a noite eu chorei naquele momento ele me abraçou a gente Olá uns minutos lá meio que desabafando sabe e no final das contas assim eu chorei tudo que eu tinha para poder chorar naquela noite e a convicção de que Deus estava no controle da minha vida na minha família as minhas contas da barbearia essa convicção ela se tornou um gigante ainda maior no meu coração mais do que a pandemia mais que a incerteza mais do que as dores mais do que tudo eles fazem ansiedade e me trouxe paz então o que que isso me trouxe mano uma segurança de que tudo estava no controle então tipo assim eu já comecei a virão gigante né se eu era o Davi pequenininho ali que ia matar o Golias eu fiquei maior que Golias e Pisei no Golias e voltei para casa contei para minha esposa e minha esposa também chorou

ficou muito emocionada e deu certo cara a gente conseguiu passar por essa por essa tempestade e deu certo e não só deu certo Você já foi lá na barbearia ela a nova lá você viu nesse na pandemia ainda surgiu a oportunidade de alugar uma loja Maior alugar uma loja maior e eu falei assim doideira né mano eu já tô aqui né para poder ficar parado não é para desafio e para a loja Maior o investimento altíssimo no meio da pandemia Pega dinheiro emprestado gastei limite do meu cartão inteiro isso era só você de barbeiro ainda só de barbeiro ainda gastei o limite do meu cartão inteiro que eu tinha que eu não tinha Liguei lá aumenta meu limite por favor o que eu ia fazer depois eu não sabia mano mas eu falei aumenta meu limite Aumentou e Opa tudo lá e fiz uma estrutura para cinco cadeiras tem cadeira de barbeiro aí nesse meio próximo nesse meio do processo apareceu alguns barbeiros assim que davam trabalhar e tal que já tinham clientes eu coloquei os caras para poder trabalhar comigo e montei a folk lá na rua mesmo né de Morais lá e tô

lá tem dois anos entre o sul aqui de Belo Horizonte uma das barbearias mais magníficas que temos mas acho que muitos barbeiros né pensam que vão abrir que vai sair tudo certo que o ter uma clientela já e por cortar bem vai ser tudo fácil que vai conseguir encher que vai conseguir também mas vai muito além disso E aí logo se saiu do seu Elias você já abriu a barbearia não logo na hora logo quando eu sair do seu Elias eu fiquei 7 meses em casa e 7 meses cortando em casa de algumas pessoas que eu conseguia e captando no novos clientes né mas não foi fácil não cara porque hoje principalmente hoje né tudo é muito caro e eu tava sozinho né mano assim tudo foi muito caro e eu não tinha essa esperança que ia dar certo quando eu saísse não sabe tipo assim logo de cara pá eu sabia que ia dar mas eu não tinha esperança que fosse dar certo logo de cara entende aí eu fiquei sete seis meses em casa saí montei a galeria depois passou dois anos e pouco mantenha da rua mas montar uma barbearia ela tá

muito além de uma estrutura né ela tem que ser uma parada que tipo assim óbvio que ela se sustentar mas A grande questão ela tem que ser uma parada muito consciente porque a minha intenção era nem que eu trabalho de dia e de noite eu vou pagar minhas contas isso pensando pois isso quando é montar uma equipe vai agregar eu vou conseguir captar mais clientes automaticamente mais dinheiro e melhorando as coisas da forma que eu puder né então assim fácil não foi eu tô pagando até hoje né várias coisas mas mais do que isso é você poder ver que a barbearia lá folk né Nós temos como propósito são lá fazer com que a pessoa saia melhor do que ela entrou isso é o básico Mas esse eu como cliente sentar e olhar para o espelho e ver a minha melhor versão caramba não sabia que meu cabelo poderia ficar assim que a minha barba poderia ser assim isso não tem preço a transformação né uma transformação de fato é isso que Deus fala na vida de todo mundo de quem quer né quando Deus ele tem a proposta de bater na porta ali isso

é abre se quiser entra ali ele vai entrar Se você permitir da mesma forma com o cliente se o cara permitir que você faça o seu melhor aí você tem que dar o seu melhor né conscientemente e apresentar para essa pessoa melhor versão dela então esse é nosso objetivo da folk além de tratar e atender super bem é fazer com que o cliente saia de lá com sua melhor versão e que Surpreenda tanto ele quanto todo mundo que tá em volta dele não é simples simplesmente um corte você olha e fala Pô mano você sempre tá de cabelo cortado né é só isso não cara você tá diferente mano é uma coisa diferente no seu rosto aí tem um corte de cabelo Pode parecer ser simples é só um corte de cabelo mas não é corte de cabelo tem toda a questão do visagismo que eu sempre apliquei quando feliz ou já conhecia isso no design em toda uma questão de rosto tem toda uma questão de formato de cabeça de tudo né tipo assim vai muito além mano então nosso objetivo na fogo que é esse né de fazer com que as pessoas saiam

de lá transformadas a sua melhor versão e que isso seja feito com uma técnica muito boa é tipo assim muito bem cortado eu até passei pela experiência legal esses dias você sabe que eu fiz uma uma massa na Smart Fit Prudente O gerente lá convidou cinco empresas e ela falou que foi uma delas e eu tive uma experiência engraçada cara que tipo assim eu fui dar uma feito para ele lá né de desconto que a gente tava dando para os alunos da Smart aí ele virou e falou assim eu falei cara vai lá na barbearia a gente tá aqui com desconto de 20% de uma parceria com Smart em três anos dela aqui aí a gente tá dormindo aí o cara falou assim ó você também tá precisando cortar cabelo eu falei então aí que você se engana porque a proposta da voo que não é cortar cabelo para as pessoas verem que tá cortado a proposta da full quer fazer o que você gosta dentro dos moldes do seu rosto e da forma que você cara não é para mostrar para ninguém para você mesmo e eu me sinto muito bem dessa forma do

jeito que eu sou eu quero Luan que que resposta diferente resposta diferente porque a maioria das pessoas querem é que você senta na cadeira que você faça um degradê ali que você faça uns padrões é uma maquininha Puff está igual puf jogador de futebol [&nbsp;__&nbsp;] igual Puff jogar futebol e é isso que é que é o parâmetro não meu parâmetro é fazer o que você gosta cara fazer tipo assim eu gosto de passar a máquina um caramba só a máquina um é se você me der se você me permitir que sugerir algo Eu Vou sugerir mas se não eu vou fazer com a máquina um ser o melhor corte que você fez na vida entendeu Aí o cara achou engraçado e tal e falou assim Vocês são diferentes mano eu vou lá e já marcou já foi já cortou e falou que de fato teve uma experiência ótima então assim cortar cabelo é muito além transformar vida das pessoas tá muito além de um simples corte Um Bom atendimento isso é sede tu é sede mais do que isso transformar as pessoas na melhor versão delas né Exatamente porque isso é isso é poderoso mano

a pessoa não vai esquecer de você nunca fora que muda a autoestima do cara muda o dia dele né como ele vai lidar com as pessoas a confiança é e a gente tem uma experiência louca lá tipo cliente que vive e fala cara vou fazer uma entrevista de emprego hoje ia cortar meu cabelo falou não tem jeito Cuidado então isso é confiança é eu tenho várias clientes cara que são adolescentes 20 e Poucos Anos o cara só olha no espelho quando vão pensa ele não olha em casa assim o cara não confia na própria imagem dele não gosta da própria imagem dele e quando tá Na barbearia ele tem a oportunidade de lidar com ele mesmo na melhor versão gente então tipo assim eu encaro isso como a missão muito sério porque é sério pode parecer ser banal ele pode até ser para alguns mas para mim não é pensa ser cara chega lá você raspa a cabeça dele na zero o cara não tava esperando tem um cabelão Pô acabou o dia dele então tudo isso seja de muita confiança muita gente penso nisso Graças a Deus eu nunca errei um corte mas já

pensou cara que situação chegar lá você tá bonitão seu cabelo da última vez hein como um cara aí meio esquisito velho é para quem não sabe vir aqui égua máscara né não tinha como ficar diferente nós você imagina o resto é muito além disso né você concentrar ter ali uma dedicação eu entendo assim se o cara tá pagando Qual é o seu preço né o preço é x eu tô pagando r 100 para 40 minutos para um corte de cabelo esse 40 minutos é seu cara e a pessoa tem que respeitar isso né tem que envolver ali começar a trocar ideia com essa barra e para chegar num bom resultado é e eu levo isso muito a sério mano muito a sério a minha equipe também a gente tá trabalhando para poder seguir essa linha em princípios princípios e a vida não empreendedor Acho que em qualquer ramo não é fácil você contou e várias dificuldades você teve principalmente pandemia Mas eu acredito que tenha fatores né que auxiliam muito nisso eu acho que um dos principais aí que você falou desde o início é o seu Network né as pessoas ali da sua rede

da igreja todo mundo conheciam indicando o outro e que fatores mais você acha que foram essenciais para você superar principalmente essa crise erguer a barbearia e ter todo sucesso que você tem hoje cara primeiro uma boa esposa esposa é excelente assim a questão da administração toda dela né e ela é a mulher que me coloca com o pé no chão ela é mulher que quando eu tô voando demais ela puxa minha corda assim é exatamente é ondulado é bom você ter uma pessoa ótima do seu lado uma pessoa que Acredite nos seus sonhos mesmo que duvide de deles a pessoa que te apoie mesmo querendo não apoiar com pé muito no chão mas eu consigo lembrar assim com muita gratidão de que todo esse processo só foi possível porque eu tenho uma mega esposa você que tá do meu lado me apoia que me ajuda na administração que não me ajuda pirar e que me situa ela me lembra de quem eu era de quem eu sou eu me lembro do tempo de profissão que eu tenho seu propósito meu do meu propósito onde tá difícil contar tudo ela fala assim olha ele é mais

barato isso sempre me citou sempre me coloca aonde eu devo tá mas um outro ponto importante é a questão da ousadia né o sair ele já é um romper né imagina um parto uma criança quando sai está rompendo um cordão umbilical ali com a mãe né E esse romper cordão ele é para vida inteira aí chega um momento em que a criança não não se vê não se vê mais a mãe ela sabe que ela é um ser e a mãe é outro outro romper acha agora de casar outro romper Ah chegou a hora de morar sozinho talvez outro romper então tipo assim é um constante com pimenta e essa essa questão de você ser usado e você romper essa questão de você ter essa ousadia é você tirar essa questão da sua cabeça de que não vai dar certo sabe tipo eu nunca pensei assim vai dar errado cara eu juro por Deus e você simplesmente começar ali com um sonho pensando vai dar certo vai dar certo e ter essa ousadia de fazer com que tudo ande de acordo com o que você acredita sabe é não tem erro na minha cabeça não

tem erro eu não consigo pensar nisso vamos lá tem uma pessoa magnífica do seu lado ter ousadia né E esse filho de empreendedorismo cara eu não adianta por exemplo você só um barbeiro querer abrir uma barbearia e achar que isso dá certo só porque eu corto cabelo bem exato então é melhor talvez você trabalhar para uma pessoa e só cortar cabelo bem Afinal de contas se não existisse pessoas que cortam cabelo bem e que são bem remunerados porque para mim tem uma coisa tem muito a ver com a outra e não existe dono não tem um equilíbrio ali né então assim quando você é o dono remunera bem existem essas pessoas todas que confiam no seu sonho e que também tem sonho que são bem remuneradas não tem erro todo mundo vai ser feliz ali certo então esposa ou uma pessoa a ousadia o empreendedorismo e esse Network para mim é o que mais me ajudou sabe por eu conhecer muita gente por esse é um carajado falar falar bastante tá lá na igreja fazer teatro cantar e engraçado é você ver você tá falando de Network mas não adianta só ter né Tipo você

tem que ser um bom vendedor cara tem que vender sonhos né vender vender uma boa aparência para galera é muito muito melhor do que eu falar assim mano você pode ficar bonitão Cara eu tô chamando cara feio né Aí você fala assim você pode ficar melhor do que você já é duas abordagens diferentes com o mesmo propósito né e torna ali um desafio para o cara né desafio pro cara eu tô na academia trabalhando o cara fala ah você trabalha não trabalha com que trabalha na barbearia É mesmo você corta o cabelo lá corta cara que que você acha que dá para fazer no meu cabelo eu falei mano eu te garanto que você vai ficar bonito que você já é velho nu velho sério toma aquele choque porque aí ele duvida né vou ter que ir lá para conferir vou ter que ir lá o cara vai dar certo velho o cara vai dar certo mano eu sou preso aqui então assim essas cinco coisas né que até uma pessoa boa do seu lado exato e isso é um bom vendedor né vendedor é um bom vendedor Eu acho que isso é fundamental mano

em qualquer área da sua vida né é o peso tem aquele velho ditado né Por trás de um grande homem tem uma grande mulher mas eu falo que ao lado de um grande homem sem ser uma grande mulher fundamental do lado seria sua esposa ou não né Eu acho que no seu caso aí principalmente ainda ela te ajudando na gestão né algumas não chegam a se envolver no negócio mas tem alguém ali te apoiando acreditando em você e te sustentando né assumindo sua bronca Então eu acho que é fundamental e o homem precisa disso né mano como né que a mulher dá uma alavancada nele a gente não é de ferro também e tem pessoas que acham que sim tem acho que tem que ter uma barbearia tem outras que realmente não levam um jeito para isso e tudo bem também sem ser barbeiro né trabalhar com ele de alguém né eu vejo não como uma ela de subordinação mais escala bateria não é à toa que se chama salão barbeiro salão parceiro isso né então acho que é o que agrega muito mas a pessoa nunca pode fugir do seu propósito ali dentro né

Eu acho que ela tem que estar bem alinhado com os seus objetivos com seu propósito a linha sua linha de trabalho e acho que gerei pessoas é uma da parte mais difícil do empreendedorismo é muita gente acha que é fácil igual a você né pô um cara despojado que conversa bem que faz amizade fácil e isso não é tudo né para você gerir pessoas e como que hoje né você vê que é fundamental ali o que que é fundamental para você conseguir escolher as pessoas certas se você já escolheu pessoas erradas que deram errado e como foi todo esse processo a sua esposa te ajudou também nisso então eu no início eu não tinha parâmetro né Eu simplesmente escolhia às vezes cumprir uma necessidade minha naquele momento ali se pagar a conta ah vem qualquer um aí pa sabe tipo aí isso foi durante o primeiro ano da nova ou que né ah tem esse cara aqui que apareceu sim assim assado o cara tem cliente para papar Ah então é isso mesmo Vem vem cinco pessoas fechamos assim mas eu descobri que não é bem assim cara Acho que toda empresa quando tem valores

quando tem meu objetivo né valores e tal você não pode passar por cima dos seus valores por para contratar alguém para preencher buraco para uma necessidade e isso é uma Isso é uma bomba uma mina dentro ali da sua barbearia que vai explodir que vai estourar questão de tempo então primeiro você sabe quais são os seus valores depois da entrevista né hoje o currículo do Barbeiro é o Instagram mas depois da entrevista você consegue ver se essa pessoa de fato está alinhada aos seus valores e se ela não tiver Sem problema nenhum até porque ela vai alinhar com valores de outras pessoas descarta manda embora desapega desapega OLX não dá aqui não é o seu lugar existe um lugar para você mas aqui não é e baseado nisso cara a gente toma muita porrada na vida né tem muita muita porrada mesmo na vida porque acaba que ser contrata uma pessoa em que você só tá precisando ali do que ela que ela pode proporcionar esquece dos valores esquece do seu objetivo e essa pessoa além de ter uma mina de baixo da tela Minas eu o ambiente de trabalho contamina tudo e acaba tornando

o seu lugar ali um lugar que não é bom para trabalhar né um lugar que não te traz alegria um lugar que armado o tempo inteiro porque ao invés de parceiros são seus inimigos concorrentes aquele tempo todo ligado e essa experiência não é só minha não essa experiência eu acho que é de todo mundo que contrata e contrata né contrato você é uma pessoa é não cumpre com seus valores com pré-requisito ali de seus valores cara não tem que pensar em que demitir mesmo de falar assim permitir não né no caso demitir funcionário teve parceiros você só encerra contra ela cara já deu o nosso nosso contrato e tal e a gente não vai renovar o contrato com você e ponto final porque de um problema que você pode se livrar rápido você demora para resolver Você pode ter vários problemas de Neve né e vira uma bola de neve com certeza absoluta e às vezes você pede uma pessoa boa que tava alinhada já com você pela contaminação dessa outra pessoa e o ser humano é muito muito corruptível né você consegue achar que que aquela pessoa tem Total razão que aquela pessoa tem

certeza que ela tá fazendo tipo assim né então você adota aquela causa a gente tem vários exemplos disso na história né as pessoas más pessoas horríveis e como Hitler por exemplo tem várias pessoas compraram a ideia dele como se fosse uma verdade e foram até o fim e isso em pequena escala dentro de empresas acontecem as pessoas pegam aquele pensamento daquela pessoa ali torna ele absoluto e começa a enxergar uma visão que nem é dela uma visão totalmente deturpada né E nem é dela mas ela adota e pega aquilo ali para ela e não pegam só para ela como também começam a disseminar aquilo ali Exatamente é isso e você pode achar assim que é até engraçado e você pode achar que eu você é um cara despojado para conversar para papar tudo mais não é fácil demais lidar com pessoas mano é meio pior defeito é esse é o meu hoje lidar é minha melhor qualidade vai gerir Talvez seja o meu meu como é que fala que o pessoal aquele ditado o defeito não é meu espinho no meu Spinner porque eu fico naquela ficava né Agora Eu Tô estudando Tô fazendo altos

cursos você fica naquele assim é ah eu vou fazer isso para agradar fulano Ah fazer aquilo para agradar esse plano e não é bem assim cara a empresa tem valores tem seus princípios tem seu objetivo e tudo mais tudo tem que andar de acordo e dentro disso porque se gira fora da sua visão tá fora da sua expectativa Então já saiu Então tá desalinhado você entra nisso tá alinhado mas quando o cara quer fazer tudo para agradar todo mundo acaba um sendo desagradável e quem não pode ficar desagradável dessa história é você que é o dono né esse você fica as coisas não gira não andam aí contamina também então tipo assim essa parte digerir é muito difícil cara é muito difícil e eu não sabia até abrir a nova folk mas paralelo a isso a gente vai estudando e vai aprendendo vai tomar porrada na cara para poder aprender e é isso tá tudo certo né Eu acho que lugar nenhum é obrigado a trabalhar sim mas quando você trabalha você é obrigado a vestir a camisa né e outro desafio que é gigantesco em uma barbearia que eu vejo a não ser Elias

eu não podia acompanhar tanto né Porque eu trabalhava na linha de trás da recepção é recepção é recepção é tipo assim eu costumo brincar que a gente contrata decepcionista porque cara cada decepção que você fala é Putz velho você vive fala com um cara assim ó eu te contratando acho que você tem Total perfil você tem total direito de sair e arrumar outro emprego pode ter clareza sim você pode estar andar na luz com a gente ó arrumei um outro emprego vou ganhar mais e tal então eu já quero te avisar para poder te alertar ou então que eu tô no processo seletivo não vou ter descartado por isso você tá sendo honesto inclusive tô no processo seletivo para poder participar disso aí eu vou torcer para o cara passar inclusive né Mas andar na luz é essencial porque isso o cara vai ter tempo de treinar o outro recepcionista e tudo mais e assim mesmo você falando isso você desenhando é mandar mensagem você lembrando você falando todos os dias o cara te avisa cinco dias antes cara vou sair semana que vem segunda não posso vir mais é muito comum né nossa pessoas

não pensam duas vezes antes de deixar na mão né ela não pensam duas não penso em você não pensam em nada não posso no futuro é indicação inclusive cara aquele cara trabalhou com você uma vez na recepção trabalhou ah trabalhou o cara sem indica ele não não indico indico uma decepção só tem decepcionista mas até que eu achei alguns bons caminhada aí que graças a Deus né cara seguiram também o sonho deles Ah e tal assim esse é um Desafio gigantesco também barbearia e pessoas boas do seu lado ali que não quer jeito recepção mesmo te ajudar e tal e eu sempre Procuro honrar muito essas pessoas sabe com Um bom salário e tal e mesmo assim não tá dando certo não é muita gente acha também que não tem que pagar Um bom salário né que é e como aí Pronto né decepção em dobro é difícil motivar alguém ganhando exato ganhar bem eu já reclama ganhando pouco já reclama mas já devia ser o Elias lá atrás né sempre alguém vai reclamar de alguma coisa ele vai reclamar de alguma coisa então tipo assim isso já é esperado né já tá na conta

aí ó para quem quer ser empreendedor Essa é mais uma das coisas aí do check-list você vai se decepcionar e muito e muito é realmente a gente aprende muito na porrada né a gente você também como o nosso caso a gente não teve quem nesse iniciasse a nossa carreira de empreendedor né quem nos mentorasse quem nos desse conselhos ali né e a gente aprendeu muito sofrendo Mesmo errando né perdemos muito dinheiro nessa né com toda porrada você vai ó tomando de dinheiro ali vai você tem uma decepção mais dinheiro que foi embora então um ponto que você falou é fundamental né o conhecimento muita gente acha que já conhece o suficiente que já sabe o suficiente mas eu acredito que conhecimento nunca é demais é e faz a gente subir do neném ali quando nasce né E tem rompe o cordão umbilical ali dentro da barriga da mãe ele tá numa zona de conforto né ele recebe alimento ele não precisa fazer nada tá tudo confortável Tudo ótimo para ele mas tem um mundo lá fora polícia é muito mais né para esquecer evoluir eu acredito que assim a carreira do empreendedorismo na nossa vida

né E como tem sido o conhecimento o conhecimento é trouxe para você como te fez crescer aonde ele te fez chegar como você enxerga isso hoje então eu como eu te disse eu tenho muita dificuldade em concentração e tudo chama minha atenção né eu busco a forma a minha fonte de conhecimento assim eu busco de uma forma diferente primeiro que eu vejo muitos exemplos eu sigo muitos exemplos de pessoas mesmo que estão ao meu redor como empresários como empreendedores Ouço muito os exemplos negativos também que as pessoas falam que as pessoas acabam transmitindo ali e agora arrumei um novo vício que é ouvir audiobook é que eu consigo ouvir cara eu vou para casa ouvindo no carro eu colocar um fone ali talvez eu consigo ouvir isso em algum momento específico só preciso dedicar Então essa busca de conhecimento ela é pelo Network né tipo assim que eu tenho é ela vem do Network ela vende exemplos mesmos né do Network e agora essa questão do livro que eu tô conseguindo ouvir e de cursos né tenho vários amigos que que a gente quer inclusive um curso de inteligência emocional esse curso para mim cara

foi literalmente um divisor de águas porque você lidar com pessoas né chega um momento em que se você não for um cara inteligente emocionalmente eu chuto o pau do barraca velho vai falar assim velho você tá aqui ganhando x você tá aqui com todo comodidade que você pode ter um ar condicionado ele tá aqui assim sem assado mas o quê mano sabe tipo Poxa velho aí você fala assim gente não espera aí inteligente aqui emocional quem tem Inteligência Emocional aqui sou eu então vamos lá isso tudo interno né mano mas o que que a gente poderia fazer para melhorar o estadinho aqui e que a gente poderia fazer para melhorar o seu dia aqui melhorar sua vida aqui dentro aí você se situa começa a ter mais empatia você começa a ter mais sabedoria ao falar essa questão do tom de voz isso manda demais velho estando do tom de voz do da forma que você fala e isso tudo Eu consegui aprender que é inteligência emocional mesmo é igual aqueles dois exemplos que eu te dei são duas coisas que se falam duas formas diferentes com o mesmo objetivo e que uma é muito

bem ouvida e a outra é uma ofensa entendeu então assim é Um Desafio também eu consegui falar de forma de forma com que as pessoas não se ofendam e isso Eu só aprendi fazendo curso assim curso gestão de que seja uma pós né são de pessoa questão de negócio inteligência emocional psicólogo isso é importantíssimo na vida de barbeiro na vida de empresário na vida de empreendedor na vida de vida entre vida tem que fazer e essa é um controle é se você não tivesse essa percepção de que você precisa estar bem emocionalmente e estruturalmente e no conhecimento obviamente são três coisas as coisas não andam não então tipo assim você tem que estar em dia com a sua cabeça indica o seu corpo indica o seu conhecimento porque porque o seu adversário entre aspas porque não é um adversário ele ele tem conhecimento ele tem tudo que você precisa ter então ele tá à sua frente é a partir do momento que você tem tudo que ele tem tá caminhando para o mesmo para mesma direção estão lado a lado ali Nem tem porque trabalhar em prol da destruição de um outro alguém você trabalha

em prol do seu negócio para crescer tanto quanto aquela pessoa que hoje é maior do que você então você só aprende isso com conhecimento conhecimento ele literalmente Libertador quando você se conhece eu falo se conhece de Fato né quando você conhece o seu corpo as suas intenções conhece o seu eu aqui dentro por mais podre que seja por mais escuro escuro que seja por mais não consigo lidar com gente eu tô fingindo o tempo todo eu preciso conhecer a partir do momento que você se conhece você se liberta a partir do momento que você se liberta sabe lidar com isso você controla esse gigante aí dentro aí para você fazer o bem para os outros você primeiro tem que estar bem com você mesmo exatamente se o cara vier aqui com o pé eu vou chegar com dois pés no peito dele então o que que eu preciso fazer para poder mudar isso é inteligência né emocional então o que que eu preciso fazer aonde que eu acho isso quem vai fazer isso por mim então você precisa se situar o tempo inteiro nisso daí para você poder ter essa fonte de de busca de

conhecimento aí que para mim hoje é para mim é importantíssimo né eu hoje vejo que essas todas essas fontes de buscar conhecimento de buscar crescer aprender como empreendedor como pessoa como barbeiro com tudo tem vários Fontes né mas eu consigo absorver de poucas pouquíssimas Fontes Eu por exemplo não consigo ler é muita dificuldade com a leitura começa a ler cara é além de entrar em Nárnia eu fico assim um sono da Branca de Neve ali mano terminou a página nem sabe o que que falou lá no começo a grande questão é essa primeira eu falo assim quer dormir Lelê ler alguma coisa você vai ler a Bíblia você dorme com 3 segundos né você vai ler um livro você lê que chega no final do lixo gente que eu tava fazendo aqui gente quem está na minha mão então assim eu fico até Comprei aquele Nárnia não comprei nada com a minha filha aí é engraçado que eu tô lá no meio do livro lendo ela vira e fala assim essa mulher aqui é aquela filha e ela é um leão ela vira e fala assim Uai pai falou né aquela menina que tava com

aquele menino que fazia isso assim eu falei filho deixa ele aqui de novo aí eu vou voltar filha é isso mesmo Nossa hein nem eu tô precisando ela só testando né e eu consigo cara então assim eu busco da forma que eu posso que é ouvindo hoje tem várias mechas de conhecimento né antigamente É aí ó Mas para todo mundo e me prende podcast né porque eu consigo ouvir e ver e eu acho muito peculiar isso por ser uma coisa dinâmica então isso me pega assim me prende e a gente tenta o tempo todo trazer também situações da realidade das outras pessoas né que a sua dificuldade Pode ser aqui muitos vão enfrentar né muitos daqui o que você tá falando precisam ouvir né vai ser fundamental pra carreira deles pra eles serem bom empreendedores ou bombas bons barbeiros é então a gente sempre tenta Traz esse conteúdo também da vivência a partir do pessoal viveu isso é legal e cara é vamos lá falamos de que é importante né pra vocês isso é um bom empreendedor ter sucesso aí na sua negócio uma boa pessoa do seu lado é uma pessoa forte que vai

ampliar que vai te ajudar que vai te levar pra frente Network conhecimento pessoas que estejam alinhadas com seu princípio com princípio do seu negócio é com seus valores e principalmente que você esteja com tudo isso muito bem definido né antes de qualquer coisa que seja você vai ser barbeiro ou dono de barbearia né Independente de lugar que você tiver é muito importante que você esteja alinhado tenha muito clareza dentro dos seus princípios né e o cara se você tivesse que dar um conselho antes né hoje para quem quer abrir um negócio quer começar um negócio que que você gostaria de ter escutado né que que você gostaria de tivessem te dito lá no início que que você poderia falar pessoal cara então é eu queria muito ter ouvido um Se prepare no Tô brincando tô brincando não queria se preparando é porque o negócio é o seguinte esse se preparar é algo que tipo as pessoas falam muito sério na vida tipo assim ah eu só vou ter filho quando eu tiver isso ah eu só vou começar a empreender quando eu tivesse isso ah eu só vou começar a se eu vou casar quando

eu tiver isso esse isso nunca vai chegar se você não tiver o que você almeja sabe tipo assim por exemplo o que eu queria ter ouvido lá atrás você literalmente assim cara a única pessoa que vai fazer isso dar certo é você então se prepara mentalmente e o resto vai dar certo assim eu tenho todas as características que eu preciso e eu tenho todas as habilidades que eu preciso ter Mas tem uma mente fraca tenho pensamentos fracos em uma pouca estrutura mental isso é minha ruina eu tipo assim eu queria ter me preparado psicologicamente um pouco melhor hesito mente mesmo vida para eu poder passar desse por alguns problemas ou menos dor de cabeça porque eu acho que isso essencial Sabe aquela teclinha enter e fica batendo ali o tempo inteiro tipo assim vai dar errado vai dar errado lá vai mais aqui eu tô ganhando menos por dia cara isso tudo de fato acontece mas isso é o início né No início nunca é fácil né não é fácil que as pessoas precisam entender é o seguinte se você já começa com limitações e ponderações e te fazem ter menos já perdeu já perdeu

você tem que ter um foco você falou então a meta tem que ter a missão e tudo gira em torno disso não tem porque dar errado cara em que eu vá Rua e decotes grátis para as pessoas experimentarem nem que eu vá em empresas e fala cara eu sou um ótimo barbeiro eu tô aqui hoje para poder cortar o cabelo de todo mundo 0800 para vocês conhecerem meu trabalho inserir o que eu faço nem que eu tenha que fazer uma ação para cortar cabelo de mendigo um mês direto para poder transformar a vida daqueles caras dentro do que eu posso e nem que eu faço qualquer coisa só depende de mim o que eu queria ter ouvido lá no início é exatamente isso cara você acredita que vai dar certo acredito então se você acredita mas ninguém precisa acreditar e vai dar certo sabe essa saúde mental isso que te dar força né te renova exatamente então assim é o início não é fácil mesmo o início tem cara de que vai dar errado o início tem cara de que queria loucura o início tem cara de que fazendo aqui mano fazendo esse dinheiro poderia

ter investido ele poderia ter feito o início tem cara de tudo mas o meio e o final cara de fato assim quem quem dá essa cara é você muita gente desiste né antes de realmente dar certo né a coisa vingar se quiser dar a cara para o negócio lá de que deu errado vai dar errado se você quiser dar a cara de que foi um sucesso vai ser um sucesso aí se você quiser dar uma cara que eu desistir é só você desistir e muita gente fica procurando né motivos Ah não deu certo por causa disso não dá certo porque Fulano ressaltou coisa ou na hora certa porque como se depender de outra pessoa se depender de outra pessoa e não depende depende da gente Cara depende só da gente isso é principal a todo mundo acha que é um dos mais outros fatores aí para você ter sucesso né Sempre tá acreditando no seu propósito sempre acreditar em você e correr atrás é que não adianta você falar não tô com uma com o pensamento super positivo isso aqui vai dar tudo certo mas tô lá sentado na barbearia esperando só os clientes entrarem

é então não dá nessa nessa experiência louca das minhas Eu lembro que acordava hoje eu acordei 5:30 da manhã todos os dias né aí Eu malho de 6:30 parece não mas eu mais 6:30 até 7:30 chega na barbearia umas duas horas antes arrumo tudo que eu tenho para arrumar espero meu primeiro cliente chegar mas o que que eu falo dessa rotina eu criei uma rotina para poder dar certo e eu lembro que na transição de uma barbearia pequena para barbearia grande que eu tenho hoje eu levantava 6 horas da manhã pegava meu pai na casa dele levava para barbearia nova para ele fazer o que Ele pudesse fazer lá para poder me ajudar para adiantar na obra eu ia para minha barbearia pequena lá trabalhava de 8 horas da manhã até 8 horas da noite saía de 8 horas da noite atravessar a rua ia lá para barbearia nova era até 3 horas da manhã 3 horas da manhã pegava meu pai levava para casa meu pai ia dormir no outro dia 6 horas da manhã tava na porta do meu pai pegava meu pai essa rotina foi um mês cara caramba então tipo assim

eu não parei eu fiquei o tempo inteiro em movimento e pensando em estratégias pensando em o que eu poderia fazer para melhorar para ajudar assim além de trabalhar em pé o dia inteiro eu trabalhava na obra fazia um monte de coisa cortava concreto lá com a Makita eu mesmo fazia o acabamento de uma parede eu fazia o que eu gostava lá porque eu gosto de ter a parada tipo assim aquele ali foi eu quem fiz sabe é o meu jeito eu gosto exato me dedicava da contratação das pessoas e tudo mais no horário que eu podia né Mas eu sempre do meu lado sempre me ajudar e uma coisa que eu sempre fico pensando assim eu penso nisso na realidade o tempo inteiro é estar sempre em movimento claro que chega um momento que você tem que parar para poder pensar e reestruturar talvez para poder ter estratégias e tudo mais mas estar em movimento é essencial eu não cai nessa questão de ficar sentado esperando sendo que não tem mais nenhum durante é você ter uma ousadia o suficiente de pegar talvez a sua cadeira de barbeiro e colocar na rua e cortar cabelo

na rua para as pessoas verem e de fato ele tem a barbearia o que que esse cara tá fazendo vai acabar a luz um dia na barbearia lá eu peguei minha cadeira buguei na rua cara luz do dia luz do dia Total chuva e tanto a gente passando tantas coisas acontecendo todo mundo vendo alguns criticando outros rindo outros elogiando zoando brincando e tudo mais aí teve uma menina que criticou aí um cara chegou para ela e falou assim moça você tá criticando ele porque ele falou ah porque ele tá aparecendo cortando o cabelo aqui na rua ele falou por isso que no mundo Existem várias pessoas que choram e outras que vendem lenço você no caso é que tá chorando aí o cara tá vendendo nem se ele tá correndo atrás dele então ao invés de falar corre atrás do seu a mente é a mulher ficou meio sem graça assim e tal e eu fingindo que eram dois de pausa ali cortar na cabeça e corta o cabelo na chuva na rua para mim não tem tempo ruim não ia reclamar de alguma coisa né Segue o baile então assim é isso que você

falou é essencial cara achar que ficar sentado ali as coisas se resolvem não resolve o barco e todo mundo acha que o áudio que cortou lá no seu Elias né fez uma clientela tinha uma clientela dele aí pessoal da igreja e tudo mais e agora a barbearia dele tá bombando né todo mundo acha que isso é do dia para noite que foi só pelo PES que você tinha no senhor ali ou pelo que você foi construindo mas não veio né tudo isso ao longo do caminho todas as dificuldades enfrentou sei colocando a mão na massa lá reforma Na barbearia mas tudo isso mostra o quão importante né você está sempre alinhado com o seu propósito de dedicação e principalmente tá bem com você mesmo né pensando que tivesse bem com você mesmo Como é que você ia dormir 3 horas por dia buscar seu pai motivar o seu pai motivar sua equipe e tudo construir a sua vida ali né tá em jogo então é um fatores muito importantes fazer aquela rede acreditar né Você acredita se nem você acredita que ele vai acreditar né Na inauguração eu não dormi né Ei dois dias virados

e no final eletricista tinha que entregar o serviço 6 horas da manhã para eu conseguir limpar a barbearia tirar aquela sujeira inteira para poder pegar os outros móveis da outra para poder passar para essa e os caras terminaram 5 horas da manhã e a barbearia o primeiro cliente era 8 horas da manhã aí foi tipo assim eu limpei ela cabulosamente rápido Liguei para minha mãe meu pai e eu preciso de todos vocês aqui agora para me ajudar a limpar a barbearia acabei eu tô trazendo os móveis para cá com amigos que inclusive são muito gratos que me ajudaram nisso é de repente fica aquele Comboio lá chego dois carros parando minha mãe meu pai minha irmã Meu irmão meus sobrinhos é todo mundo começou a limpar a barbearia aí eu já tava cara eu tava Baiano já meu corpo já estava funcionando mais e me ajudando sair até fumaçada pensacionalmente lotada aí eu falei bom vou para casa agora fui para casa minha sogra peguei minha sogra Levei minha sogra para minha casa para olhar minha filha e minha filha não ia colocar todo lá aí minha esposa veio comigo minha esposa me ajudou a

esposa de um barbeiro meu também ajudou e cheguei na barbearia barbearia já estava funcionando já tava todo arrumada com os móveis que eu já tinha colocado Tudo limpo tudo certinho recepcionista luz câmera ação e e todo mundo começou a trabalhar e o dia foi excelente no final do dia fui fazer corte de Barro porque eu tava Igualmente e dormi na cadeira sonhei horrores falei assim cabuloso mano terminou 5 horas o dia foi uma benção cara e Nossa foi difícil demais e no outro dia era domingo aí no outro dia ele começou tudo de novo então assim é dias e dias sem dormir noite de noite sem dormir e foi cabulosamente cabuloso não deu tudo certo eu corri muito atrás não parei de apoio me ajudou e no final das contas assim eu não eu não dei lugar para preguiça né para para esse pensamento negativo eu simplesmente agora vamos embora todo mundo me ajudou trabalhou em prol disso e o negócio deu certo então assim os bastidores não são não tinha nem lugar para isso não cara poderia até passar na cabeça né tipo assim nossa queria ter dinheiro para alguém fazer o que eu

tô fazendo porque isso é puxado isso é pesado mas eu tô contando a minha história é E fora que tem mais dois pontos importantíssimos aí né além de semeadura né hoje a barbearia é Falcão sucesso por vários frutos foi plantando ali dentro do caminho e outra coisa que acho que muita gente tem dificuldade né que você comentou e agora de pedir ajuda é todo mundo acha que tem que fazer por si só né que é sustentar eu dou conta não quero pedir ajuda para ninguém até mesmo para Depois eu que fiz é importantíssimo né você contar com as pessoas né contar as pessoas certas também né Isso é fundamental mas não tem medo de pedir ajuda também se você tem condições paga alguém para fazer se você não tem faça e se você não consegue fazer tudo sozinho Peça ajuda acho que ajuda você já vai ter o resto da sua vida né como empreendedor inclusive você não vai estar contando com ajuda você vai remunerar as pessoas por isso é um pouco diferente é compensar elas pelo trabalho né mas ajuda é essencial depende da sua família você ter ajuda dos seus amigos né

passa sem envolver os caras né pedir essa ajuda porque para carregar uma cadeira cinco cadeiras aliás para carregar uma cadeira é fácil agora cinco cadeiras já foi espera aí difícil o que que eu preciso para poder fazer isso de braço quem tem braço vai é família Então se pedir ajuda aí cara é um reconhecimento de que você é um ser limitado até porque você vê que de fato para o resto a vida você vai ter colaboradores vai ter pessoas ali que vão te auxiliar e te ajudar dentro da profissão delas sempre sempre Depende mas tá na cadeira para estar em pé para estar limpando para estar lembra das pessoas e ajuda no início aí ela é fundamental para poder tornar o seu negócio um negócio de sucesso por muitos muito esforço É uma história muito bonita de contar mais uma vez obrigado por ter aceitado o convite mas cara vamos lá já é um sucesso mas acho que não é o teto né da barbearia fogo que Quais são os planos aí do Aldo aqui da folk barbearia para o futuro então a folk cara eu pretendo cada dia mais crescer né com ela é

hoje no mercado Belo Horizonte Eu acredito que a gente tem essa questão da comissão do barbeiro um pouco diferenciada mesmo Por acreditar mesmo na em honrar a mão de obra Apesar de que isso é dificílimo fazer porque no final das contas a barbearia tipo assim ela era lucra né mas a gente no lucra tanto quanto se esperava no car mas eu não vejo problema nisso a partir do momento que todos estão felizes e tá todo mundo sendo bem remunerado e barbearia ganhando particularmente que ela passa a não ganhar e tem algum problema Você precisa de rever isso talvez começar do zero de novo ela precisa mas eu quanto folk pretendo depois da barbearia já tiver rodando sozinha né porque sustentável justo pensar em outras unidades em outros lugares estratégicos E além disso passar por digital em algumas coisas em que a barbearia hoje está se tornando referência né que a questão do atendimento eu acho que tá assim no mercado já tá pode até ter um pouco saturado a entrar em outras questões aí no mercado e tal mas a gente não pretendo sucumbir não sabe pretende seguir na nossa linha que tá dando certo

e se for preciso for dar uma repaginada dá Talvez uma mudadinha algumas coisas a gente também tá super aberta a estudar também ia pensar mas eu quero assim fazer com que a folk cresça nesse princípios fazer com que ela falou que cresça para ajudar mais pessoas e de fato passar um pouco mais para o digital também para poder ajudar mais gente né tipo assim escalar que eu vejo que é um bom mercado então assim só esperando o momento acontecer na hora certa vem né Na hora certa vem e eu tô trabalhando para disso se você tivesse que descrever Qual que é o diferencial da folk hoje qual seria então cara nossa diferencial é na folk além de um bom atendimento de um bom corte é você conseguir de fato é ouvir o seu cliente e transmitir aquilo dentro do corte porque o desafio do barbeiro literalmente é reproduzir o que a pessoa espera então tipo assim nós temos todo um contexto assim por exemplo aí eu quero cortar assim assim assado se eu ainda assim fico em dúvida ou fico assim não será que ele tá querendo dizer isso se existe margem de dúvida margem

de dúvida era mostra uma foto cara Mostra uma referência então assim o nosso objetivo principal é fazer com que todos os clientes de lá da barbearia saia com sua melhor versão isso dentro da proposta do cliente né o cliente chega e fala assim ah eu quero raspar com zero aqui mesmo que eu vejo que é impossível cara fazer isso que não vai dar certo eu vou fazer o melhor que eu posso não vou desrespeitar a vontade do meu cliente mas se ele me der oportunidade se ele quiser ali é dar uma melhor versão para ele dentro do meu conhecimento que é o que eu busco todos os dias é ter cada dia mais mas agora daqui para frente é só sucesso mais ainda né Espero que seja mesmo bom pra gente fechar para quem não sabe que cantou aí por muito tempo com a voz dele aí por muitos lugares pra quem pra quem já ouviu né sempre lembra com muito carinho sempre lembra com muita honra da voz dele é uma honra Então vou pedir para você dar uma palhinha aí básica pequena qual que é cadê a palinha deixa eu dar ela aqui

pá um pedacinho aí da música que você mais gosta você tá doido tem jeito não por essa não esperava não é isso aí todo mundo esperando isso meu Grand Finale A Sereia do bolo nosso Deus não dá aquele granutinhobre algo cantava aí é isso o cara quebrou minha perna junto quem quiser é só cortar o cabelo comigo e o cara vai cortar cabelo eu canto velho entendeu O cara chega lá ficou muito boa Pronto consegui sair quiser ouvir o áudio cantando Aí é fogo que fica na Prudente de Morais e é um do sul de Belo Horizonte uma das melhores barbearias daqui da região cabelo tá na régua né à toa né botei com esse cara os cara tem a mão também incrível para cortar cabelo fazer a barba a tudo que vocês precisarem cara você quer deixar uma mensagem final da Galera cara mensagem que eu poderia deixar aqui é o seguinte nunca desista e inclusive Conte com uma rede de apoio Porque sem essa rede de apoio é difícil ser alcançar alcançar lugares né Você tem um limite ali limite curto inclusive para se alcançar sozinho né se você tem uma rede de

apoio uma rede em que você acredita e que você Não fuja dos seus valores para ter essa rede iPhone aí que vai dar certinho esposa do seu tempo sei que a agenda aí é extremamente lotado seu tempo é corrido é um privilégio ter pra gente receber aqui no nosso podcast é um podcast que a gente Esperava muito tempo é finalmente foi dar certo então obrigado mesmo irmão Eu que agradeço fiquei feliz demais com o convite aí foi bom lembrar da minha origem tamo junto obrigado a todos aí que nos acompanham não se esqueçam de baixar o best Barbie melhor aplicativo para gestão para sua barbearia pro agendamento online né muita das coisas que a gente falou que a gente pode te auxiliar com best Barbies a passar por muito mais coisas né de uma maneira muito mais fácil auxiliando aí na Gestão na agendamento seus clientes o melhor atendimento aquele abraço Valeu galera tamo junto falou [Música]`,

  summary:
    "Episódio 3 da Temporada 2 do BestBarbers Podcast. Alldrik Silva compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
