import type { VideoContent } from "./types";

export const podcastraylander_santos_S2_ep05: VideoContent = {
  slug: "podcast-raylander-santos-s2-ep05",
  youtubeId: "q606gdqLXno",
  title: "BestBarbers Podcast com Raylander Santos — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 5 da Temporada 2 do BestBarbers Podcast com Raylander Santos. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "raylander santos",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2023-02-27",
  duration: "55:03",
  category: "Podcast",
  tags: ["podcast", "temporada 2", "entrevista", "gestão", "barbeiro"],

  transcript: `[Música] senhoras e senhores sejam bem-vindos a mais um best barbras podcast é sempre uma honra ter você nos acompanhando para quem ainda não me conhece eu sou o André é um dos donos aqui do best barbras e hoje tem aula de receber aqui o Highlander da Highlander dos Santos barbearia uma das barbearias referências lá em Contagem cara vou pedir para você se apresentar um pouquinho contar um pouquinho da sua história aí como que foi começou a Highlander Santos como que você fez para chegar até aí qual que foi as dificuldades você enfrentou no meio do caminho e compartilhar um pouquinho dessa história com a gente fala galera sou Highlander tem 31 anos eu tenho 11 anos que eu tô no mercado da barbearia o início não era Highlander Santos barbearia era RN era Irlanda e Nayara inicial do meu irmão inicial da minha mãe e meu pai tinha uma empresa era uma oficina e o nome foi de muitos anos eu falei assim não cara vou salão ter RN na época nem era barbearia eu fui e coloquei salão ter RN e vim nesse processo aí de anos 11 11 anos de profissão é o

que eu te falei 11 anos no início de todo de todo negócio que você abre as dificuldades né eu mesmo eu pensei em desistir várias vezes velho nossa é a galera criar credibilidade comigo até a galera até chegar num valor de corte alto a época era seis sete reais então até mesmo você fazer um dinheiro você tinha que falar para caramba aqui quando nós tava brincando tem que ralar demais então é pensei em desistir várias vezes mas graças a Deus vim vem achando saídas para para crescer também não não vitimizei hora nenhuma de falar esse trem aqui na mão já vi a galera já estava já no mercado top entendeu então vim buscando saídas para mim vir sempre melhorando até na época de salão terreno vim fazendo alguns cursos fiz o primeiro curso o primeiro bar foi lá no na Pampulha no Restaurante Paladino eu fiz seu Elias e Eduardo Miller aí na época eu lembro que o curso era mil reais eu não tinha condições de fazer não eu tava doido na época então é importante ser amigo meu é meu melhor amigo até hoje Hugo mods o cara eu vou te passar seu

carro eu vou passar o cartão para vocês de 10 vezes para conhecer esse cara aí caramba Ah então mete esse cartão para mim de 10 vezes fez o curso tava cheguei cedão primeiro dá foi o primeiro velho Eu Cheguei galera tomando café já estava lá dentro porque eu vou conhecer esse cara aí hoje aí fiz o curso na época abriu muito minha mente eu era tipo do bairro mesmo ralava de chinelo a lava tipo assim eu queria melhoria mas eu não sabia o caminho para melhorar né O que que você tinha que fazer né ninguém tinha te ensinado né isso aí peguei fiz o esse curso eles quebram muito minha mente cara eu cheguei cheguei no bairro eu falei vou pedir a galera Pode sentar aqui por favor Pode sentar aqui por gentileza ele ensinando né as formas e você fazer isso no bairro é difícil demais de chegar num cara que você de 10 15 anos assim Pode sentar aqui por favor tá louco velho você é louco você tá arrumando aí seu velho eu vou educar essa galera velho eu vou educar por mais que seja amarrou hein Por mais que eles falam

assim que você tá que eu tô ficando doido mas o meu propósito era fazer eu ganhar credibilidade dele no meu bairro Eu sabia que eu só ia ganhar dinheiro dando credibilidade passando isso pras pessoas né eu comecei a ralar de sapato social mais apertadinho Blues social comecei a colocar minha barbearia no tipo agendamento parede de atender aquele povoada e comecei a tentar de r 7 eu passei para 12 Eu bloqueei dobrei fiquei Viki galera paga véio apaga a galera tá vendo que eu tô mudando começou vir pessoas de fora eu comecei a que eu te falei bater muito em rede social em rede social falei vou fazer esse jogo virar cara Teve um dia que eu tava eu tava eu tava na casa da minha avó Velho Amigo meu falou você tá vendo aí que o seu Elias tá abrindo é vaga para para entrar na barbearia dele eu falei ah você é louco velho não vou fazer esse trem não sou do bairro não é para mim não eu sou favelado velho lá em Savassi Pampulha esses trem não aí fiz velho fiz a inscrição mas fiz tipo sabe quando você só faz falei

vou fazer ele por fazer aí fiz ali e tal passou um tempo eu nem eu nem era muito com esse trem de e-mail olhar essas paradas assim para eu chamei uma vez no Dia das Crianças chamei uns 10 barbeiros lá da minha região vamos cortar cabelo lá na favela lá perto lá perto de casa abençoar as crianças vamos montar uma estrutura lá vai cortando de uns 300 cabelo na roda eu agradecemos mesmo sabe o mais legal que a gente fez em prol de nada a gente fez para abençoar e tal eu creio que muita gente vai ser abençoado e vai ter retorno disso aqui velho mesmo fazendo sem sem intenção meu telefone foi tocou velho ele é eu falei é ele mesmo cara você não vê o e-mail não falei olha você bem você nem sabia quem tava falando cara de ser bem sincero velho eu nem mexo com esse trem aí não cara eu não sei nem olhar esses trem direito eu cara é o seu Elias velho você foi selecionado aqui para fazer era ele te ligar você foi selecionado aqui sem barbeiros aqui para 10 cara você tem interesse em Vim porque

você teria que tá aqui já amanhã de roupa preta e com seus materiais eu falei assim ai cara vamos mandar o endereço cheguei lá velho que a galera todo de maleta roupa social padrão a galera toda socialzona velho tava no dia de gravatinha eu falei os cara de maleta falei meu Deus do céu com a mochila da minha mãe vermelha véi falei meu Deus do céu o que eu tô fazendo aqui velho eu você queria para mim não eu já falei nossa é outro nível velho bem além do que eu passei chegou bem além do que eu imaginei cheguei lá e tal cortei o cabelo no Dia ai ele foi me selecionando fui selecionando e fui só passando Ô cara você precisa de reconstrução cortar cabelo eu vi que você sabe Mas é o mínimo é o mínimo que eu quero ver aqui ser o que acontece cabelo a única coisa que eu não quero ver aqui no barbeiro de hoje é cortar cabelo eu quero ver a vida dele quero ver a vida dele com Deus eu quero ver a pessoa o coração dele Cara ele falou assim olha eu vou te ensinar tudo

que você quer aprender eu falei tipo se tiver humildade de aprender demais eu lembro que bem ele chegava nas reunião e lenhava todo mundo e todo mundo às vezes até sair até com ele cheio de lágrima Fala aí alguma coisa disso aqui eu vou aprender nem que seja futuramente se um dia eu tivesse minha loja era não fazer muita coisa que eu não gostava de ouvir lá hoje eu entendo ele como Chefe hoje eu hoje eu entendo tudo que ele falava comigo era para o meu crescimento para melhoria eu via muita gente saindo de lá chateado magoado faz mal velho eu vou pegar essas críticas aqui é quando eu tô meu negócio eu não errasse a mim não fazer assim sabe e na época foi uma das primeiras equipes dele então até para ele foi novidade não era para todo mundo como hoje eu converso muito com ele ele fala comigo esse cara você me pegou numa época que até eu aprendi tá então tipo assim para ele para ele eu imaginava que era difícil tratar a gente Dessa forma e hoje eu entendo era necessário mas eu peguei tudo e virei tudo para o

lado bom velho absorveu minha energia positiva tudo tanto que eu fui um dos primeiro barbear o Bruno foi a primeira na época ele já tinha a loja dele eu falei assim olha coloquei para minha meta fui fui em cima dessa meta trabalho lá quanto tempo ralei um ano e três meses três meses eu falei independente de qualquer coisa vai ser isso se vende meu carro montei a estrutura toda já vinha aí já vim pra Voltei pro bairro um cara que você tava no início já voltei foi só o cara na época era febre né ela que ralava no seu Elisa Nossa Senhora né hoje tipo assim ele na época ele tinha duas loja tava abrindo a segunda loja ajudou descarregar o caminhão Cadê tipo assim na época era um início para ele e para nós também só que quando a gente saiu de lá a gente nas regiões saiu como vitrine o Bruno lá em Betim como vitrine ele sabe de Contagem eu vim no caso em Contagem então era o que era era você tentar colocar Savassi dentro do bairro Riacho Você é maior dificuldade dificuldade em público né um público completamente diferente Bom

dia tudo bem pode me acompanhar aqui por favor Pode sentar aqui por favor do cara vai lá para você assim você tá doido o que que fizeram com você lá do outro lado vai celebrão velho você tá muito doido mas eu comecei a ver que aquilo ali era melhor do que um corte de cabelo entendimento Com certeza a diferença é o que faz a diferença ele eu comecei eu comecei a ver e a barbearia daquela forma ali ia virar e comecei por mais que eu não estaria na Savassi mas eu comecei o mesmo atendimento o mesmo nível de quando eu tava lá a mesma cobrança que eu tinha eu comecei a aplicar no meu negócio ó velho não faz isso porque sem ser assado galera vamos fazer assim coloquei a equipe toda alinhada e nisso nisso a gente foi crescendo Vamos abrir na segunda loja a segunda loja eu já comecei a ter necessidade de Pô velho vai adiantar números aqui não eu vou ter que fazer algo Eu vou ter que estudar algo para mim parar de ficar em rede social e faturada dentro da barbearia aí você isso para mim também era para

mim era meu maior desafio então só recapitulando você tinha a sua barbearia lá tnr é salão terrier salão tnr e aí depois saiu para o seu Elias né passou um ano e três meses você abriu a sua barbearia você abriu ela sozinha essa primeira unidade sozinha a minhas três é só minha não tem só isso não e aí você começou mas aí já começou com alguém te ajudando lá a cortar ou só você cortando na época que eu saí Como já estava tipo assim é o nome meu nome já tinha pegado muito o audre que ele é hoje ele tem a barbearia dele também eu não sei qual que é o nome barbearia isso o áudio que era um cara que tipo assim eu tinha ele igual igual irmão lá dentro da barbearia ele falava assim ó cara você tomou uma rachada eu tomei ele falava assim é isso mesmo mas vem cá você quer aprender como você não toma essa rachada ele ia lá e me ensinava porque o áudio que já era contusão tipo já tava acostumado com a galera top já tinha visto já estava vindo de uma igreja tipo assim a

clientela dele a galera dele já era top Então já sabia lidar com isso eu não eu saí do bairro aí ralado dentro da Savassi mano futebol para atender celebridade e você tudo muito diferente isso você não pode né você tem que saber a forma que se aborda do cliente a forma que você fala o que você fala às vezes você se comporta você entendeu então para mim foi tudo novidade que falou comigo assim cara você pensa em Abrir sua barbearia Você viu que o seu nome tá crescendo falei você é louco tô vendo que o meu nome tá crescendo para mim tu é a mesma coisa irmão ele tá assim cara todo mundo que rala aqui hoje ele hoje hoje é considerado a melhor barbearia na época do Brasil né velho nem da região do Brasil aí chegou a ganhar a melhor equipe do Brasil praticamente a equipe Nossa era muito [&nbsp;__&nbsp;] sabe o seu nome tá crescendo muito Às vezes você não consegue enxergar daqui mas por fora olha o tanto de gente tá te chamando para fazer curso cara vamos colocar o nome da sua barbearia de railanesas barbearia eu vou te dar

a identidade visual toda de presente salogo tudo foi o áudio cara foto assim ó você tá louco mano vou colocar meu nome numa placa ele falou assim cara confia em mim eu já estudei isso eu tenho certeza todo lugar e cobra tantos mil para fazer me dá r 500 que eu vou ter alguns gastos vou perder meu tempo eu vou desenvolver tudo para você tudo vê assim Ah velho então faz então vamos descer Ele me mostrou aí fez na capa fez em tudo que tinha de material de material ele ele colocou aí eu vim como raylander Santos barbearias e na época o trn ele não ficou fechado eu fiquei eu fiquei com um um eu tinha na época eu no final que eu saí de lá aí eu e mais um aí eu falei olha eu vou sair Vamos colocar mais um no meu lugar Aí coloquei e nesse esse amigo meu na época ele ele era de confiança minha Ele é igual o Fred hoje para mim Fraga um cara de muita confiança Olha eu vou sair eu não quero que você fecha esse ponto tudo que entrar aqui se entrar aqui 20 mil

reais é 10 mil reais meu 10 mil reais seu só tira para pagar a luz água aluguel que você vai pagar o restante é tudo isso se você vender um refrigerante no freezer cara é meu e seu mas não deixa essa loja fechar por nada essa loja não pode fechar que eu já tinha planos para ela aí mano beleza nesse tempo todo a loja lá foi trabalhando foi se pagando sobrava sobrava um dinheirinho a gente dividia sempre em dois tinha vez que eu deixava ele ficar com mais para deixar ele também né ele não gasta saber que quando voltasse ele ia colher isso também fraca velho vai ser meu braço direito ele vai colher isso aqui esse crescimento dessa loja só que na semana que eu já tava nos planos de sair esse cara meio de conversa Olha eu casei minha esposa quer que eu monte a minha loja eu não consigo ficar mais com você e tal na época como é que você perde seu primeiro funcionário cara falei nossa agora vamos voltar daqui nunca mais eu pego aqui errou meus planos como é que eu volto sozinho vai tentar fazer o jogo virar

Aí o menino que ele já tava treinando já tava treinando já tava começando a desenvolver voltar esse menino aí na época o Robson trabalhava no Torre Eiffel assim mano tô desempregado fiquei sabendo que você vai abrir uma barbearia posso passar com você uma temporada lá de seis meses sete meses e falei velho vamos embora mais pensei numa [&nbsp;__&nbsp;] vai sair eu seu Elias na época que tava bombando mas um cara do Torres eu vou fazer um alvoroço na internet mostrando rede social que tá indo dois barbeiros de washingão pra ir pra pra para Contagem assim comecei a fazer internet bati na internet para [&nbsp;__&nbsp;] tanto que quando chegou nós três no bairro para nós pagar foi tudo novidade nós tudo ralando social é porque eu vim de carro vendi tudo fiz uma estrutura fiz uma estrutura top Isso foi em que ano abriu a primeira eu acho que quando eu abrir é a primeira quando eu abri a primeira foi em 2000 Eu tenho 11 anos 2000 até Comecei em 2012 vendo um ex-cunhado meu cortar cabelo mas também é bom começar então para o cara que não tem nada para ver que o Barbeiro

hoje o Barbeiro ele na até a galera ver que barbearia dá para fazer uma grana que dá para ter uma vida boa a galera julgava demais barbearia porque é muito negro que não tem estudo nenhum Se você pegar a maioria das galera que senta aqui perguntar você formou você fez o que o cara fala a maioria fala assim oitava série primeiro ano a parei na sexta não tem uns que nem estudou então para você pegar e falar assim era uma profissão de escape ali né E hoje já mudou completamente né isso pra você falar assim Ah velho um barbeiro ele pode comprar um carrão e uma casa top pode pá velho tipo assim viver é top Isso aí foi difícil eu lembro que nas pareceres ele falava que tinha até vergonha de falar que era barbeiro que às vezes quando você chegava na casa trabalha de quê aí eu corto cabelo é esse presidiário é bandido ou é alguma coisa do tipo esse cara demais então até para você falar assim eu sou barbeiro Você tinha que ver onde você falar né barbearia veio quando o Elias revolucionou E aí todo mundo teve orgulho de

falar não é barbearia eu sou barbeiro você falar com alguns barbeiros assim até cabeleireiro eles endoida ela até ela pensa né para uns então tipo assim a barbearia revolucionou tipo assim hoje das galera fala assim ó você vai hoje a galera até brinca final de ano meu barbeiro da minha região o cara cheio porque hoje eles entendem que a profissão é valorizada um barbeiro Hoje ele pode ter uma casa boa ele pode ter um carro bom ele pode fazer viagem top é eu Elias principalmente vem mostrando né pra galera que era possível porta ver abrindo a mente Da galera né para alcançar isso daí é na minha época que eu saí é saiu eu passou um tempo e saiu uma galera né pulou uma uma série de problemas lá interna lá que saiu uma galera Só que alguns conseguiu ser grato né outros teve que tipo assim num jogo Porque fizeram nada da gente deles então tipo eu fui grato para cara eu fui um cara que eu mandava mensagem para ele todo dia velho eu falar sobre aí obrigado daquela vez você me xingou lá na Copa ou irmão te amo velho de verdade

Obrigado pelas vezes que você me falou que que eu não ia conseguir eu consegui Obrigado pelas vezes que você me fez embora chorando hoje eu entendo e hoje se eu não tivesse passado por isso às vezes eu não estaria da forma que eu tô hoje eu consegui virar tudo que poderia ser negativo né olhar com outros olhos negativos e virar para o lado bom velho falar assim não eu também vou botei meu carro top eu vou conseguir as minhas coisas eu vou realizar os meus sonhos e consegui velho reverter a situação ou não aguento mais velho dessas palavras desde o Leonardo esses cara eu fui até no cu dele Leonardo do Improvável né Eu acho que eu fui um cara improvável todo mundo até mesmo da minha região não acreditavam outras estatísticas né isso eu poderia virar como poderia ser né Hoje meus amigos Até faca Mix nova velho é até difícil de você assim cara eu só vi você fazer nada eu queria isso eu não fazer nada que você tá de jogar bola né velho aqui em todo mundo fiquei um tempão tentando jogar futebol futebol sabe eu vou fingir que eu trabalho

aqui meu pai finge que me paga e aí eu era desse jeito e ficava velho eu ficar de boa meu pai me dava ali semana ali r 200 Dá para me dar um rolé massa passava tranquilo mesmo e fazer tipo virar tudo e falar assim pô velho da Galera falava assim corte de cabelo lembrar de mim hoje é seu nome né hoje eu consegui hoje eu consegui fazer isso quero mais difícil e quando que você viu você ficou um mês e 1 ano e três meses lá no no seu Elias né quando você viu que era o momento que você sair e falar não agora eu tenho que ver se Provavelmente na minha barbearia né Tem que montar o meu negócio e expandir não tem momento certo não ele nunca foi um momento certo a gente sempre vai estar apertado a gente sempre vai estar sem dinheiro a gente sempre vai estar endividado aí eu fui colocando meta mano eu coloquei uma meta e tudo que entrava eu só tiravamos por eu ganhava lá vamos supor que eu ganhava 10.000 eu tirava o sete das contas os 3.000 que eu tinha eu colocava lá em

ovos investia investia lá pegava o meu dinheiro investi os caras vão comprar isso não velho investir Ah vamos comer isso eu fiquei eu fiquei uns 7 8 meses não comi nem cachorro quente na rua caramba não tô zoando eu ia embora eu chegava comi o pão com café que eles me davam o almoço eu levava Marmitinha e todo mundo indo para o restaurante de novo caramba salário lá no teto sala lá no alto galera tudo ganhando bem tipo assim uns para uns Ah velho vou viver a vida boa que me dar aqui eu já entendi não falei velho momento propício nunca vai chegar de passar tô com muito dinheiro sobra nunca vai nunca velho não vai chegar se tivesse o dinheiro sobrando vai acontecer um imprevisto então é melhor você sempre estar pensando lá na frente eu comecei a fazer isso a pôr na obra colocar na obra colocar na obra colocar na obra colocar na obra eles me fala sobre o que você tá arrumando vai sair para tomar uma água você não vai o negócio você não vai você só vai quando é de graça é abençoado agora vocês vão entender é o

plantando fui só plantando no final ainda faltou dinheiro lá eu vender meu carro eu morava eu sabia que era tudo da mesma rua ali na mesma região e meu carro e dei a O Golpe Final né e falei velho agora é a hora é essa se eu vou conseguir comprar um carro eu não sei mano chorei demais Ô chorei de vender meu carro eu falei depois que ele não tava lá mais né velho mulher vai ganhar vai ganhar a menina e velho isso ainda estava para virar pai ainda falei assim meu Deus agora eu vou ganhar minha menina vou ter que andar com ela nas costas velho igual canguru sei lá mas eu fiquei doidinho aí nisso eu tava dando uns cursinhos já fora Fraga velho eu falei com Deus que eu não queria fazer o que todo mundo tava fazendo eu não quero velho ficar nesse trem de workshop eu não quero ficar rodando eu fui lá em Jequitinhonha dar um curso caramba e dá um cursozinho top os cara me pagou um valor tipo bem valorizou bastante Fraga velho fui voltei fiquei dois dias lá eu falei na volta para cá oferecendo para

mim não quero ver minha menina crescendo eu quero ser um pouco mais presente a maioria da galera que viaja é acaba perdendo né queira ou não ser grande de um lado mas perde seu lado positivo né nega eu não quero isso para mim por mais que eu não vou ganhar dinheiro com isso eu não quero se for para mim ganhar dinheiro dando curso eu quero ganhar dentro da minha barbearia velho orava orava pedido demais aí um dia eu acordei de madrugada sonhei velho sonhei com curso formando barbeiros velho outra mão do vento irmão todo mundo workshop meu Deus eu não quero isso eu sei que se eu continuar eu vou rodar muito eu vou crescer muito nisso mas eu não quero ser visto não quero ser bem sucedido Mas eu não quero serviço eu prefiro viver é o que eu falei achar que tá vivendo uma vida simples agora para tá Investindo na frente para colher velho eu quero totalmente ao contrário Deus se não for aí vem formando barbeiro velho eu lembro que eu acordei eu escrevi tudo num bloco de notas mandei para o Jorge na época ele fazia meu marketing digital falei

com ele cara ele adora um curso Principalmente eu sei que eu sonhei isso se você achar que tem que modificar alguma coisinha em outra umas modifica mas não modifica muito não outro dia ele me mandou eu falar seu curso oito meses que eu tinha voltado do seu Elias já já nem sabia que que você já tinha saído já tinha já tinha saído tum aí o áudio fez tudo para mim vim com os meninos e tal Eu falei cara eu não quero não quero ficar dando workshop e todo domingo dando curso velho todo domingo eu não passava nem os domingos dentro de casa todo domingo todo domingo todo domingo um diazinho né final de semana é boa mas velho eu vou eu vou desgostar disso porque você não tem prazer velho sabe quando você vai sentir o prazer é quando você ralar para [&nbsp;__&nbsp;] aqui é fechar o seu dia e entrar dentro do carro que você sonhou vai entrar dentro prazeroso e não adianta você ficar se matando de trabalhar no final fala assim Uai tem que seguir nem aproveitar do que que você conquistou né velho mas eu trabalhei nem um carro que eu

quero meu sonho eu tô conseguindo desfrutar dele você vai perdendo prazer velho eu falei cara eu não quero perder o prazer nisso que eu faço eu gosto pra [&nbsp;__&nbsp;] falei não quero aí lancei Eu lembro que eu lancei é eu lancei no Instagram formando barbeiros primeira turma edição primeira do ano sei lá o que sei lá o que nunca tinha dado curso de nada na vida fechei 22 alunos a 2.500 é o final de dinheiro mano isso aqui não é possível que você quiser me dar minha vida e comecei o formando barbeiros a primeira escola dentro de uma barbearia num Brasil hoje hoje eu vejo que a maioria que tenta fazer isso aí formação de barbeiro isso aqui isso aqui é meu velho não adianta aí os meninos Falam assim aí todas as vezes que a gente vai fazer informando a barbeiros vem 10 alunos 15 alunos 12 alunos 8 alunos de cara né velho 22 é um sonho que Deus me deu e ele tá sustentando velho não tem erro não tem nem nem explicação né velho me matando e nisso eu comecei a ver eu poderia colocar os meus barbeiros também para ganhar

um dinheiro então comecei hoje até falei hoje lá na Magalhães da galera mais velha de casa o Fred hoje é um dos meus barbeiros mais velho ele ele domina o formando barbeiros inteiro imagina se precisar de eu nem nem no no formato da vida eles não precisa de ouvir sucesso Porque ele é o Barbeiro que já faz é um barbeiro ele já tem um carro dele já colocou as lentes E aí cara o sonho dele aí você me fala ai mas ele é feliz é o que eu te falei lá no final eu prefiro dar ele os 50% de tudo que ele faz ele ser satisfeito e ele realizar os sonhos deles porque o dele 30% e ele vê só eu ganhando é aí a rotatividade começa a ficar grande aí começa a perder em vez de você achar que você tá ganhando você tá perdendo porque você não tem um barbeiro feliz eu nunca de nenhum barbeiro meu para chegar 6 horas da manhã os meus bebês chega de 6 horas da manhã e vai embora 10 horas da noite domingo passado abriu três barbearia as três barbearias abriu domingo eu nunca pedi ninguém

para abrir domingo mas a galera começou a ver e a comissão é valorizada que eu cresço eles também crescem eu falo com os meninos direto eu brinco eu brinquei dizer pelo Fred vamos trocar seu bravo vamos pegar um Corolla o meu Corolla eu preciso pegar outro carro irmão e assim vai entendeu então tipo assim eu mostro para ele a valorização que eles têm e todo mundo ganha dinheiro em cima estimula e a galera se eu ficar no meu mundo só eu vou ganhar dinheiro só eu posso ganhar dinheiro meu irmão eu não ganho dinheiro você começafundar e não vê né a areia você começandar em cima de uma esteira eu falei eu falei isso hoje com um barbeiro meu Olha tem que ver o que que você tá fazendo com o seu dinheiro você vai ficar andando igual aqueles hamster na esteira é correndo correndo não vai sair não vai sair do lugar não é hora de você olhar pensar planejar e começar a mudar a posição disso não sempre vai ser assim e é o meu pensamento hoje hoje para mim ganhar dinheiro as mesmas vezes sem ganhar dinheiro se o cara não tem

essa mentalidade dentro da barbearia o dono se o dono não tiver essa mentalidade e para ele ganhar dinheiro os barbeiros tem que ganhar dinheiro meu irmão conjunto andando em cima eu fiquei assim um bom tempo correndo correndo e achando você quer só para mim que é só para mim eu vi eu vi os cara paga eu vejo negro e pagando 30%, 32%, 33%, mas o corte mais velho dá para todo mundo ganhar é para todo mundo ganhar mais ainda né o negócio e isso dá para você deixar muita gente feliz entendeu barbeiro que quer Honrar é vestir a camisa ele ganha dinheiro quanto dono quanto dono eu vou te falar com você hoje com a minha mente de hoje dependendo da porcentagem que eu ganhava lá um tempo atrás Pode ser que eu nem saia porque era muito bom já era muito bom na época não tinha conseguido enxergar nada dessa forma né velho eu ganhava 30%, eu já ganhava um salário de 10 pau imagina se eu ganhasse 50 pensa entendeu para que que você iria mas tem outro lado da moeda também né o cara saber aproveitar a oportunidade de saber se dedicar

né porque não adianta também pode trabalhar no melhor lugar do mundo com a melhor comissão é se você não tiver disposto a mudar de vida igual o Fred aí né aí também não adianta né as duas os dois lados da moedas aí para fazer com certeza os dois lados da moeda velho você tem que saber pegar oportunidade abraçar oportunidade entendeu a gente ficar só na oportunidade as 24 horas são para igual para todos velho exatamente da forma que você vai saber aproveitar ela cara e me fala aí duas coisas que você acha que fez assim você mudar de mentalidade que fez você mudar de vida mesmo duas coisas vou te falar uma que eu falo eu falei hoje lá dentro da barbearia a igreja depois que eu fui para igreja eu comecei a fazer as coisas de Deus que eu vi o que é certo o que é errado o que pode fazer o que não pode eu acho que foi primordial na mudança da minha vida não só Na barbearia mas como pessoa como tudo como tratamento das pessoas como como tudo sobre vida Deus e o que eu falei o que eu falei

com ele aqui também as vendas as vendas mudaram o meu negócio O barbeiro achar que ah não só o corte de cabelo hoje se você sentar lá na minha barbearia se assusta se assusta chega lá para cortar o cabelo a única coisa que nós vai ver eles vão falar de corte de cabelo aí começa aí começa assim complementar e isso querendo ou não é 90% de um negócio e não só Na barbearia e tudo que você for fazer e tudo que você for fazer o que move é as vendas você vai virar o seu negócio você tá vendendo o tempo todo o tempo todo você tá ali velho passa ali na sua cadeira ali 20 empresário todo dia todos os dias com uma uma oportunidade diferente um trem diferente ficar ligado nas oportunidades da vida cara e tudo às vezes tá ali cortando o cabelo do cara o cara Ah velho mas eu vou para praia o que que você acha o cara tem como ir para praia sem fazer uma hidratação 65 vai ficar longe e assim você vai só escalando cara mas você vai para fazer uma hidratação você tem que mantelar você

tem que levar um creme de pentear o cara é sério cara olha mas o creme de pentear Isso é para quê para duas função ele serve também para você fazer um zero como um livrinho pincher Ah já mas não tem secador escova não meu amigo aí o corte era 35 saiu a 600 a r 500 hoje a gente nem Comemora mais quando a gente não é maquininha de cartão 300 Ah é normal né não vai mais dar paulada o padrão é é a paulada é o que o cliente precisa é oportunidade é ficar atento no que o cliente vai falar às vezes você tá ali o Adão cara te falou que você é um monte de coisa gente deu altas brechas cara te deu umas cinco seis brecha você tá lá falando de assunto nada a ver velho eu fico só caladinho só ouvindo tem hora que os meninos até assusta Ô Fred você não passa na hidratação que vai pra praia é mesmo né velho mas você vendeu para o cara o que que tem velho isso mesmo velho tem hora que eu vendo tem hora que eu vendo tanto serviço que eu passo

meus meninos fazer toda véi Espero que ele vai continuar com seu atendimento ele vai fazer os cara vai que é isso então consequentemente eu fazendo isso e comecei a aplicar e comecei a dar treinamento isso para os meus meninos comecei a mostrar para eles que eles podem faturar até três vezes mais com o mesmo número de cliente que eles têm não é quantidade nem número e é qualidade qualidade tá sempre atento ali no cliente vai falar e dá para ele o que ele precisa e isso Isso mudou a mentalidade da minha barbearia da minha empresa você acha que então nos seus cursos nas suas mentorias hoje em tudo se ensina o segredo tá nas vendas nas vendas aí seria o diferencial para quem quer aprender com você aprender é o diferencial hoje eu vou te falar que você em Minas não tem mais não tem nenhum barbeiro que vende mais então a gente fala com toda autoridade do mundo pode chamar qualquer pessoa que trabalhou comigo hoje hoje em Minas Gerais não tem barbeiro que faz que faz mais mais vendas do que eu num dia não faz eu fiz eu fiz 83 procedimento a

brincadeirinha disputando só tinha corte marcado e só corte marcado propostas procedimentos vendendo selagem barba e isso para todos máscara hidratação tudo num dia eu falei cozinheira pega pega a visão para vocês verem igual um louco mas fiz para eles que é capaz você mostrou que era possível né porque eu falei assim olha para mim convencer eles que dá eu tenho que fazer mostrar né na prática então tipo velho um dia muito louco velho um dia muito louco dentro da barbearia eu consegui eu fiz todos os todas as linhas do embarcação do aplicativo só que tava tudo corte falei assim e mostrar para os meninos hoje que é possível velho e eu comecei a desenvolver isso velho na época que eu fui lá no Bruno lá o Bruno falou assim olha não meus custos estão bombando o Bruno Brito tá bombando mas a minha empresa ela precisa de um cara igual a você cara tem que ser o c porque eu tenho certeza que você vai me ajudar nessa parte restante tudo a relação a ele tava decolando só que a barbearia tava se mantendo Olá vamos lá ver esse trem vamos lá sentando pelo seu

Bruno eu vou eu vou dar um curso depois eu vou deixar todos os dias da semana um barbeiro se eu passar um dia lá da sua barbearia ele vai trabalhar ele vai ele vai ser o chão lá dentro Vai lá vai lavar um cabelo não vai para olhar não ele vai trabalhar e de graça vou dar nem r 1 para o cara que for mas ele vai vai ser o melhor dia da vida dele ele vai velho é isso então aí fizemos vamos lá e fizemos o curso de vendas passa isso eu acompanhei seis meses a barbearia triplicou velho ele ficou seis meses fazendo trabalho lá com ele de lá sentar eles mostrando para mim foi treinamento evoluiu demais nossa Fulano segurar um cara desse aqui então tipo assim e comecei a ver Aí peguei um outro amigo falei o Juninho do Costa ele falou que os cara tô comendo dificuldade eu falei vamos fazer isso também vamos velho eu comecei o curso começou a querer expandir falou pá eu vou começar a ter que rodar de novo já comecei a ficar mais tranquilo então eu faço isso com uns amigos com um amigo ou

outro a galera é a galera mais próxima que foi uma um dos cara que me ajudou o Bruno me ajudou demais esse esse Juninho a gente tinha muita amiga ali me ajudou ele me ajuda com muita coisa então tipo assim essa galera aí tipo eu consegui ainda salvar muita coisa velho ela tem muita coisa ainda para compartilhar por aí [&nbsp;__&nbsp;] mas e aí falando em projetos então já que você quer ficar mais em casa aí curtir mais a família que são seus planos em relação a curso em relação à mentoria que que você pretende fazer aí esse ano eu vou eu vou ver se eu desenvolvo mais o formando barbeiros é uma renda muito boa hoje que a gente que eu tenho Na barbearia e até mesmo meus meninos eu quero voltar a fim nesse ano é dentro da minha barbearia e eu vou tentar dessa mentoria online velho Braga fazer ensinar um cara de longe vender Fraga sem precisar de vir aqui tentar Sei lá uma vez ir lá mas hoje a chave da barbearia tá na venda é isso que você atribui o sucesso aí das três unidades hoje então na venda as

vendas na venda Primeiramente Deus depois as vendas certeza né com certeza o Pilar de tudo e as vendas a venda é o coração do negócio o cara que vai falar eu sou muito bom Tecnicamente eu rodo tesoura eu corto outras formas eu bato de cima cara para teatro Tá bom eu conheço muito barbeiro aí que é muito cabuloso na mídia mas que hoje Se vim falar assim ah vamos fazer uma viagem não tem condições de fazer eu tenho é vários amigos assim eu tenho é centenas entendeu então hoje eu não quero você faça o Highlander aqui é muito é mídia cara eu quero mais paz e saber fazer fazer o meu trabalho Flávio eu quero menos mídia e mais resultado é o que eu penso e consequentemente um bom trabalho com certeza mas gente vai querer ver mas a gente vai querer aprender né sim mas eu acho que hoje a venda é o coração da barbearia e Mas me dá dois fatores aí além das vendas que você acha que é fundamental hoje para que você consiga coordenar as três barbearias é numa forma padronizada de atendimento de qualidade O que que você mais

se acha que contribui para você conseguir gerir tudo isso cara é você uma sempre criar o seubrar direito hoje o Fred ele eu sei que tem câmera na barbearia ele trata barbearia como se fosse dele entendeu então acho que é confiar nas pessoas Acho que não não existe crescimento sem confiar nas pessoas todo crescimento se você ele vai ter que você vai ter que confiar nele vai ter que confiar em você e assim vai fazer pessoas de confiança cara e é o que eu te falei Um Outro fator quer ver e fez a gente crescer comprometimento aí a gente tem muito comprometimento com cliente entregar experiência da experiência e realmente acho que é primordial velho o comprometimento do cliente chegar ele ser atendido no horário dele cliente chegar ele assim senti um ambiente agradável é o que eu falei lá no início pode me acompanhar aqui por favor Pode sentar aqui por favor não é todo mundo que faz Às vezes tem muito barbeiros aí que dom de 10 mini corte 10 no Bruno de 10 meses dando de 10 mas não tem o padrão o padrão padrão Highlander Santos antigamente o cara não vai

falar o seu padrão Não fala assim o meu padrão Bruno Brito padrão mas todo mundo teve um padrão que copiou que aplicou e tem dado certo é o padrão da barbearia o padrão e o seu Elias conseguiu colocar na barbearia que quem faz o padrão que é a chave do Sucesso Ah mas eu não quero copiar eles ele para mim eu não vou andar de gravar do cara mas pega esse 70% do que ele faz coloca dentro do seu negócio né simplesmente a estética ali né no modo investir né simplesmente você não precisa ter uma barbearia Igual a dele para você tratar o padrão padrão Ele é cinco estrelas Independente de onde ele foi eu falo muito nos meus cursos cara primordial o negócio virar o padrão cinco estrelas para chegar aqui tem um ambiente legal é uma conversa Legal tem uma água para ele tomar eu acho que é o padrão vendas e confiar nas pessoas certas e confiar nas pessoas certa para fazer só barbearia bombar três chaves para fazer para fazer o seu negócio virar achar sem dúvidas É isso mesmo e o best Barbies vem justamente para aliar né a vocês

nessa caminhada da gente resolver aí os problemas que muitos ficariam sofrendo com números né você conseguir enxergar organização da sua barbearia para você não perder seu tempo se preocupando com isso né E poder dedicar seu tempo aí as vendas né ou comprometimento a experiência com cliente e me dá mais um conselho aí para quem quer abrir a sua barbearia né quem já trabalhou aí com muitos outros né que já trabalhou em outros barbearias mas tem um grande sonho aí de ter o seu negócio próprio Qual que é a dica aí que você daria para quem quer começar agora cara é acreditar em si mesmo né velho eu acho que a melhor pessoa para confiar em você é você mesmo o Deus sempre planejar confiar em Deus e tem erro não cara fazendo um bom trabalho fazendo um trabalho honesto fazendo um trampo bem transparente eu creio que não tem não tem erro não uma pessoa e que tem comprometimento eu falo uma frase eu falo uma frase eu falo eu falo ela em todos os meus cursos Hoje os cara fala assim Ah velho mas cortar cabelo com sete filhos demais não cortar cabelo comigo

é muito fácil o cara quer cortar cabelo comigo ele marca comigo um horário e eu tô sempre ali no horário que ele marcou em atender mas você atende ainda atende cara eu gosto demais em dia que eu chego 6:00 5:00 da manhã eu tenho 5:40 da manhã de noite ainda 5:40 a gente fica doido velho é uma frase que eu eu ouvi na igreja leva para minha vida eu nunca digo não pra missão que me salvou barbearia é minha missão me salvou velho tipo me fez mudar de vida mano me fez tipo assim eu olhar e falar assim ó eu esses dias pra trás eu tava dentro do meu carro eu falei entendeu um carro de um amigo falei com ele assim ó tem um carro desse aí nem nem sei cortar mil cabelo eu cortei o cabelo era 67 hoje eu tenho um carro que eu entrei hoje eu tenho as coisas que eu sonhei não tenho tudo ainda mas tô bem tô bem encaminhado então a barbearia me salvou meu irmão eu falo é a minha missão é barbearia Então umas capa aí 5 horas da manhã 4 horas da manhã 3 horas

da manhã eu lembro dessa frase aí eu nunca digo não pra missão pra me salvou nunca me salvou é uma frase que eu tatuei ela no meu cu velho eu nunca digo não para mim só me salvou e até meus meninos fala quando já virou um lema lá né velho porque barbearia mudou minha vida cara eu não tenho como você pegar e e olhar para Jesus que te que te cuidou e te limpou fez tudo e você olhava e falou não tem como velho tem como eu pegar hoje eu eu o nível que a barbearia o que a barbearia tá me proporcionando eu virar para não não vou te atender não mas como assim eu não tenho essa opção de pessoas nenhuma você ia qualquer um corta cabelo comigo hoje ah mas tem gente que brinca assim você quer cortar seu cabelo de de rico e de jogador meu amigo eu corto cabelo de qualquer um velho esse sem excepção de pessoas esses dias para trás o Vargas me mandou mensagem era sábado era um sábado meio-dia amigo você consegue vir me atender agora minha agenda lotada eu falei amigo cara eu faço muita questão

de te atender cara mas eu tenho uma agenda aqui de meio-dia 17 se for pós horário eu consigo eu faço questão de ir aí te atender você na sua casa mas eu tenho um compromisso aqui com a galera que né é comigo há muito tempo né compromisso né Independente de quem for você Ah não eu vou marcar esse gênero aqui vou fazer isso cara aí já começa o que eu te falei lá tá se comprometimento é o que faz das vezes a Fideli a fidelização do cliente do César da sua barbearia sucesso da sua vida então eu acho que é uma chave Fundamental e essa frase aí cara se todo mundo levar isso para a vida todo mundo sempre vai sempre crescer sempre vai crescer tem condições de voar vou acreditar também basta você acreditar né porque depende só de você né e depende só de você velho cara eu acho que tão importante quanto né a barbearia mudou sua vida mas você tá conseguindo mudar a vida de muitos outros aí né Eu acho que isso aí vai além de grana que você já ganhou de ter três unidades faturar né você vê vai

além porque eu nunca imaginei né velho eu nunca imaginei que eu ia ver parar um ano falar assim nossa velho esse ano praticamente nós bateu milhões de reais as três unidades você fala e fala assim Nunca nem passou pela sua cabeça né velho Achei que eu nunca ia ganhar r 10 velho então tipo assim e você vê a alegria da galera velho dos meus meninos a maioria foi pra praia eu não fui velho a maioria dos Cavalos comigo assim seus barbeiro viaja mais do que o seu pai graças a Deus tudo bem eu acho que os cara tá da hora velho para mim é mó alegria ver a galera bem os meninos felizes eu eu deixei de ir para deixar minha mãe ir ver sua mãe vou levar minha mãe dá todo estrutura para ela para ela comer beber e fazer tudo mãe é pra praia vai vai com Deus à vontade vi meus meninos isso pra mim isso para mim é satisfatório vitória né Para mim é bom demais velho deu de eu ligar para você e como é que tá assim ô velho eu não sei onde eu ponho dinheiro não sei o

que que eu faço o que que você acha que eu faço isso velho esse cara nem sabendo aí aprendendo até o rolo você fala assim eu estou com um barbeiro mas tá assim ai minha capinha aí o que que é isso aí r 200 atrás ele fez uma capinha de com dinheiro eu falei velho cara tipo assim você vê a galera eu vou te falar com vocês vem falar comigo assim eu não sei o que que você arruma isso só gosta de barbeiro que ninguém acredita falei os melhor velho é porque eles entendem a minha língua porque eu também era assim né velho eu fui um cara sempre disciplinado eu fiz tudo certinho Velho era o cara mais avacado que tinha nós tinha era 13 barbeiros feliz eu era o cara que mais apanhava velho mas ao mesmo tempo eu falo assim esse cara é o que vai me dar mais fruta esse cara que vai arregaçar esse cara aqui ninguém quer velho eu quero ele velho ah mas esse cara não tem jeito tá é o melhor para mim velho aí que você valorizador mesmo cara aqui é o cara que quando ele vê

que você conseguiu ajudar ele você conseguia mudou a vida dele é o cara que ficou o Fred Fred é igual irmão para mim mano você sabe ele é igual família minha mano ele tudo que eu faço eu levo ele é o Barbeiro ele chegou ele chegou na barbearia ele tinha um par de tênis um dedão para o lado de fora o cara começou a comprar cinco seis tênis por mês eu falei que que é isso ele falou velho eu só tinha um velho e tal e comecei velho eu que eu falei no início o cara trata barbearia a minha barbearia como se fosse barbearia dele então tipo não tem como velho não tem como você não olhar e não ficar feliz de ver o cara que entrou ia vir Ralar todo dia a pé e voltava a pé hoje tem um carro dele ele falou que o maior sonho dele era parente dele pois além Tipo isso satisfatório de ver que não é só você que tá conseguindo entendeu que a equipe toda a vitória do céu você fala filha pai é irmão é a família de todo mundo se for olhar aí hoje são

três funcionários meus os 13 a família todo mundo comendo e bebendo em prol daqueles e fala assim cara isso é bom demais velho isso aí é melhor do que os cara fala assim velho os cara fala comigo assim mas como é que as coisas por ser acontece eu falo seu velho porque eu gosto de ver acontecendo nos outros para acontecer em mim depois eu prefiro ver eu prefiro ver o meu menino sorri primeiro para mim depois eu sorrir velho eu acho em dobro né velho eu acho que que isso é bom praga velho você vê o seu o seu funcionário o seu prestador de serviço ele feliz e você fala assim cara velho o cara tá feliz demais velho é bom demais vocês chegaram no ambiente de trampo você que nem o velho eu fico de cara meus meninos velho chega passa pano em tudo limpando o vidro organizando e fala assim cara velho isso é bom demais velho mas se você chegar num ambiente não tem prazer de fazer isso fica todo mundo triste aí fica um ambiente chato ruim aquele climão pesado para trabalhar Bom dia a pessoa já nem olha nem olha

para você velho Então graças a Deus a gente tem a gente tá trabalhando num ambiente muito agradável aí onde está todo mundo feliz eu acho que é o mais importante também Eu já entrei em barbearia aí eu chegar na barbearia velho todo mundo de cabeça baixa ó os cara aí o patrão chegou assim ó os cara comédia chegou aí né que isso velho que que é isso de eu chegar no dono e falar assim velho os cara falou assim os caras ouvindo a boca dos seus funcionários o comédia entrou velho já tá difícil trabalhar mano eu por mim eu trocaria minha equipe toda ele o quê velho trocar numa equipe de Oi vamos trabalhar nos oito velho que isso é melhor o que velho Deixa eu ver essa comissão 31 por cento de falar com você você não tá na Savassi você não é Fulano nem tudo que Fulano faz tem que fazer aumentar essa comissão vamos fazer isso vamos fazer aquilo vamos ver se todo mundo começando a ficar feliz aqui então aparentemente só você tá ganhando dinheiro mas nem você tá ganhando Então vamos começar a mudar um pouco isso aí e ver

todo mundo ganhando que eu acho que você vai começar a ganhar vai ser mais feliz você chegar perto dele ele até briga comigo ele tá precisando de dinheiro emprestado graças a Deus tô tranquilo tô tranquilo você entendeu Mas eu vi muito amigo e barbearia nisso aí velho é muita barbearia acaba nisso né velho fraco é milhões de barbearia É muita gente fala assim ah mas é a mesma coisa aí o Railan [&nbsp;__&nbsp;] mas eu o seu Elias eu ganhava 31%, eu vou meter 31% fala que se se eu highlain tivesse colocado da 31% a minha comissão Hoje eu tava rico os meus barbeiros tava pobre e tava todo mundo infeliz e chegava dentro da barbearia nem um bom dia ali ninguém ia dar entendeu aí hoje eu eu te falo para você eu não tô rico mas estou no caminho eu sei que uma hora eu achava que vai virar ainda dobrada porque tem muita coisa boa acontecendo para mim e eu tô vendo que eu só tô crescendo então eu vejo a minha galera feliz e eu consequentemente eu tô feliz também então você tá todo mundo faturando é uma chance de eu dobrar

triplicar eu motivar ainda mais essa galera a crescer a chance é 100% de tudo dá certo entendeu errado eu viajo as coisas é tudo do mesmo jeito continua acontecendo mesmo acontece tudo melhor mas se for a 31 por cento aí vou falar com você na hora que o Barbeiro até fala que tá com passando mal mata até alguém dentro de casa para não ir falar o quê velho vou lá ganhar 31% de novo e vou Nossa Senhora Deus me livre sei lá o que que você começa aquela pessoa eu acho que você ia ficar feliz você tem que fazer as pessoas felizes Eu acho que é o que que é o primordial para achar no lugar do outro também né velho o cara não consegue entender como seria o lado contrário né só fica na visão dele ali fechado duas referências aí na sua vida que você acha que assim não esse cara realmente foi espelho para mim né Eu queria ser igual ele ou então me ajudou demais Fala aí duas pessoas referência na sua vida as pessoas duas pessoas referências que me ajudou muito ajudou muito ó velho eu teria até três pode

ser eu teria até três uma que é meu pai sempre é o cara que acreditou todos os meus planos em todos os meus negócios esse amigo que eu tenho o Hugo que pagou o curso para mim que acreditou sem saber hoje a gente faz muito negócio junto negócio grande sem saber de como seria as coisas e o seu Elias todas as vezes que ele me chamou atenção que ele me cobrou que ele me xingou beleza foi um dos motivos as três maiores referências meu pai o Hugo e logo depois do seu Elias o terceiro ainda show demais último recado para galera para a gente finalizar esse podcast se manda aí para galera qual que seu de pecado é galera É acreditar confiar poder sempre em primeiro de tudo e o principal de tudo cara trabalhar não adianta você falar eu não vou trabalhar não vou acordar 10 horas 11 horas e vou é a mesma coisa não dependente se tá tendo cliente ou não comprometimento se é de 9 às 20 é de 9 a 20 Ah mas tá difícil eu abrir de 9 às 20 todos os dias tem dia que eu não atendi

cliente eu já fiquei a semana que eu cortei três cabelos mas eu tava lá todo dia eu falava assim velho sábado eu cortei dois cara vai abrir domingo para fazer alguma coisa às vezes não dava nada mas eu tive que comprometimento porque eu sabia que isso ia virar que se uma hora ia acontecer pessoal eu tô plantando velho é igual você vai na igreja tudo pela fé velho olha só ele já tô abrindo de 9 a 20 que eu sei que vai esse trem vai de 9 a 20 eu não vou conseguir mais vou ter que começar a abrir 6 da manhã 7:05 é o que tem acontecido eu plantei Hoje eu tô colhendo eu acho que comprometimento acreditar nos seus sonhos não tem erro e eu que eu falei lá atrás eu nunca digo não para missão que me salvou Nunca diga não para missão que te salvou fica aí o recado final irmão eu te agradeço aí pelo seu tempo você quer correria aí principalmente virada de ano planejar tudo novo ano né mas eu tenho certeza que você vai conseguir alcançar muitas pessoas através desse podcast agradeço aí todo mundo que nos

acompanhou até o final espero que vocês tenham gostado dicas valiozíssimas aí com a Highlander E não se esqueça o best Barbie está aqui para te ajudar para transformar sua barbearia para alcançar o nível que você nunca imaginou para você ter tempo pra vender pra preocupar aí com a experiência do cliente pra realmente transformar a sua vida da barbearia valeu [Música]`,

  summary:
    "Episódio 5 da Temporada 2 do BestBarbers Podcast. Raylander Santos compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
