import type { VideoContent } from "./types";

export const podcastmarcony_visagista_S2_ep01: VideoContent = {
  slug: "podcast-marcony-visagista-s2-ep01",
  youtubeId: "27K5cBFCJnc",
  title: "BestBarbers Podcast com Marcony Visagista — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 1 da Temporada 2 do BestBarbers Podcast com Marcony Visagista. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "marcony visagista",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2023-01-30",
  duration: "1:14:55",
  category: "Podcast",
  tags: ["podcast", "temporada 2", "entrevista", "gestão", "barbeiro"],

  transcript: `[Música] fala barbersinho bem-vindos a mais um best barbras podcast é um prazer ter você nos acompanhando em mais um episódio hoje eu tenho a honra de mais uma vez receber essa presença ilustre referência no visagismo referência também na equipe seu Elias Marconi também participou da nossa primeira temporada do podcast no Episódio número 5 se você não assistiu te convida a assistir também esse episódio lá ele também contou um pouquinho da história dele mas sem mais delongas vou pedir para você apresentar rapidamente para quem não te conhece ainda e contar um pouquinho de todos os projetos que você tem atuado de tudo que você tem vivenciado como você tem gerenciado tudo isso e feito para chegar até aqui cara mais uma vez é prazer estar aqui né agradeço e o best Barros é uma empresa incrível Né desde tudo né falar com vocês que eu acho que vocês têm um gosto aqui Ficou muito bacana legal o copo né que eu tenho um lá em casa a lembrança boa E aí gente sou quem não conhece né apresentando aí Marconi ou com seu Elias lá seis comecei a trabalhar com ele numa oportunidade que eu eu

tive eu conheci a barbearia através da televisão por um sonho meu trabalhar lá né eu vim de uma família muito simples corta o cabelo desde os meus 14 anos e quando quando já tá mais ou menos uns 5 anos ali de produção eu fiz o meu primeiro curso eu Elias que inclusive foi o primeiro curso que ele deu na vida dele também não chamava nem barbearia ainda ele a gente criou já uma perto da network né assistente dele também era casado com uma moça que é parente do seu Elias também de alguma forma que é o Jonathan eu te Criei um Network por isso que eu falo Network e ele me indicou né para um teste no seu Elias e aí eu fiz o teste mesmo sendo muito bom né O Elias contratou Olá já há seis anos agregando a equipe né e agora dois últimos anos né somando junto com meu novo projeto cara e seis anos de caminhada já venceu muita coisa lá dentro Eu imagino mas conta um pouquinho para o pessoal hoje o que que você tem atuado quais são os projetos que você tem exercido lá dentro da equipe Suel

Elias né Quais são esses novos projetos que você tem atuar de dois anos para cá basicamente depois ali da durante a pandemia já tava buscando me inventar eu Primeiro Curso que eu fiz impactou muito foi em Londres com Josh lamonica né O Elias ele chamou ele postou no grupo da barbearia falando que ia fazer um tá ia ser com Josh e o pessoal e quem saberia quisesse se tivesse um dinheiro e poderia ir eu não tinha dinheiro todo na época mas eu falei com meu irmão que era um sonho meu eu moro lá na casa da minha mãe ainda da coisa para fazer já tinha ajudado ela muito na questão cara quando a casa coisa para fazer e não tinha tanta grana assim mas eu falei cara eu quero tanto ir eu quero tanto estudar e aí eu tinha uma parte do dinheiro meu irmão vendeu a moto dele fui lá fazer piso lá quando eu voltei continuei assim aplicando bastante treinando e comecei a postar a foto dos cabelos foto comecei a postar as minhas técnicas ali mesmo assim às vezes tendo aquela aquela zoação às vezes dos colegas né Que te deixa com

vergonha às vezes fala cara você não pode ficar com vergonha vai ter gente para te criticar o tempo todo entendeu então assim você faz as coisas você faz tudo de um jeito vai ter gente para te criticar você faz de outro jeito vai ter gente criticar se você é uma pessoa usada né e fala o que você de fato pensa e faz o que você quer é vai ter pessoas criticar você não faz nada vai ter gente que vai falar que você é parado demais então cara siga o seu coração independente do que as pessoas estava pensando eu fui fazendo no Instagram eu fui postando vídeo fui rodando minha tesoura né e fui crescendo e atraindo mais clientes eu tô olhando na câmera que a gente tem outras câmeras aqui gente mas eu acho que é lá não é também não fechou não é verdade tem tanta câmera aqui gente bateu recorde de câmera né Então vem equipado hoje que eu olho nessa nessa Qual que é que tá pegando fechado tanto faz e [Música] depois que eu voltei lá comecei a educar então a gente assim Aprendi muita técnica legal na época sobre o

Uber Direction o cabelo longo cabelo médio Limpo um pouco mais sobre formas agregou muito valor sabe mas mesmo viajando todo lado aí Ensinando barbeiros dando técnica crescendo eu ainda me deparava com alguns questionamentos não tinha resposta e até mesmo esses Professor eu inclusive não dava muitas mensagens até não directs idiotas para tirar algumas dúvidas e perguntar perguntava algumas outras pessoas perguntavam para o Elias mesmo eu via que tipo chegava num ponto que eles não tinha mais respostas entende e aí eu sou aquele cara curioso assim cara e agora né E aí o que me frustrava muito uma das coisas que me frustrava era um cliente sentar na minha cadeira ou às vezes até no palco eu dando curso eu já vi que já aconteceu com outros educadores também e a gente fazer um corte perfeito Tecnicamente lindo mas no final o cliente não gostar ele pentear para outro lado ele bagunçar o cabelo ou ele a esposa dele também achar que não combinou com ele que não ficou legal a gente deixou né e deixava tipo E aí como assim o cliente não é o certo não é o foco né ele que tem que

ficar satisfeito entende eu percebi que a gente tava numa era de barbeiros e queriam conteúdo para outros barbeiros agradar outros barbeiros Não um cliente e é onde comecei a buscar mais disso cara desentender mais para entender que que esse cabelo aqui tá transmitindo mas esse cabelo aqui faz sentido esse corte esse essa barba faz sentido para essa pessoa aqui onde que tá esse estudo para mim saber E aí eu vi falar sobre visagismo onde eu comecei a estudar e no momento que eu também já tava precisando Reinventar em tudo né da minha imagem na minha técnica queria passar tava no momento queria passar mais força seriedade na minha imagem também eu minha filha tinha acabado de nascer eu comprar um apartamento e nisso a gente sem trabalhar então eu quero me sabe tava precisando de algo novo de me Inventar jogos diferente foi onde que eu emergir completamente eu coloquei todas as minhas forças mesmo tô na minha energia nesse conteúdo falei cara se eu fosse amizade se você melhores do mundo eu vou estudar tudo comprei o curso Felipe ralo eu que é considerado o pai do Brasil comprei do Robson Trindade Prepare os

livros eu paguei uma mentoria de uma consultora de mágica ela foi lá em casa eu estudei um método da Alice pesos é do sete estilos universais também e fui estudando e Criei um método dentro da barbearia aplicando os clientes fui testando E aí chegou no ponto que o neto dava redo eu comecei a oferecer para aqueles clientes mais mais exigentes né eu tinha alguns certos clientes que eu tinha um pouco de medo de fazer que era a gente joga que já tava muito acostumado comigo um deles é o Rafael vários deles que o cliente que cortava comigo ele há cinco anos e gostava Já sim entendeu o que não gostava e o que tá do lado de fora esse foi os mais fáceis de mostrar consultoria porque para eles tudo já era novo então explicar a forma do rosto temperamento dele aplicar o meu método tudo era novo sabe só que eu falei assim como que eu vou oferecer para até para esses clientes que já até gostam do corte mas eu sei que tem um potencial de mudança na vida deles a imagem deles mudar eles vão ser uma melhor pessoa melhor empresário alguém

melhor na família eu tenho certeza que todas as pessoas têm um grande potencial de melhorar do ponto que elas estão realmente a versão E aí eu lembro que eu falei com o Rafael vamos fazer a consultoria que vai mudar a sua vida ele falou comigo assim é se não vale a pena e r 500 eu vou falar com o seu Elias e aí eu vou queimar seu filme e ele disse assim daí ele fez a consultoria comigo e eu falei assim não a Deus abençoa negócio e tal pensei assim e eu sei que algo real porque me transformou é mudou muito a minha imagem né as proporções do meu rosto o equilíbrio da testa o aumento do queixo ó trouxe mais proporção também entregando um pouco mais de seriedade que é o que eu queria passar e eu tenho um resultado nítido eu chego nos lugares as pessoas hoje me tratam diferente uma pessoa de mais autoridade eles era tratado como um adolescente uma criança e uma pessoa de sabe então assim eu vejo o tanto que isso trouxe de benefício para minha vida por isso que eu quero levar isso para a vida de

Inúmeras pessoas e fiz quando terminou ele que já é um empresário né E tu e já tinha uma imagem de certa forma até boa ele falou tudo sensacional E aí o cabelo dele mudou para outra coisa que ele nunca pensou que poderia ser já estava tão ali na zona de conforto né o jeito de ser de vestir e Eles tomam uma pessoa assim muito melhor a imagem dele depois disso eu falei cara eu vou nunca mais oferecer para ninguém De hoje em diante eu ofereço sentou na minha cadeira Eu ofereço gosto Então tem muitas mensagens pessoal quando tem os clientes que sentam então vende todo lado minha agenda de dezembro agora já está fechado há muito tempo entre clientes e consultorias em janeiro também já tô com agenda praticamente toda cheia já com várias consultorias e agora ela tá 1.500 bacana demais tem muito cliente chamando perguntando e fechando e não só eu mas como os nossos alunos também né que a gente criou também uma formação tem muita coisa legal para falar informação mas vou deixar você interagir para não ficar sabendo Bora lá mas então você falou que porque até muita gente acha

que às vezes a consultoria né que em relação ao visagismo é só mudar ali um corte de cabelo alguma coisa assim mas conta para o pessoal então eu conheci agora através do podcast o seu serviço de mentoria o que que eu vou ter nesse serviço o que que eu vou Marconi vai me proporcionar nesse serviço da mentoria é uma consultoria consultoria é porque a gente tem a mentoria que sobrar alunos pro cliente são consultorias quando você quer fazer a consultoria comigo eu tenho quando ela tava r 500 eu tinha um tem um Fly sabe tudo um PDF explicando o passo a passo como imagem ali onde eu e o que que vai estar incluído e o que eu tô achando mais legal que eu tô já precisando já tem um mês atualizar e na correria não consegui sentar para atualizar o de r 1500 e é o que eu explico para os alunos tem uma narrativa e precisa construir que depois autoridade ela vai sendo tanto que fica cada vez mais fácil e você vender no seu produto por exemplo hoje eu mando um áudio para o meu cliente falando olha eu tenho horário de

tal e é 1.500 ele só fala assim beleza eu quero ele pergunta fica questionando quem que vai ter que vai ser porque já viram inúmeros resultados na minha página clientes que já fizeram comigo que indicam eles então eles nem precisam mais de tanta coisa sabe mas fazer isso então assim você fechando comigo a consultoria você vai ter então três encontros essa de r 1500 tá antes é a de 500 era um encontro só mas eu vi que não era o bastante foi por isso que eu aumentei agora ela é 1.500 são três encontros o primeiro encontro é de duas horas e os próximos dois encontros Eles são de uma hora segundo de uma hora eu pensei em colocar o terceiro de 40 minutos mas aí o cabeção Deixa uma hora também então terceiro de uma hora também tá então assim para o pensando no barbeiro né seria dentro do seu Elias seria um tempo que primeiro dia nós conseguimos Dentro de duas horas fazer dois cortes duas barbas teria isso quatro procedimentos e duas horas é então só para a gente também já pensar no benefício que o que você pode ter né nos dois

próximos encontros seria basicamente o atendimento de corte e barba e No segundo encontro um corte de barba é isso é Lembrando que daria um faturamento total de 120 que que a gente ganha uma comissão hoje no serias de 40%. esse valor então só para fazer fazendo com a consultoria dando 1.500 são dois encontros Então vale muito a pena por barbeiro e por 20 muito mais por que que o cliente muito mais cara eu mando uma tabela para você quando você fecha comigo fechando isso tem que depositar um pique de 20% para a gente garantir porque a um horário extenso não tem como eu deixar vago mais do que a gente falhar isso mente Eu acho que o cliente que fecha isso ele é um cliente que de fato quer então mas eu aconselho sim para um valor de 20% para confirmar presença e você logo após essa confirmação em caminho questionário de autoconhecimento você vai responder em número de perguntas baseadas temperamento saber seu propósito de vida é algumas coisas que já vai respondendo isso essas perguntas São perguntas assertivas para me traiu que você precisa extrair entendeu e a experiência começa em casa eu

sei que quando os clientes eles chegam na barbeiros fala assim nossa cara é eu lá em casa e respondendo essas perguntas e já me imaginando coisa que eu nunca fiz Eu nunca parei para sentar e me perguntar onde eu quero chegar na minha vida como eu quero que as pessoas me enxergam como que eu quero que as pessoas que eu quero expressar para minha imagem para as pessoas o que que eu quero expressar para mim mesmo com a minha imagem quem eu quero ver no espelho quando eu olhar no espelho entende as pessoas estão tão no automático né Não Param para sentar e pensar um pouco né Essas coisas e é muito importante né você ter esses pensamentos porque isso vai de fato moldar quem você quer ser para não passar 10 20 30 40 anos e você olhar e falar cara nunca fui quem eu fiz nada do que eu queria fazer quem eu sou aqui nessa terra entendeu as pessoas duvidam muito além do seu próprio potencial né então por isso que o autoconhecimento quer mandar as coisas que tem dentro disso é espetacular porque isso além de ajudar a mapear qual vai

ser o melhor estilo para você porque está na sua essência ajudo você entender também mais sobre porque você faz certas coisas tanto coisas positivas quanto negativas ou pontos de melhoria eu não gosto de falar não negativo todos os temperamentos tem pontos de medo e tudo isso também tá ligado com a imagem você pode criar uma certa imagem para ajudar você se vendo no espelho alterar o seu comportamento para melhorar aquele ponto ali que você tem né de melhoria certo cara Você tocou num ponto importante que inclusive eu acho que a dificuldade muitos barbeiros é de como justamente agregar mais valor aos seus produtos né ou até iniciar mesmo a dar uma mentoria uma consultoria e Em que momento que você entendeu que você poderia aumentar para 1.500 e qual que foi a chave para você agregar valor mais valor ainda a essa Consultoria cara foi no momento que eu percebi que assim que eu não era nenhum consultor de imagem porque eu percebi que os consultores de imagem eles cobram média de 5 a 6 mil reais só que eles fazem os cinco encontros eles queriam doceria muito bem elaborado né quem trabalha só com

roupa com a parte de roupa e eles fazem personal Shopping Mas então assim eles cobram esse valor mas o trabalho deles também é muito maior só que eu percebi que tinha aqueles homens que estão ali dentro da barbearia eles querem mudar a imagem eles querem saber o melhor formato de óculos além do corte da barba ou se o relógio tá certo ou não pelo menos uma dica do Blazer da calça da camisa alguma coisa só para eles iniciarem nesse mundo eu percebi que não tinha esse meio termo ou era um era outro e aí eu juntei tudo cara eu não tô estudando sobre neurociência não tô estudando mais de sete Então vou ensinar isso meu cliente porque eu tô tendo sucesso por conta disso é uma das coisas que tá me trazendo sucesso é isso eu tô estudando muito sobre como controlar e moldar minha mente para o sucesso moldar minha mente para resiliência usando o autoconhecimento para isso então indico baseado nas dificuldades nos clientes vão indicando livros o cara você tem que ler esse livro porque você tem essa dificuldade você ler esse livro aqui ó legal vai mudar muito então eu até

Criei um termo eu chamo de arquiteiro que é o Barbeiro arquiteto porque eu visagista que é comum comum assim seja aviso você já já é o top mas eu digo que o meu método que eu que eu estou trazendo eu não acho que essa chave ele ele traz essas características entendeu que é é muito mais do que só cortar cabelo é mais do que o próprio visagismo que o Felipe ensina que a linguagem visual que no dia a dia ali você entende um pouco mais do que a gente tá falando que ele passa a mão o cabelo entrega um corte autêntico entendeu Eu vou além no dia que o cliente senta na minha cadeira para começar ele já criou um compromisso por exemplo o Filipe ele ensina que a gente tem que agregar valor no dia a dia aumentar um pouco seu preço Eu já li inclusive no livro quem pensa enriquece para você ler esse livro que vai mudar a vida de vocês o dinheiro é um mecanismo da transformação você pode prestar atenção que todas eles falam no livro Napoleão Rio ele fala isso no livro que primo rico indica esse livro Inúmeras

pessoas indicam esse livro Jorge já vim indicando esse livro E aí se você ele fala assim que a maioria das coisas pagas tanto que nos Estados Unidos as coisas funcionam porque a maioria das coisas são pagas entende quando você paga por algo você cria compromisso Por que que tá olhando Marconi deu muito certo na época lá que bombou aquelas técnicas de Tesoura porque eu tirei um dinheiro do bolso e fiz um compromisso eu fiz dar certo quero um dinheiro que eu não podia dar errado entendeu porque eu não tinha necessidade né exato então quando o cliente ele põe r 500 ele cria um compromisso com ele entende ou ele mesmo né de fazer valer aquele dinheiro né talvez gratuito para ele que ele é pisar já viu aquela frase você não pode jogar pérolas aos porcos É verdade então uma das chaves tá aí é lógico que você tem que ter o conhecimento mas o dinheiro e a venda ativa muito mais o conhecimento ele então quando o cliente ele senta primeiro a energia muda completamente né Eu acredito muito na energia que é uma das coisas que o livro quem pensa que essa também

fala no Poder da do éter da energia então o cliente quando ele paga 1.500 ele já chega eu sinto que os clientes de que marcam os turistas chegam preparados eles eles já estão com energia sentindo que algo vai mudar na vida deles então é muito mais fácil é muito mais eles estão muito mais recentes mas ativos ao conhecimento a mudança né então eles estão olhando para você um simples detalhe da pomada que você vai explicar do jeito que ele tem que passar eles ouvem eles presta atenção no mundo eles compram eles passam eles aplicam E aí onde que tá o resultado porque você pode falar para o cliente assim ó cara essa pomada cabelo é isso aqui que você tem que fazer compra esse ele nem no dia a dia se você ficar falando essas coisas para o cliente ele vai achar ruim Cara eu tô querendo descansar só corta meu cabelo aqui por isso que você tem que mostrar que você é um profissional diferenciado e vendeu o produto não é ficar dando o produto de graça nos maiores erros aí de quem já é visagismo também é isso ficar entregando muito conhecimento para

quem não tá preparada mesmo que você pegar uma pessoa da primeira série e começar a ensinar ela coisa da quarta série verdade vai travar vai dar errado e aí essa foi a chave principal de juntar hoje eu falo além do formato de rosto do cliente eu mostro para ele Qual que é o formato de óculos melhor eu tenho os meus cases foi uma ideia que eu tive então eu vou fazer um cliente sem imaginar na cadeira eu vou pondo os óculos e mostrando para ele porque aquele encaixa melhor e o que que aquilo transmite e ele vai viajando assim ele vai se sentindo Caraca eu nunca pensei nisso eu vou dando exemplo das formas dos carros das coisas da proporção e eles vão eu vou literalmente vou dando uma aula ou encantando o cliente e aí a gente vai criando um projeto junto para ele se vestir melhor para ele arrumar o cabelo de um jeito melhor ele projeto que vai durar quatro cinco meses para ficar pronto te define que o cabelo o cara vai crescer daí ele sempre cortava o degradê do nada falou não vai crescer a partir de hoje ou o

cara tá com cabelo aqui a gente fala não vai tirar tudo ou ele tá com cabelo de um jeito e vai ficar igual não vai mudar nada vai mudar só o um a sobrancelha ou bigode e principalmente o que eu mais a mentalidade dele de e talvez algum detalhe na roupa isso sempre eu vejo todos vão mudar né mas eu tô entendendo que às vezes o cara pode ser que não mude tanto tem cabelo por exemplo que é só o penteado estava errado o cliente está com medo não é o Thales também tá ali fora ali ele sentou e falei e aí a gente faz cara você só não tá penteando direito molhei o cabelo assim passada e joguei Nossa tá top demais só faltava ele tá entendendo ele Acontece muito disso o cliente não tá sentindo bem com o cabelo dele ele sentar na barbearia o que aí o Barbeiro vai faz um degradê faz mas cara se você tivesse questionado cliente perguntado ele usado aos técnicos ali ia ver que talvez o cabelo nem era para cortar era pra deixar crescer era só para pentear da forma certa então juntei esses três pontos

viu o que que tinha no mercado lá fora Estudei sobre dinheiro mais sete e essa foi a grande chave acho porque além de visual né Principalmente O que você tem passado aí para o pessoal é conhecimento né e o conhecimento ele transforma né então a pessoa ela começa a entender as coisas de um jeito diferente né começabrir os olhos né para pensar mesmo de coisas que eu nunca tinha pensado mas hoje para os barbeiros que nunca se imaginaram visagistas né porque que ele deve se tornar um visagista cara primeiro e os clientes já estão chegando na barbearia muitos e procurando amizades teve um cliente meu um colega nosso lá na barbearia que sentou na cadeira dele cortou e falou assim cara você conhece uma amizade Isso eu quero na cadeira dele né Aí ele falou que me conhecia conhecia mais algum outro e tal e aí o cliente Falou Ah tá porque eu tô precisando depois eu vou marcar com na cliente dele então assim os clientes já estão chegando eu tenho cliente que marca comigo que chega na porta da barbearia que eu não conheço nunca sentou na minha cadeira chegando na recepção e

pede amizade e porque todo barbeiro quer ser mais valorizado ser referência isso vai vai fazer isso porque o seu linguajado vai melhorar sua postura né é o conhecimento do não do Futuro já tá sendo do presente de falava que era o futuro mãe do presente então por exemplo você vai subir no palco hoje quem quer ser educador para poder falar de técnica apenas já não é tão novidade sabe você falar de uma técnica de Tesoura agora você sentar e conversar falar sobre pessoas você falar sobre temperamento o que que aquela forma expressa como o cliente passa a mão no cabelo que de fato ia ficar bom para ele às vezes não é nenhum degradê um cabelo super simples com passando as pontinhas por cima da orelha aquilo que de fato vai ser autêntico para aquela pessoa entende não ensinar mais um freestyle não que isso seja errado mas que já tá chegando um ponto que muitas pessoas estão sabendo disso estão saturando e não é um conhecimento profundo também isso vai valorizar a barbearia num todo os clientes vão chegar no ponto que eles vão olhar para a gente como ele vai olhar para mim

como um dentista não nesse nível entende sim ele muda a imagem das pessoas ele muda o valor que as pessoas têm na sociedade eles não são não olhar pra gente como consultor de imagem entende então isso vai levar a classe do barbeiro cada vez mais acima show eu acho que o Elias conseguiu trazer uma grande inovação e transformação para o mundo da barbearia como um todo né E você acha que o visagismo vai ser o grande agente transformador da próxima geração de barbeiros eu tenho certeza já tá porque a gente já tem mais de 200 barbeiros né Foi um lançamento da formação que a gente já teve né Nós somos fundadora agora final de janeiro a gente deve fazer e nós temos alunos já espalhados pelo Brasil e até pelo mundo tem aluno na Austrália em Portugal que já estão aplicando e faturando muito mais encantadíssimos eles mandam textos falando assim cara meu cliente está me tratando assim com muito respeito tá Encantado com o jeito que eu converso agora umas coisas que eu tô falando para ele sobre o rosto dele sobre quem ele é e assim tá sendo Fantástico Eu durmo e acordo

pensando em como melhorar cada detalhes lá de dentro da forma como melhorar ainda mais as mentorias que eu tenho dado para eles em Como ajustar tudo para ficar cada vez mais perfeito e assim agora em dezembro a gente finalizou muitas coisas inclusive uma grande novidade que a gente tem agora é um código CBV que a gente chama do Conselho um conselho e a gente vai registrar de fato Quem fez a formação completa se tornou um visagista da mesma forma que o médico tem um CRM então nós temos agora um site oficial né da formação e aí o cliente ele pode entrar nesse site conferir se o Barbeiro de fato ele é formado e ele vai ter um código único dele como se fosse um CPF fazer um querer desse encerramento basicamente isso eu demais né E elevando também né mais ainda o setor né a área e Cara eu acho que muito muito barbeiros né eles vão se encantar com isso mas na prática eu decidi agora eu sou barbeiro decidi cara eu quero ser visagismo eu quero correr atrás disso quero isso pra minha vida qual que era o primeiro conselho por onde ele

deve ir você daria para ele cara e ele é o iniciante de tudo né Começou agora primeira coisa é saber cortar cabelo bem é Tecnicamente então fazer um curso para iniciantes ele tem que fazer um bom curso antes ele pode inclusive fazer o que eu fiz que eu acho muito bom trabalhar na barbearia de alguém né a troco de realmente chegar lá de ajudar mais ali dentro da barbearia da pessoa também te ajudar porque tem demais disso gente sabe tipo uma pessoa que tá precisando de um barbeiro ela se ela contratar essa pessoa por exemplo ela contratar alguém muito bom e se alguém muito bom vai querer ficar porque já tá querendo ter a dele também sim mas ele precisa de alguém então assim o ideal para esse cara que tá empreendendo ali inclusive o que eu fiz eu ensinei meu irmão eu ensinei outras pessoas mas é depois eu deixei tudo fui para o seu Elias Mas enfim funciona muito Então procure essas pessoas do que eu fiz um rapaz que me ensinou foi o Wesley peguei para ele pedir ajuda e aí ele foi me ajudando até eu virar um na área oficial

dele lá dentro né vale até muito mais às vezes que o curso porque no curso de iniciante aprende o básico Mas você vai aprender a cortar cabelo mesmo na praia na prática Depois tem números técnicos aí até online até o YouTube pode te ajudar né é eu tenho curso online também só de técnica né de só de tesoura para quem ainda quer aprender o cara quiser o Barbeiro quiser fazer seja moite técnica ter um conselho faça amizade tá porque isso já vai tipo a frente de muita gente a sua forma de conversar a sua postura porque ser barbeiro não negócio assim e você tem que falar vou antigamente tinha disso né vou cortar um cabelo aqui até alguma coisa dá certo da minha vida até eu era uma profissão intermediária ali né vou cortar cabelo até que descida exatamente o que eu vou fazer da vida os cara Decida que vai fazer da vida poxa cara eu cortando o cabelo eu realizei sonho que tem muita pessoa pelo superior que talvez não fez realizou ainda entende então assim é um negócio de valor para a sociedade é isso que os bárbaros tem que entender sabe

eu vejo que muito barbeiro ainda desvaloriza muito a profissão Ele acha que ah eu sou barbeiro mas sou barbeiro Tipo na cabeça dele ele não tem aquela noção Pô eu sou um barbeiro é o orgulho né Você pode também ser um barco consultor visagista entende um cara que pode ganhar muito que pode andar num carro importado recentemente né O Elias até postou lá também Realizei um grande sonho meu que foi comprar uma Mercedes comprar um cra legal demais tem um apartamento massa caseiro já fui várias vezes para Europa conheço pais da América Latina Já viajei todos os estados do Brasil né então tudo devido a isso né então senta quente na minha cadeira e conversa de igual para igual é médico que você entra na minha cadeira que tem um carro às vezes igual ao meu às vezes até ainda pensa em comprar quantos que Já sentaram na minha cara nossa aquele carro que você compra todos os ml Parabéns mano Aquilo é muito doido eu vou comprar ele e tal então cara é isso você pode sim conquistar e cortando o cabelo mas você não pode ficar naquela visão presa tipo assim ah vou

cortar o cabelo aqui é só isso tem que pensar fora da curva Então você nunca vai separar vou fazer mais do que as pessoas estão fazendo entende eu falo que vale a pena estudar cara eu falo que vale a pena porque por exemplo Visa investir um valuation lá se a gente for olhar de todos os de tudo que eu tenho estudado aí uns 200 mil reais Nem de tudo que eu já tenho estudado desde o visagismo mas as outras técnicas pode pensar assim cadê dinheiro demais velho um médico ele investe de um milhão milhão tranquilo a faculdade e ele estuda é sete anos é seis sete no mínimo aí não é dependendo desse especialização para quando ele formar ele trabalhar fazer plantão fazer tudo né então tipo assim eu tenho médico que eu conheço aí que trabalha na madrugada inteira para ganhar 750 no plantão aí hoje um Marconi tem uma consultoria de duas horas a 1.500 pronto É lógico que tem os dois outros encontros que já vai também muito mais menos pesado e tal mas só mano às 4 horas são 4 horas ainda penso que é plantão né então assim cara olha

aí o tanto que dá para se valorizar Se você usar a mente né que mais uma vez quem ensinou essa mudança de mente assim muito gigantesca não tem como eu negar foi esse os livros do Napoli Rio entendeu aprendi muito com Elias Ele abriu muito a minha mente sabe mas assim de abrir o cérebro e arregaçado eu falava mano que mundo que eu tô o que que é isso eu não sabia dessas coisas como assim eu posso transformar pensamento em realidade seria ele primeiro você cria Inclusive eu acho que essas coisas são as coisas mais legais assim pra gente colocar nos cortes né que é isso são Chaves primeiro você pensa Imagino que você quer Seja lá o que for Olha que doideira é isso Ah então eu mostrei para vocês aqui uma chave que foi os pontos que eu fui ligando do lado de fora que era o que o Construtor fazia tal do óculos da roupa enfim mas cara primeira coisa que eu fiz pensar onde eu queria chegar eu quero cobrar e antes eu nem pensei em 1500 primeiro eu comecei com 500 eu fui humilde né assim eu falei pensei assim

500 reais é muito diferente é loucura eu fechava meus olhos à noite imaginava O cliente me pagando E agradecendo e a vida dele mudando sentia isso né tinha isso E aí quando aconteceu eu falei Bá falei que nem Gaúcho aqui agora né É verdade é porque tem algum então eu converso muito né a gente tem até na equipe agora tem um Nando tem o Douglas eu eu e os lugares que a gente e aí é incrível é surreal Quando você vê as coisas acontecendo Eu juro para você que quando eu comecei a estudar dízimo por mais que eu acreditava no conteúdo Eu sabia que melhorou a minha imagem a minha vida vagamente eu pensava que poderia talvez cobrar uma consultoria mas na maioria dos casos até o César tá aqui ao me deparava no início que eu tava estudando ele já me acompanhava é meio como que eu poderia dizer meio duvidoso de algumas coisas de como a técnica poderia ser realizada na prática e o cliente pagasse se sentisse completamente satisfeito com aquele processo e aquilo transformasse de fato a vida dele e hoje eu tenho certeza absoluta de cada passo do resultado que

aquilo oferece porque aquilo foi trabalhado primeiro você pensa e automaticamente o universo ele cria para você você não precisa saber como vai ser você só precisa saber onde você quer chegar dentro da sua cabeça quanto você quer receber quanto você quer cobrar qual o resultado que você quer que seu cliente tenha só imagina o que que você o cliente que você quer que ele tem pronto vamos vamos como se fosse uma inteligência artificial né hoje tem os contatos tem a inteligência artificial que cria cop eu coloco ali qualquer atitude que você quer que a pessoa tome com esse post Aí ele vai lá e cria é isso cara o universo é dessa forma eu quero ganhar 20 mil por mês e quero que todos os meus clientes me tenham tenham respeito por mim pronto o universo vai organizar e criar isso para você do nada você vai começar vai seu cérebro ele vai começar a dar ideias de cursos que você pode fazer ideias de coisas comparação de outros mercados porque a gente a nossa cabeça é muito pequena né Deve estar manchada né tesoura vê o corte ele acha que é só aquilo mas

cara o mercado ele é muito grande entende pode proporcionar muito mais né as coisas pode ser feito E aí estudar eu fiz um curso Ele tem mais ou menos uns dois anos que eu tô estudando visagismo que é o que eu falei e já tenho e admir 500 então será que não valeu a pena as noites que eu passei estudando os livros que eu não li não cara se eu tivesse estudado direito 56 anos quantos clientes que eu tenho que estudar direito que estão até sem trabalhar investindo quanto numa faculdade estudaram quanto o tanto que ele estudaram para agora muitos ganharem tem muitos que ganham muito bem Tem advogados que trabalha comigo lá que são ganham muito bem mesmo mas quando a partida tem uma grande massa que tá ganhando quatro cinco seis mil reais né mostrando para você barbeiro que você tem muito advogado tem o mesmo tanto que você só precisa enxergar não você acreditam né não precisa potencial entendeu E é um ponto importantíssimo que você falou é que hoje é o mercado ele não visagismo não tá tão difundido no mercado né proporcionalmente falando então quanto menos tempo você demorar para

tomar sua decisão né para acreditar em você mesmo que isso pode mudar sua vida né menos concorrentes você vai ter ali né menos gente na disputa você vai ter né Marconi começou ali dois anos atrás né E já tá colhendo todos os frutos Então eu acho que tudo só depende de você cara de você mudar essa mentalidade você realmente acreditar em que você pode né então acho que muitos barbeiros vão passar acreditar Depois disso né Alguns ainda vão demorar a acreditar né mas a gente torce sempre que seja muito rápido para realmente traga transformação para a vida deles e pros clientes deles né mas cara me conta uma coisa como é que foi para você sair ali né só do corte e passar e ensinar né ensinar é uma coisa difícil é uma prática difícil e qual que você acha que foi o segredo para o pessoal realmente conseguir absorver a sua mensagem Cara eu acho que no início não tem nenhuma regra eu acho que é só simplesmente eu fiz o que eu queria eu fiz ação o jeito que dava da forma que dava com o que eu tinha eu decidi que eu

ia dar curso eu montei um flyzinho lá convidei três alunos botei eles para sentar lá E ensinei do jeito que eu sabia que o cliente gosta do meu corte eu vou ensinar a forma que eu sei é tudo que você sabe se dá certo pode ser transformado no método desde que você tem que mentalismo que você tem na sua cabeça escreveu uma organizada mas nem isso eu fiz no início eu simplesmente os caras cortei o cabelo na frente deles e fui ensinando passo que tava dentro da minha cabeça cortando o cabelo e falando no final do curso do dia eu falei vocês gostaram Deu para entender pegou nossa Gostei legal acho que assim você tá um pouco travado ainda na hora de explicar teve uns meninos que fala isso para mim não sei que tem lá sim mas me ajudou muito gostei pus o certificado na mão deles tirei uma foto para mostrar que eu dou curso na rede social quem não é visto não é lembrar não é visto não é lembrado eu postei muitas pessoas Já chamaram querendo fazer o cu da foto pagando aí foi onde que eu sentei para organizar um

pouco melhor ficou perfeito na segunda vez não na terceira também não na quarta na quinta na sexta não vê o seu Elias por exemplo dá um milhão de curso e tava conversando no aeroporto ele fala que todo o curso tem algum detalhe tem alguma coisa que ele sente que tem que melhorar e você nunca vai estar perfeito segredo é fazer cara é começar não você vai postergar nunca vai chegar a hora entende então quanto mais você faz mas vai conseguir aperfeiçoar e é lógico se você puder ter condição de fazer um relatório faça né ou estudo até mesmo no YouTube é o próprio visagismo para poder aprender lingua entender de pessoas então 60 que você já sabe que estilo que essa pessoa já muda toda essa comparação que que você é colérico eu vou direto no ponto eu vou conversar mais assim ó porque ele vai gostar mais essa Gwen entendeu vou te conquistar melancólico eu vou por cálculo melancólico aquele cara que ele ele pensa sempre que é mais viável que é mais econômico que é mais seguro que é mais organizado ele tem um horário certinho para todo então se você atrasar com

ele e ficar chamando ele para brincar ele não vai gostar a fazer piadinha demais então é muito enriquecedor isso e fazer caras você quer é ministrar um curso quer ser educador escreve um papel primeira coisa que você quer Qual resultado que você quer ter pronto só isso aí já valeu que você já mandou para o universo que você quer você já criou um compromisso a escrita ele é poderosíssima é como se fosse tivesse assinando criando um termo tá criando um contrato com você mesmo se você escrever no papel vai acontecer Tá mas passa essa é a ideia faça que fazer aonde que mais uma chave aí ó feito é melhor do que perfeito né não é à toa que você já chegou aí onde você tá né mais uma dica aí para vocês e cara eu queria entender mais uma coisa assim né trazendo na prática hoje né no seu dia a dia como é que é sua rotina como é que você divide sua semana você tá atuando também no barbear quantos alunos você ministrar aulas hoje é quantos dias da mentoria você separando essa semana ou sendo separa então tem a mentoria ela

uma vez um mês a gente faz a mentoria para todos os alunos a formação para Eles tirarem dúvidas diretamente comigo porém online para todo mundo que tá dentro da formação barbeiro visagista barbeiros que estão se tornando os ajista né ela tem acesso a um ano a gente vai dando esse acompanhamento mensalmente além das aulas que estão gravadas o grupo secreto para tirar dúvidas né e o material de apostila também eles têm aí eu tenho aula no barbear segunda-feira tem vezes que eu não estou lá por viajando então Tadinho do Rio de Janeiro por exemplo agora a gente tem as semanas eu vou estar em algum estado diferente nos dias seguintes também nós temos os práticos onde a gente ensina a técnica de corte e também um pouco do isaacismo Não tudo eu mostro como eu faço também consultoria eu faço ali o pote Mas para ser o consultor a única forma realmente vai fazer na formação porque eles ainda muito conteúdo né então é isso a minha rotina falei tudo Acho que sim mas trazendo né Mais um ponto aí cara você falou que vai viajar quase todo final de semana aí eu tô final

de semana em janeiro e a família como é que fica como é que você faz para gerenciar tudo isso daí e equilibrar tudo essa balança Ah cara minha esposa ela tá do meu lado então alinhei muito bem com ela onde eu quero chegar e a gente alinhou isso junto né então ela sabe muito bem e ela me apoia então por exemplo agora em dezembro esse finalzinho aqui ó Lembrando que na sexta e no sábado hoje não ofereceu Elias eu não trabalho mais que alguns todo barbeiro não trabalho mais então sexta e sábado eu fico em casa então geralmente as viagens São sábado à noite para ministrar no domingo às vezes pega segunda um pouco da terça entendeu eu viajo no sábado à noite né Isso pega ali às vezes domingo mas sempre a sexta eu vou casa de alguma forma e é uma parte do sábado também sempre Então quando você me dá uma folguinha ali né quando eu não vou viajar domingo aí essa sexta e esse sábado eu parte dela para fazer coisas minhas também né que é fazer alguma ação talvez alguma consultoria online no período ali de uma hora passa o

meu dia muito bem dividido nessa poder ficar em casa você sabe que você consegue tirar um tempo na academia um tempo para meditar um tempo para ficar com a família é bem legal Sabe dá para se organizar bem Já levei a Geise muito em viagem comigo minha esposa tá levendo inúmeras viagens quando eu ia viajar assim mas quando não dá para ela ir também tranquilo fico olhando em casa lá e eu já testei um conforto melhor então ela sabe que tem também né Eu só tenho uma filha hoje tem planos de ter mais uma que vale a Helena Pensa numa menina que é agitada ela desde a manhã ela já acende a luz papai papai E aí quer brincar que é isso que aquilo já pega um brinquedo já pega outra coisa ela é muito mas deve ser bom demais né é bom cara você falou que você tá muito bem alinhado né com a sua esposa em relação aos seus sonhos né Aos seus objetivos quais seriam os seus maiores Sonhos hoje cara o meu foco total hoje eu optei por exemplo por não abrir por exemplo uma barbearia para mim agora entendeu Até

conversei com Elias que eu tinha assim uma vontade ali tava de abrir uma franquia mas eu optei por focar completamente colocar todas as minhas forças na minha formação porque é por mais que ela já tá ela tá pronta mas só que eu que tô vivendo todos os dias a consultoria na prática então eu vou melhorando cada vez um método às vezes uma palavra um jeitinho diferente eu vou otimizando eu vou cortando cada vez mais o medo para deixar um negócio cada vez mais Redondo mais fácil para mim para o cliente então eu tô sempre ali melhorando né Igual recentemente eu fiz uma apostila de 200 páginas caramba digitadas tudo por mim tudo que tá dentro da minha cabeça transcrevi criar imagens autênticas juntei com design a gente criou uma logo para formação Nós criamos é todo o design autêntico original nosso toda tudo que tá escrito tá tudo dentro da minha cabeça é o nosso método Nós criamos o site Então depende de uma equipe gigante gigantesca não mas equipe grande né então nós precisamos ali de um programador para criar o código né Foi muito loucura o cara ele coligou pode cozinho dentro direto

da hotmart então toda vez que um aluno ele se forma ele consegue emitir o certificado automaticamente é gerado um link para ele um único né que ele não se repete e que é transformado no CBV que ele vai ser publicado no site ao vivo público né para qualquer pessoa pesquisar então todo esse mecanismo gerou o trabalho né Pelo visto então e aí tem a fundo do site que é criado por um programador é a cara do site que é criado por um outro design a logo foi criado por um design a apostila foi criada por outro a nós temos todas as páginas também tem a programação do lançamento é porque a gente quer fazer preparando assim algo incrível mesmo para Janeiro para o pessoal E aí depende uma equipe também de videomake diferenciada né tem uma equipe trabalho com a gente com copo com tudo para a gente poder focar totalmente na formação porque dessa forma a gente vai conseguir melhorar a qualidade de ensino que é o que tá dentro da minha cabeça que é o que o Marconi tá conseguindo fazer por isso que ele tá conseguindo cobrar r 1.500 e transferir isso

na melhor qualidade para quem tá fazendo a formação online né em qualidade de vídeo e qualidade de estudo de apostila material né que vai ser os óculos paquímetro ou paquímetro para poder realizar esse sonho de mudar ao número de barbeiros eu quero que eu fecho os olhos à noite e eu imagino muitos barbeiros se transformando em visagistas Eu imagino a família dele sendo transformadas eu faço isso à noite eu pego eu fecho os olhos e imagino Multidões de barbeiros Olha o propósito que Deus colocou no meu coração o propósito é algo que se encontra no caminho tem você nunca vai saber exatamente qual é o seu propósito não fica parado cara se você caiu no mundo do cabelo você sente um gosto por cortar cabelo você fica feliz vai fazendo isso dá o seu melhor nisso entendeu você nunca vai saber exatamente por exemplo eu não sabia se eu ia virar um tocar na igreja quando era pequeno que eu comecei Ou se meu foco depois ia ser só você barbeiro por muito tempo eu achei que eu ia começar abrir uma barbearia minha não eu saí eu dei abandonei minha barbearia O Elias e

agora quando pintou os franquias que era um sonho meu eu pensava então barbeiro eu falei não não foi Deus do nada veio colocou esse negócio do visualizo no coração eu tentei tirar isso porque nem eu acreditava em um certo ponto e ele falou não é isso Você vai continuar eu senti no meu coração para continuar e hoje já tem muitas vidas eu tava indo embora junto com Kenny de um menino lá do Acre me ligou porque eu tinha passado no meu contato para ele e ele emocionado fico chorando querendo a gente tava no carro comigo né tava no viva voz do carro ele mano eu tô muito feliz Acabei de eu fiz uma consultoria hoje e o cliente me abraçou e pagou tanto e eles custando assim soluçando assim tipo empolgado falando e aí quando o telefone Desligou o Kennedy que viu o meu minha raça meu estudo ele falou assim a gente viu quem te viu valeu a pena né cara eu vi você estudando vinho no carro fala para a gente ouvir música você não vou estudar a gente ir embora junto né chegava Na barbearia no na hora da do lanche você

tava estudando você tava com o livro aberto toda hora que eu olhava para você você tava estudando tava vendo o curso tava criando E hoje olha o tanto de vida então esse é meu foco para os próximos anos aí é poder educar né com um visagismo mal no número de barbeiros no mundo possível para que eles transformem as vidas e a vida deles realizam os sonhos deles ganhando mais faturando mais sendo respeitado vivendo a energia do visagismo que a mudança Primeiro eles não dá a imagem deles vão mudar o comportamento deles vão mudar quem eles são eles vão entender quando eles entenderam o valor que eles têm para o mundo já mudou tudo porque eles vão falar pera aí não são um cortador de cabelo eles levam eles eu não vou aceitar a cobrar aqui r 15 um corte 20 não vai eles vão olhar não eu preciso mudar tudo errado eles vão por si só ficar com raiva disso quando eles entenderam o valor que eles têm para a sociedade e aí nessa forma eles vão cobrar mais e o cliente vai pagar mais o cliente vai querer ouvir mais o cliente vai ouvir

o conhecimento o cliente vai transformar a imagem dele o cliente vai conseguir um emprego melhor com aquela imagem e aquele cliente vai levar esse conhecimento para a família dele e esse cliente vai transformar a família dele a família dele é infinito a transformação que vai transformando o outro que vai transformando o outro eu quero esse é meu foco Esse é o seu propósito de vida transformar o maior número de barbeiros através da educação e depois os meus sonhos pessoais que é levar uma qualidade de vida cada vez melhor para minha família e realizar alguns sonhos bestas aí que quando tiver no ponto alguns Já realizei que era um apartamento eu morava numa casa de tijolo com barro a praticamente a minha vida toda Barracão que tinha perca em volta poder construir uma casa para minha mãe que aí ela está morando numa casa melhor agora é morar num lugar muito bacana que eu moro hoje dá um esposo conhecer as coisas que conheço tem um carro né cara que andava de mobilete era barbearia e agora tá de Mercedes Então já realizei muita coisa mas ainda tem algumas coisas ainda que eu quero fazer quando

chegar o momento eu posto lá no Instagram aí vai estar na hora né É realmente né cara eu acho que Mas além de tudo é eu acho que é importante a gente reforçar aqui tudo isso é fruto fruto de muito investimento e muito esforço né as pessoas muitas pessoas na verdade querem chegar lá né mas não querem pagar o preço que você pagou né e detalhe mais importante ainda pessoal por mais que ele já tenha acolhido tudo isso né Vocês viram que ele tá num período de revestir tudo isso que ele já colheu para colher Mais ainda né então muita gente não quer quer só colher né e pronto acabou já tô bem aqui vamos sofrer mas você quer ainda mais né Sempre Mais E como você falou acho que além de tudo cumprir um propósito né um propósito impactante um propósito importante um propósito sobre vidas né Eu acho que isso daí vale mais do que qualquer coisa mas cara o sonho então da franquia mas adiou só Ou abandonou Eu acho que só dei mesmo que ainda quero ter um lugar físico para eu entrar para mais vendo de um mundo digital hoje

como eu consigo escalar um negócio que queima muito mais ainda no meu coração eu poderia pensar só no EGO de avo investir um lugar físico porque todo mundo vai ver aquilo né é uma coisa mais visual é um negócio mas não eu prefiro fazer algo que vai ser muito mais escalável que vai alcançar mais vidas nesse momento agora porque esse eu monto uma barbearia capital que eu vou usar para fazer isso para poder atender muitos clientes legal mas eu tenho certeza que do jeito que eu tô fazendo eu consigo impactar a vida de inúmeras barbeiros que vão impactar milhares de clientes entende aí eu posso postergar isso um pouquinho mas não aqui entendeu Eu acho que se você quiser fazer tudo de uma vez só você não vai fazer nada aquela ideia de começar o ano a esse ano eu vou ler cinco livros no mês eu vou fazer academia vai ficar na rodoviária o seu trabalho ganhar mais porque depois que você tiver ganhando mais tudo Vai facilitar até para procurar saúde facilita até para você poder relacionamento você vai mudar quando você tá ganhando um pouco mais ali que você focou primeiro no

seu trabalho isso seu trabalho te dando uma renda Melhor tudo o resto fica mais fácil começa a pensar cinco anos esse eu tenho uma dica para dar para você já tá finalizando é pensa na sua vida de cinco anos Eu por exemplo hoje eu tô com 26 cara não vai acontecer nada tão grande o ano que vem ainda nem no outro eu tô criando base para quando eu tiver com 32 35 anos eu consegui construir uma coisa legal então 10 anos fazendo Inúmeras coisas baseado num num propósito não entendeu então o propósito agora para vocês um negócio que vai achar na caminhada eu cheguei no ponto que eu entendi o que é o que eu quero agora que eu sei aonde eu quero o resultado que eu quero eu acordo e durmo pensando em coisas que eu tenho que fazer todos os dias baseado em check lists diários checklists mensais check-list de seis meses e a um ano inúmeros planejamentos é a partir do momento que aquelas coisas vão acontecendo eu vou riscando e vou elaborando novas para que daqui um prazo de 5 a 8 10 anos eu consigo alcançar determinados resultados E aí

você fala assim há 10 anos cinco anos ó passa aqui hoje eu tenho 26 para me ter 33 35 né O Elias hoje tem sete anos é um pulo é muito rápido é rápido dá o tempo que passou de pandemia aí para a gente ver né a gente faz três anos e se a gente ficar correndo atrás de chega segunda para tentar mudar a vida para o final de semana não vai dar você vai ver que não mudou nada tentar mudar a vida em seis meses tentar porque aqui seis meses a gente entra na rede social ver alguém educando ver alguém crescendo você acha que em um mês você consegue construir aquilo as pessoas têm que botar na cabeça que não vai isso não vai acontecer muitas pessoas se frustram né acreditando nisso acreditando nisso isso não existe isso não existe não existe a caminhada toda pessoa que você vai ver lá com o resultado alguma coisa ela tava muito tempo na casa no quartinho dela estudando para chegar ali agora a acontecer aquilo que é visível tem Constância a raiz já tava a raiz ela vai entrando para a terra e ninguém tá vendo

quando você tá estudando enquanto está estudando amizade no meu quartinho ninguém via aí quando você compra o carro aí todo mundo vê né aí todo mundo lá entendeu exatamente isso que acontece e só existem dois tipos de pessoas né Eu costumo falar isso mas que acreditam que vão conseguir e as que acreditam que não vão e todas as luzes e você põe na sua cabeça que você vai conseguir tenho certeza que você coloca na sua cabeça que você vai você já não vai conseguir é porque tu tá ligado de energia seu cérebro então tudo que você vê com que você fala tudo que pensa é transformado em sentimentos né você pensa em uma criança triste e vai tirar um sentimento ela feliz e outro você pensa no escuro te gera sensação para o outro e você fala que você é uma pessoa dessa Próspera esse veste assim olha no espelho energia muda isso faz você buscar faz você ter energia para tentar inúmeras vezes mesmo que dá errado todos os dias igual hoje mesmo recebi inúmeras notícias de várias coisas que deram errado uma página que eu criei no site que deu errado uma logo

que a gente criou que não deu certo um vídeo que tá errado hoje Inúmeras coisas deram errado cliente que você vai fazer consultoria e não vai dar certo de primeira talvez entendeu E aí que que você vai fazer Vai morrer não pede desculpa para mim devolve o dinheiro dele você não tá vivo faz outra página paga outro design instinto o dinheiro ladrão te roubou faz outra coisa você não tá morto Enquanto você tiver vivo você tem que continuar fazendo Vai para academia com uma banana tá passando mal Vai faz alguma coisa entendendo vai dar errado mesmo todo dia né então assim pode dar errado é o legal é o seguinte que às vezes você dá errado dá 30 vezes você né Eu já vi muitas pessoas falando isso né o primo rico mesmo dizendo já falou isso várias vezes que falha Ali vai eu já falo várias vezes né e as pessoas têm essa ideia de que você precisa mais acertado do que errar mas na verdade você só precisa acertar uma vez entende um projeto top por exemplo o dono do Spotify ou eu acerto da vida dele que ele chegou o dono do

Marcos do kenberg ele falou que tinha tentado várias outras coisas quando ele fez aquilo ali né Eu acho que o Steve Jobs não sei se ele tinha feito algum outro projeto antes sei que ela musica eu acho que outras coisas também né só no projeto dos foguetes lá ele falhou inúmeras vezes até conseguir então não então ou seja ele errou mais do que ele acertou mas quando dá certo quando ele acertou um acertou um baita acerto entende ele comenta até dos gráficos né Desse pessoal enriquecendo né que não é ali né que não é Curvo né ele vai errando do nada ele acerta muito um lado enriquece né fenomenal exatamente então só existem as que acreditam e vão conseguir e esse aqui não acredito as que não acreditam é aquelas que acorda de manhã e fala assim ah vai dar certo e nunca vai dar mesmo né aí qualquer atitude dessa pessoa qualquer energia que ela criou quando ela falou isso não põe uma roupa legal porque já não vai dar certo mesmo aí ela se olha no espelho tão derrotado hein a energia baixa mais ainda vai falar meu cliente nunca vai me pagar

mais de mais ainda minha imagem é boa como que eu vou acabou já é menos dinheiro menos Network menos energia menos saúde menos vontade de fazer pensa que não Cara vocês citou um ponto aí que a gente não conversou ainda mas sobre Network né como é que foi para você como é que isso mudou sua vida né como é que andar com pessoas né Acima da Média trouxe mais inovação trouxe mais conhecimento trouxe mais mudança mesmo para de nível para você de vibração né Você fala muito de energia Eu acredito muito em vibrações também né das frequências que as pessoas vibram então eles realmente fez ir para uma vibração acima certeza acredito muito igual eu falei para você e além até mesmo do Network é físico tem um físico também que você vai estar ali perto das pessoas mas eu vejo que a energia ela passa mesmo até ela transcede o físico então um livro Igual eu falei um livro quando eu tô lendo um livro ali na polia um rio parece que eu fecho o meu olho minha cabeça vai lá na época começa assim pode como ele pensava é loucura mas para mim

é uma espécie né mas por exemplo tá com grandes clientes hoje por exemplo o visagismo tá me conectando em clientes maiores que pensam diferente e eles querem abrir para mim o que eles pensam são importadores de caminho é basicamente isso é o cara ele já percorreu todo um caminho para ganhar quanto ele ganha hoje para fazer as coisas que ele faz e às vezes numa sentada ali de 20 minutos ele te encurta o seu caminho todo Total deu um negócio que você tava travadaço lá chega não mano entendeu por exemplo eu quero escrever um livro no futuro aí chegou um cara para mim nessa questão do Network tentei com ele eu tava nossa mas vai demorar vou ter que digitar tudo então tem que esperar um momento talvez quando tiver não sei com quantos anos eu para com isso eu falei Como assim para com isso mano manda um áudio para um copyright dessa já me passou todos os contatos o cara que vai imprimir o livro O cara que vai editar e tudo manda a sua história para esse cara ele vai o copo arte ele vai digitar tudo corrigido colhe o design manda

para gráfica imprime seu livro tá publicado e pronto Não é só isso entendeu Tipo assim não vai ser tão simples assim tem um trabalho mas perante é o que a gente imagina que é você sentar levar uma página por dia um parágrafo né com essa vida corrida e aí você fica assim pá Como que o cara tem 10 livros publicado cinco versos séries no Instagram dos caras Assim você fica sem esperar 10 anos para escolher né cara dá curso ele viaja ele cura o vento no Instagram e ele escreveu cinco livros ainda velho sério você tá entendendo E aí você começa a entender que as coisas são mais simples do que mais ele né entende o cara consultoria eu achava que eu ia precisa ficar anos para conseguir cobrar um valor desse entendeu um ponto que eu vou assim eu já vi grandes mentores né explicando o que diferencia por exemplo o Bill Gates do das pessoas mais comum uma vez né financeiramente falando em resultado não é que o cara ele ele é mil milhões de vezes mais inteligente de que uma pessoa que ganha três quatro cinco mil hoje não quer dizer que

ele é milhões de vezes melhor em tudo entende significa e ele separava algumas horas do dia dele para criação que que é criação é o cara sentar uma hora do dia dele fala assim cara hoje eu vou ter uma grande ideia um livro por exemplo uma grande ideia vou criar um livro no histórico um bom nome mudar para o videomake e vou escalar esse livro familiares de pessoas e aí ele faz dinheiro e escalável entende sim aí a gente fica pensando né esse cara como que ele não é que ele trabalha bilhões de vezes mais do que a gente mas ele faz a coisa certa da forma certa ele usa coloca energia neles certas né exato Então é isso que a gente tem que abrir a mente sabe que eu tô aprendendo agora também né eu tô falando que uns meses para cá que o que eu não paro de ficar conhecimento esse conhecimento rico agora que eu considero esse rico eu tenho pegado É nos últimos tempos mesmo essa ideia de que talvez três horas do seu dia fazendo algo novo estudando um curso novo alguma coisa nova vale mais do que a repetição

Mecânica do que você já faz na cabeça você já sabe entende sim então você passa o dia inteiro ali cortando o cabelo e chega em casa você só quer descansar aí no outro dia a mesma coisa o que que vai acontecer chegando no final do mês você vai pagar as contas se der para pagar tudo né no outro mês vai acontecer tudo de novo de novo se você não parar no ciclo né e sentar e pensar em algo grande algo de criação a única coisa que muda a vida de uma pessoa completamente é criação criar o que uma barbearia nova criar um método novo criar uma forma um conhecimento novo para oferecer para o cliente são coisas novas entende é às vezes não nem coisas novas às vezes para você mas você não precisa de criar também tudo quando eu falo criar as vezes pode só pegar uma coisa que já existe para você e aplicar no seu dia a dia uma coisa nova para você mas não quero você tem que criar algo novo mas usar algo novo que já existe no mercado para você sair da sua zona de conforto ali principalmente né

acho que é a dificuldade de muitos né cara e assim a gente muitos conselhos bons né sobre o que fazer né para ter sucesso para se elevar né no nível de vida de barbearia de família mas que que você diria para um barbeiro hoje não fazer para ele ter sucesso né O que que você ouviu o que que você tem visto pessoal ensinando aí e você acha que não dá certo o que você acha que não é um caminho legal pessoal seguir Qual é a dica do que não fazer para ter sucesso não fazer cara pai essa foi difícil né só responde o que que você tem que tá acostumado falar o que que tem que fazer tem que ser errou assim que você na verdade é tão simples que trava a gente né O que que eu acho que eu não sei em que ponto que tá a pergunta mas existem Inúmeras coisas que você não deve fazer né que que você acha passear você não deve ser ganancioso que isso vai te atrapalhar tem que ser ambicioso as ganância ela Troia qualquer pessoa né não ser invejoso eu acho que saber entender o

mundo de forma empreendedora ser homem mesmo as coisas que estão acontecendo por exemplo tem que ter aquele mimimi sabe tipo assim eu via que existia dentro da barbearia as pessoas fala ah O Elias ele ele não me impressionou educador aí ele não me marcou ele não sei o que tem lá cara começa a olhar o que que isso talvez não tá acontecendo será que o seu nome agrega tanto para ele a ponto dele fazer isso por você o que você está oferecendo em troca ao invés de ficar só questionando que quando vê o resultado das pessoas bata Palma comemore de sentimento positivo se você não consegue criar sentimento positivo sobre a conquista de algum amigo que tem ou de alguma pessoa que na internet a gente costuma ter um sentimento eu que deveria estar vivendo isso agora você tem essa mentalidade você nunca vai chegar lá quando você imagina quando você tiver lá uma pessoa pensando em sobre você Então mude esse sentimento quando você olha pessoas ricas e bem sucedidas né você tem que ter uma percepção se você acha que pessoas ricas são chatas não são legais e que elas não mereciam tá

ali você tá trazendo para você tá dizendo que você não pode estar lá você tá dizendo que ser rico é ruim que ganhar que dá certo as coisas boas são ruins você tá emitindo sentimento ruim sobre coisas boas quando você começa a emitir sentimentos bons sobre coisas boas Elas começam a vir para você teve alguém comprando passa daqui a pouco vai acontecer com você teve alguém dando educador dando o curso ou tendo uma consultoria Nossa o plano alguma coisa uma casa essa cara Queria sentimentos bom se você não conseguir criar esse sentimentos logo de cara pelo menos finja esse sentimentos bons e Em algum momento eles vão se tornar reais sabia você tem que treinando quase você fim é literalmente fingir você vai hackear porque os nossos ser humano ele ele tende a fazer muitas coisas a economizar energia algumas coisas por isso que a gente tende a ter preguiça naturalmente você tem que aprender a hackear mesmo né sua biologia natural Então quando você sentir inveja mesmo de alguém uma dica ótima dê aquele post rever engole Fala mano esse cara tá de parabéns eu queria estar no lugar então eu não posso ter

sentimento Mano esse cara merece parabéns e eu quero aprender com ele quer saber eu vou comprar um curso aqui desse cara faz ao contrário vai lá e faz ao contrário da pessoa transforma energia e nós não temos controle sobre todos os sentimentos que você vai ter imediato mas você tem controle sobre o que você vai fazer é isso essa é controle entendeu E é uma dica do que você tem que fazer é isso não não fazer né não fazer uma dica do que não fazer para ter sucesso não ser invejoso principalmente se tiver inveja engole seco e transforma essa energia para algo que vai te fazer chegar lá tá cara mais algum conselho aí pra gente fechar para quem realmente quer transformar a vida para quem realmente quer ter uma transformação igual a você para quem quer encontrar o seu propósito Qual que é o último conselho que você para esse pessoal aí cara um negócio que veio assim é povo né Eu acho que para concluir sempre eu falasse assim cara tenha teve uma pessoa honesta tenha planos anotados para você visualizar e quando você visualiza a imagem das coisas que você quer isso

traz energia para você continuar no dia a dia porque o dia a dia ele não é fácil então quando você visualiza coisas que você quer alcançar isso cria novas energias todo Renova suas energias todo dia entendeu visualizar coisas dentro da sua cabeça por exemplo você tá aí agora você pode criar uma visualização de que você vai chegar em casa e vai dar uma bagunça é a história que você contou para você você pode criar dentro da sua cabeça Nossa eu vou chegar na barbearia e vou fazer uma consultoria o cliente não vai me xingar ele vai publicar na rede social e todo mundo vai falar mal de mim beleza mandar embora cara essa história que você tá contando para você não para tudo certo eu vou chegar lá mas o cara vai pirar no meu Consultoria ele vai me pagar e ainda vou mandar mensagem para o Elias de tanto você pensar isso isso vai acontecer entende então cria a sua história na sua cabeça e tenha Deus acima de tudo e uma coisa legal também que venha na minha cabeça assim colocar em prática que é muito legal cara tem uma postura de uma

pessoa bem sucedida bem o que que é uma pessoa postura mesmo a forma como você sentado não chega o cliente você acha que nem chega na barbear jogando joguinho ou você vai receber o cliente você pega na mão dele [Risadas] cara faz assim e aí meu caro pega filho tá tudo bem Pode ficar à vontade aqui eu aceito um café uma água um chá olha firme dentro todo seu cliente Você às vezes chega no ambiente no aeroporto ou chega no meio do ambiente qualquer lugar às vezes uma loja e você já se sente inferior cara entra dentro da loja mais cara que tem tops mesmo que não for para comprar nada só para você quebrar essa energia o mundo tudo é de Deus então um dia se você quiser você pode ter qualquer coisa que existe desde que você trabalha por isso seja honesto Então quando você chega no ambiente onde que você acha que é incrível mal que você deu e você da sua cabeça todo mundo é ser humano qual você tem mesmo poder te conquistar Então já entra diferente como se você fosse dono daquele lugar é isso não será arrogante mas

a sua postura reto ninguém vai te estranhar naquele ambiente mas se você chega um falante diferente Ou até mesmo dentro de uma barbearia um lugar novo e você tá e você já tende a ficar assim ó Pedro e as pessoas elas vão te tratar como inferior porque você já tá dizendo que você inferior pode fazer um teste você vai em rodoviária aeroporto Supermercado resolver alguma coisa trocar alguma coisa em loja chega Olá ela te trata de um vai custar para resolver você trata a pessoa assim olha por exemplo primeiras vezes no aeroporto não era para ter sido resolvidas e a pessoa deu um jeito Poder de Deus posicionamento poder de persuasão a fala Correta que coisa que o visagismo tem que fazer eu pego assim ora tudo bem Prazer meu nome eu falo desse jeito meus colegas porque conhece mais molecão e hoje eu tenho mudado muito mas com as pessoas do lado de fora qualquer momento posso fazer negócio que momento vai contribuir para o meu perto de um cliente eu tomo eu tô com um problema gostaria né tá com isso e houve algum horrível né agora faz falta É eu tô esquecendo

de falar no microfone eu gostaria de saber se você poderia me ajudar com isso e com seu cliente a mesma coisa tudo bem vamos fazer a consultoria aí o cliente pergunta qual que é o valor você então custa uns r 500 mas é porque a gente já tá justificando ninguém tá pedindo para você justificar o seu preço olha dentro Vale 500 Valeria muito mais mas por enquanto tá r 500 entende tudo como você se posicionem se expressa né o próprio barbeiro já se valoriza ele deixa as pessoas botarem preço nele escolher enquanto não deixa as pessoas escolher Quando você vai você escolhe quando você é isso com certeza bom esses foram vários conselhos aí de Marconi né Eu queria agradecer Mais Uma Vez pelo por ter aceitado o convite mesmo né a agenda Mega lotada final de ano com a gente pode ver aí sobrando pouco tempo pra família e se dispor de vir aqui gravar com a gente mais um episódio uma honra mesmo um prazer né deu para aprender muito também se eu aprendi Espero que muita gente aprenda né Eu acho que tiveram conselhos aí valeuzismos né então se você assistiu até

o final te agradeço peço que compartilhe também com seus amigos com os barbeiros aí para que a gente possa levar um nível cada vez mais beleza que agradeço o pessoal do barbers é isso Irmão tamo junto aquele abraço [Música]`,

  summary:
    "Episódio 1 da Temporada 2 do BestBarbers Podcast. Marcony Visagista compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
