import type { VideoContent } from "./types";

export const podcastbruno_brito_ep02: VideoContent = {
  slug: "podcast-bruno-brito-ep02",
  youtubeId: "aGmy8i9indo",
  title: "BestBarbers Podcast com Bruno Brito — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 2 da Temporada 1 do BestBarbers Podcast com Bruno Brito. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "bruno brito",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2022-07-14",
  duration: "51:05",
  category: "Podcast",
  tags: ["podcast", "temporada 1", "entrevista", "gestão", "barbeiro"],

  transcript: `e o nosso público barbeiro e bar Beira eles comporta muito como E aí Olá senhoras e senhores sejam muito bem-vindos ao nosso segundo episódio do mexe babys podcast eu sou Gabriel um dos dois aqui no best bailes e nesse Episódio vou ter o prazer de entrevistar Bruno Brito ele quer uma referência não só no Brasil mas também na América Latina nesse ramo da barbearia tem uma experiência muito interessante Desde quando ele saiu de cortar o cabelo na varanda de sua casa até hoje tem uma das barbearias mais bonitas mais charmosas do nosso país ele também quer educador influenciador digital eu sei que tem muito acrescentar para você está nos ouvindo agora sem mais delongas Bora o nosso podcast senhoras e senhores barbeiros e barbeiro editor do Brasil muito bem vindos ao best barbas podcast eu tenho a honra de receber aqui o Bruno Britto um dos maiores barbeiros aqui do nosso país seja bem-vinda Bruna que isso cara eu tô honrado né tá aqui no podcast do best bar mas e poder contribuir com passar a galera aí o segredo né Oi Total canção do exílio está sair enfim que possa alcançar milhares de pessoas

para que eles possam ter as próprias experiências e após eles podcast aqui e aí sim não ter resultado também tá tudo aqui que for compartilhar espero que vocês não só ouça vou assistir mas coloque em prática Essa é a visão Quero trazer já no início Obrigado meu legal demais honrado vai ser muito da hora e tô preparado para as perguntas bacana demais para quem não sabe o Bruno foi o primeiro apoiador do best Barber sua generosidade assim é a 9 para com a gente desde o começo foi lá na barbearia dele e falou você que é o nome desse aplicativo já fez histórias e tudo mais sou muito grata a Deus por sua vida Bruna e ficou muito feliz mesmo você tá aqui bom pessoal que ainda não te conhece que eu acho meio difícil Larissa Conta aí um pouquinho da sua história e como é que você chegou nesse mundo a barbearia como é que você chegou o patamar que você tá hoje também que tem muita história para contar e é isso mas estou assim Começando aqui da parte do Gabriel falou nesse apoiador tem uma barbearia e vem evoluindo bastante tempo tem

bastante gente trazendo empresas para o nosso negócio continue avançando e a best Barbies é uma empresa assim não é responsável pela ajudar a gente aí no gerenciamento no agendamento assim porque não apoiar né então é é alguma coisa que eu sempre falo e é de suma importância é o seguinte esse relacionamento por muito tempo a gente teve um relacionamento só tecnológico nunca tinha ninguém com que eu conversasse o que aparecesse assim como você nos responsável pela empresa Então esse vínculo apesar da tecnologia está cada vez a razão é uma das coisas que eu valorizo Então como estava ali na barbearia cara cara é isso que eu preciso de uma pessoa que me ouça os problemas que eu tenho aqui na gestão administração nós lamento e o Gabriel a justiça aqui e vocês mais que prontamente vai lá e resolve esse negócio muito mais fácil por isso que ele tá crescendo o carnaval dispositivos tem apoiado e Tá incentivando a gente você precisa conhecer o aplicativo veste Vargas E aí a minha história é o seguinte né eu vou começar desse jeito eu não gosto muito de ficar contando a minha história porque a minha história

tanto faz para as outras pessoas as pessoas elas não estão importando tanto com a minha história quer saber como eu cheguei eu cheguei agora estão preocupado com como chegar no resultado que a gente tem eu de fato isso que eu vou comprar eu sou o Bruno Henrique Brito hoje mais conhecido como Bruno Brito então tem o Bruno Henrique bem como vc disse não sabe né que é um garoto né de filho de mãe solteira e ele é irmão de mais dois que a Tatiane o Carlos sou casado minha esposa a gente namorou Há 9 anos e morei mas um dia eu não então a gente casou eu tenho já tem dois anos de casado hoje o Barbeiro Sou empresário sou palestrante seu proprietário da Blue Beach shopping e a intenção aqui é revelado é todo o nosso caminho contar uma história comecei cortando o cabelo na varanda de casa primeiro minha mãe começou a fazer um curso cabelereiro ela queria reduzir uma despesa dentro de casa porque a gente nunca teve tantas condições então a gente cortar o cabelo necessidade meu caso eu tava grandão tinha ficasse assim uma meu cabelo que cortar e aí

ela não fazer um curso e aí eu coloco Acabei de vocês depois ainda ganha uma grana com isso e ela não deu sequência na área da barbearia na época cabeleireiro que ela queria assim e aí ficou camada lá em casa e eu tenho irmão mais novo então já sabe para quem sou eu só que ele não deixou cortar o cabelo dele de mediar não casa deixa eu cortar só pelo menos eu vou deixar o seu cabelo mais bonitinho que a mãe só passar uma máquina dois no nosso cabelo redondinho é só que ele é só que ele só vem até pela primeira carteira de identidade máquina de fazer e ele não tá amor de Deus eu quero começar tão Costa legal também minha mãe não sabia fazer com a carne deixa que eu vou fazer um corte der para você e aí depois eu vou começar a ganhar um dinheirinho com isso e vou ter condições de cortar meu próprio cabelo legal também só que não foi assim que começou com dificuldade ele não queria deixar aí eu fazia um presente triangular aqui em cima dos dele fazia quadrado fazer tudo errado e para voltar

a massa de um certo e assim cara foi acontecendo os vizinhos amigos foram bem nessa coisa acontecer e vieram cortar comigo também então assim eu fiz sete anos cortando o cabelo de graça na varanda de caso até o dia que minha mãe falou basta pela primeira pessoa que reconheceu E valorizou o meu trabalho com a minha mãe então eu não reconhecer de uma forma muito agradável não mas eu entendo por reconhecimento E aí minha mãe fez uma cirurgia tá operando o peru a vesiculo e ela tava cheia de pontos em casa e aí que aconteceu tinha 7 amigos esperando para cortar cabelo e a a namorada hoje esposa de ML esperando sair no domingo no ela levantou cheia de ponto veio Albergue e topo chamado na tomada sobrou Deixa de ser trouxa porque quando ele tem dinheiro eles vão Na barbearia olha Eles não têm ia se encontrar com você e se você não fosse bom ele não estaria aqui então quantas não te pagaram pelos r 5 no corte de cabelo eu não te devo a marca então como eu falei que no início a intenção era contar a história por contar mas para

deixar o ensinamento sobre a história então muito das vezes está ouvindo aí sua mãe seu pai te dando um conselho né tipo talvez não é de forma agradável você puxar a orelha possa é precisa cobrar um valor aí pelo seu trabalho Você precisa melhorar você precisa escolher as pessoas que tá andando porque essas pessoas estão explorando as pessoas mas mães mim só me ajudando E ajudando já te ajudou a tem mais de sete anos e com a cabeça sem graça e toda vez que sem dinheiro estava no salão quando não tentar que você tem gente tem que dar ouvido as pessoas mais experientes as pessoas que realmente gosta da gente e foi minha mãe de fato que foi a primeira pessoa que reconheceu e valorizar o trabalho então quando a gente então vem aí minha mãe já falou que não ia me importar mais cabelo devolver a máquina em qualquer um pagar aí cada um foi na casa dele buscou que tinha não era muita coisa também trouxe 13 reais r 5 2050 e me deu o dinheiro aí sabe que eu fiz eu levei o dinheiro lá para minha mãe minha mãe tá aqui

o dinheiro agora você me devolve a máquina que eu vou voltar qualquer coisa que você é muito burra mesmo é muito trouxa eu te mostrando que esse dinheiro é seu você tem Malu aí na língua viu instalar para caramba cara posso ganhar dinheiro com isso então até então eu me viro sempre como coitado nunca tinha que ser até hoje tem um pouquinho de problema com com não merecimento não faço muita coisa pelos outros e menos para mim agora eu tô começando a travar essas bloquear essa parte da minha vida tá então falei muita coisa para mim inclusive Oi e aí é esse dinheiro minha mãe me deu foi aí que pensei que era na época tinha 17 ele não chegou da 35 metros um pagou cinco essa pô mas não se eu ganhar trinta réis por dia é a mesma coisa que nós lá onde trabalhava queve no cartório Então vou cortar três cabelo por dia não preciso mostrar para ninguém para trabalhar para mim aí conversa todo o Barbeiro começa a fazer essas coisas quando vai sair da empresa onde trabalha e aí fui lá peguei o dinheirinho comecei a cobrar as minhas nem

todo mundo pensava pagar nessa época trabalhava no cartão de rede de imóveis E aí veio uma tempestade muito forte lá em casa e arrancou 93 a minha casa e aí começou a chover dentro rapidamente peguei meu celular coloquei essas novas Telhas em casa e resolver um problema mahan colocamos a usaram porque eles Ganchinho de ter a minha antes lá e na outra semana vem a chuva de novo Oi e aí mais nove meses até hoje não sei 49 meu número e aí não tem como cara eu peguei já tava três anos no cartório redimob trabalhando ela trabalhando Prefeitura Municipal de Betim na Secretaria de Habitação mexendo falou que já meio do cadastramento que minha casa viu depois fui para a parte de certidão no cartório de registro E aí peguei meu celular filme aquela situação a gente molhando na televisão cama monte de coisas e cheguei no chefe mandou no cartório foi Cara não posso mais ficar aqui eu preciso me manda embora do carro não tem uma história com barba ele começa em 2005 cortando cabelo de graça na varanda mas como barbeiro profissional conversa em 2012 e foi quando eu saí do cartório

falei cara olha só a situação da minha casa ela tá toda debaixo da água e a gente perdeu algumas coisas eu não posso mais colocar uma telhas inventar de novamente pode ser que vai voar por em casa é muito acidentado e essa parte fica bem gente no barranco eo vento vem arrebentando tudo e eu vou precisa bater uma laje para minha mãe então eu já tenho tempo de casa porque você acertasse comigo para mim ir embora e bater essa mais minha mãeu achei que ia ficar em face não tá doido você é muito útil aqui para mim muito prestativo eu vou apagar laje e vou a batendo no seu celular porque eu preciso do seu serviço ele não pode trazer sua carteira que eu vou assinar uma 10 e você tá liberado cara então assim a gente no começo não tem mais ele era a mão de Deus né sobre minha vida uma forma de usar aquele homem para não pagar a laje para mim e exatamente mingau que era meu por direito porque imagina só se esse cara paga lá e Flamengo estaria lá até hoje por gratidão o cara me atender no momento

muito importante da minha vida que ela tirava a manhã daquela daquela situação então assim cara aquela neste momento eu não entendi e aí mais uma vez eu trago em cima aqui do Face tá falando podcast vitória nos ensinamentos muitas coisas talvez está passando hoje você não entende se perdeu seu emprego acontecer alguma coisa margaria perdeu um colaborador Talvez né alguém foi desleal com você talvez alguém traiu a sua confiança então todas essas coisas vão cooperar para o bem lá na frente só vai entender talvez não vai entender agora porque a gente passa de fato cara uma história muito difícil não é só barbeiro todo mundo sim e aí quando eu fui fazer a laje eu falei mãe eu quero só sei serragem fazer o curso básico porta não um filho dinheiro é seu não vier da laje aí peguei o r 600 fiz um curso básico com eu disse a Alves lá em Betim mesmo de dois meses e o Pastor Rafael ele falou comigo assim cara por não faz um curso que eu gosto da oportunidades em 2012 salão do Rafa aí fiz o curso dois meses foi trabalhar com ele aí cheguei no

mármore trabalhado durante um ano e aí eu vi que a gente tinha os mesmos resultados sempre sabe no começo eu não fiz ninguém cortava o cabelo comigo eu tenho uma história e meio e me para trás que era dançarino de axé hahaha instante passei a galera começar aviso ar né cara assim não fosse dançarino de axé saca você não corta bem não você é isso certinho e tal e aí ninguém cortava o cabelo comigo então todo mundo procurava o Rafa o Rafa tinha mais 12 anos de barbearia não é para salão Então cara você faz uma transmissão é muito difícil então para mim Guarda tá vendo rápido tem que sair do negócio aí ele começou a sair só que os caras você não tava comigo conversava comigo acaba ele não vou ficar esperando Rafael aqui mas não cortar o cabelo comigo e embora e aqui não vai deixar-me a gente chateado mas aquele cara aqui sentava na cadeira aí eu valorizava muito então sem fazer um pezinho ali fazer uma barra sempre dava um agrado no começo então não falo mais uma vez sobre ensinamento sobre a minha história no começo a profissão e gente

precisa agradar o cliente vai ficar cada uma todo o resto da carreira até hoje existe o tal da moralzinha baba moralzinha com você dá moralzinha você Oi e o cara não valoriza o próprio trabalho e aí quando eu trabalhei com o Rafa tá no zuando churrasco que mudar esse negócio aqui que colocar um ar condicionado um café um uma balinha para o cliente aqui eu queria ser seu sócio vai falar não dá r 1500 Esse é meu sócio Essa foi só que eu entrei com a sociedade o Rafael foi Saiu o que queria descansar achei muito tempo estava cansado então quando as sociedades Agora vai tomar conta e tranquilamente só que ele chegava no final do mês aí tudo que a gente que eu produzir como eu não tava era dividir sua casa tem que trabalhar junto comigo para responder dividir sobra não cara não é o que eu quero tem um propósito Igreja Ministério da igreja negócio fazer né O Reino crescendo essa terra então assim cara eu tô muito focado na igreja você tá faltando mais meio vai vai voar vai dar grandes vou sair vai bater Arraso você tá mais comer para

que me devolveu o dinheiro ainda nem me emprestou a cadeira que usava a marmita dele aí é um armário de cozinha de um espelhinho fui lá e Monteiro saldo não 2013 estão profissionalmente falando conhecer em 2012 com Rafa 2013matheus ao normal aí para nós ter muita história né 2013 salobro não 2015/2014 Bruno Henrique barbearia forma Nossa não é grande aí mandei essa segunda estrutura em 2015 Montei no Barra Shopping já mudou a história contexto da Maria e a em 2015 eu recebo a mensagem no Direct do seu eles ele falou assim que você não tem vontade de fazer seletivo Será que nós aqui foi citado aqui tem essa unidade então fiquei assim cara muito encantado e coração disparou na hora porque tinha um mês que eu tinha investido 22 minerais da América quebro para mim shopping e era modelando literalmente deles é um xerox era uma cópia em miniatura eu aprendi isso com longo do tempo e não é e se você copiar literalmente um conceito fui lá coloquei fachada do tijolinho todo cinza e amarelo igual ele a bancar igual dele coloquei a gravata o colete a calça social sapato do céu tudo dentro

do meu bairro a comunidade que é o Citrolândia Betim então é um bairro tem um índice mundial de tráfico de drogas é um tem uns nublado de assassinato mas também tem um se pessoas que deram certo então eu ganho de lá do Citrolândia da colônia de Santa Isabel e implantamos em serviço de excelência dentro e o Elias viu isso ele ele ficava ali né olhando as pessoas se destacavam o cara eu vejo que você gosta muito do nosso conceito inclusive se implantou olhei dentro né então como você já tem toda esponjamento eu queria fazer você faz seletivo e não foi tipo um convite foi uma seletiva de fato três meses no seletivo para entrar você me avisa e aí quando a gente entrou eu fiz só quatro meses da Bárbara isso ele se deixei um barbeiro tô trabalhando para mim ficar eu estou indo lá para os dias eu quero dar grandes golos quer aprender mais sobre consigo abrir vou deixar você aqui só passa o tempo ele sair quatro meses só ele saiu eu tive que voltar eu pedi o Elias eu preciso de dois currículos me ajuda colocar a minha lá melhor para

mim aí manter a aberto que eu tava devendo agiota cara não a nossa me fazer isso tá porque é complicado demais agiota e de virar minha sogra é não sei porque eu tinha mais medo e aí na casa dele lá eu preciso pagar e tal ele o castigo de vestir uma camisa uma seu Elias eu abro no grito eu tô cara eu sou muito grato eu não queria ter feito você passar por esse trabalho de seleção Então você ter que selecionar tem que treinar teve que é lapidar e agora tu deixa na mão mas todos os barbeiros do Brasil que está no lugar mas eu preciso contar-lhe sono eu preciso uma raça coisa que eu preciso pagar lá e agora eu tô deixando assim então foram 4 in ribs muito conhecimento muito aprendizado eu ficava colado no seu livro queria de fato fazer com que a marca crescesse eu queria de fato fazer com que a marca fosse reconhecido inclusive hoje você só na minha cabeça e nunca me falou isso eu acredito se eu tivesse lá até hoje eu seria um de educadores dos outros negócio né Barber Day online de aquele tem mesmo

tudo funcionamento que eu tô sem a busca de crescer mas eu ficaram voltei para trollar ele ficar agora é hora de fazer acontecer E aí eles juntou toda a equipe orou pela minha vida e falou assim não isso tô cara você vai sair sai para fazer bem feito sai para fazer direito e assim foi saímos Montamos a equipe de novo chamei uma pessoa para trabalhar comigo com sociedade quero Felipe Bolt muito importante para misturar também o Felipe boot a gente juntou uma grana e foi para o centro de Betim 2015 então 2.500 começou número para ver shopping em grande escala estrutura gigantesca a cadeira de massagem a marca ganhou uma expressão enorme e saímos do corte de 28 no bairro Foi máximo a gente conseguiu já para r 40 então é um outro medo que a galera tem apresentar eu vou montar uma barbearia nova no bairro qualquer coisa que todo mundo tá cobrando lá no cobrar isso eu não quero prostituiu mercado quero ser o diferente sim eu quero entregar excelência no centro então tu não tá com medinho eu vou comprar a 40 Então essa foi a parte competitiva do negócio então eu

tinha que entregar mais do que todo mundo tava entregando é e Montamos o Felipe boot ele saiu num certo período depois de um ano um pouquinho e aí passei a ser simplesmente o dono do negócio e aí Eu reconheci um processo do meu irmão lá de trás e passei para ele parte da em preso e aí Karen explodiu não teve como porque meu irmão mas estou administrador eu sou cara operacional da equipe lidera a equipe em ponto eu a marca que é hoje não é Bruno Brito lá no shopping São 18 anos de mercado somos líder em Betim reconhecido nacionalmente né como é conhecida como está Minas Gerais também depois disso o torneio educador Já rodei mais de três estados no país Vou direto lá para o Paraguai ministrar cursos também me tornei embaixador da Jaboque Brasil e mais de seis anos também sou parceiro aí the best parceiro da assistência do cabeleireiro enfim Temos bastante parceria Cara não sei dizer quantos alunos de verdade eu acredito eu ia deve ter passado aí menos 10 mil alunos desde os dois mil e dezesseis que a gente começou a entrar na eu falei de workshop com

mil pessoas 500 pessoas 300 um aluno né curso online hoje graças a Deus tem mais de 1.300 alunos através de curso online e também fora do país que pessoas estudamos através do curso online e o McQueen né cara fantástica que entraram ao serviço em o meu irmão estou administrador mas teve Minha cunhada é contabilidade tem os meus barbeiros que fazem no serviço implicava minha esposa que aí braço direito braço esquerdo ajuda sempre e a gente vai crescer né cara hoje tem um grande parceirão que eu li não é um parceiro aí não só de negócio né cara o cara meu pastor cara é meu conselheira meu amigo estou hoje na gente tem parceria alguns negócios aí a gente não pode estar falando agora que ainda tá para como precisar mas bem grandes coisas aí da parte da educação Na barbearia da parte digital da barbearia e a gente vem desbravando e o mercado para explorar tudo hoje a barba ele virou uma indústria né sim não é mais só cortar cabelo então nossa história começa Barão de casa chega Nessa grande e atmosfera que é hoje aproveitando todas essas oportunidades e crescendo cada a cada

vez mesmo cortar o cabelo se loucura muito orgulho assim é o que eu falo pra galera quanto mais longe você tiver da cadeira mais crescimento você vai trazer o negócio essa acho que eu quero dormir uma hora o André que é melhor sorte que daí fala isso direto né tem que sair uma hora do operacional legal demais Bruno e manda as pessoas que você mais fala é do barbeiro mudar a mentalidade né Não só pensar em na cadeira igual você tá falando que atingiu esse nível de prosperidade quando sai do operacional e aí o negócio bomba esse então o que que você indica o pessoal nesse casa como essa mudança de mentalidade cara primeiro ponto importante é deixar de ser todo mundo então falando do meu lixo o nosso público barbeiro e bar Beira eles comporta muito como todos se comportam ai eu vou colocar a fachada assim que tá todo mundo colocar a vou colocar Barbie Polly lá fora porque tá todo mundo colocando como o cara vai fazer a definição e ele vai cobrar no serviço ele não vai se basear pelo Quanto custa a empresa dele ele olhar quando o cara do

lado tá cobrando e costuma colocar mais barato ainda tem intenção de lhe pegar o cliente de lá e colocar aqui então eu tenho que deixar de ser tudo e quanto que eu percebi isso olha tinha os resultados que eu queria deve ter bastante cliente era ter dinheiro como o negócio ele ficar sustentável tem cliente toda hora então já era reconhecida Ali no bairro todo mundo queria cortar comigo mas eu não tinha vida eu virei um escravo da barbearia eu meio tranquei lá dentro Margarida eu vi a chave para fora e preso porque primeiro que eu não tinha horário eu ia até muito tarde trabalhando como Tinha cliente toda hora então chegava oito da noite 9 10 11 horas meia-noite 1:00 2:00 3:00 da manhã não sei quem é mais doido é o quarto dele o seu cliente corta a cada três horas da manhã cara já cortei acredita tem gente que está assistindo que é também já cortou e a gente é um e eu vou vão bom recomendo ali na Margarita nunca tinha uma cozinha né tudo misturado e o que que vão LED comendo ali e aí foi aí que eu descobri que

não podia comer pão com salame né porque senão ficava voltando aqui nosso cliente porque não era todinho era refrigerante era o pão salame era uma coisa o cara passava ali vendendo rapidamente é isso que eu quero minha vida aí dava domingo eu tava atendendo até meio-dia só que esse meio-dia até quatro da tarde cinco anos ninguém contava comigo para festa de família alguma coisa festa todo mundo arrumaram que eu arrumei esses mas eu tava sem cortar o cabelo então é isso que pede que não existia naquela época estava tão bonito que eu não tinha então o que aconteceu cara eu não quero isso mas eu quero deixar de ser todo então chegava assim ao em casa eu lembro como funciona tirava a mão do bolso colocava na cama sempre monte de dia e era isso que envolve a gente o cara eu tô bem demais ao tamhanho dinheiro ainda não Oi gente tem a gestão aplicativo online tem toda a parte né administrativa barbearia é muito melhor o nosso conhecimento e eu cheguei até dar troco errado cara nota de 100 e Steam da troco de dois reais é da nossa senhora achar alguém eu

disse reais não me falou e aqui no salão desgastando almoçava não tinha horário não consegui sair com esposa em contato comigo nas festas de família não basta cheiro ser tudo bem comecei estudar então eu fui estudar o mercado fui entender o que que as barbáries igual a minha fazia que era bermuda chinelo camiseta Qual é mano já é caramba toalha manchada espelho quebrado banheiro sujo no cabelo ahh adequado ferramenta que não era tão boa não ficar exatamente isso que eu tô fazendo então comecei a me dar uma mentalidade o que que os grandes players estão com André e aí foi frequentar as grandes lá ver isso o funcionamento manobrista aplicativo online de existir nada na época um cafezinho lugar ficar colocar a roupa de frio Blazer jaqueta o capacete atendimento personalizado vocabulário adequado e Caramba isso E aí foi o que eu comecei a colocar na Marlene então estudei o mercado primeiro não tem dia como ele funcionava nas duas extremas tanto da mais baixo planta alta e entrei no meio não vou falar que eu virei um top porque eu fui barbearia que eu vi totem de carregador que tinham televisão no Oeste os

carregador Simca 3 não consigo ter isso mas aquele carregador com três rapidinho eu consigo Então o que eu falo com a minha galera que ele saiu já fazer próximo passo é melhora o próximo é corrigir a gente tá não fazer até hoje muita gente acha que já tá no nível de correr de tudo não está fazendo até hoje então quando eu entendi qual que é a diferença de ônibus comecei colocar preço Oi e aí onde vem o medo da galera é onde vem eu falo da mentalidade não é sobre atender todo mundo que você não é mais todo mundo é sobre atender quem valoriza o seu trabalho se é sobre você atender aquela pessoa que gosta de ser bem atendido não máscaras pessoas não aceitam aceita mesmo porque tá brigando pelo mesmo público o povo de 10reais de 15 anos e não tô falando tá errado sempre vai ter esse público a pessoa Às vezes não tem condição de pagar mais que isso mas cadê os caras dos mercados dono do hotel na academia da enfim das empresas dos negócios locais como que o seu nome vai chegar nessas pessoas que foi assim chegou quando

eu mudei meu posicionamento então primeiro coloquei a ordem de hora marcada começou a falar usadas no bairro Nova brincar chato demais agora tem que marcar horário com ele aí os caras entravam sem camisa meu Barbieri os caras pegar o meu controle a água do frigobar colocava do lado só pra tirar o chinelo p e vai ficar fumando falei que eu quero canal na minha barbearia você encontrar vez que pegar a máquina passar a axila Nossa e passava na barba e aí eu fui e a galera infelizmente acontece até hoje pegar ela não consegue se posicionar Então esse foi o patrocínio no meu crescimento Então essa notícia ruim ela corre muito rápido aí como a galera falam sobre leque vai agora tem que marcar horário tem que entrar no aplicativo online é nós que tá todo almofadinha entrar por favor por gentileza Então os donos dos negócios locais ai ficar assim agora vou procurar ele então precisa ter medo porque vai ter o povo vai criticar mas eles vão Patrocinar o seu crescimento foi essa essa mensagem ela vai ganhar mais força e chegar em quem você quer e foi assim a nossa mudança e até

hoje cara e um Betim nunca te a história Até onde eu sei alguém obras r 48 não corte de cabelo ele chegou nesse vídeo e eu quero nos próximos um ano e meio cobrar r 60 a minha maior referência é o seu Elisa responde pra ninguém em Belo Horizonte com a equipe cobra r 50 então então espera aí eu tô à dois reais de chegar no livro não é festa não quero ultrapassar o valor porque eu acredito que é é possível sim então não estou faltando somente até o resultado dele eu quero um vinho pouco além questão de valores cobrados pela Mares Só que aí o seguinte eu vou perder frente eu acredito que mais que cinquenta por cento Mas eu não quero ficar atendendo 20 pessoas que era 35 que pode pagar minha mãe então exclusivo e personalizado atendimento à obra e esse é o maior desafio do barbeiro você ele abrir mão daquele cara que nós mais cara quatro comigo há 7 anos amém que ele cortou sete anos agora tá na hora de reciclar a clientela e fazer esse negócio assim é melhor do que ter 20 pagando 10 melhor ter dez

pagando 20 e ciência em você vai ter muito melhor e uma das questões também é que você fala muito é querendo ou não a pessoa tem que se posicionar no digital né quem não está no digital ainda hoje então é um futuro digital presente quem tá no digital tá atrasado onde estava na verdade até o passado se você for olhar assim pequeno então digital tá muito atrasado e o que que você acha que é essencial um barbeiro uma barbearia tem nesse tipo de presença online justamente para alcançar esse objetivo né de alcançar esse público que vai valorizar o trabalho e vai se ajudar não ser mais um escravo e é cara assim o digitar lhe proporcionou hoje eu atender uma vez por semana porque através do digital eu exploro hoje mas oito fontes de rendas né então através de passeio e essa veste os online através do YouTube através do Instagram então eu importante falar aqui esse crescimento da Bruno veio para mim ficar ouvindo bonito também e parcelo digital então se não tivesse digital estaria corta cabelo todos os dias e não tá errado aqui em corta todos os dias por quê Porque ela

consegue sustentar o próprio negócio sustenta ela mas só que muito difícil ela escalar o negócio então por exemplo é para gente cortar hoje cabelo viver só de cabelo assim cortar muito cabelo sustentar negócio e a si própria agora por exemplo a gente tá aqui conversando pode ter algumas pessoas comprando o meu curso online é uma renda passiva tigre de determinado tempo é gravando as aulas gerando audiência gerando o gerando reciprocidade gerando autoridade para que as coisas funcionam de uma forma mais fácil entre aspas né para falar assim mas automática é sempre melhor palavra automático então isso possibilita a gente dessas fontes de renda mais e também você conhecido tem gente que é ser reconhecido quero ser conheci se eu não fosse na rede social juntar aqui agora gravar o podcast do best bar mas e talvez não seria a parceria que a gente tem hoje E sem contar também cara com o funcionamento do digital da empresa hoje o cara vai pai ele só até confundir essa parte aqui uma loja ele vai abrir a gente dele vai lá e só pelo Direct ela só que o Stories agenda aberta bom E como estava tipo

todos os clientes fossem receber aquela aquela aquele história mas o algoritmo não faz isso não muito importante também o cara trabalhar com tráfego pago com certeza porque para gente falar vamos falar aqui em Betim tem seis barbearia sair de alto nível mas tem a Bruno para deixar o mostrando de Serviço direto através do tráfico foi pago e muita gente achar mas tá sendo pago um trás frente mas quem disse que é só para trazer beijo tem que posicionar também chamar para elevar o nível de consciência do cliente até chegar o povo dele comprar de você só que as pessoas também não estão tirando uma parcela financeira para esse para esse tipo de trabalho então assim cara digital eu fui residente No começo eu não queria saber do WhatsApp não quis saber Instagram a gente tá com 100 mil seguidores eu muita gente tanto barbeiro quando o cliente é um pesados de outros meios também e o digital ele possibilita cara você exponencializar o seu e esse é meu fone visitam quem não tá no digital ou tem três pessoas né tem o fornecedor e tenho consumidor e tem um produto tema também fornecendo e quem

não tá bem consumindo é o produto que está aparecendo uma chuva e de alguns para ele comentar entendeu então eu acredito que a pessoa precisa começar a fazer um trabalho por mais que seja simples e aparecer você terá e abro mas por onde começar começa a contar a sua história só que eu conta a sua história só para falar quem você é ensina como você chegou onde você chegou menos história Então você possa dar uma dica de digitar é assim ó sempre pense a começa a sua história começa contando a sua história no meio da sua história você sai dela e coloca a terceira pessoa três assistir até criar uma conexão e me ensina para ela coisa simples porque se você está coisas simples para ela ela tem condição de colocar em prática Se ela colocar em prática tiver resultado com que você ensinou servir autoridades Com certeza e aí você vai começar até a confiança dessa pessoa então se você é constante nesse vídeo você começa a ter resultado no digital tanto para cliente aí se não cara com pentear o cabelo como cuidar da Barra ou conversam assim ele como higienizar enfim aquelas

educador ensino cara como comprar o Pedro especial o maior pende Qual a melhor máquina esses as coisas básicas mas isso é muito básico é porque está querendo ser o grande rápido demais então se apaixonar tão simples enquanto a todo mundo propágulo extraordinária que eu tô preocupado com o cinto porque ninguém faz e aí eu tenho resultado saúde lá sim então se você ensina uma coisa simples no digital e a pessoa coloca em prática e teve resultado o padrinho vem um ponto ela hoje ninguém compra mais só por reciprocidade compra por confiança bom então carga quantas vezes as pessoas têm vergonha de mostrar a casa onde mora Quem é a forma que fala os perrengues passa na vida é um presente pertences mexendo é bom agora que é uma um ele te ligo e a uma parada do meu emocional eu muita gente tem medo de mostrar isso cara isso sou eu então são essas feridas sim que cicatrizou que não servir de remédio para as próximas pessoas e na no digital não precisa ser um astro não é para você ser uma pessoa é um personagem porque eu já fui personagem também os 10 minutinhos

quando fui trabalhar o seu dia daí era só azar então tio tio o curso eu ia lá Nazaré comprar um sapato das a causa das blusas o óculos não sei o que o dinheiro que eu recebi do curso ficava todo na Zara e não era eu entendi então cara o cara tem que viver de vez em quando os penteados vez com o pé no chão Alencar mas tem que me der na grande largaria tem que me ver essa no perrengue Problema Emocional é dificuldade na família e ficar esse cara é a cara da gente então eu confio nele é de automaticamente é as pessoas começam a comprar os seus produtos que seja ser seu cliente da cadeira Maria seja comprar um curso com você seja indicar você para outra pessoa então está no digital hoje permitiu exponencializar Nossa negócio e quem não tá nele infelizmente várias atestado não só não vai escala sim e justamente por todas essas dicas não é que você deu eu acredito que a pessoa pode alcançar os objetivos mas no seu caso você alcançou assim ó e não só no Brasil mas também fora do Brasil tanto que você uns

barulhos que mais vai para fora do país das palestras serão educador lá fora e como é que esse experiência conta um pouquinho pessoal porque não é comum né É cara assim eu fiquei muito surpresa né pelo primeiro convite ali do pessoal da home pro lá no Paraguai quando eles me chamaram para ministrar um curso fora do país certeza que está falando Bruno Brito é de né outro nossa casa não é a primeira vez que eu fui no Paraguai foi eu criei a situação então eu falo muito isso tem gente tá esperando só ser convidado faz cara eu vou forçar o convite Então tava num evento no bar music Oi e aí eu tava com barbeiro também reconhecida é normal e colocar aquela mulher ali me levando para guardar esse sério vou lá conversar com ela agora aí falei com ela que não é que eu faço para mim Paraguai aí ela falou assim não só precisa me falar aconteceu cachorro no seu as suas pedágio está na final tem encaixando eu só querem paga só me passar um lugar para mim dormir só isso E aí cara as pessoas que não me chamou eu fui

lá ministrei um curso entre as para gratuito mas ela pagou hospedagem alimentação de me deu um valor simbólico Não não quero que você vai assinar depois disso Paraguai ficou me conhecendo então eu forcei uma barra Paraguai me conhecer depois disso a maior empresa Maria que ela tinha que arrumar pro viu através da semente me levou por isso que certezas estão falando cara séria não a gente que é você aqui foi o maior cachê que eu tive até hoje na história de ministrar cursos foi o curso que eu levei mais pessoas e presencialmente estando eu sozinho palestrando foram 240 pessoas que eu nunca consegui fazer isso ainda aqui no Brasil falei não cara é É surreal E mais uma vez eu vi uma oportunidade porque eu olhei para comer faça a gente não tem Embaixadora só o maior empresa e não tem baixado aí eu já ofereci para fazer trabalho para eles e aí o Euler quer um parceirasso aqui visionário o cara tem mais um negócio aí dentro aí que é uma gente que a gente tem vontade de prestando um serviço para ele lá dentro acabou que os voltei da segunda vez Paraguai vem

tornando Embaixador técnico dava metrô muito bater então hoje cara eu sou divulgado pelo Instagram deles alcançando aí México pelo Argentina Chile e daqui a pouquinho começa a ver os convites e hoje a gente já tá para voltar lá nos próximos mesmo está mais um curso trágico xó tô assim cara a experiência é muito primeiro que é o a cultura Elsa fronteira a gente não acha que as pessoas vão parar para nos ouvir então os simples funciona acho que a seu como que a experiência cara não queria falar como foi a minha experiência eu quero falar que o seguinte os simples funciona eu não lembro nem nada até hoje extraordinária ao que faz colocar isso aí é muito difícil de fazer isso eu sempre se encarar Mas é isso que ficar em cima é isso que me levou a outra Fronteira É isso aí mas você Embaixador internacional é isso me trouxe os resultados aqui que eu tenho hoje então cara experiência de tá pisando em outra nação e tá ali com a bandeira do Brasil cara é a mesma do jogador de volta em outro Ninja é cara a gente que é barbeiro assim uma

boa parte que sempre sonho de ser jogador eu acho que a experiência o cara tem de ser jogador profissional acho que já que você não tem como barbeiro profissional reconhecido internacionalmente Então esse cara eu acho o que nós temos que acreditar né que existe um Deus que é poderoso para fazer infinitamente mais nossas vidas mais natural mosca sim eu tenho assim cara grandes feridas a minha vida grandes Dores em fora da minha mãe que para cada um perde ela quatro anos foi a pessoa que valorizamos o trabalho e essas feridas cicatrizadas hoje serve de remédio para Muitas pessoa por isso que eu não falo até agora você não falou de um corte de cabelo até agora entendi então a minha meu chamado meu propósito é exatamente esse quando eu entrei no vermelho fiz simplesmente reforma na casa minha mãe é Deus eu te chamei para reformar uma casa também para reformar a geração e Através disso que a gente tem vários testemunhos de pessoas que receberam seus casamentos de pessoas pediram perdão dos seus pais perdão sua mãe de pessoas que saíram de bichos pessoas que hoje estão entendendo de novo emprego através dessa ferida

que eu tive mandou muito grande que Deus cicatrizou e o a gente continuar levando através aqui também até do podcast o cara é muito é a sua história é um conjunto de coisas que você deve usar como um bom testemunho para as pessoas acreditar então você temos que vai ser o jogo Lego simples é para poucos que ele entrou no que fazer assim que mais funciona mas muito muito bacana e Bruno em termos de posso anemia né Foi um dois anos e meio até um pouco mais muito difíceis e que você ver para o mercado da barbearia cara então fala aí para dormir é assustador né você diretamente essas manchas que vieram as lesões mais forte Agora minha mão e é um Problema Emocional eu já tenho ela desde 2012 e apareceu no nariz meu pescoço eu trato ela volta né com dermatologista só que não poderia eu perdi quarto Barbie eles vão risca um negócio grande que a Bruna está no shopping hoje ela é sustentada hoje por equipe também e não só o meu caso mas teve muitos empresários que investiram o negócio mas não era mesmo e é outro mas também fecharam

as suas barbáries que eles não conseguiram restabelecer equipe bom então como eu sou barbeiro velho já aconteceu lá umas decepções em barbearia coisa não venha casa mais particular que eu tive que mandar um barbeiro embora depois do outro foi o outro foi também o que foi que eu olhei para dentro daquele elefante gigante foi meu Deus agora aí fazendo falando em palavra mais populares né Eu não sou educador de 2016 eu não sirvo para todo mundo é como se diz falar assim comigo você é o bichão você me xingar todo mundo quer ver você fazendo o seu negócio agora E foi exatamente o que eu fiz cara bate em várias fotos de barbearia F seletiva levantei o equipe de novo e restabelecemos mas o que que eu posso falar Posso para dormir ainda as pessoas estão emocionalmente abalados sabe e ficou preso muito tempo então muitas pessoas tiveram rir problemas emocionais acabar gerando gastrite Sônia mancha na pele queda de cabelo decepções algumas pessoas também é se aproximaram mais da família outros se distanciar Então tem que pensar o seguinte que ela é muito bom de barbearia que falam assim posso poder me faz de

forma estratégica da empresa muitas barbearias de uma vez só querem eles terem resultado então eu sempre fui um bom ouvinte e ouvir meus cabelos parte que estão satisfeitos que precisa melhorar então eu passei a tratar individualmente cada barbeiro cada um temperamento cada um temos tiro cada um perfil Então você possa falar para vocês o que fazer para crescer posso anemia é cuidar mais as pessoas falar contigo então cuidado até de você tem trabalho sozinho que também que eu tô fazendo agora em supermercado tô jogando mais bola tô curtindo mais a vida tô acelerando um pouco de conhecimento o conhecimento vai vir até com mais força porque eu tô cuidando de mim primeiro para mim tá bem para poder cuidar de pessoas que a gente possa é delícia gente coisa de pessoas Então está bem é importante posso é porque tá todo mundo correr sério prejuízo né mas tem um prejuízo Empresarial mas tem da Saúde também com certeza somente de saúde mental então eu refleti muito sobre isso tá é e cuidar de mim cuidar na minha equipe e principalmente para explorar muito à venda para o mesmo cliente serviço de valor agregado a gente

conseguir fazer Caverna de um produto de uma química é estabelecer metas desafio vinificação mais principalmente recompensa ou se tempo pensar aquelas pessoas estão trabalhando com a gente vai ficar muito feliz muito importante para todos aí da barbearia que valorizar a equipe é muito essencial para a gente fechar o que que você pensa esse novo modelo que têm surgido agora de franqueado barbearia só que a sua visão sobre essas cartas não né Eu gosto demais até mesmo posicionar porque Esse é o seu Elias cara eu vejo por um monte de Deus sabe o cara assim que vem abrindo caminho com a galera passar só que tá abrindo caminho pela mata fechada e tá passou para tô passando umas foto deixando tudo sinalizado colocando tudo bonitinho não é por aqui o caminho e aí cara aqui pensando análise swot né Tá na sua Ótica aquela fofa né são as forças as oportunidades fraquezas ameaças então olhando pela pela empresa simisa hoje eu vejo como uma força e oportunidades para a empresa dele é só que a e ele fornecer por muito tempo né como eu trabalhei com ele tido um certo contato próximo dele e assim foi

muito resistente e hoje abriu né a mentalidade ali ainda mais que é um cara grupo visionary respeitado aí no mercado e eu acredito Clube aumente tá tô puxando o saco não que de fato é mesmo diferente mas mundialmente respeitado bom e é uma oportunidade e uma força assim mas e aí vamos olhar o outro lado da moeda aí Quem é que tá do outro lado se que vai receber uma franquia na Cidade vamos nascer uma franquia seu Elias em Betim Será que era meu beco lá no shopping hoje está pronta Será que a Bruna lá no shopping vai competir de uma forma de igual para igual ou é uma ameaça porque análise swot ela para isso você tem que pensar nas amigas não que ele se é ser uma ameaça para ninguém só que a crescer A marca dele aqui neste que fala isso mas por exemplo vamos falar que vai chegar uma franquia mesmo interior de São Paulo será que os valores lá então preparados para receber de igual para igual por isso que Deus repetir porque a minha visão significar Eu louvo a Deus e operadores todos os dias quanto mais Deus da

sabedoria para ele abrir o caminho mas no caminho passar então é um futuro aproveitando a ver Shopping ser franqueada e o que ele vê a vista está falando que o assunto que acontece e vai aparecer aqui mas você fala assim vamos lá no mundo que é muito conceituada que dificilmente seria então mais uma vez Então eu falo o seguinte você não pode ver então prepare-se para receber do Futuro Shopping então comecei a organizar com a minha entendeu teremos breve em nome de Jesus e aí você tem que se preparar [Música] para competir de igual para igual a gente tem um custo ali e como colocar um custo no valor percebido pelo Com certeza que armas vai existir o corte cinco dez quinze vai mas a gente quer falar sobre ela trazer essa galera dos cinco dez quinze também para o próximo I Então existe após a força EA oportunidade para ser liso e existe ameaça para quem não tem preparado porque tenho para te falar é o meu ponto isso mesmo também nunca me falou isso mas se eu trabalho no pequeno barbearia e eu tô um pouquinho cansada que você insatisfeitos e a pressão

uma barbearia grande eu posso fazer parte eu vou querer isso mesmo fazendo suscetível automaticamente se perto da equipe carioca você mesmo tá tá entrando na da franquia do Rio Preto a a manchar por exemplo então gente é o seguinte mercado é para todo mundo os ensinamentos aí para todo mundo os cursos online estão disponíveis os jovens estão disponíveis cursos práticos ou conhecimento tem então não existe melhor forma Será que nós podcast falando conhecimento a ti sabedoria é fazer acontecer com os então conhecimento dentre gente tá cheio de por isso mas não tá colocando nada em prática então a Mas isso não estava mais passar para vocês é é não foi nada mais fácil quando ela abriu o Instagram não tinha ninguém para entrar primeiro seguidor foi igualzinho tem no Instagram de todas as pessoas a gente começou com 1,23 fato se e como a gente chegou lá gente tá sempre compartilhando por isso que a gente tá aqui no mestre Barros Hoje podcast Contando um pouco da Vitória um pouco da minha visão de mundo um pouco que eu sou dos assuntos do mar menina para ver se eu te conheço mesmo todos certeza que

muda ele sai daqui com conhecimento mas sabedoria será um pouco sair colocar a metragem um pouco do que aprendeu aqui então é ter sabedoria ouvir as pessoas mais experientes não só esperando as pessoas que gostam de você entender que o ciclo de funciona e que Deus é poderoso para fazer infinitamente mais na vida é só que natural me entende ele é massa demais Bruno brigadão Deus abençoe e prospere daqui a pouco está no teu a Bruno Brito aqui do ar para tirar a volta aí para que isso aconteça logo espalhar né nosso conceito da nossa forma de trabalhar de entregar um serviço com excelência aí com certeza eu vou ficar pequena para nós ver pessoal você que ainda não conhece o Bete Barbies o link está aqui na descrição desse vídeo e o Bruno e o carro o irmão dele foram os maiores contribuintes para o nosso sistema várias funcionalidades foram sugestões e ideias dele então eu sei que vocês hoje estão desfrutando nessas funcionalidades e se você tem alguma dúvida alguma crítica alguma sugestão alguma melhoria você pode também tá entrando em contato com a gente dos canais de atendimento que vão estar aqui

se vê lá o Bruno também nas redes sociais dele e até a próxima valeu aos Trilhos tamo junto O que é nóis Valeu demais né E aí [Música]`,

  summary:
    "Episódio 2 da Temporada 1 do BestBarbers Podcast. Bruno Brito compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
