import type { VideoContent } from "./types";

export const podcastmarcony_visagista_ep05: VideoContent = {
  slug: "podcast-marcony-visagista-ep05",
  youtubeId: "I2_w5I8EuzA",
  title: "BestBarbers Podcast com Marcony Visagista — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 5 da Temporada 1 do BestBarbers Podcast com Marcony Visagista. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "marcony visagista",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2022-08-04",
  duration: "1:09:22",
  category: "Podcast",
  tags: ["podcast", "temporada 1", "entrevista", "gestão", "barbeiro"],

  transcript: `e eu vi que era muito mais do que cortar cabelo né Tava relacionado apto fala/bercinho bem-vindos a mais um best Barber podcast é sempre uma honra ter você nos assistindo que você ainda não é inscrito no nosso canal se inscreva ative as notificações deixe seu like seus comentários os nossos vídeos nesse Episódio de número 5 nós Recebemos um convidado ilustríssimo referência internacional em consultoria de imagem que ele que vem construindo um legado o principalmente mudado a vida de muitas pessoas através do seu trabalho como barbeiro empreendedor como educador eu tenho certeza que você já viu ou ouviu falar sobre o Marconi então eu te convido a assistir esse vídeo até o final e deu uma aula sobre visagismo sobre como você pode elevar o seu nível com barbeiro que mudar a sua vida também sem mais delongas Bora para o vídeo e tchau até os senhores sejam bem-vindos a mais um best Barbies podcast hoje nós temos aonde receber aqui o Marconi estrela e dono da barbearia tem muita história para compartilhar com a gente faz mal marcante apresenta o pessoal e tem o Marconi De onde veio de onde surgiu esse interesse do mundo

da barbearia como se construiu sua história nesse meio do bloqueio o pessoal aí é primeiramente agradecer aqui ao solo Beth Barros né e é uma honra estar aqui com vocês e eu comecei nesse mundo da barbearia PSOL basicamente para ajudar minha família eu queria trabalhar qualquer coisa não tinha pessoas às vezes colocam assim pensam que a gente tinha um grande sonho né e não na verdade não vamos falar realidade mesmo eu queria trabalhar com qualquer coisa né que eu consegui chegou uma renda ele quando eu tinha meus 13 14 anos e a primeira profissão ali que realmente eu consegui até por conta da idade foi cortar o cabelo né eu tava uma época queria ajudar minha família já passou por uma situação doações difíceis né de prestação de alguns momentos necessidade de comida em casa dele e aí teve um dia tô fazendo eu quero vamos um trabalho sair e vou arrumar um trabalho eu quero mais legal eu olhar para você diretamente ou pode ficar tanto faz tanto faz eu acho que deve ter filho depois que um podcast desafio para mim dormir bem respirando aqui é livre e é isso aí eu vi

uma barbearia e deparei com ela barbearia assim como você pensar em como seria né cortar cabelo aí eu comecei eu disse rapaz que chamava Wesley eu fui até a barbearia do outro lado e comecei a ter um parceiro difícil com a cabelo comecei a pedir ele para me ajudar no ensinar início ele não deu tanta ideia acima de tanto eu preciso te inscrever falou não ele eu não sei quer antes de inclusive ele me ajudar eu comecei a fazer um cursinho gratuito sabe do governo chamava local chamado Frei Estanislau ele tinha que é onde Eu Sempre morei um eu comecei a fazer um curso lá gratuito uma vez que você manda ele vir Era longe né do Amazonas até o Teresópolis Oi Cristiane lá na verdade uma unidade do Sol Caetano que é um outro bairro em um pouco ainda depois aí e aí eu vou passando se ele falou realmente Ligar interessado daí eu comecei a ele foi viu que eu tava realmente sala ele se de fato me ajudar comprou os materiais para me matriculou no curso e começou a minha história a barbearia e 67 anos quantos anos mais ou menos 11

anos hoje eu tô com 20 fiz completei 26 anos tá nova ainda tem até uma estradinha né vamos aí já a bagagem né exatamente cara foi preciso acionar o quando eu comecei a ver os que nos primeiros clientes da Verdade no início era muito difícil porque a primeira semana por exemplo cortei o cabelo então ficava sentado aqui no sofá esperando que a gente chegar e mas isso que a gente chegava queria cortar com Wesley né É lógico aí eu falar vai cortar amigão ele não esperava E aí você no começo o sofrimento qualquer lá mesmo então a gente fez muita coisa errada quem achar ruim xingar que eu estava paga conta o pescoço cliente ele o cabelo do jeito que eu não queria mas infelizmente é no início é difícil mas também infelizmente é isso que faz a gente entender é o quanto que é importante o cliente não é brincadeira uma profissão de verdade é você pode mudar o destino de seu cliente é através de um corte você consegue elevar a autoestima dele qual os time eleva a energia com a energia eleva a produtividade na todas as áreas da vida de pode

completamente o contrário você pode destruir a auto-estima do seu cliente fazendo às vezes um bigode errado fazendo um corte que não faz sentido para ele e isso vai acabar com as time dele com energia dele fazendo ele ficar muito chateado ele chegar em casa até brigar com a mulher dele fazer qualquer outra coisa muito ruim porque simplesmente que você estraga o cabelo tá a Karen lá então se a brasileira então cliente comprou a vidro existe um processo para tudo você só tem que estar alinhado saber que aquilo ali nós não é brincadeira um trabalho e se empenhar cada vez mais por essa situação nunca acontecer é lógico que a gente sabe que tudo todas as coisas né até vamos falar isso ela é pouco quando começou a construir no início tudo dava certo né Já lançaram ali os primeiros computadores os primeiros produtos ainda no sistema não funcionava a secretaria correta sem por cento e na vida é assim que funciona a gente tem que parar seu amigo e para você eu acho que deve ter começado então de uma forma despretensiosa né mas hoje o sua visão da barbearia é completamente diferente Nessa visão

sobre o ciclo e sobre o mundo ainda barbearia é uma outra vertente é um contra o pessoal um pouquinho como é que foi esse processo né como que foi esse essa construção a visão que você tem hoje da barbearia e de como isso pode mudar a vida de uma pessoa basicamente tudo começou quando eu vi o seu Elias na televisão lá em Betim E aí eu vi o seu Elias barbeiro Fantástico né cortando o cabelo de jogador de futebol e eu quando eu vi ele na televisão dando entrevista no esporte TV Globo Esporte eu falei eu falei assim pensei assim é que nosso dá para grande sendo barbeiro né dá para ganhar dinheiro dá para crescer muito e a isso foi Enchendo os meus olhos né eu comecei a visualizar sonhar Inclusive eu falei com os barulhos que você quer ter alguma coisa fica pensando primeiros como que vai ser no processo no dinheiro só visualiza o que você quer só pedir só imaginar E aí eu visualizava isso E aí eu consegui através de amizade com se uma amizade ali eu virei colega do assistente deles né EA co um bom trabalho mesmo em

Betim mesmo sendo um lugar simples sempre me dei de que E aí quando eu preciso Elias Precisou de um barbeiro aqui na Savassi é o Jonathan Acabou me indicando E aí a minha visualização lá de trás como se fosse materializar aí eu faço fortalece foi construindo né Fiz um teste meu foi no dia do teste no cabelo foi o pior lá você não foi bom mesmo eu falo isso e o mesmo assim eu fui selecionado eles me contratou no dia que da contratação e falou assim Marconi ser todo contratar você não porque você é muito bom Tecnicamente tá tem que melhorar muitas coisas O porém que eu acho que técnica qualquer barbeiro pode aprender ele se empenhar entrem lá e vai prender agora a força de vontade o caráter algum dos pontos né que ele falou que trabalhou que contou muito né para mim contratar desde então tô lá só quase seis anos e aí não sei se quer perguntar alguma coisa para esse fico mas aí já tem uma histórias marcantes Né desde o dia que eu entrei lá eu te perguntasse para encontrar a questão de onde eu comecei a me destacar mais

no ramo Educacional e até chegar nesse momento hoje do visagismo mas eu quero deixar você também para não ficar com ele que eu continuo seguindo nesse assunto aí não Bora seguir nessa ordem cronológica aí eu me conta entrou no seu Elias como é que foi lá como é que foram os desafios Como é trabalhar com seu Elias né Acho que da mesma forma como você sonhou ali quando era mais novo muito maravilhoso deve sonhar né Muito barulho deve ver reportagem de ver palestra dele e e parar com ele sonhar até mesmo fazer cursos é mas me conta um pouquinho como é que foi o sua experiência né para o pessoal também saber como é que foi tudo isso daí a sua vivência desse processo basicamente quando eu cheguei fiquei deslumbrado porque os onde lugar muito simples e a barbearia era do Fantástico né Eu não conhecia nem Belo Horizonte a região sul direito então os clientes eu me encantavam as pessoas local tudo era novidade a novidade para mim e eu não sabia nem como importar muitas das vezes mas eu fui aprendendo a conversar melhor a importar é mesmo caminhar até mesmo como tratar

as pessoas nem ver que são pessoas normais né que até vez quando eu atendi um jogador de futebol atende artistas já também e são pessoas normais pessoas na maioria das vezes assim bem legais pelo Humildes que estão ali tranquilo para cortar o cabelo e só mistificam muitas vezes é isso nade bem sim e como mais é lógico né que é importância à educação né o seu funcionamento desde o início eu vi que mesmo sem ter esse embasamento técnico e hoje eu tenho sobre conceito de imagem Eu já vi importância dentro de você a melhor de sempre buscar a tomar outra melhor é mais organizado melhorar até a forma de conversar de falar com cliente né o respeito é que todo esse contexto Ia contar muita gente acha que isso não faz diferença né você tá com uma roupa mais arrumada né Você está se dedicando a prestar um serviço com qualidade né porque muita gente acha que a estética né mas L tudo envolve a experiência que seu cliente vai ser com aquilo né então vai muito além disso eu acho que é uma ontem que muita gente ainda não valoriza e precisa valorizar né

então com certeza e a gente vai tocar nesse assunto aqui de forma vazamentos assim científico bem detalhado pessoa entender e faço a importante porque quando a gente fala que não existe bem importante tá sempre me arrumado cuidar bem do cliente em todos os aspectos a gente ainda acha leva esse forma especial né as pessoas Ah eu sei que é importante estar sempre importante porque meu cabelo sei que importa mas as pessoas não têm noção da quantidade da porcentagem que só afeta nos resultados tem gente falando medicamente mas deixa só resumir como é que foi essa história né É E aí eu lembro que seis meses que eu tava no Elias e ele mandou no grupo da barbearia cozido tem tô vendo aqui o telefone tem vários alunos aqui entrando ainda na formação ainda parabéns aí todas as mãos aí tá entrando mesmo e basicamente e não seis primeiros meses que eu tava ali ele já mandou no grupo da barbearia Elias lançar o segundo Barber Day conference que é o maior evento hoje o workshop barbeiro e barbeiros no mundo né eu guardei com nós temos outros eventos grandes também que engloba a questão da

à venda de produtos se tem uns instantes mas workshop é falando de workshop é uma Shopping do mundo hoje ia ser o segundo mas antes dele fazer o Shopping Barueri como ele é para Londres estudar é com Joelson é que já foi eleito um dos maiores barbeiros do mundo né amém spar ele mandou no grupo da barbearia qualquer um barbeiro que trabalhasse lá e quisesse junto com ele poderia ir e marcasse com o investimento né as pode vir mais vai ser muito fácil né ele tava indo estudar pagar o dele não ia pegar um barbeiro do nada eu vou pagar o seu investimento mais de 20 milhões e eu já tô morando em Betim me pegando trânsito tá e eu falei eu quero fazer esse curso eu não sei como mas eu vou fazer aí eu em Betim primo mais novo Max ele trabalhava como servente de pedreiro e eu ensinei a cortar cabelo nem acreditava ele aprendeu hoje porta muito bem mesmo né para demais porta muito bem eu lembro pessoal falando mais cortando a cabeça ou de perder e ele faz os detalhes hoje no cabelo algumas alguns pontos assim que eu fico

impressionado direcionado né com a destreza EA leveza que ele tem na mão e esse irmão meu Max ele tava dois anos ali cortar o cabelo juntando dinheiro para comprar uma moça indireta é uma hora e aí ele comprou essa moto e aí ele ficou é um mês quando eu contei pelo meu sonho ele de lá fazer o curso ele vendeu a moto e me deu o dinheiro fato aqui na verdade eu nem eu já contei essa história duas vezes a gente for olhar bem aconteceu mesmo né Vamos abrir o jogo aqui eu até tinha gente um dinheiro seu um cara bico num cara que ajudar minha família até tinha uma parte do dinheiro E se eu me esforçasse Eu acho que eu conseguiria ter ido às vezes até com meu próprio dinheiro para ter que eu tinha um outro irmão mais velho lá em Portugal e trabalhava de empilhadeira na Continental e ele ligava falava que não tava gostando tanto do serviço que era longe era pesar e Eu sempre pensei que ele perdão a gente também para servir e eu pensei sim cara tô indo em Portugal meu irmão nem na Inglaterra isso mesmo

em Portugal se eu vou ele vai junto além dele participar desse curso ele vai estar naquele momento na época nem sabia o que era isso né mas Network é matemática a gente vai estar entre a gente vai criar seja um mega curso isso vai Talvez travar um pouco a mente dele mas eu acho que ele já vai em em Barueri a imenso ali dentro exatamente e e os momentos que a gente tivesse em casa na casa que alugou eu poderia treinar ele ensinar e foi assim e eu consegui pagar o treinamento dele com dinheiro que eu tinha e o meu irmão de fato pagou meu perguntou todo mundo e seja bem bolado exatamente verdade aconteça história várias vezes mas o que acontece primeira vez só a primeira mão tá todo mundo que esse ser e essa facilidade bebeu a moto dele para me ajudar isso aí eu sempre falei isso é verdade fato mas que fato foi também para ajudar esse outro irmão que tava lá é minha barbeiro lá hoje ele tem barbearia dele lá também bem legal Portugal e inclusive seu irmão resolveu foi para lá também tá junto preta bem feliz tá

certo Os dois estão na barbearia a gente agora exatamente aí galera aí você vir hoje é aniversário do Marcos Parabéns sempre melhor eu não sei se vai ver aí registrar a resultado parabéns pronto fiz o curso foi outro nível outro a visão que eu jamais disse fosse foi para tia ligar eu me perdido aqui nas datas mas uma já tem uns 4 anos 2000 acho que foi 2017/2018 entendeu eles treinamento tem um tempo mas também separar pensar né dois anos de poder minha já então é é muito rápido passa muito rápido 2018 Vou conferir mas basicamente isso E aí aprendi muitas coisas legais Eu lembro que eu chorei lá no dia do curso porque eu não conseguia executar as técnicas do jeito que eles eu era muito longe ainda minha idade fato é que o conhecimento os transforma e quando a gente voltou para o Brasil continue picando é as técnicas de tesouro ele falava isso não calma aqui agora você não tá conseguindo fazer você vai assimilar de conhecimento e vale a pena eu só lembrava que morava numa casa e vitim e sem muros sem se era uma cerca ainda lá e precisa

ajudar meu pai minha mãe meu irmão vendeu a moto dele eu falava tudo isso para não conseguir aprender ar é só não ia lembrar de como é que fica tranquilo né não tem E aí foi mas quando eu voltei a raiva era tão grande dor investimento que eu tinha feito eu falei eu tenho que ficar bom eu tenho ficar nem que seja na marra ele está sendo feita e meio e postar uma foto e falava e aí a gente que a gente a gente começou a administrar os é para o Brasil todo cheguei a ser convidado pela Vivo continuar Argentina fui para Portugal ministrar fiz uma turnê lá ele praticamente quase todos os estados aí brasileira ensino e é eu ia perguntar né você já teve mais experiências internacionais mas pelo visto foram muitas né aí teve umas quatro cinco aí foi bem legal tudo isso pela Travessa aí dá a barbearia e através dos cursos crescendo também olhasse convidou para fazer parte da academia dele foi o primeiro educador junto com o Rogério a ministrar no bagulho de a cada em ele ele é uma das maiores escolas de equipe pesadíssima né eu vou

abrir a cara é equipe de respeito é o pessoal que falar só o Barbeiro já realmente muito falta e consegui estou até hoje né lá no bar de marcadinho atualmente foi convidado a palestrar no 2.0 inclusive hoje sou palestrante lado e visagismo é uma introdução ajudei a construir conteúdo lado de visagismo e é isso estou na minha equipe há quase seis anos acrescentando né acredito que eles também tá muito feliz pelo resultado que eu atingir seu Marconi que chegou lá para o Marconi de hoje e a visão que eu tenho de barbearia muito diferente de hoje de cortar cabelo é de é algo diferente ao que mudou a minha vida mudou a vida da minha família está mudando a vida de muitos alunos de pessoas que estão aí junto com a gente e deu pessoal então que tá querendo aprender para o pessoal que tá sonhando aí também se especializar em conhecer e entender mais sobre o visagismo um pouquinho como é que foi o processo Como que você se descobriu no visagismo né Quais foram os seus principais dificuldades O que que você teve de principais ganhos também com estudo então basicamente né lista

com anemia Eu já tava pensando em Reinventar é algo diferente eu Nós aprendemos técnicas na Inglaterra e aprimorando essas técnicas Mas fala aí que às vezes olhava para um corte de cabelo e eu coloco perguntava se esse cabelo tá expressando e corte Expresso alguns alunos até perguntar o professor quem que eu vou fazer esse corte de cabelo tem por que que eu vou fazer esse corte quando eu vou fazer esse corte então foi um momento como esse despertar um pensamento assim não é só cortar tem algo a mais Psicótico o que que eu cheguei nesse resultado como que eu cheguei nesse resultado em e outros fatores que aconteceu só o que que tem corte que a gente não se agrada tampa a gente se agrada mais E aí eu comecei a pensar também refletir sobre a minha imagem por quê que mesmo já sendo um barbeiro de autoridade até hoje eu ainda não entendo Qual que é o melhor corte para mim ele as pessoas vezes chegava e falava para você precisa de mudar o que você mais melhorar a isso aqui eu falava não é isso que às vezes nem eu mesmo me reconhecia

que o meu corte de cabelo e já ensinando para todo mundo e eu comecei a refletir um profundamente que não era só aquilo tem algo muito maior por trás e aí onde que eu já pensava no visagismo e comecei a Pesquisar mais sobre visagismo nesse de fato a ler os livros A pesquisar sobre o criador sobre o conceito eu vi que era muito mais que cortar cabelo não estava relacionado a pessoas a linguagem visual a entender a essência da pessoa bom e como ela se alto conhecia e e como estilo com a imagem basicamente a manifestação a quem a pessoa é a essência dela não entender também a cor Ligar proporção a hora é o que que só as proporções mais valorizadas por isso que às vezes a gente olha para um corte de cabelo e acha nossa esse esse cabelo ficou alto demais vossa cara você olhar para uma cabeça achar que eu acabei sem longa demais o curta demais e eu perguntava O que é que às vezes o nosso olhar se agrada de determinados imagem desagrado de outros em te agrada de um corte desagrado de o ciência por trás dos nossos

gostos né já existia descobrir que existe fatal de proporção Áurea e explica perfeitamente como funciona as proporções valorizadas falando esteticamente vezes nas proporções variadas bom então visuais mentem né falta em três pilares que a personalidade que basicamente o desejo oculto que seu cliente tem Sabe aquilo que realmente queria lá no fundo mas que ninguém consegue entender ele às vezes nós temos aí o segundo Pilar que é estética e é a proporção Áurea aplicada né as proporções valorizadas e nós temos autoestima e é o desejo que o cliente tem de ser reconhecido na sociedade o cliente não vai cortar cabelo com você não é Ah eu quero tirar só para tirar o cabelo entende o cliente ele corta cabelo porque ele tá pensando em tudo ele tá pensando ele tá pensando no trabalho dele ele já imagem ele corta cabelo de imaginando chegando em casa a mulher dele e adorando a imagem dele ele corta o cabelo imaginando pessoal no trabalho ele respeitando esse ano bem sucedido ele já pensa no corte já combinando com quem ele é com a roupa né ou com ele sendo premiado lá para lá naquele campeonato de surf ou ele

sendo premiado o fato de skate lá ou ele se no é conhecido como advogado ele sendo reconhecido como um médico bem-sucedido e a imagem é um dos principais fatores que vai trazer se reconhecer é aquela famosa frase né que a Carol não é que vai chamar mais atenção não é uma Ferrari e um Celta né mas bom o visagismo então ele pega os desejos ocultos ali cada pessoa né ajuda ela a expressar da forma mais assertiva possível Ele é mais ou menos isso perfeitamente Exatamente isso então quando você é um barbeiro e não trabalha só técnico a cooperação exato que eu tenho para dar basicamente é a diferença entre um pedreiro e um arquiteto do pedreiro ele não tem a chance nem conhecimento suficientes para embasar o cliente já questões é por exemplo e a vamos fazer essa casa com esse detalhe com essa corpo você vai combinar isso que vai expressar isso com uma cor tal com um quarto deste tamanho e com essa altura porque vai combinar e vai ser melhor para quem você é porque você quer para o seu não ele é basicamente vai focar realmente no a parte operacional um

arquiteto Engenheiro eu já vou mais a fundo eles vão no projeto eles imagina esses planejus eles vão estragar o cliente questionar cliente entender mais sobre o cliente né e e dessa forma fazer um serviço mais bem elaborado e visagista diferente do barbeiro vai ficar mente é isso veja e simplesmente abaixar o cabelo o que a gente falar a porta se ele se simplesmente copiar uma foto que ele te mostra ou o cliente chegar e perguntar assim ao que que é melhor e você acha que era o meu rosto que que é melhor para mim aí você virar a faz um degradê aí a faz um corte assim ah o que que você gosta é eu vou ele fala exatamente o que que você gosta que você gosta é diferente antigamente não era bem assim né antes o Barbeiro sugeria Neo o tipo de corte mais adequado é E hoje é muitas vezes ao contrário né justamente foi só chegar lá e fala fica É mesmo né então é basicamente assim teve alguns momentos igual eu tô falando que antigamente era de um jeito aumente é de ouro mas Na barbearia fato é que até então

até atualmente assim é raríssimos raríssimos os barbeiros os que têm esse conhecimento aprofundado para conseguir oferecer para o cliente um serviço diferenciado para me entender mesmo você consegue hoje aplicar o a primeira forma é você vai usar ele no seu dia a dia para fidelizar o cliente me entender mais do desejo oculto seu cliente através dos gestos dele no gestual seja a forma como o cliente passa a mão no cabelo Você já fala cara esse cara é tão gramento colérico e esse é melancólico isso aqui é frio Mágico é realmente ele passa a mão cabelo sim ou direcionando bem certinho pode saber olha ele quer ver a festa desta área da Razão Abrir bem certinho bem direcionado transmitir controle ação elegância tudo isso o características de uma pessoa de ação uma pessoa que gosta de desafios de empreender então a forma o cliente anda como ele senta já começa imaginar aqui e determinados cortes até a forma como você vai conversar com ele que ele não vai se identificar em ele passa a mão assim jogando para baixo pode saber que ele é um temperamento mais de controle que ele chama de melancólico mas eu

trabalho mais também perfil disso é um tentar melhor de controle são pessoas algumas divertidos então se você fizer um corte muito radical para essa pessoa Talvez não vai suportar esse corte então através da forma que a pessoa passa a mão cabelo tira começa Nescau que ela gosta é só que hoje é o meu que empreende com isso Entendi então hoje é um dos meus dos meus mentores que é o Filipe ali o que é considerado o alho saggista é a dor dos adidos foi ferrar o brilho francês e registros termo em 1937 basicamente ele era um cabeleireiro maquiador e muito criativo né então ele pensava fora da Caixa na França eles fazem entende que corta cabelo não é só começar cabelo tava mexendo com a identidade das pessoas e isso Poderia gerar grandes resultados na vida da pessoa e poderia também terá prejuízo dependerá forma ser o Face legal e tem todo um trabalho então muito além do visual né mas também uma análise comportamental ele de cada um né que vai influenciar nos vários outros fatores né exatamente hiper Nobre ele já percebi isso desde antes o como se diz start dele para registrar

Esse erro foi eu tava caminhando né pela rua e ele viu uma pessoa mexendo no Jardim ele perguntou para as pessoas e jardineiras ou não eu sou paisagista diferença é a pessoa jardineiro ou é o profissional que Vai podar que vai jogar um adubo e o paisagista é profissional que planilha trabalha na planejamento esse Jardim vai aumentar litros vai Será que essa planta vai comer aqui aquela si só não vai suportar terá que a essa casa o local a funcionalidade dessa árvore dessa planta vai funcionar Ei RO e eu penso assim então são barbeiro também não ele já pensou só um jardineiro não sou só um cabeleireiro né Aí ele é um cabeleireiro e maquiador E aí ele falou sou diferenciado só alguém aí ele pegou erro paisagista para criar o visagismo paisagem é de paisagem de paisagem envisage em francês é rosto e o ismo é o sufixo é a segunda parte da palavra que expressa o conceito do estudo do movimento e aí ele juntou avisar ou serviço tudo rosto tudo da pessoa mais aprofundado e aí ele registro enterro o fato é que não escreveu assim muito sobre o visagismo né Aí

nós temos hoje no Brasil que é o Felipe Harley foi considerado o pai do que o Brasil e foi responsável por juntar né as características as linhas as formas com temperamento o que que é o temperamento são tendências de comportamento das pessoas então Singer eu consigo olhar para o seu rosto olhar para uma pessoa e já começar a entender como ela age funciona como era mais extrovertida sincera demais ação é uma pessoa mais metódica ou menos isso todas essas informações elas vêm até você em questões de milésimos de segundos para quando você tá estudando é que nem medicina você vai passar antes para entender o que depois a pessoa ela vai pegar e mestrado instalar ela faz uma cirurgia entende que ele tem uma vez que ela pode cortar e salva uma pessoa que estão em segundo ali né eu visualizo é isso estão em segundos ou naquele conhecimento que os livros eles vão vir aqui ó aplicar o movimento que o cliente faz já fala eu não posso falar isso não posso é onde o cliente ele sai Encantado ele fala diferente ele realmente entendeu hahaha ele conseguiu extrair de mim o que eu

queria expressar E aí eu e prende com isso hoje eu tenho um produto né eu acabei de inclusive sair da Drogaria ali fazer uma consultoria com o Luís eu cobro r 500 nesse atendimento eu não consigo usar o visagismo meu dia a dia nos cortes para valorizar para fidelizar mais e o cliente também uma consultoria um metro de Com certeza né É porque o filho ele ensina para a gente a usar o visagismo como na visão dele é uma teria obrigado todo o Barbeiro se visagismo ele fala que é uma injustiça na visão dele os clientes né não seria atendido uma pessoa que tem um conhecimento homens sobre a imagem e o que que ele fala se se sua imagem é só identidade e sua autoestima madeira às vezes corta sem ter conhecimento Pode ser que ele e vai venha a ferir a sua imagem você vem de tarde isso vai gerar alguns distúrbios uma crise de identidade de você por exemplo que eu dei em literal é o cliente ficará insatisfeito que você cortou o bigode dele a mais que ele queria por não ter entendido ele e às vezes Uns vão te falar

na hora outros não até que ele vai ficar com raiva e vai chegar em casa esses pode brigar com os pais dele pode perder o emprego porque ele tava chateado na entrevista o que é imagem causa improvisando pessoa causa tristeza Nossa baixo é tira autoestima da pessoa e isso tira a energia ela se torna menos produtiva como se o você colocasse um médico que não tem tanto conhecimento assim para fazer uma cirurgia aí ele pode salvar ou na uma pessoa né mas é vai ter que contar com a sorte ali é isso também sério porém eu percebi eu poderia além Ou seja eu vi que os é mais do que só eu interpretar o que eles queriam ali no momento muito carinho ainda entender mais para talvez até projetar uma imagem Ou seja criar um posicionamento demais na rede social dependendo do que ele quer conquistar iriam entender de forma técnica mesmo como o rosto deles funcionavam eles queriam não só e utilizar-se do temperamento De forma inconsciente mas que eu literalmente explicasse para eles o que era transferência por trás para eles também tomarem consciência disso e começar a utilizar isso na vida dele

de forma mais racional ainda tomar conta daquilo carro inconsciente até eles mesmo começaram a se questionar Será que isso mesmo que eu quero eu tenho que ir conversar com a minha imagem até mesmo se policiando é dependendo das ações ali né e Zalo às vezes ele tá andando de uma forma que ele nem tá percebendo está causando um impacto negativo na imagem dele exatamente E aí o que que eu fiz para poder gerar o valor para poder o quê o cliente ele ainda tem um pouco de cuidar teria no início ali um pouco idade de entender sem papo beleza eu já corto o cabelo com Marconi eu já fico bem satisfeito que que eu vou cortar com ele um determinado de pagar 500 reais ao invés de pagar 60 70 ou 110 tem um corte de barro e tu apaga quem se as um determinado de e depois r 250 um retorno bom então eu agreguei fato é que se importasse comigo só para explicar isso para ele explicar o rosto ele já já entenderia e isso aí mudaria completamente a visão dele da imagem dele tudo é o que um inclusive Luiz falou hoje

nossa aula que você me deu aqui mudou a minha vida ele falou isso mudou me abraçou agora essa do que ia valer muito mais então agreguei alguns toques visuais para o cliente já visualizar antes da Consultoria e é basicamente eu tenho alguns formatos de óculos lá armações Então já tá incluído eu falo cliente qual que vai ser o formato de óculos que mais vai encaixar para ele e só uma dúvida os cães têm de arroz com aquele que é expressar e também dou algumas dicas até mesmo e vestuário de roupa de de acordo com quem quer expressar ele quatro episódios no telefone mostrando pra gente vai ficar Qual que é o estilo dele dentro do sétimo universais entendi Explique o que é que são símbolos arquetípicos a gente faz manda para ele um formulário no Google para descobrir qual que é o temperamento dele e eu comparo todas as eleições um resultado que deu lá no Google da formulário e aonde que a gente traça um objetivo muito sério muito mais do que são corte para pessoa ficar satisfeito é aquele corte e você vai lá todo felizinho e as 60 tem aquele vai abrir

o que não é Village santa e vai te dar para qualquer dia que você vai sair satisfeito e aí eu como usar de você vai sentar lá e meus alunos e quem também é você vai sentar naquele corte de em vez de demoradas 40 às vezes pode demorar até mesmo para demorar 20 o tempo eu já isso ele consegue entender o seu desejo por exemplo teve cliente meu que você entrou lá Oi e ele pediu a princípio para fazer um degradê porque todo mundo só de carro mas vendo teste gestual dele teste emocional a forma comigo conversar eu vi que ele não queria fazer um degradê só queria eles não tava sabendo cortar o cabelo então eu só conectei o cabelo dele expliquei qual a ser a pomada e como ele é pentear esse cabelo no final ele virou para encarar cara era isso que eu queria mandar um corte sem nem não poderia ter ficado ali 40 minutos fazendo um degradê para no final e saindo satisfeito não gostar então eu e nem 20 minutos e vende uma tomada ele elogiou mandou mensagem feliz naquele não querem code lá E agradecendo e vamos tomar

elogio de comprar outras pessoas e ficou super satisfeita que eu era isso que eu queria animais e aí tem esse corte ela que você vai ficar satisfeito ali e ainda tem um produto para você criar uma imagem por exemplo eu tenho um produto digital também quero um funcionário rede social eu já estou satisfeito com seu corte de cabelo Marconi mas ainda queria além queria saber o formato de óculos de entender sobre mim como eu posso melhorar mais ainda ela de um posicionamento de marca pessoal nessa aí a consultoria eu coloquei essenciais muitas pessoas já estão com ela que você tinha que colocar a viagens a construir mas ele não calma pessoal ainda no seu tempo né para conhecendo os produtos nem o pessoal já marca pela barbearia tem toda uma apresentação que a gente envie mente vai hoje no início parecia muita coisa sabe mas é hoje que a gente já tá querendo hábitos é bem barulho a gente ligou lá perguntou se tinha um horário para recepção recepção já envia apresentação para mostrar tá incluído o cliente feche ele vem no dia né com o formulário já respondido aí eu dou uma lida no

formulário o que que eu cresci formulário o que tem preço perguntas que são bem pessoais e aí nesse formulário já nem te respondia a casa dele para poder ficar só e eu já entendo muitas coisas aquelas E aí algumas outras coisas são bem tranquilo de falar em mesmo às vezes e-mail outro a ideia de fazer isso foi até porque eu sei que tem muitas barbearias vai eles trabalham do lado do outro sim entendi então nem todo mundo vai ter o luxo de ter uma sala eu já Criei um método pensando nisso a lógica você tem um ver a sala exclusiva eram mais volume indo aí eu não tenho uma pessoa também pode ir a mesma forma que a Com certeza né a gente vai começando um passo de cada vez né até chegar lá né sendo começou lá com 13 14 anos nem se estima para cortar cabelo para aprender e aí hoje não é um dos maiores referências aí no Brasil principalmente na hora do do visagismo Mas então a gente falou muito sobre o impacto do visagismo na vida das pessoas mas me fala na sua vida né você falou que passou por

momentos aí de conflitos internos mede dúvidas me conta um pouco como é que foi que o visagismo entrou na sua vida o que mudou quem você é então basicamente é Bom primeiramente a visão que eu tinha né sobre corte de cabelo nunca mais enxerguei corte de cabelo da mesma forma Oi e o estudo em si ele vai revelando eu vou ter que entrar só um pontinho docinhos a críticos o pessoal entender tá em algumas características gente é o seguinte vamos lá eu vou ter que dar uma mini aula de viagem para a gente entender Por que que mudou resultados vamos direto primeiro resultado E aí eu vou explicar um pouquinho no contexto eu basicamente hoje consigo ganhar muito mais trabalhando menos são muito mais respeitados estou muito mais respeitado por quem eu sou pela minha imagem pelos meus clientes para a unidade que eu cansei se você me convidar para palestrar em vários lugares da entrevista de até canal de televisão já a gente está prospectando está crescendo a nossa formação com a cada vez maior conseguir realizar meus sonhos de casar de ter uma um apartamento com piscina e tudo isso mais antes são

os resultados é porque o visagismo basicamente você vai conseguir aumentar o seu valor do corte e valorizar o seu tempo essa hora não é o bem mais precioso que a gente tem na vida é o tempo mas você não aumentar o valor da sua hora vai morrer de trabalhar eu não criar outras formas e usados no ele valoriza Ah entendi já é um termo que já existe há mais tempo tão que tem muitos clientes que já já ouviram ter amizade possível Na barbearia para as coisas também fortaleceu inside meu foi um cliente que mesmo antes de me formar no sair que eu vou lá na barbearia mesmo falou que ia conversar com os agitos de um ensaio tão grande né eu quero contar com vontade isso é é eu falei olha eu não sou exatamente mas eu já estudei nessa que eu já tinha feito com os quilômetros mas isso só fortaleceu porque ele me tratou diferente me respeitou aplicar Então mas se tivesse me formado no curso de visagismo que fez impulsionar eu poderia ter porque ele já foi achando que ia ser mais caro e agora tô esperando aqui vem depois funcionou que

era mesmo mais ele queria a exclusividade ele sabe de tudo já tá então resultado esse gente aí ó é um caminho para você trabalhar no dia mais a maconha Eu tenho vários Margarita pode implementar isso seus bagulhos aí que vai aumentar mais ainda o faturamento da barbearia e pode fazer seu a minha cada mim né você pode fazer pode assim nada pode fazer um conteúdo e traz sentindo que você faz ela não tem nada melhor do que se olhar para um corte de cabelo que você fez e falar cara eu fiz isso aqui por isso porque expressa isso para isso e o cliente ainda fica satisfeito porque a gente não ficar vocês eu estou entrando técnica gente só para você entender aconteceu de ação é a minha vida não me amar eu tenho temperamento sanguíneo a ficção tem tem leite comportamento a existem quatro temperamentos ambos entrar aqui quem que é por isso que Pocket 70g a gente não estender demais basicamente são tendências de comportamento sanguíneo é uma pessoa que age muito pelo impulso quantos estilos e suspendo tiva pessoa que gosta de conversar agora de falar você deixa fala demais foi aí que

eu entendi porque que eu gostava as pessoas entendeu sanguíneo esse cara extrovertido e ao mesmo tempo tão cara que ele tem dificuldade é o tipo de pessoa que a gente cuidade em planejar a vida em sentar de fato fazer esse a maioria de sanguínea ele vai colocar eu para trabalhar atrás de um computador programando ou dois números pequeno demais se alguém se eu entendesse meu temperamento trabalhar se isso eu consegui ligar o juiz superar mas inconscientemente igual a maior das pessoas nem sabe o que é isso nem Qual é o temperamento dela ela simplesmente acho assim aí eu não tenho dom para mexer com isso eu não tenho um dom para que ele está totalmente relacionado ao temperamento ai não sabe aquela pessoa mais intrometida que elas é que ela gosta de fazer o serviço dela gosto de fazer tudo bem certinho mas ela não tem intenção de abrir a empresa dela novamente um dramático um conforme que a gente fala meu não corre um sérum com aquela pessoa que o tempo todo está buscando desafios coisas novas moléculas e os jogos eram coléricos por exemplo eu sou se não tem todo de carro resultados

e as feições e o estilo é derivado do temperamento Entendi então seja polêmico Abrir bem direcionado testa geralmente é bem maior Bom dia pela definida entende um olhar baixo que expressa a força que é um símbolo arquetípico como seria mais reta eu não código geralmente é mais caído olhar nós desse daquela pessoa que transmite até uma certa tristeza na imagem Mas é uma pessoa que também tem muito poder de que a maioria dos hacks são melancólicos aqueles caras que focam no trabalho deles o sanguíneo não eu tô aqui ó passa uma música haha só chega a mensagem Ita entendeu e o colérico ele também é bem sentado mas ele é mais ação então ele também não consegue você pode ver que o acho que é voz né que fazia a programação para o Steve Jobs ele era concentrado lá no trabalho dele enquanto estive era mais colega então ele faz um pouquinho ali dava resenhado ali e aí já que ele da ordem né Ele queria ver o projeto acontecendo um torno basicamente vou resumir aqui eu sou sanguíneo então eu usava o cabelo bem cacheadinho caindo totalmente Na terça estou avisando já engolir cortar

meu cabelo tá então tem cortar toda semana não consegui cortar já tem duas semanas é caso você respira de pó questão de toda semana linhagem dar um jeito de cortar ele é um pouco mais cheio mesmo antes usava degradê eu não posso te incomodar muito porque a orelha está acabam muito melhor abaixo bem todo mundo sempre oferecido de graça faz degradê tá na moda tá na moda é pelo seu cabelo três e é bom Eu nem falava três senão eu nem me fala cara é ruim enquanto o ímpio e os valores tem medo de usar termos pejorativos as conversar e é mesmo que seja seu amigo que esteja brother que seja de até né mexendo qual se você tem que elogiar ele botar ele para cima falar bem dele ele já que isso fica tranquilo seu cliente uma bobeira eu buscar uma solução melhorar de vida e você só botar ele para bar mesmo seja brincadeira né então é isso aí é então por exemplo um ponto proporção Áurea que foi deixar o cabelo crescer mesmo ele grande arrumar um jeito de conter É isso tirou a atenção da orelha passei Minoxidil bigode tirou da

atenção do tamanho do nariz o queixo intrometido então eu não tinha barba em que cresceu aqui já alonga o rosto e e aproxima mais a proporção a hora que uma proporção agradável o nosso olhar se agrada em antes não tinha nada do que eu tô Pet na era bem enroscadinho mesmo cargo na terça é tão cabelo bem valorizado assim natural porém que um ponto que aconteceram o seguinte é expressar muita também são até bagunça demais é demais né eu olhava para mim esse cara não é organizado não confio no vou contar tá aparecendo entende menino e aí que entra a chave amanhã a gente entra a chave porque é comprovado cientificamente que a imagem ela cria nas pessoas sentimentos eu e os sentimentos eles criam reações e as reações queriam ações e reações criam resultados é um ciclo né a pergunta que a gente tem que entender que agora com que imagem cria sentimento o que fez isto focal e um Augusta vi um pai da psicologia analítica Olá tudo que você tá vindo à sua volta passa pela sua retina e avaliado em menos de um segundo e milésimos esse seu sistema límbico na

hora ele faz avaliação emocional e ele crie você sentimentos e sentimentos pode ficar o salvar a usar várias reações seja calafrio ou seja sejam medo ou seja alegria o teste que agora vamos fazer um teste na prática hora Pensa numa criança sorrindo aqui agora criação bem bonitinha Sorrindo com olhão bonito olha alegria que já tá você não tá nem você só tá mentalizando a imagem agora vamos pensar ele sorriu né Agora vamos pensar uma imagem da morte né do Pânico né que aquilo 30 do preto assim né tampado vir atrás de você no escuro olha olha Rio mesmo que já te gerou a expressão de arte na hora de todas essas imagens são compostas símbolos arquetípicos ou seja linhas cores e formas e tem um significado em em qualquer pessoa no mundo mesmo sem ter estudado vai ter a mesma reação ou seja o preso sempre vai expressar esse de seriedade a linha reta Quando você vier se entende que é mais estabilidade a inclinar você vai sentir que é mais dinamismo perigo rosto do Coringa tem inclinados e sempre vai sentir mais instabilidade perigo o Superman que é quadrado se sente que é estável

cursos pode confiar e por aí vai Existem os objetivos é o fato é e quando você ver uma pessoa dependendo de como ela está a imagem dessa pessoa e vai causar a outra pessoa e milésimo de segundo que um sentimento de ressentimento vai causar o que ações e resultados então a sua imagem pode fazer você conseguir um emprego ou não a sua imagem pode fazer você conseguir fechar um negócio não conseguiu network ou não e vai fazer com que você está bem com uma mulher ou não ou sua esposa não já viu aquela famosa frase que é você nunca terá uma segunda chance de causar uma você nunca terá uma segunda chance de causar uma boa primeira impressão mesmo na verdade Você nunca tempo que a sua imagem ela fala muito fala até mais do que as palavras muitas vezes mentem e pronto então a gente entendeu que o seguinte Henrique Quando Você Se olha no espelho a imagem de você tá afetando Primeiramente você tem então eu era sanguínea era um cara que já tá dando bem com você Mega intuitivo pô meter a cara e fazer as coisas acontecer mas a minha vida

profissional tava dando um boa parte errada porque eu não tinha uma agenda falado que ele tem um curso online mas eu não conseguia nem criar um PDF eu não consegui estruturar o meu curso eu não sabia nem quando que era sozinho fechar o curso aliás esqueci até de páginas esquecido o dia do curso profissional mas ao mesmo tempo era um cara que tinha um trabalho massa um cara que ficou um cara fazer acontecer nesse exato mais. Então as pessoas gostar a desfilar Mas concordo que se adaptasse melhor esse lado da organização juntasse com esse lado intuitivo e a ficar muito bom então eu usei da imagem para melhorar não só esteticamente ou seja quando o são aumentei aqui o cabelo né para eu odeio tirar missão do brilho bigode a ti atenção do nariz ao vip aba falando as profissões Estéticas e tem todo um cálculo que se faz presente é mas também é trouxe linhas de organização tirei o cabelo cacheadinho que transmite a sua verdade já tem um certo descompromisso família era muito carinho na testa até da minha área da Amazon não acontecer tampa se transmite muita emoção e intuição movimento cultural

e ele faz muito eles estão com a testa E inconscientemente por que eles estão então aqui querendo viver as emoções ele vem às vezes está com os olhos né com criam com maquiagem para dança da emoção é um grande exemplo o desenho do Pink e o Cérebro sério branco tem um textão cabeção é o que pensa mais é dominar o mundo o tempo todo querendo vários planos e ao mesmo tempo pretinho né porque o queixo dele é pra dentro ele é travesti verdade já ou ainda dele o pink ele tem um mega olho né olhão e ele é esperamos final então a forma segue a função essa máxima declarada por Luiz Sulivan nenhum dos maiores arquitetos do mundo é a forma segue a função então seu rosto ele tem uma funcionalidade as feições tem a famosa por isso que seja era famosa cara de elegante a famosa cara de brava famosa cara de bonzinho demais e onde que entra a consultoria de Maio o cliente tem um emprego que exige transmite seriedade preciso de receber respeito e ele tá com vários símbolos arquetípicos no rosto nem sabe o que então transmitindo suavidade nas características de

um temperamento fleumático sendo que ele quer ser colega dentro dele a coleta eu não se identifica com a imagem dele porque a imagem de por fora está um frio mas ele tá um pouco acima do peso a base dele também arredondado que eu vou abrir Não entendi Nem o que que é isso está em constante contradição fez pó só que com linhas arredondadas já que eles e as pessoas no serviço eu achei o cara de bonzinho demais eu vejo até passa por cima das opiniões não respeita né ultrapassa o limite que ele Kirin comprou para ele e se trabalhas com crianças um gesto transmitir mais essa Aconchego Skyrim para as crianças talvez a gente tudo bem com a carinha de bonzinho né mas por falta dele tava está errado por isso que não tem como padronizar o que é bom que é ruim não dá para ver tudo depende da situação né um degradê perfeito pode ser o pior poste o cliente corte na tesoura perfeito talvez pode ser o pior corte em degradê por exemplo tem várias publicações se ele é mais contratado e que é isso ele pula de uma máquina direto para

máquina dois que ele fica bem escuro naquela passo frio ele vai transmitir muita força principalmente E você tá no contexto God Bless lá que vamos cheap usa uma roupa um terno completo uma roupa mais clássica e elegante com esse corte e totalmente Relacione a imagem de um soldado alguém de respeito alguém de força mas você faz um degradê com menos contato por exemplo mas passar se você já vai pensar mais em jogadores mais autoridade você vai transmitir muita jogabilidade é isso que você quer transmitir no seu trabalho muito de habilidade e experiência uma pessoa que está ali mas não tão focada mais tudo também vai depender do trabalho que você tá por exemplo o menino de 19 18 anos que começa a trabalhar na gerência de um banco agora então ele já não tem Bárbaro E aí ele coloca esse degradê bem esfumaçado inconscientemente as pessoas tendem a sociais remotas entendeu naturalmente a se ele coloca um pouco de barba linhas mais retas óculos roupa um pouco mais claro vai quebrando essa idade de 18 anos 19 e as pessoas vão Acreditar nele mais rápido então se ele quer mudar de carro aqui subir rápido

É como se você tiver já por exemplo eu quero estar naquele cargo ali como que aquela pessoa que tá naquele cargo se veste hoje comporta se importa com que o seu cabelo dela então já sabia que eu já tenho que aderir essa imagem adaptando e lógico para quem você é e logo a sua imagem puxa para aquele cargo de forma mais rápido Oi e a sua imagem adequada no meio que vai atrasar os seus objetivos recursos né Você pode usar eles ou não né e em seus benefícios malefícios né Eu acho que o pessoal vai começar a pensar duas vezes né agora na hora de colocar uma roupa pode cortar o cabelo ser é tudo isso o meu caso por exemplo só para finalizar e que mudou que a gente pergunta a chave essa sempre passar assim mudou tudo né detalhes Então fala para o Danilo que um fio de cabelo há mais ou menos para o seu cliente muda muita coisa então fato de enxergar mas na minha terça de pro cabelo um pouco mais direcionado eu utilizava pouco mais cheio de utilizar uma roupa mais organizada uma calça jeans uma camisa pra dentro

da calça um relógio com isso aqui mais baixo a gente mais seriedade e elegância uma vez eu adaptar o melhor meu tempo para mim hoje eu não sou aquele cara completamente a deusa around the sims organizado comecei não a sua transmitir mais organização são características de um outro temperamento é o Colégio com também comecei a ser mais assim mas incisivo mas objetivo quando me olho no espelho agora é só não sou mais racional esses de agendar com a legenda e quando o cliente não tá Na barbearia tem que tá tudo bonitinho é bancado preciso impulsionar preciso cortar o cabelo antes eu passava três quatro semanas pés em tudo aqui de crescimento tava nem aí Teste que importa é o dente de na mentalidade como um todo né verificar o tanto que mudou para mim já me acompanha ele era tudo meio bagunçado hoje não eu penso na cor na imagem que eu vou postar na sequência silêncio no que eu vou falar na letra na fonte a comunicação arquétipo no que eu quero transmitir o sentimento que eu quero causar nos meus vídeos nas pessoas quando elas estão assistindo e Uso todo esse poder do

conhecimento da agido para poder está em todo lugar e aí quando os estudos a gente se vê que tá na estrutura para as pessoas está na imagem tá na roupa até na comida né aquela famosa frase né a primeira a gente come com os olhos ver com a boca né então a gente precisa ser e parecer se não ou seja não adianta só o bolo ser bonito e ele tem que ser bonito e gostoso hein o Siena ele tem que conhecer você nós entre um bolo bundt bolo gostoso que não é tão bonito e um bolo gostoso que é bonito se elas provam volume e não adianta também bonito mas quando você o meio tá podre tá ruim tá então a gente tem parecer e o legal que quando você primeiro imagina que você quer ser e a DECO a sua imagem logo o conteúdo na sua mente também ele só atualiza o que eu tô falando isso é o que eu acabei de falar com vocês quando eu comecei a me vestir uma pessoa que imaginava uma pessoa elegante mas eu tinha medo de investir assim falar mais por sou barbeiro não posso mesmo

e aí Hebreus barreiras e bloqueie comecei a investir quando eu me olha no espelho que a imagem faz Ela atinge o sistema límbico e as emoções cara você racional se elegante você é sério se organizaram Então esse sentimento começa a criar em ações qual que são ações Livres mais livres e esperar a expectativa que eu tô criando as pessoas e logo você também começa a ser de fato mais elegante mais inteligente prender mais encomenda mais avançado então a imagem ela tá o tempo todo influenciam na nossas atitudes Qual o sentimento e consequentemente Nossas ações e resultados é um ciclo né você vai decidir para qual lado você quer alimentar ele né se é para o lado positivo de você tar sempre se vendo bem e alimentando isso aí reforçando isso daí todo dia e também ao contrário nesse você tá se olhando sempre desarrumado no espelho nesse mau cheiro e tudo mais você vai alimentando negativamente assim mais me também E aí vai perdendo mais ainda Essência né exata e quando fala em se gente é exatamente o sadismo a gente sempre se limita em investir bem esse e se vestir mal fato é que

existem sete Estilos diferentes e dentro desse 7 estilos você pode ser um cara que tem um determinado estilo que se veste mal e num determinado estilo e se veste bem e muita gente confunde se vestir bem com vestir da fome por exemplo Turbo Hoje eu tô transmitindo um casual elegante mas você tem estilo esportivo não é presa de show do Gabriel Medina é um cara que se veste muito bem mais dentro do estilo dele sim é um cara que se um dia ele foi visto de presente uma roupa de alfaiataria ela vai estar adaptada para o estilo dele esportivo casual ele não vai colocar um terno elegante formal assim que vai ser uma pegada mais casual era um carinho às vezes um coração lenço a cor bem extrovertida que um rosa uma pegada sabe com mais que ele tipo do corte né Entendi então o mais que ele vai num lugar mais formal e sempre vai carregar esse dele então não acha que vestir bem é sai o estilo terno não a pessoa não confunde essas coisas não tem nada a ver você consegue ser um esqueitista que anulam o skate Se veste bem em

vista que se veste é Mulambo como se estivesse bem e consegue ter um estilo elegante igual o meu que se veste mal surpresa planeta Essência Eu sabia que eu queria ser assim tanto que vocês for pegar minhas fotos de antes e depois eu tenho lá na barbearia com um sapato e uma calça meio que mais clássica Mas se a causa toda embolada o sapato meio que decisão nada a ver com errado porque na extensa e eu até queria ser assim quando eu nem sabia como ser eu de fato queria ser e acho que um ponto importante também né a gente comentou aí sobre o freio de que aquele cliente nem queria fazer um fake Né tava ali só fazendo porque o pessoal todo mundo tá fazendo então desafiar o pessoal também né a encontrar o seu estilo né colocar para fora né tudo que realmente quer ser não ficar só tentando copiar dele mais alto que a gente tem nossas referências né mas não ficar indo só na onda como a gente fala né eu acho que é importantíssimo espaço mesmo para construção pessoal médio você se gente descobrir mesmo de você né se reafirmar

com pela sua eficiência pelo quem você é né aí eles bom para a gente fechar duas perguntas principais é próximos planos próximos passos que seja ao meio aí pro futuro e já começou a consultoria né Pensa em Expandir os cursos pensa assim dar cursos internacionais O que que você pretende aí como próximos passos então basicamente primeiro projeto Foi criar a construir não foi nada fácil aquele o estudo hoje não Tipo o que eu estudei o visagismo com os meus mentores mas nesse modelo de consultoria foi um projeto meu esse passo a passo para qualquer bairro Inclusive a minha mentalidade foi se isso fez bem para mim tá fazendo isso porque a gente pode fazer bem para todos os barbeiros para lotar a agenda e elevar mais ainda um livro da barbearia mais do que já foi levado e para nos posicionar daqui a pouco para nós nos posicionarmos como barbeiros consultores de margens você explica para o seu cliente Qual que é o melhor corte para ele você tá consultando ele sobre a imagem dele não é só mais a ver o seu um consultor de imagem o fazem visagismo e o meu projeto meu

plano meu propósito de vida né desde que a minha mãe conta que não era nem para ter nascido eu já tinha ligado é feito todo o procedimento e mesmo assim engravidou de mim hein eu queria até processar o médico e a mãe dela falava aqui não faz não se ele ver que estão procurando seu propósito basicamente isso é transformar a vida de milhares de barbeiro sair pelo Brasil e pelo mundo não tem a intenção ainda de ter um negócio próprio meu agora agora mas quero ter nossa cultura aí vocês vão gente quer ter um negócio físico também a verdade já tem vários negócios né que primeiro negócio é a construir uma teoria o efeito Ela tanto dentro da barbearia quanto às vezes faço consultoria on-line para clientes de outros estados também né eu consigo fazer eu tenho um metro consultoria também parcial ele é 11 E aí ele também com a execução entende que dá para sempre entender dentro nisso e tem o os meus cursos mas info produtos que são é o meu nosso curte quer pegar isso eu vi que isso deu certo então que já tem que fazer derramar benção na vida

você tem que multiplicar fazer com que eles também consigo ir hoje eu tenho uma formação a gente tem vários alunos já tem resultados para você que é lá na comunidade no lugar bem simples cobras r 5 um corte Hoje essas perguntando uma coisa mas eu não consegui usar abusar de falar isso vai ser a barbearia mais top A Barbie é mais legal ainda sua região você vai querer ser tanto você vai ter tanto cliente que ainda vai falar assim é cara Band é onde você vai abrir uma barbearia no outro lugar Um lugar melhor assim lugar mais nobre ou várias mesmo e aí você vai deixar isso aí para abrir sua outras pessoas né ou para você que está aí mas tem um sonho de um dia trabalhar com seu eles com a gente ou trabalhar numa barbearia em Hollywood quem quer trabalhar com filho que trabalha em São Paulo quer trabalhar fazendo consultoria de imagem quer sair só do literalmente levar uma vida de qualidade para sua família ganhar mais trabalhando menos entendendo o que tá fazendo trabalhar bonito estiloso Chevrolet respeitando mais valorizando o de teu carro que você quer a casa que

você quer sabe o que o visagismo vai fazer aí para tem ganhar né estão esse basicamente aí é o meu projeto né projeto legal bom Fi acho que você citou já duas referências né principais aquele dia que seja seu Elias e o pai do visagismo do Brasil né mas quem mais você tem aí de referência hoje cara e tem várias defesa minha vida né desde pai e mãe esposa mas vamos focar aqui na Honda faria com certeza que eu falei O Elias e o Filipe cozinha um filho Nem Costa cabelo ele está fraco 50 anos estudando a linguagem visual né para entender o que mais pressa um Citroen fusquinha gente tem escuro então para ele desculpa você transmissor idade ou senhora com fusquinha para o Citroen C3 C4 eu não começa a contar de força queria construir as custando que os cinco Citroen C3 ou C4 Milan os carros mais vendidos para mulheres no Brasil ponto importantíssimo isso a linguagem do alforje de cabelo e o filho Fiel ele estuda isso linguagem visual identidade da Imagem e aí correlacionando-os com os trem para mim você de qualquer pessoa por isso é uma grande referência mas

se tem um grande amigo que está o nome dele aqui que o Rogério grande Rogério Araújo foi um profissional que são muita moral e aí quando eu entrei no feliz que me ajudou cara elegantíssimo Quem sabe a gente não vai ter a honra de receber esse também né certeza e eu influenciei ele né a estudar o Jardim não estudou minha cidade liso bem já tá ficando é o ele já entendia muito sobre roupa aí agora está aplicando a consultoria de imagem mais voltaram orbitalmente calzadilla comigo ele me agradece muito né Por ter incentivado isso mas eu também só tenho agradecer ele todos os outros conhecimento incentivos que ele deu quando entrei na barbearia lá que era muito simples humilde não sabia por onde percorrer não lembro que eu queria fazer o curso em Londres vários outros colegas que falava para mim não ir falar que ia gastar dinheiro à toa ele foi um dos que ela vai Classic conhecimento muda a 20 High daqui a pouco você pagou o pato já paguei já recebi Já viajei muito mais é um tudo de novo não tenho eu tô sempre buscando recentemente já adquirir cursos né ontem

mesmo antes de adquirir um novo eu tô sempre adquirindo Logo Eu já não tenho medo que utiliza concurso que vai agregar a gente olha esse para o Mack nos cursos só vendendo e falar cara será que vai ser isso mesmo mas sim há dez quinze por cento que às vezes a pessoa tá falando já é o bastante para valer mais do que a pessoa tá te cobrando e vai te dar um resultado nenhum imaginável É a Gi tem marido esperar de um curso às vezes de dois mil e quinhentos e vinte mil Federal a mágica imagem para milagre tá vai existir mas com certeza todas as pessoas vão te entregar de ferramentas para se construir sim grandes resultados é a gente pode ver que se não teve é desses de ouro nem nada né mas ao longo do que você foi contando a gente vê que tudo sempre com muita dedicação muita garra né Acho que o segredo é isso é pode ser o curso de 2 ou de 20 é o que vai determinar os resultados menos vai ser seu esforço né Sua Entrega ali para isso eu acho que o visagismo ainda traz

isso né se é você tá entregando realmente algo que agrega né e o valor é só consequência disso a Cone Muito obrigado a você né Nós temos aqui um kitzinho nossos convidados que vieram na nossa primeira temporada que agradeço esse lindo veste Barros e Valeu a gente agradece mesmo imensamente represente entender bem Red Bull tem doce de leite tem Caneca Lisa sem massa legal não é você guarda com carinho aí realmente para nós é uma honra né Acho que tem muita agregar É principalmente um conteúdo aí que a gente quer levar para o Brasil todo para fora e que possa mesmo tocar a vida aí de muitos barbeiros Neto hoje muita gente fala do mais de 7 Neto vai ficar umas sete aí e alavancar mesmo o ramo das barbearias essa atmosfera aí para um outro nível certo vó obrigado Mais uma vez aí aí muito honrado com o convite ou E aí [Música]`,

  summary:
    "Episódio 5 da Temporada 1 do BestBarbers Podcast. Marcony Visagista compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
