import type { VideoContent } from "./types";

export const podcastisrael_avila_ep04: VideoContent = {
  slug: "podcast-israel-avila-ep04",
  youtubeId: "O1PMhWWbj2M",
  title: "BestBarbers Podcast com Israel Avila — Bate-papo sobre Gestão de Barbearia",
  description:
    "Episódio 4 da Temporada 1 do BestBarbers Podcast com Israel Avila. Conversa sobre gestão, crescimento e os desafios do dia a dia de uma barbearia.",
  keywords: [
    "podcast barbearia",
    "gestão de barbearia",
    "bestbarbers podcast",
    "dicas para barbeiro",
    "como crescer barbearia",
    "israel avila",
  ],
  source: "bestbarbers",
  channel: "BestBarbers",
  publishedAt: "2022-07-28",
  duration: "46:34",
  category: "Podcast",
  tags: ["podcast", "temporada 1", "entrevista", "gestão", "barbeiro"],

  transcript: `a cinquenta por cento do meu resultado hoje foi qual é Olá senhoras e senhores caríssimos ouvintes do best Sales podcast sejam muito bem vindos eu sou Gabriel Rangel um dos donos aqui no vestido ali e eu vou ter o prazer de entrevistar E aí eu Ávila ele quer uma das mentes mais discutidas no ramo da barbearia lançou praticamente o atendimento a domicílio E hoje é uma das principais referências na área tem o seu próprio estúdio atende vamos dizer assim clientes de luxo e ele vai ter muita mas muita informação valiosíssimas para compartilhar com vocês Episódio senhoras e senhores barbeiros de todo o Brasil estamos aqui com Israel a vilã um dos principais influenciadores hoje desse meio o Brasil e Rael Seja bem vindo aqui ao best values podcast a daí pelo convite a honra conhecer galera muito tempo tá gente tem uns bons anos já né Eu sou fã da estrutura aqui ó é top demais Israel vamos começar primeiro se apresenta aí para o pessoal você que é bem conhecido mas é bom para quem ainda não te conhece pessoal é prazer meu nome é Israel Ávila eu sou barbeiro aqui em Belo Horizonte

a 8 anos já tem essa cara de novinho mas tem uma estradinha aí comecei a trabalhar desde auxiliar né no Torres Na barbearia 2 com seis meses que eu tava lá já consegui pegar uma cadeira na verdade dentro de 6 meias eu já achei a Europa já tinha ido para o Estados Unidos fazer custo da em curso e feito curso com Oi Mili dillblack seu Elias os cara tudo então assim o meu primeiro ano é uma virar eu acredito que foi quase 15 anos aí sabe quanto é que eu acho que o que Eu cortava em um ano eu não corto nem hoje sabe se dá um fiado que eu tava mas aí consegui trabalhar lá comecei com na época tinha 17 anos né 16 anos na verdade 15 e 16 anos era bem legal porque eu tinha 15 anos o cara mais novo da barbearia tinha 30 né ano foi um desafio muito grande graças a Deus deu muito certo hoje eu tenho aqui minha dela eu saí do Torres em 2019 no dia trinta e aí no dia três de janeiro a descobrir sair com a na frente e outra atrás aí porque

eu cansei do sistema convencional de barbearia mesmo assim não que esteja errado mas cansei de fazer aqui lá e aí não sabia que eu ia fazer também não é em salvar e Zinho já meu pai amanhã vê sua acho que conseguiu fazer não quero mais isso tal e aí meu pai minha mãe não você tem que correr atrás mesmo pode fazer faz vai que a gente tá consigo e isso foi na virada né E aí eu saí do Torres fui para o encontro eu não tinha minha barbearia né aí já começou a minha história né que eu fiz o cara não quero ter um algo convencional não faz sentido investir tanto em uma barbearia já sei como é que tu chora tudo isso aqui e não queria investir E aí umas cliente me mostraram atendimento então esse tão fazer Muita gente me conhece é porque em 2017 eu ganhei o campeonato também de barbeiro no Barber Day conference Eu fui o primeiro campeão com 17 anos de idade e tinha um cara no palco com 27 anos de profissão e ele não Eu terminei o meu e depois foi engraçado que eu terminei o dedo

nos Bastidores foi bem legal trocando ideia com a galera e tal Então esse foi o primeiro reconhecimento que eu tive mas depois veio essa parada domicílio E aí veio com anemia né estamos cliente mostrou que eu podia cortar cabelo em casa e eles me pediram então lado enquanto você não abriu sua barbearia vem cá nesse vem cá vem cá vem tá ele me mostrar esse ramo de atendimento em domicílio e deu muito certo graças a Deus aí veio para bebe pandemia para mim né não posso reclamar e de jeito nenhum foi muito bom né claro que né Tirando esse lado da pandemia mas no lado comercial de trabalho foi muito bom e é hoje 2022 Eu tenho um outro empreendimento novo empreendimento que é uma sala comercial tô atendendo exclusivamente então tem o público de domicílio também e tem um público quem é que vai lá na sala então atendimento exclusivo só eu e o cliente é por isso que eu tô aqui também né que não tem como a gente fazer tudo sozinho né pelo menos o corte tudo mas tá chegando um ponto aí que tem que estar com a galera do mestre

Barbies aí para não entender depois mas eu acho que é isso né minha história é essa Comecei na profissão com 15 anos e é isso bom essa história é cheia de surpresas é e coisa aí no meio tiver muita coisa e uma coisa assim que quer muito visível acredito para quem te segue para quem tá mais próximo assim do seu dia a dia para mim você é uns barbeiros senão o Barbeiro que pensa mais fora da caixa Vamos colocar mais sai do convencional e eu acho que isso chama a atenção seja isso para quem faça os cursos tiver nas redes sociais viajando pela Europa e tudo mais E e essa questão do domicílio vem muito casado com isso né E como é que essa questão de trabalhar domicílios a rotina fixa lhe de bater. Entre aspas de 8 às 8 horas da noite praticamente contra o pessoal isso começou em 2001 2016 foi quando eu fui para a Tony Guy nem em Londres E por que que eu visse lá a primeira coisa que eu vi naquela época a gente está falando de Londres libra esterlina era 60 para onde um corte na pele gás

60 libras eu queria cortar cabelo com ele mas não dava 6:20 que tava libra vezes é senta e a gente tava pagando um arroz e feijão e um bife lá que que a gente tava com vontade de comer comida brasileira r 140 mano é porque eu tava vendo quatro libras 26 livros um prato de comida né E aí eu fui entender primeiro valor agregado porque lá se aceita Livres é r 60 sem a conversão e segundo a arte por trás do cabelo então eu falei assim cara é primeiro são cliente delas que valoriza isso e eu cheguei no Brasil o Brasil tava saindo daquele salão né em 2014/15 né graças ao seu Elias e o Torres é mas ainda assim a gente tava muito bom Então desde sempre eu enxerguei o que é o que pode ser feito além porque eu imaginava olhar os caras andando na rua e falar assim cara o cara tá com tênis de mil com a calça que no mínimo uns 800 reais r 500 a blusa de 200 300 relógio Alice o cara não meter um Rolex alguma coisa assim BMW BMW né fora qualquer outra acessório né E

aí cara o cabelo o cara pagando r 25 r 30 então sim eu só tô falando assim o quê que passa o antes da minha cabeça que assim eu enxerguei um Talvez uma maneira diferente de cliente Porque sim eu não achava justo o cara fazer isso o cara tem um tênis de um pouco eu falei r 1000 mas hoje um tênis da Gucci no mim não é 67 mil reais né então assim não fazer sentido e aí é porque de atendimento a domicílio toda essa questão igual o trabalho hoje porque de onde eu vim era uma linha de produção Oi e aí a gente não consegue fazer isso lá não consigo fazer amor Gary convencional querem um atrás do outro e tal então atendimento em domicílio ele deu muito certo é por causa dessa exclusividade que é você e o cliente e aí é onde você consegue realmente tem um valor agregado alto que é onde eu tô hoje então hoje a minha cliente ela é 95% milionário tem dois por cento que bate nos be ele não brincando mas não é milionário sim mas assim que o resto né graça tipo assim normal mas

eu falo assim é eu consegui fazer esse cara olhar para o cabelo dele e tem importância tão quanto o iPhone quem tem no bolso porque cara se ele raspar o cabelo claro que tem muita gente Careca não tô falando né no hoje politicamente certo tem excelente mas eu falo assim o cabelo é muito importante na imagem do cara velho muito importante então sim eu acho que nós barbeiro não deu a devida atenção o saque para ir se passe caramba Neymar ele é conhecido muito a bola máscara quantas pessoas só ouviram falar do Neymar por causa do cabelo que fiz o Moicano então eu quis entender isso mais quando veio a domicílio sem eu saber o Nil tudo isso porque único exclusividade que é só eu e o cliente a mas gente é uma coisa que não tem igual é a taxa de indicação não tem como mas não qualquer negócio é tipo assim é muito alta porque você tá dentro da casa do cara você é só você e ele saca então sim beleza O Elo do barbeiro já é forte igual vamos Tô sim qual outra pessoa que passa uma faca no seu pescoço

não existe entram nem sua esposa família seu marido faz e isso de maneira mais exclusivas e você e ele tipo assim é é mais ainda então assim seja na sala ou dentro de casa muito mais dentro de casa que está no ambiente que tem esposa dele tem um filho dele tem a casa dele e aí assim é um mercado que eu me apaixonei tem então assim venha valorização do meu trabalho que é o principal ah mas tem a gente frustrada Na barbearia e vem muito disso cara não É valorizado não ganha bem e não faz né então assim isso para mim é o principal não que eu sou movido ação dinheiro mas assim É valorizado o cliente entende o valor além de lhe pagar ele entende valor e um negócio que quando o cara certa gosta não tem igual Então seja na sala ou em domicílio né com seu eu acho que eu não falei um tanto de trem Responde essa pergunta eu respondo vocês hoje essa questão de valor agregado não somente no atendimento a domicílio é de negócio prestação de serviço não é muito importante você e se não você acaba que fica

preso como você falou né só os corte é 20reais para sempre se você não agregam valor à minha experiência e justamente se entrega uma experiência muito positiva para seus clientes hoje você atende no mercado como você disse que tem é o no bairro né do Vila da Serra Nova Lima que tem a maior quantidade de senão uma das maiores quantidades de milionárias por metro quadrado do Brasil ela sai a matéria é é a mãe mais tromba trupica e Milionário de vez em quando ontem mesmo né Tem um vídeo da Ferrari Lamborghini ali na verdade com duas uma Ferrari Lamborghini e muita gente fica fica mal é normal exatamente muita gente fica sonhando com esse e-mail como é que é trabalhar nesse meio como é que você ser barbeiro nesse meio o seu barbeiro dos Milionários se assim podemos dizer cara é um negócio aí que tá é é e eu venho de família cara humilde tipo assim eu não sou rico também mas assim vou chegar lá mas assim é eu nunca vi dinheiro demais nunca vi nada disso não tá acostumado com isso e na época que eu mais ganhei dinheiro há um tempo

atrás foi ganhar sétima reais o mês de primeira rio de dinheiro Oi e aí assim a lidar com a clientela que gasta isso em um jantar e isso mexe muito com essa cabeça cara com certeza então assim é a principal coisa que eu que eu aprendi sabe tipo assim vendo essa galera era que o dinheiro ele é ele é só uma como é que eu posso colocar ele ele não é o dinheiro que nós que vende classe baixa que tá subindo para nós o dinheiro ele tem um valor tão assim para eles não é o contrário o dinheiro sempre a consequência de alguma coisa é E aí aonde entra porque eu falava assim cara tô atendendo um cara aqui cara você ter ideia eu vou contar a história aqui eu conheci um cara que ele gastou em Dubai e com XIX e uma noite 300000 você entende e o cara me contando Nossa foi top tá senão bacana e as normas legal faço mano esse dinheiro mudar e me minha família meu pai minha mãe todo mundo velho e o cara gasta em uma noite só que aí que tá nesse caso desse cara não

né mas assim grande parte da minha clientela eles me entregam que há de mais valor que o dinheiro Oi e aí é o que eu tentar a planta recebi porque se eu for um cara com a cabeça fechada eu fico Esse povo tem que cobrar mais caro porque ela tá falando comigo gastou ontem 50000va deveria ter cobrado ele 3 mil no corte tipo assim né exemplo mas aí que tá essa criança ela e compartilha aí entra na questão de exclusividade tudo eu comecei a parar para analisar minha clientela tem vários clientes com empresas com faturamento deve gigante até bilionário é que o cara que eu abaixo o dele que ganha rio de dinheiro também não tem um tempo de qualidade que eu tenho com ele sim e assim eu sinto isso demais que é os cara queria me entregar você mano eles me ajuda a pensar fora da caixa me ajuda a ganhar o que vai ser mais valoroso que realmente botar o dinheiro no meu bolso e também mano tanta aí eu já ganhei mil a 450 é de gorjeta 1500 na verdade então sim mas sábado esse cara que me deu r 1500

de projeto foi o cara mais pobre que eu atendi tem que passei no sentido de ele é um cara que tem bilhões mas é um cara que não consegue me agregar em nada Oi e aí tem cara que está em outro nível mas assim ele se entrega tipo assim mano o que há de mais valor que me ajudar a chegar lá também então e primeiro tem que estar apto a receber isso então assim eu sempre falei isso com os meus cursos Quando eu fui para o Vila da Serra eu ficava o dia inteiro na vidraça olhando para fora e aí eu via a galera com roupa caríssima Então a primeira vez que eu vi uma uma jaqueta de 20 mil reais e falando meu Deus E é só que aí tipo assim eu guardava isso para mim a primeira vez que eu vi uma Ferrari eu falava assim meu Deus e tal depois eu fui ver ela todo dia depois eu entrei depois eu peguei na chave e eu acostumei com tudo só que assim é isso que eu falo meus cursos na verdade muitas as coisas não precisei ter nem colocar a mão mas

eu querer sente a atmosfera e o ambiente me fez entender mais o meu cliente e aí foi chegar nessa nessa conclusão que eu vou assim para essa clientela eles conseguem entregar o que há de mais valor do que o dinheiro porque que ele é só uma moeda de troca é esforço dia para eles força tipo assim e aí aonde entra outra coisa eles resolvem problemas que a consequência disso ganhar muito tinha então Os caras que eu sempre conheci já já lhe dei com todos os públicos mas os cara que mais trabalhos que mais não Entendes que mais resolve problemas que mais grande e tons Entendi parece que aquilo que ninguém quer fazer vamos lá e faz E aí foi isso que eu aprendi mais dele entende tipo assim atender a galera com dinheiro que eles Gastão como qualquer coisa e ao mesmo tempo eles eles querer me ajudar e eu tá atrás e foi isso que me fez entender é a imaginar tipo assim cara hoje eu sei o que quer chegar na casa eu imagino e tem uma chave de uma Ferrari pendurada lá é coisa que ninguém talvez imaginou para mim é um

sonho mas assim para mim já não é mais lá essas coisas e aí quando eu vou atender esse cara eu consigo olhar ele mais no porque às vezes o cara vai te falar alguma coisa que foi você vai assustar na sua reação você vai assustar então eu procurei a entender esse público entrando na sociedade dele então é almoçando onde eles almoça investindo pouco que eu podia ir Eu tô tomando café comprando tudo que eu podia para fazer no bairro fazia eu acostumei com a galera Então hoje eu acho super normal qualquer coisa tipo assim eu conheço um cara que trabalha só de helicóptero é 8 horas da manhã o carro já gastou quase 100 mil reais é normal É a vida dele no para mim eu não assusto 9 quis mas por estar inserido no meio entendeu Entendi e aí querer desculpe só e aí tipo assim querer entendeu que que ativou aquilo ali nele para ele fazer isso entendeu e muita gente Talvez seja se perguntando Ah como é que o Israel mas nada é esse é o principal que você passa as informações aqui pessoal mas muita gente talvez tem se perguntando como

é que você chegou lá tem que ser fez que que você acha que foi a virada de chave que que você acha que foi a principal coisa que você fez para conseguir tá hoje Onde você tá atendendo esse público no bairro você tá com a condição que você tá cara é e pensando nisso ontem eu tô desenvolvendo o meu método e eu tava parando para pensar é tipo assim vai ter gente que vai falar assim ah você tá lá por causa do Torres porque se montar uma barbearia você foi para lá beleza ele realmente motor mas a Bárbara não entrava cliente bom e é todos os market que foram feitos lá não deram certo tanto é que a barbearia ela é reduzida sabe então assim eu posso falar de boca cheia que como a minha clientela Quem fez foi eu como enchendo o bolso de cartão e gastando dinheiro que eu não tinha que era e cara e tipo assim a a galera pode achar que é que é zueira mas não era eu não tinha dinheiro para nada tava quebrado tinha acabado de ó só para você ter ideia tá vou abrir aqui pra

vocês Eu tinha quando eu fiz 17 anos de idade na verdade é quando eu tinha 17 e é três dias antes de eu fazer 18 eu comprei um carro aquela pilha Nossa barbeiro tá alto viajando curso tá entrando tanto de dinheiro lá para mim aguentar aqui papá peguei um dinheiro fui lá meti um carro Honda o Barcelona daquele jeito né divididinho eu não divide digitar toda vez mais dividida e poucas vezes não passei arrebentando Então tinha um carro tinha um iPhone do ano tinha tudo do Top entre aspas eu ganhava trabalhando na época tipo meio horário que eu estudava ainda eu ganhava 4 meses Oi e aí de um mês para o outro eu passei nem a 700reais isso é preciso já era assim tava um saca então assim sai de onde eu tava chuta lá fui no pó então é a não teve garantia não teve nada foi esse manto quer ir velho vou aceitar o desafio então foi eu que aceitei e foi a melhor coisa que eu fiz na minha vida passei dificuldade se não fosse meus pais ia ter dado muito ruim bom então tive que vender carro tive que refazer

minha vida por completo cara Oi e aí eu tinha assim cara de verdade tinha setenta reais para mim fazer tu me avisa eu tinha setenta reais que eu te ajudado duas semanas tão 30 tipo literalmente isso aí que o Instagram bombando tá Instagram famosinho Que trem todo e passa uma pintinha lascada bom então é onde é que aí foi onde eu parei para analisar me atendeu foi gente onde é que tá a mãe dela aí eu fui ó se eu ficar sentado aqui dentro da barbearia e não vai entrar cliente e não trava Porque era uma loja dentro de uma loja a barbearia ela dentro de uma loja então eu tive que ir nos restaurante então não tinha dinheiro mano almoçar pagar r 28 no prato era uma fortuna para mim sabe então às vezes almoçava pouco ficava com fome para caber dentro do orçamento mas eu tava onde meu que a gente tava E aí ninguém faz isso os cara não tinha tipo assim não não investir r 10 no café a mais ele é por causa ele tomar um café ficar sem reais na boníssima Ali no bairro ficar 15 os cara não

tinha coragem e aí eu pegava esse dinheiro e fazia isso E aí eu ia para restaurante um cara e a um lugar que eu arrumei muito cliente encontro de carro bom então ativos posto de gasolina foi lindo maravilhoso tem que pagar nada só os carro parado lá Ferrari Lamborghini que tem toda ficava cubano os cara o cartãozinho no bolso chegava e seu irmão bacana bem nova é isso sou fã do carta ao toque a minha aproximação já é diferente desse tipo assim eu não chegar a barba no Vera tipo assim cara deixa eu te apresentar aqui o seu barbeiro em tal lugar atendo lá maneira diferente tal isso só pecava nos caras é só você tem um carro de mesmo né o tipo de vida você merece eu atendimento para fazer a venda mesmo né E aí velho foi assim um a um a ponte de eu ir para balada e esse sério Fui para balada várias vezes sem dinheiro sem nada sem beber nada lá dentro nada disso E aí pura ou eu ai que tá uma coisa que eu sempre aprendi meu avô me falou isso aí ele falou assim ó na vó

era taxista e fosse Israel Se tem uma coisa que você tem que ter contato e meu avô esse cara velho se você precisar de um avião caindo e fui ontem e lembro do telefone de cor Oi e aí eu sempre presei isso de Caramba você conhecer gente conhecer gente conhecer gente saber quem faça meu pai fala a mesma coisa meu pai a baiana ainda tem um sotaque ele fala Gabriel na vida são relacionamentos é exatamente isso ainda tá moderna mas aí cara quando eu chegava nesses ambientes assim quase sempre tinha alguém que eu conhecia Então se alguém que já me viu e aquele ambiente ali que você né aqueles você não precisa ser amigo Você viu o cara uma vez você olha aí velho como é que você tá E aí eu ia entregar o cartãozinho várias vezes eu já coloquei cartão no bolso de gente fazer um cara dono do camarote tava tri louco lá o cara nem me escutar eu mando não deixou o cartão aqui depois você vê e foram várias vezes o cara chegava um menino tal era até estranho é porque eu encontrava os clientes Na barbearia todo formal e

ia na balada os cara treloso o skar meu braço vai chegar no outro dia lá e aí beleza e aí foi assim foi num a um entendeu então assim foi eu tentando aproximar de gente os cara me dando tá aqui na tora tipo assim velho não não tem nada e aí eu tive que mudar todo o meu posicionamento aí aonde eu comecei a falar sobre o método é o Barbeiro O barbeiro igual eu faço hoje ele é constituído por quatro pilares eu tenho que dar meu telefone é eu tava voltando isso eu tenho a tudo anotado mas disse que foi esse um resumo que eu comecei a fazer é que ele é corte Network marketing e audiovisual II E aí que tá a porcentagem diz que é o segredo onde a galera Acabei de soltar esse no Instagram vindo para cá é o que mais tem hoje na profissão é barbeiro frustrado cara tá cansado cara não aguenta muito pelo dinheiro que não consegue ganhar direito mas aí que tá noventa porcento dos cursos ainda tá para ensinar o cara a ser educador cortar né tá em palco tá tá tendo visibilidade e isso é

muito diferente do que tá com cliente sim um dos caras que foi o melhor educador do mundo foi cortar meu cabelo e rasgou minha cabelinho tomar camisa inteira e eu preciso tempo de deu machucado e esse cara é muito legal né então assim tanto é que na época estava na turnê foi com o seu Elísio Yoshi aí eles parou olhou assim Marquinhos Quantas cabeças é enorme é muito diferente a gente bater esse papo 5 cara é educador ele não tem a mão leve para o cliente gostar ele tem um resultado no degradê ele do corte é muito diferente do dia de força então beleza então cara é constituído sempre vou falar mais não tanto que o às vezes quando você vê esses caras fazendo esses cortes Talvez um cara leve uma hora uma hora e meia e aí no dia a dia o que ela tem que fazer um corte em 15 minutos 20 minutos ali né então assim ó corte networking e marketing e audiovisual foi isso que me fez chegar aqui dá uma pela porcentagem cinquenta por cento do meu resultado hoje e foi quase Network 50 de sem por cento e cinquenta

por cento foi Network então eu sempre presei isso desde o início ter contato conhecer gente Network o segundo não é a porcentagem 25% Market aí eu marketing volto posicionamento né estilo como se fala como que se entende como é que você vai aproximar O cliente marketing é realmente colocar o produto para vender né então toda essa parte que eu sempre gostei de fazer meu Brand né minha marca engraçada que eu sempre cria algumas coisas e eu vendo tudo né então que a galera gosta do nome da dobredin da parada que eu gosto de fazer bom então marketing para mim é isso é colocar o produto na cara do cliente do jeito que ele quer E aí foi isso que eu precisei muito bem imagem meu estilo meu nome né enfim depois quinze por cento foi audivisual então foto muito bem fofo né fotografia e tal eu posso dizer que hoje eu tenho equipamento né que é de fotógrafos nem botar o direito tem um equipamento que eu tenho e o vídeo principalmente o vídeo em Belo Horizonte hoje são poucas pessoas que eu tenho como referência no vídeo porque eu já tô sendo um patamar

de igual eu tenho uma empresa de áudio visual também de vídeo prestação de serviço então o vídeo e a fotografia e me fez fez ajudar mais um marketing é o meu trabalho chegar mais para frente e o por último com a porcentagem menor o corte então e para mim na minha visão é mais do que minha obrigação em carregar o nome de barbeiro Entendi então assim como que eu cheguei nessa clientela como que a pergunta foi foi assim cara foi eu saber se os pilares que eu acabei de passar aqui Network e tal e entender o que que é ser eficiente entendeu o que que é e hoje Principalmente eu tô reestruturando 100% negócio então hoje eu tô num patamar é que eu tenho muito cliente no WhatsApp tá lotado meu ticket é alto só que ao mesmo tempo muito barbeiro eu acho que tá e já tirando o pé agora nossa top tanto ganhando X é e cara agora tô sim eu tô com medo entende tipo assim então se mando pera aí eu tenho que arrumar uma maneira de atender os clientes mandar mensagem papá Então eu estou montando o robô Oi Ney

com as novidades que você sabe que que eu sei é vim com a sala um atendimento super exclusivo eu sempre o cara minimalista não quis gastar dinheiro não porque eu sou mesquinho pelo contrário eu invisto tudo meu é top mas quando eu montei a barbearia eu montei ela cabe no meu bolso tanto é que veio com anemia fechou e para mim não fez diferença nenhuma eu comprei tudo quitado tudo à vista e aí agora nesse novo patamar no Vila da Serra com essa nova estrutura Eu contratei um arquiteto sabe Tô fazendo negócio paleta de cor e tal então assim é é um conjunto de isso tudo e principalmente das cara mesmo para ir atrás do cliente mesmo entendeu E aí agora eu vou chegar em 100 porcento a minha da eficiência e aí até a por favor alto mesmo é seu bar mesmo Olha eu tô falando isso em todos os lugares que eu vou eu quero seu barbeiro primeiro Barbie Tu viu que vai faturar o que um cabeleireiro e fatura que é normal se virar para falar semana que eu conheço cabeleira que já faturou 150 mil reais mesmo no mês que ele

e ele é não é dono do salão ele é sozinho aí você chega lá o cara tem ele mas 15 pessoa que a equipe dele ele tem ele e 15 auxiliar dele sabe E aí eu falei assim cara porque que não tem nenhum Barbie a fatura no 15 conto 20 conto aí aonde eu falo com você sobre o curso é o que eu acabei de soltar no meu Instagram não tem ninguém pegando isso para fazer não tem cara a galera Kiel passo a passo mais rápida e aí é onde a diferença de educador para barbeiro mesmo sabe como ela é muito aqui Aperta tem um Ramon Ruiz e o cara que trabalha sozinha agora tá me vendo trabalhar sozinha acha que é novidade mas tem um cara aqui do lado uma barbearia clássica e o corte dele é r 120 o Ero sempre foi o corte mais caro de Belo Horizonte em barbearia e até hoje hoje não vou Elias tem seu exxpirence mas é diferente né corte de cabelo né tô sem cantores Aventure tal mas o corte de cabelo mais caro é é dele então sim eu tô preparando para chegar nisso E

aí eu falar onde eu falei a minha meta é fazer r 1000 todos os dias a minha primeira meta é essa no dia que eu chegar ali se eu vou dobrar ela entendeu muito bom agora só tem que ter cuidado pessoal aí vai para balada cheio de cartãozinho de maravilhoso daqui a pouco ele vai ficar louco lá né vai que dia para beber a culpa é de Israel Mas isso é o voltando para esse foco aí do audiovisual em são os aspectos assim que mais se destaca do seu trabalho né Isso começou como um hobby isso Começou a como o interesse seu e foi se aperfeiçoando que é bem que hora ó dá para contar isso eu tenho que voltar na minha história tatuagem aqui ó Isso que é índia né já contei para você já sabe disso hoje uma vez falando Taj Mahal né que você morou lá não tem número então eu morei na Índia a hora que loucura eu meu pai e minha mãe meu pai passou evangélico A gente foi lá fazer missões eu não sou um cara né Eu sou crente evangélico mas não sou muito exemplar né então já

quem for criticar a ilha mas eu falo assim desde lá eu já tinha acesso a isso porque lá tinha um trabalho a gente trabalhava com um pastor lá que ele tinha o áudio visual então assim é só precisa entender na em 2010 a gente equipamento lá que não tem no Brasil hoje que era rede era grua na época tinha tipo assim tinha cara tinha coisa demais a blackmagic essas câmeras que tem hoje na época ela já era normal tipo assim era equipamento que era privado de Globo não ter tipo assim então eu sempre gostei e comecei a trabalhar com isso lá saco então tem foto minha com 10 anos de idade operando grua um grupo de quase um milhão de reais e se não for mais então eu gostava muito disso então desde lá eu era apaixonado com isso E aí vive o Brasil com continue ajudando aqui também nos que tinha as produtor e tal mas era é tudo relacionado a igreja e aí Na barbearia me encontrei com isso porque eu conseguia fazer os vídeos para divulgar o meu trabalho então foi assim unindo as duas coisas e aí assim é um negócio

que eu sou apaixonada e eu e aí a gente tá vendo até que o áudio visual tá chegando tá e recentemente com o cara que desbravou o mercado de novo o Tiago fingir por causa do áudio visual né então assim o negócio que eu sou completamente apaixonado cara já seu tá lá em Dubai fazendo um vídeo lá cortando na sua casa essa é a meta aí que tá meu objetivo é um dia é de ser patrocinado já vai para Best bábby sair mas é um dia viajar o mundo mesmo fazendo isso então com YouTube e tal e tipo assim aí vem outra coisa a profissão barbearia ela é aí volta naquela primeira pergunta que você me falou o quê que me fez enxergar né e tal a nossa profissão ela é Libertadora cara ela é a sua também né a da Susie também porque é você tem um computador Você trabalha aonde você tiver adiante enfim e nós tem frente ela tá uma esse cara onde é que você tiver você tem gente Oi Lilo que tem cabelo vai cortar e porta no mínimo uma vez por mês eu vou colocar menino então sim eu

falei assim cara primeira coisa é isso também a gente tem a profissão que ela é de certa forma não mas a gente pode realmente viajar o Brasil viajar o mundo cortando o cabelo e aí entra outra parada que é que eu sempre quis não é que eu sempre quis mas é o que eu quero onde e ter o patrocínio das marcas e tal chegar no lugar que não tem acesso a nada tão caro não tem acesso a internet não tem acessar a profissão nenhuma estudo nenhum você deixa lá uma máquina e uma tesoura para o cara fazer irmão ai tipo assim se ele cobrar um real em cada corte se ele cortar 10 Ele tem 10 reais num lugar que não tem nada nem água deve reais o cara fala muita coisa você nem um dia né em 30 dias hein e eu só tô falando assim que é uma profissão que assim como liberta muita gente das drogas é conheço né Tem um Ariel que ele saiu da cadeia e virou o Barbeiro é uma profissão que eu acho que pode liberar tipo assim pode dar renda onde não a pessoa que tinha mais

imaginava entendeu então aí eu quero viajar o mundo fazendo os vídeos né Tenha nessa parte e ensinando a galera cortar cabelo e ganhar dinheiro com isso quando você tiver aí do bar e você manda uma mensagem para gente acabar das barracas E nada e como você acha também que essa questão agora está Mudando mudando não né complementando vamos dizer assim a sua exclusividade o tipo de trabalho para o modelo de estúdio e da onde surgiu essa ideia o que que você acha desse novo modelo entre aspas que vai Me dá um pouco atendimento a domicílio por quê que veio esse essa ideia agora o estúdio é o sala nessa seu estúdio sua sabe cara porque que veio pela demanda então assim é eu não vi o porque eu colocar um custo fixo em um negócio que eu não tinha porque eu vou na casa do cliente atendo ele dentro da casa dele sem custo nenhum e eu falei assim cara Beleza Tá ótimo muito bom mas tá chegando um patamar hoje que eu preciso eu da verdade eu tenho uma carta na manga que é ter muito cliente então Ou eu vou ter que aumentar

meu preço demais né pa né baixar clientela que negócio todo mas eu não achei que é um momento eu fosse cara e eu não tenho banco de dados meus clientes eu não tenho voz marque aquele negócio né tudo certinho eu não tenho nada estruturada é eu e meu meu cliente é só ligou para mim o WhatsApp marcou é isso eu falei cara antes de eu pensar em aumentar o preço eu vou fazer tudo sem por cento para o última coisa e o cara querer que eu faço e aí foi onde eu vim com a sala eu espero aí se eu tô faturando tanto e se eu tiver parado em um local e ele vir até o local eu consigo atender o dobro né e faturar o dobro em um dia só então foi isso em troca Então hoje eu tô no local a gente vai lá eu consigo atender muita gente eles ficam feliz porque é na no bairro deles quando atravessando a rua então assim aí por que que eu fiz dentro da sala comercial num prédio comercial porque o meu marketing e eu eu não acredito tá e já é Israel é e

provou isso gente eu tenho 8 anos eu tenho eu sair 2019/2020 21 22 desde quando eu sair eu nunca tinha feito panfletar tipo assim nem panfletagem Mas vamos por sim nunca tinha saído para falar se ó corta o cabelo tá aqui meu contato tipo assim e qual era eu e o cliente ou em local que tu ligou eu falei com vocês dez sim tô aqui mas não tinha cartão não tinha parte de falar assim Vou investir tráfego era só eu e o cliente era eu e Tete a Tete então assim maioria das vezes quando começou a engrenar a minha cliente ela é veio muito indicação é onde eu falei com seus que possuem um atendimento exclusivo sozinho O Elo de confiança é muito grande então quando começou a engrenar Eu praticamente não precisei fazer marketing marketing é o sentido nesses que eu falo de de ter que ir atrás de cliente dando né chamando para cortar mas era muito mais igual eu eu continuar almoçando em onde que ele está é muito mais para ter uma familiaridade Então o que acontece hoje quando o cara me indica para o amigo dele não vai me mandar

mensagem ele já me viu no bairro dentro e já me viu almoçando aonde ela almoça aqui então é isso sabe então é só que eu não tinha cartão não tinha tráfego não falava assim ó nunca rodei nada disso então eu só fui fazer isso agora saco de realmente falar espera aí vão fazer tudo então meu cartãozinho ficou pronto agora será que meu cartão como é que ele é chique demais né Vamos mostrar para vocês é E aí é onde eu tô tipo assim querendo entender sem por cento do negócio métrica tô estudando tudo planilha e tal só que planeta não dá certo já tem coisas mais evoluídas né então é a sala veio para isso e porque no prédio comercial para me entregar toda estrutura então um cara tem estacionamento tem um atendimento de recepção né que ele vai subir no elevador é exclusivo E aí olha eu comecei eu acho que você nunca termina o que eu com e eu lhe falei do Market que eu não acredito mais esse Market de panfletagem mesmo do cara não é o que eu falei com vocês de de você tá ali presente entregar o cartão para

o cara vou conversar com ele mas eu tô falando assim naquele de rodar anúncio rodar Que trem sem o cara tá ali te conhecendo sem ter esses Pilares que eu falei the Network the Market tudo bem posicionado Não adianta o cara só ter isso e tipo assim sabe então a a loja de porta para Rua para mim não faz muito sentido sabe fazer hoje quando eu apliquei todo esse método que eu faço né de atrair o cliente então não precisa é através de sair com o a estrutura da sala tudo fica top legal e como você falou deixou a entender também aí né a gente tu veste bar mesmo justamente tá avisando todos esses pontos que você falou então o pós da pessoa ali a gente pediu um quantas estrelas e deu o atendimento do Israel entra no poste também de a pessoa você não posso da barbearia né Vamos colocar assim além de receber o feedback você ali a cada dia eu puder comprar a cada mês quando foi o seu faturamento no mês também tem uns gráficos feinhos lá a sua meta é 1000 né a pessoa pode sentar metasinha dela aí no

gráfico também ela saber como é que ela tá todo financeiro também para não chegar numa situação de ator gastando mais daí chegar numa situação de quebrar e aí entra na parte da exclusividade que a novidade daqui a pouco a gente solta para todo mundo que esse aí vai vai abalar o mercado Vamos colocar a cena que vai ficar uma questão muito importante do seu negócio cara que Barba ele não tem cara eu falo assim eu saí do Torres comecei a ganhar o triplo e era tudo na cabeça né era é meu cartão de crédito eu sei quanto que eu posso ir eu você e a vó e esses mas não tem aquele negócio assim ó a gente já gera planilha esses ó olha os números lá e Analisa praticamente é tudo automatizado com o aplicativo né e a gente também tem aviso para o cliente não esquecer isso querendo ou não cuidar barbearia tem esse problema né dê a pessoa não aparece no dia você perde aquele horário então acaba que é tanta coisa ali tem você falou do Market Também quem um dos pilares importantes ali né Eu estou funcionalidade que é você poder

disparar mensagens em massa para sua base então chupão que seu dia da barbearia terça-feira de tarde tá com movimento mais fraco você querer fazer uma promoção você diz para isso e por fim focar no Network a gente fez essa semana funcionalidade ficou bem bacana que é você adicionar uma observação no histórico da pessoa você não esquecer que que você conversa com ele gente ele gosta exatamente vai ficar legal sai eu te agradeço demais sua participação aqui com a gente nesse epi e veste babys podcast a gente tem uma parceria de longa data e vai vir muita novidade foi só eu teste barra teste primeiros episódios gravados aqui tá foi o teste vale eu agradeço demais pessoal que não segue qualquer ir lá o seu arroba é Israel a Vila aí eu água aí eu abro o f ou f em breve se Deus quiser não vou pegar né o saiu água Miguel demais ficamos honrados e pessoal fique ligado que em breve tem novidade com Israel show não foi minha Valeu demais Valeu o [Música] E aí [Música]`,

  summary:
    "Episódio 4 da Temporada 1 do BestBarbers Podcast. Israel Avila compartilha sua experiência como profissional do mercado de barbearias, discutindo gestão, atendimento, crescimento e os desafios do dia a dia.",
  keyTakeaways: [
    "A importância de uma gestão profissional para o crescimento da barbearia",
    "Como a tecnologia transforma a rotina do barbeiro e do dono",
    "Estratégias práticas para fidelizar clientes e aumentar o faturamento",
    "Os desafios mais comuns enfrentados por donos de barbearia",
    "Como se diferenciar em um mercado cada vez mais competitivo",
  ],
  painsAddressed: [
    { pain: "Falta de gestão profissional na barbearia", relevanceToBB: "alta" },
    { pain: "Dificuldade em fidelizar clientes", relevanceToBB: "alta" },
    { pain: "Crescimento desorganizado do negócio", relevanceToBB: "media" },
  ],
  quotes: [],
  benchmarks: [],

  relatedFeatures: [
    {
      title: "Sistema para Barbearia",
      href: "/sistema-para-barbearia",
      description: "Gestão completa para barbearias com app próprio.",
    },
    {
      title: "Clube de Assinaturas",
      href: "/clube-de-assinaturas",
      description: "Receita recorrente com cobrança automática.",
    },
  ],
  relatedVideoSlugs: [],
  relatedBlogSlugs: ["melhor-sistema-barbearia-2026", "barbearia-por-assinatura"],
};
