/**
 * PROJETO DO CLUBE — as 34 peças aprovadas do acervo, texto literal.
 *
 * ARQUIVO GERADO. Fonte única:
 *   docs/operacional/plano-v3-maquina-vendas/biblioteca-copy/LANDING-PAGES.md (n=100)
 *   + SELECAO-REESCRITA.md (n=34 selecionadas), normalizados em
 *   `copy-landing-pages-34-selecionadas.json`.
 *
 * NÃO reescrever texto aqui. Quem muda a copy muda a peça no acervo — e a mudança
 * aparece na página e no anúncio ao mesmo tempo, que é o ponto de ter um id (L###)
 * viajando no nome do anúncio.
 *
 * Só DUAS coisas foram derivadas mecanicamente (nenhuma palavra inventada):
 *  1. `situacao` — do campo `perfil` do acervo:
 *       «Clube manual» → manual · «Troca de sistema» → migracao ·
 *       «Abertura e expansão» → abertura · todo o resto → geral.
 *     As 17 peças de CONTEXTO (L041–L098) ficam em `geral` de propósito: §1.4 diz
 *     que nesta rodada elas não são rota nem herói, só o par de FAQ em destaque.
 *     Carimbá-las com uma situação faria o `situacaoDoAnuncio()` re-personalizar a
 *     página por um palpite temático — o oposto do que a guarda de personalização é.
 *  2. `artefatoExigido` — do mapa de §6.2 da arquitetura. É o que a guarda V9
 *     (`ponteEfetiva`) lê para NÃO prometer demonstração aberta enquanto a captura
 *     for placeholder. Peça que promete ver algo e não tem o que mostrar cai para
 *     «Como segue a conversa».
 *
 * Sem `"use client"`: os quatro `page.tsx` são server components e leem este módulo
 * no servidor (inclusive dentro de `metadata`).
 */
import type { PcPeca, PcPecaId } from "./pc.types";

export const PC_PECAS: Record<PcPecaId, PcPeca> = {
  L001: {
    id: "L001",
    conceito: "O clube na sua cabeça",
    situacao: "manual",
    etapa: "Topo",
    titulo: "Cliente na cadeira e dúvida sobre o pagamento do clube? Confira a cobrança na BestBarbers.",
    apoio: "Conheça a assinatura com cobrança recorrente no cartão da BestBarbers e veja como conferir os pagamentos na rotina da sua barbearia.",
    botaoPrincipal: "Ver a cobrança do clube",
    exemploTitulo: "Veja o pagamento antes de decidir o atendimento",
    exemploTexto: "A demonstração começa pela situação que interrompe seu trabalho: saber como está a cobrança de um assinante. Mostramos o caminho disponível no produto e combinamos o que a equipe consulta e o que precisa do responsável. Assim, você conhece a rotina que está contratando, além da tela do aplicativo.",
    faqPergunta: "A cobrança recorrente elimina todo atraso?",
    faqResposta: "Não. Pagamentos podem falhar. A demonstração também precisa mostrar como identificar a pendência e o que fazer depois.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L002: {
    id: "L002",
    conceito: "A conferência dos comprovantes",
    situacao: "manual",
    etapa: "Topo",
    titulo: "Seu clube pode cobrar no cartão, em vez de depender de pedir comprovante.",
    apoio: "Veja a cobrança recorrente no cartão da BestBarbers: adesão autorizada, acompanhamento dos pagamentos e orientação para tratar pendências.",
    botaoPrincipal: "Ver como cobrar no cartão",
    exemploTitulo: "Do “já pagou?” à informação da cobrança",
    exemploTexto: "Na BestBarbers, o cliente autoriza a assinatura no cartão e a cobrança segue o plano. Veja onde acompanhar o pagamento e identificar uma pendência. Se hoje você recebe manualmente, confira também como orientar seus assinantes na nova adesão.",
    faqPergunta: "Meus clientes atuais entram automaticamente?",
    faqResposta: "Não. A adesão e a autorização precisam ser feitas conforme o processo confirmado para o seu caso.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L003: {
    id: "L003",
    conceito: "Datas que se espalham",
    situacao: "manual",
    etapa: "Meio",
    titulo: "Tire a cobrança do clube da sua lista de lembretes.",
    apoio: "Conheça a cobrança recorrente no cartão da BestBarbers e confira como ficam as datas e os pagamentos do seu plano.",
    botaoPrincipal: "Conhecer a cobrança recorrente",
    exemploTitulo: "A cobrança segue o plano. Você acompanha o que aconteceu.",
    exemploTexto: "Mostramos a adesão e o acompanhamento no sistema. A conversa considera as datas e os acordos que você usa hoje, para explicar o que precisa ser preparado na mudança. Isso ajuda a tirar a cobrança da memória sem esconder as situações que continuam exigindo atenção.",
    faqPergunta: "Posso manter as datas atuais?",
    faqResposta: "O funcionamento precisa ser confirmado para sua regra. Não prometa uma mudança aos clientes antes dessa verificação.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L004: {
    id: "L004",
    conceito: "A planilha paralela",
    situacao: "manual",
    etapa: "Meio",
    titulo: "Veja a comissão do clube sendo calculada, sem começar por uma planilha em branco.",
    apoio: "Conheça o cálculo de comissão de assinatura e o extrato por profissional da BestBarbers. Compare o funcionamento com a regra da sua equipe.",
    botaoPrincipal: "Ver o cálculo da comissão",
    exemploTitulo: "Do atendimento à comissão de cada barbeiro",
    exemploTexto: "Abra o exemplo da BestBarbers e acompanhe os atendimentos até o extrato de cada barbeiro. Veja a regra aplicada e compare com o seu fechamento. Se você quiser conferir uma situação da sua barbearia com o time, o pedido de contato fica abaixo.",
    faqPergunta: "Serve para qualquer regra de comissão?",
    faqResposta: "Depende da regra que sua barbearia usa. Mostre como faz o fechamento hoje para conferir a configuração e qualquer adaptação antes de contratar.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "clube-extrato-comissao",
  },
  L005: {
    id: "L005",
    conceito: "O balcão interrompido",
    situacao: "manual",
    etapa: "Topo",
    titulo: "Dê à equipe um caminho para conferir a cobrança do clube.",
    apoio: "Conheça a cobrança recorrente da BestBarbers e prepare com a equipe o que consultar antes de atender um assinante.",
    botaoPrincipal: "Ver a rotina do clube",
    exemploTitulo: "A informação precisa estar onde a equipe consegue conferir",
    exemploTexto: "Veja na BestBarbers onde consultar o pagamento e como identificar uma pendência. Depois, confira quem da sua equipe poderá acessar essa informação e quais decisões continuam com o responsável. A demonstração mostra o controle antes de você mudar a rotina do balcão.",
    faqPergunta: "O sistema decide todas as exceções sozinho?",
    faqResposta: "Não. As regras disponíveis e as decisões humanas precisam ficar claras para sua equipe.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L008: {
    id: "L008",
    conceito: "Cobrar pessoalmente",
    situacao: "manual",
    etapa: "Topo",
    titulo: "A mensalidade do clube não precisa começar com uma mensagem de cobrança.",
    apoio: "Na BestBarbers, o cliente autoriza a assinatura no cartão e você acompanha a cobrança recorrente pelo sistema.",
    botaoPrincipal: "Quero ver a cobrança automática",
    exemploTitulo: "Entenda como sair do lembrete manual",
    exemploTexto: "Veja como o cliente adere, como a cobrança acontece e como acompanhar a situação do pagamento. A conversa explica a passagem da sua rotina atual para o processo disponível no produto. A cobrança recorrente reduz a dependência de um novo pedido manual a cada ciclo; pagamentos recusados continuam exigindo tratamento.",
    faqPergunta: "O cliente precisa autorizar a cobrança?",
    faqResposta: "Sim. A assinatura e suas condições precisam ser compreendidas e autorizadas pelo cliente.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L011: {
    id: "L011",
    conceito: "Trocar sem salto no escuro",
    situacao: "migracao",
    etapa: "Topo",
    titulo: "Troque de sistema sabendo o que vai acontecer com as cobranças do seu clube.",
    apoio: "Conheça a BestBarbers e entenda quais passos dependem do time, da sua barbearia e dos seus assinantes antes de tomar a decisão.",
    botaoPrincipal: "Entender como trocar o sistema",
    exemploTitulo: "Primeiro desenhamos a passagem. Depois combinamos a mudança.",
    exemploTexto: "Antes de sair do sistema atual, confira quais dados podem ser aproveitados e quais assinantes precisam fazer uma nova adesão. A proposta da BestBarbers descreve as tarefas de cada lado e o acompanhamento das cobranças em andamento. Você decide a troca com esse trabalho à vista.",
    faqPergunta: "Os cartões dos clientes são transferidos?",
    faqResposta: "Não conte com isso sem confirmação técnica. Uma nova adesão pode ser necessária e deve entrar no planejamento.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L012: {
    id: "L012",
    conceito: "Cadastro não é cartão",
    situacao: "migracao",
    etapa: "Meio",
    titulo: "Saiba o que seus assinantes terão de fazer para mudar de sistema.",
    apoio: "Vamos conferir dados, cobranças e novas autorizações necessárias para planejar a passagem do seu clube para a BestBarbers.",
    botaoPrincipal: "Conferir a mudança das assinaturas",
    exemploTitulo: "Confira a autorização antes de avisar o cliente",
    exemploTexto: "O time verifica o que existe no sistema atual e como a cobrança funciona. Se houver nova adesão, você precisa conhecer o caminho e a comunicação antes de avisar os assinantes. O objetivo é trocar com tarefas definidas, sem descobrir essa dependência depois de contratar.",
    faqPergunta: "É preciso encerrar o clube atual para conversar?",
    faqResposta: "Não. Você pode conhecer as condições e a viabilidade antes de decidir pela mudança.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L013: {
    id: "L013",
    conceito: "A falha que motiva a troca",
    situacao: "migracao",
    etapa: "Topo",
    titulo: "Conheça o cálculo de comissão do clube antes de trocar de sistema.",
    apoio: "Se o fechamento continua fora da ferramenta atual, compare sua regra com o funcionamento da BestBarbers.",
    botaoPrincipal: "Comparar o cálculo da comissão",
    exemploTitulo: "Veja a conta que motivou sua busca",
    exemploTexto: "A demonstração mostra como os atendimentos participam do cálculo e como conferir o extrato do profissional. Você traz a regra atual e conhece as possibilidades e os limites da configuração. A conversa sobre migração acontece com essa necessidade resolvida, e não apenas com uma nova tela bonita.",
    faqPergunta: "A minha regra será mantida exatamente igual?",
    faqResposta: "Isso precisa ser confirmado na demonstração. Qualquer adaptação necessária deve aparecer antes da contratação.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "clube-extrato-comissao",
  },
  L016: {
    id: "L016",
    conceito: "Regra que não cabe",
    situacao: "migracao",
    etapa: "Meio",
    titulo: "Veja como registrar os serviços do seu clube na BestBarbers.",
    apoio: "Leve a regra de corte, barba e uso para a demonstração. Confira o que dá para configurar e como o atendimento entra na comissão.",
    botaoPrincipal: "Ver minha regra no sistema",
    exemploTitulo: "Sua regra sai do papel e vai para a demonstração",
    exemploTexto: "O time apresenta a configuração disponível e o caminho do uso até a conferência. Você identifica o que é atendido e o que exigiria mudança. Com essa resposta, pode comparar a solução e discutir a passagem do sistema atual com mais clareza.",
    faqPergunta: "Toda regra é possível na BestBarbers?",
    faqResposta: "Não. Precisamos mostrar o funcionamento para o seu caso e explicar as limitações antes da proposta.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L021: {
    id: "L021",
    conceito: "A ideia guardada",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Quer lançar assinatura? Veja como cobrar no cartão e calcular a comissão na BestBarbers.",
    apoio: "Conheça o sistema e a proposta de ajuda para configurar o clube e orientar a equipe. Preço e serviços do plano são decisões que você prepara com os dados da sua barbearia.",
    botaoPrincipal: "Ver como começar meu clube",
    exemploTitulo: "Saia da ideia com decisões para colocar em prática",
    exemploTexto: "Você traz o preço atual dos serviços, sua ideia de plano e as dúvidas da equipe. A conversa organiza o que precisa ser definido e mostra o funcionamento do produto. A proposta descreve a ajuda na configuração e as tarefas da barbearia. O preço do clube precisa considerar seus custos e o uso esperado, sem fórmula universal.",
    faqPergunta: "O time escolhe um preço que garante lucro?",
    faqResposta: "Não. Podemos organizar a decisão com seus dados; o resultado depende também de custos, uso e execução.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L022: {
    id: "L022",
    conceito: "Regra antes do convite",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Monte um clube que seu cliente entende e sua equipe sabe atender.",
    apoio: "Defina os serviços e a regra do plano. Depois, veja como configurar e acompanhar esse funcionamento na BestBarbers.",
    botaoPrincipal: "Preparar o plano do meu clube",
    exemploTitulo: "Do que você vende ao que a equipe faz",
    exemploTexto: "A conversa começa pelo plano que pretende oferecer. Mostramos as possibilidades do produto para adesão, uso e comissão, e esclarecemos o que precisa ser preparado. Você conhece o trabalho de implantação antes de divulgar, para que anúncio, balcão e sistema sigam o mesmo combinado.",
    faqPergunta: "Preciso ter tudo decidido antes de conversar?",
    faqResposta: "Não. Conte sua ideia e as dúvidas que ainda precisa resolver. As decisões da barbearia fazem parte da preparação.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L023: {
    id: "L023",
    conceito: "O preço copiado",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Antes de copiar o preço de um clube, veja como ele se comporta na sua conta.",
    apoio: "Altere mensalidade, visitas e custo no simulador da BestBarbers. Veja o que sobra antes das outras despesas quando o cliente usa mais.",
    botaoPrincipal: "Fazer a conta do meu clube",
    exemploTitulo: "Mexa nos números e veja a diferença",
    exemploTexto: "A ferramenta educativa calcula a contribuição direta com as entradas que você informa. Mostra a fórmula e o que ficou de fora, como os demais custos da empresa. Depois, compare também com o que esses clientes pagavam no avulso. Se quiser conhecer o produto, o pedido de conversa com a BestBarbers fica separado da simulação.",
    faqPergunta: "O resultado é um preço recomendado?",
    faqResposta: "Não. É uma conta ilustrativa para explorar hipóteses. O preço depende dos dados e das condições da sua operação.",
    ponte: "use_material",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L025: {
    id: "L025",
    conceito: "Sábado cheio e semana vazia",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Quer um clube para os dias em que sobram horários? Confira a regra antes de vender.",
    apoio: "Conheça as opções da BestBarbers e confira uma regra que faça sentido para seus clientes, sua equipe e sua agenda.",
    botaoPrincipal: "Ver opções para o meu clube",
    exemploTitulo: "Comece pela semana real da barbearia",
    exemploTexto: "Identifique os períodos disponíveis e a oferta que pretende fazer. A demonstração mostra quais regras o produto atende. A preparação considera o uso do cliente e os custos, para você não vender um plano que aumenta a disputa nos horários já cheios. A contratação não garante ocupação dos horários vazios.",
    faqPergunta: "Posso restringir o uso aos dias que eu escolher?",
    faqResposta: "As opções precisam ser confirmadas na demonstração para o seu plano. Só divulgue a regra depois dessa checagem.",
    ponte: "use_material",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L028: {
    id: "L028",
    conceito: "App é parte do projeto",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Sua marca no aplicativo. Seu clube de assinatura dentro da experiência.",
    apoio: "Conheça o app da BestBarbers para sua barbearia e veja como o cliente encontra o plano e autoriza a cobrança no cartão.",
    botaoPrincipal: "Ver o app para minha barbearia",
    exemploTitulo: "Veja além da imagem do celular",
    exemploTexto: "A demonstração mostra a apresentação do app e o caminho disponível para a adesão ao clube. Você entende as possibilidades de personalização, os materiais necessários e o trabalho até colocar a solução em operação. O investimento e as condições são apresentados antes de agendar a conversa.",
    faqPergunta: "A prévia já é meu aplicativo publicado?",
    faqResposta: "Não. É uma demonstração. Personalização e publicação têm etapas e condições próprias.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "app-marca-ficticia",
  },
  L029: {
    id: "L029",
    conceito: "Começar com operação existente",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Coloque o clube de assinatura na barbearia que você já tem.",
    apoio: "Conheça o app, a cobrança recorrente e o cálculo de comissão da BestBarbers. Prepare o lançamento considerando seus clientes e sua equipe atuais.",
    botaoPrincipal: "Conhecer o clube para minha barbearia",
    exemploTitulo: "Veja o que muda no atendimento e na cobrança",
    exemploTexto: "Veja na BestBarbers como o cliente adere ao plano, como a cobrança acontece no cartão e como a comissão aparece para conferência. Você também conhece o trabalho de implantação. Para preparar a oferta, compare o preço e o uso do clube com o que seus clientes já pagam no avulso.",
    faqPergunta: "Preciso transformar todos os clientes em assinantes?",
    faqResposta: "Não. Essa é uma decisão da sua oferta. O projeto deve considerar a convivência com o atendimento avulso.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L031: {
    id: "L031",
    conceito: "A placa pronta",
    situacao: "abertura",
    etapa: "Topo",
    titulo: "Prepare o clube de assinatura antes de abrir as portas.",
    apoio: "Conheça a BestBarbers para organizar app, cobrança e comissão junto com a equipe e o calendário da inauguração.",
    botaoPrincipal: "Planejar o clube da inauguração",
    exemploTitulo: "Seu lançamento começa na preparação",
    exemploTexto: "Conte quando pretende abrir, quem já está na equipe e como imagina o plano. Mostramos o produto e as tarefas necessárias à implantação. A proposta explica o que depende da barbearia e quais prazos precisam ser confirmados antes de divulgar o clube aos clientes.",
    faqPergunta: "O app estará publicado na inauguração?",
    faqResposta: "Isso depende do processo e das condições confirmadas. A data da abertura orienta a conversa, mas não é uma garantia automática de entrega.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L041: {
    id: "L041",
    conceito: "Agenda cheia bolso apertado",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Veja o que sobra da mensalidade depois do custo dos atendimentos.",
    apoio: "Mexa em preço, frequência e custo por visita no relatório educativo da BestBarbers. Entenda a diferença entre agenda cheia e uma conta que faz sentido.",
    botaoPrincipal: "Ver a conta do meu clube",
    exemploTitulo: "Mais uso pode mudar o resultado do plano",
    exemploTexto: "A simulação mostra o cálculo com as hipóteses informadas e explica quais custos não estão incluídos. Você consegue comparar cenários sem esconder o resultado desfavorável. Antes de decidir preço ou expansão do clube, também precisa olhar comissão, demais despesas e receita avulsa substituída.",
    faqPergunta: "Esse valor é meu lucro?",
    faqResposta: "Não. É uma contribuição ilustrativa antes dos custos que a ferramenta não inclui. Os dados e a interpretação precisam ser conferidos.",
    ponte: "use_material",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L042: {
    id: "L042",
    conceito: "O cliente que já vinha",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Compare o que o cliente pagava no avulso com o que passou a pagar no clube.",
    apoio: "Use a comparação da BestBarbers para olhar o gasto anterior, a mensalidade e o custo de atender o mesmo cliente.",
    botaoPrincipal: "Entender a comparação com o avulso",
    exemploTitulo: "Olhe o mesmo cliente antes e depois",
    exemploTexto: "Reúna o gasto anterior, a mensalidade e o custo do atendimento nos cenários comparados. Separe dado registrado de estimativa e observe outras mudanças do período. O material educativo explica a lógica; a conversa sobre BestBarbers fica disponível para quem precisa conhecer o produto e organizar o controle.",
    faqPergunta: "Todo assinante significa receita a mais?",
    faqResposta: "Não. Parte da mensalidade pode substituir pagamentos anteriores. O resultado depende dessa comparação e do uso do plano.",
    ponte: "use_material",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L043: {
    id: "L043",
    conceito: "Cliente usa muito",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Veja como o custo do clube muda quando o assinante vem mais vezes.",
    apoio: "Mude as visitas, o preço e o custo no simulador da BestBarbers. Veja a conta na tela, inclusive quando ela fica negativa.",
    botaoPrincipal: "Testar a conta com mais visitas",
    exemploTitulo: "Teste a regra também quando o uso aumenta",
    exemploTexto: "A simulação calcula a contribuição direta com suas entradas e permite enxergar quando ela fica apertada ou negativa. Depois, você precisa considerar capacidade de atendimento, outros custos e receita avulsa. Quem quiser conhecer o sistema pode pedir contato sem precisar concluir a ferramenta.",
    faqPergunta: "Existe uma frequência garantida de uso?",
    faqResposta: "Não. Os números da simulação são hipóteses. Seu planejamento precisa considerar dados da operação e cenários diferentes.",
    ponte: "use_material",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L044: {
    id: "L044",
    conceito: "Receber não é cobrar",
    situacao: "geral",
    etapa: "Meio",
    titulo: "Entenda quando o dinheiro do clube estará disponível para sua barbearia.",
    apoio: "Conheça as condições de cobrança e recebimento da BestBarbers antes de assumir o investimento ou planejar a mudança.",
    botaoPrincipal: "Conhecer taxas e recebimento",
    exemploTitulo: "Coloque entrada e saída no mesmo calendário",
    exemploTexto: "O atendimento apresenta as condições vigentes para sua contratação. Você compara o recebimento com as despesas e identifica o intervalo que precisa cobrir. Essa preparação faz parte da decisão de começar ou migrar. Não conte com antecipação que não esteja confirmada na proposta.",
    faqPergunta: "Vocês garantem recebimento na hora?",
    faqResposta: "Não. O recebimento segue as condições efetivas do meio de pagamento, apresentadas pelo time.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L051: {
    id: "L051",
    conceito: "A pergunta do barbeiro",
    situacao: "geral",
    etapa: "Topo",
    titulo: "“Quanto vou receber no clube?” Veja a conta para responder à sua equipe.",
    apoio: "Acompanhe o cálculo de comissão da BestBarbers, dos atendimentos ao extrato de cada profissional. Compare o exemplo com a regra que você quer adotar.",
    botaoPrincipal: "Ver a comissão do clube na tela",
    exemploTitulo: "Mostre ao barbeiro de onde vem a conta",
    exemploTexto: "A demonstração parte dos atendimentos e chega ao extrato. Você conhece o critério usado pelo produto e compara com o que pretende combinar na barbearia. A proposta de implantação explica a configuração e a orientação incluídas, para a regra não ficar apenas na conversa do dono.",
    faqPergunta: "Serve para a comissão que uso hoje?",
    faqResposta: "Vamos conferir sua regra no produto. Qualquer diferença deve ser explicada antes da contratação.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "clube-extrato-comissao",
  },
  L052: {
    id: "L052",
    conceito: "O fechamento contestado",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Confira a comissão do clube pelo caminho do atendimento até o extrato.",
    apoio: "Conheça o cálculo da BestBarbers e veja o que cada registro representa no fechamento dos profissionais.",
    botaoPrincipal: "Ver como conferir a comissão",
    exemploTitulo: "Uma conta que você consegue explicar",
    exemploTexto: "Veja na BestBarbers como os atendimentos registrados participam do cálculo e aparecem no extrato. Compare o resultado com a regra da sua barbearia e identifique o que precisa conferir. O exemplo ajuda a explicar o valor; os acordos com a equipe continuam sendo definidos por vocês.",
    faqPergunta: "O sistema garante que nunca haverá divergência?",
    faqResposta: "Não. O cálculo depende da regra e dos registros. O produto deve ajudar a acompanhar o que aconteceu, sem substituir a conferência.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "clube-extrato-comissao",
  },
  L054: {
    id: "L054",
    conceito: "O cliente de outro profissional",
    situacao: "geral",
    etapa: "Meio",
    titulo: "Veja como a comissão é calculada quando o assinante passa por profissionais diferentes.",
    apoio: "Acompanhe um exemplo na BestBarbers e confira o resultado no extrato de cada profissional.",
    botaoPrincipal: "Ver a divisão da comissão",
    exemploTitulo: "A assinatura é a mesma. Os atendimentos mostram quem participou.",
    exemploTexto: "Acompanhe os atendimentos de um assinante com profissionais diferentes. Veja a regra aplicada pela BestBarbers e confira o resultado no extrato de cada barbeiro. Para usar na sua operação, compare essa configuração com o acordo da equipe antes de contratar.",
    faqPergunta: "Preciso dividir tudo manualmente?",
    faqResposta: "O produto oferece cálculo de comissão de assinatura. A demonstração deve confirmar como sua regra pode ser aplicada e quais conferências continuam necessárias.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "clube-extrato-comissao",
  },
  L056: {
    id: "L056",
    conceito: "A oferta que ninguém faz",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Prepare sua equipe para explicar e oferecer o clube aos clientes.",
    apoio: "Use o conteúdo da BestBarbers para ensaiar a explicação do plano com quem atende. O cliente precisa entender a oferta antes de decidir assinar.",
    botaoPrincipal: "Ver como explicar o clube",
    exemploTitulo: "Do “tem assinatura” à oferta que o cliente entende",
    exemploTexto: "O material orienta um ensaio da conversa: apresentar o plano, responder às dúvidas e explicar o próximo passo sem pressão. Compare o exemplo com sua oferta real e ajuste as condições antes de usar. Se quiser conhecer a BestBarbers, o pedido comercial é separado do acesso ao conteúdo.",
    faqPergunta: "O material garante que a equipe venderá mais?",
    faqResposta: "Não. Ele ajuda a preparar a explicação. Resultado depende de oferta, procura, atendimento e execução.",
    ponte: "use_material",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L064: {
    id: "L064",
    conceito: "Cliente que não sabe usar app",
    situacao: "geral",
    etapa: "Meio",
    titulo: "Veja como seu cliente encontra e usa o clube no app da BestBarbers.",
    apoio: "Conheça as telas e prepare a explicação da equipe para quem precisar de ajuda no celular.",
    botaoPrincipal: "Ver o clube pelo celular do cliente",
    exemploTitulo: "Acompanhe o caminho que o assinante vai fazer",
    exemploTexto: "Assista ao caminho de adesão e uso no celular. Veja o que o cliente precisa fazer e quais dúvidas a equipe terá de responder. Depois, confira com a BestBarbers a orientação prevista na implantação e prepare o apoio para quem precisar de ajuda.",
    faqPergunta: "Meu cliente terá de descobrir tudo sozinho?",
    faqResposta: "A barbearia precisa preparar orientação para quem tiver dúvidas. Conheça o fluxo e combine as responsabilidades antes de começar.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "app-marca-ficticia",
  },
  L071: {
    id: "L071",
    conceito: "Tentou e parou",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Entenda por que o clube apertou sua conta antes de tentar outra vez.",
    apoio: "Use o material da BestBarbers para comparar preço, uso e custos da tentativa anterior. Descubra o que precisa rever antes de voltar a oferecer assinatura.",
    botaoPrincipal: "Rever a conta da minha tentativa",
    exemploTitulo: "Sua experiência vira o começo da análise",
    exemploTexto: "O material ajuda a separar o que foi observado do que era expectativa. Você olha o gasto anterior dos clientes, os atendimentos do plano e a comissão. Quando houver uma necessidade de produto, a BestBarbers mostra o funcionamento relacionado. Uma ferramenta nova não corrige sozinha uma oferta que não fecha a conta.",
    faqPergunta: "Trocar o sistema garante que a próxima tentativa dará certo?",
    faqResposta: "Não. Primeiro precisamos entender a causa e o que precisa mudar. Pode ser necessário rever a oferta ou adiar o clube.",
    ponte: "use_material",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L074: {
    id: "L074",
    conceito: "Sistema comprado e parado",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Recebeu login e senha, mas o clube continuou parado? Conheça a ajuda para começar.",
    apoio: "Veja a proposta de implantação da BestBarbers: configuração do clube, orientação da equipe e tarefas combinadas com a sua barbearia.",
    botaoPrincipal: "Ver o que a implantação inclui",
    exemploTitulo: "Saiba quem prepara, configura e confere",
    exemploTexto: "A conversa reúne sua regra e as decisões que ainda faltam. A proposta informa o trabalho do time, a participação da barbearia e as condições para avançar. Você sabe qual ajuda está contratando e o que precisa providenciar para que a implantação aconteça.",
    faqPergunta: "Vocês fazem tudo sem minha participação?",
    faqResposta: "Não. Sua equipe precisa fornecer informações, tomar decisões e participar da preparação. As responsabilidades são combinadas na proposta.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L081: {
    id: "L081",
    conceito: "Preço completo",
    situacao: "geral",
    etapa: "Fundo",
    titulo: "Saiba o investimento do app e do clube antes de agendar a demonstração.",
    apoio: "Conte o que sua barbearia precisa. O time apresenta a composição da BestBarbers, com módulos, taxas e condições aplicáveis.",
    botaoPrincipal: "Saber o investimento completo",
    exemploTitulo: "Confira a solução que você está comparando",
    exemploTexto: "Você recebe a explicação do que está incluído no serviço e no produto para seu caso. O preço de entrada não substitui o total da proposta. Depois de entender o investimento, decide se quer seguir para conhecer o funcionamento na demonstração.",
    faqPergunta: "O preço inicial já inclui todos os módulos?",
    faqResposta: "Não necessariamente. O atendimento deve explicar o investimento completo para a sua necessidade antes do agendamento.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L084: {
    id: "L084",
    conceito: "Depois da assinatura",
    situacao: "geral",
    etapa: "Fundo",
    titulo: "Conheça a ajuda para configurar seu clube e orientar quem vai usar.",
    apoio: "A proposta da BestBarbers reúne produto e implantação assistida com entregas e responsabilidades definidas.",
    botaoPrincipal: "Conhecer a implantação assistida",
    exemploTitulo: "Da sua regra à preparação da equipe",
    exemploTexto: "Conte como pretende operar o clube. O time mostra o produto e explica o trabalho de configuração e orientação aplicável ao caso. Você conhece as condições e o que precisa providenciar antes de aceitar. A implantação é um serviço com escopo combinado, não uma promessa de assumir a gestão da barbearia.",
    faqPergunta: "A ajuda de implantação está incluída em qualquer plano?",
    faqResposta: "Você confere o que está incluído e o que é cobrado na proposta para sua barbearia, antes de contratar.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
  L091: {
    id: "L091",
    conceito: "Bastidor da cobrança",
    situacao: "geral",
    etapa: "Meio",
    titulo: "Veja como conferir a cobrança de uma assinatura na BestBarbers.",
    apoio: "A demonstração acompanha uma tarefa que aparece no balcão: saber como está o pagamento do plano antes de seguir o atendimento.",
    botaoPrincipal: "Ver onde conferir o pagamento",
    exemploTitulo: "Assista ao caminho completo na tela",
    exemploTexto: "Acompanhe na BestBarbers como chegar à informação da cobrança e reconhecer a situação do pagamento. O exemplo usa dados fictícios identificados. Veja quais consultas e ações fazem parte da tarefa; depois, confira com o time como adaptar essa rotina à sua barbearia.",
    faqPergunta: "Isso é uma cobrança real de um cliente?",
    faqResposta: "Não. A demonstração usa dados fictícios identificados para mostrar o funcionamento sem expor clientes.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L095: {
    id: "L095",
    conceito: "O barbeiro explica o extrato",
    situacao: "geral",
    etapa: "Meio",
    titulo: "Mostre de onde vem a comissão do clube usando o extrato da BestBarbers.",
    apoio: "Veja uma demonstração dos atendimentos, do cálculo e das informações disponíveis para o profissional conferir.",
    botaoPrincipal: "Ver o extrato da comissão",
    exemploTitulo: "A conta fica ligada ao trabalho registrado",
    exemploTexto: "Acompanhe os atendimentos do exemplo, veja a regra aplicada e confira o extrato do profissional. Depois, compare com o fechamento que você faz hoje. Se precisar esclarecer uma diferença, peça contato com o time da BestBarbers antes de decidir pela contratação.",
    faqPergunta: "Posso levar minha regra para comparar?",
    faqResposta: "Sim. Explique como faz o fechamento hoje para o time verificar o que o produto atende.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "clube-extrato-comissao",
  },
  L097: {
    id: "L097",
    conceito: "A tela pelo olhar do dono",
    situacao: "geral",
    etapa: "Topo",
    titulo: "Veja o clube na BestBarbers antes de pedir contato.",
    apoio: "Assista à demonstração aberta de adesão, cobrança e comissão, com dados de exemplo. O cadastro só entra se você quiser falar sobre a sua barbearia.",
    botaoPrincipal: "Assistir à demonstração do clube",
    exemploTitulo: "Conheça o trabalho por trás de cada tela",
    exemploTexto: "A apresentação percorre tarefas relacionadas ao clube e explica as configurações demonstradas. Você vê o produto antes de levar sua regra para a conversa comercial. Se uma necessidade específica não aparecer no exemplo, pergunte ao time antes de decidir: a demonstração não presume atender a qualquer modelo.",
    faqPergunta: "Preciso me cadastrar para assistir?",
    faqResposta: "Não. Você pode assistir sem cadastro. Se quiser conversar sobre a contratação, use o pedido de contato separado.",
    ponte: "veja_primeiro",
    formularioVariante: "curto",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: "demo-capa",
  },
  L098: {
    id: "L098",
    conceito: "A implantação narrada",
    situacao: "geral",
    etapa: "Meio",
    titulo: "Veja o que acontece entre contratar a BestBarbers e começar a operar o clube.",
    apoio: "Conheça as tarefas de preparação, configuração e orientação previstas para a implantação do seu projeto.",
    botaoPrincipal: "Conhecer as etapas da implantação",
    exemploTitulo: "Você sabe qual ajuda está contratando",
    exemploTexto: "Confira as etapas de configuração e orientação previstas na proposta da BestBarbers. Veja quais informações a barbearia fornece e o que o time entrega. Com essas tarefas definidas, você compara a ajuda de implantação junto com o produto.",
    faqPergunta: "Quem confirma o prazo para começar?",
    faqResposta: "O time confere as informações, as decisões pendentes e as dependências do projeto antes de combinar o cronograma.",
    ponte: "como_segue",
    formularioVariante: "padrao",
    botaoContato: "Quero conversar sobre meu clube",
    artefatoExigido: null,
  },
};

/** Os 34 ids, em ordem. Usado por teste e por `pecaDaRota` para validar. */
export const PC_PECAS_IDS = Object.keys(PC_PECAS) as PcPecaId[];
